# Generated by Django 6.0 on 2026-01-08 12:40

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NavigationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "primary_navigation",
                    wagtail.fields.StreamField(
                        [("link", 2)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Leave blank to use the page's own title",
                                    "label": "Link text",
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("page", 0), ("title", 1)]],
                                {},
                            ),
                        },
                        help_text="Main site navigation",
                    ),
                ),
                (
                    "secondary_navigation",
                    wagtail.fields.StreamField(
                        [("link", 2)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Leave blank to use the page's own title",
                                    "label": "Link text",
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("page", 0), ("title", 1)]],
                                {},
                            ),
                        },
                        help_text="Alternative navigation",
                    ),
                ),
                (
                    "footer_navigation",
                    wagtail.fields.StreamField(
                        [("column", 6)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Leave blank if no header required.",
                                    "required": False,
                                },
                            ),
                            1: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Leave blank to use the page's own title",
                                    "label": "Link text",
                                    "required": False,
                                },
                            ),
                            3: ("wagtail.blocks.URLBlock", (), {"required": False}),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("page", 1), ("title", 2), ("external_link", 3)]],
                                {},
                            ),
                            5: ("wagtail.blocks.ListBlock", (4,), {}),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 0), ("links", 5)]],
                                {},
                            ),
                        },
                        help_text="Multiple columns of footer links with optional header.",
                    ),
                ),
                (
                    "footer_links",
                    wagtail.fields.StreamField(
                        [("link", 3)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Leave blank to use the page's own title",
                                    "label": "Link text",
                                    "required": False,
                                },
                            ),
                            2: ("wagtail.blocks.URLBlock", (), {"required": False}),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("page", 0), ("title", 1), ("external_link", 2)]],
                                {},
                            ),
                        },
                        help_text="Single list of elements at the base of the page.",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
