# Generated by Django 3.1.8 on 2021-07-27 13:55

from django.db import migrations


CATEGORIES = (
    ("", ""),
    ("", ""),
)


def create_categories(apps, schema_editor):
    Category = apps.get_model("categories.category")

    for name, icon in CATEGORIES:
        Category.objects.create(name=name, icon=icon)


def remove_categories(apps, schema_editor):
    Category = apps.get_model("categories.category")

    for name, icon in CATEGORIES:
        try:
            Category.objects.get(name=name).delete()
        except Category.DoesNotExist:
            # Skip, category doesn't exist
            ...


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_categories, remove_categories),
    ]
