# Generated by Django 3.2.13 on 2022-06-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0002_create_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.FilePathField(
                blank=True,
                max_length=250,
                null=True,
                path="/",
            ),
        ),
    ]
