# Generated by Django 3.2.13 on 2022-05-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_create_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.FilePathField(
                blank=True,
                null=True,
                path="/tmp/pycharm_project_686/etna/categories/static/images/category-svgs/",
            ),
        ),
    ]
