# Generated by Django 5.2.1 on 2025-06-18 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_category_icon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
