# Generated by Django 6.0.8 on 2026-09-14 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explorerindexpage',
            name='twitter_og_description',
        ),
        migrations.RemoveField(
            model_name='explorerindexpage',
            name='twitter_og_image',
        ),
        migrations.RemoveField(
            model_name='explorerindexpage',
            name='twitter_og_title',
        ),
        migrations.RemoveField(
            model_name='highlightgallerypage',
            name='twitter_og_description',
        ),
        migrations.RemoveField(
            model_name='highlightgallerypage',
            name='twitter_og_image',
        ),
        migrations.RemoveField(
            model_name='highlightgallerypage',
            name='twitter_og_title',
        ),
        migrations.RemoveField(
            model_name='timeperiodexplorerindexpage',
            name='twitter_og_description',
        ),
        migrations.RemoveField(
            model_name='timeperiodexplorerindexpage',
            name='twitter_og_image',
        ),
        migrations.RemoveField(
            model_name='timeperiodexplorerindexpage',
            name='twitter_og_title',
        ),
        migrations.RemoveField(
            model_name='timeperiodexplorerpage',
            name='twitter_og_description',
        ),
        migrations.RemoveField(
            model_name='timeperiodexplorerpage',
            name='twitter_og_image',
        ),
        migrations.RemoveField(
            model_name='timeperiodexplorerpage',
            name='twitter_og_title',
        ),
        migrations.RemoveField(
            model_name='topicexplorerindexpage',
            name='twitter_og_description',
        ),
        migrations.RemoveField(
            model_name='topicexplorerindexpage',
            name='twitter_og_image',
        ),
        migrations.RemoveField(
            model_name='topicexplorerindexpage',
            name='twitter_og_title',
        ),
        migrations.RemoveField(
            model_name='topicexplorerpage',
            name='twitter_og_description',
        ),
        migrations.RemoveField(
            model_name='topicexplorerpage',
            name='twitter_og_image',
        ),
        migrations.RemoveField(
            model_name='topicexplorerpage',
            name='twitter_og_title',
        ),
    ]
