# Generated by Django 4.0.8 on 2023-02-16 16:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("collections", "0031_alter_sub_heading_fields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="explorerindexpage",
            old_name="sub_heading",
            new_name="intro",
        ),
        migrations.RenameField(
            model_name="timeperiodexplorerindexpage",
            old_name="sub_heading",
            new_name="intro",
        ),
        migrations.RenameField(
            model_name="timeperiodexplorerpage",
            old_name="sub_heading",
            new_name="intro",
        ),
        migrations.RenameField(
            model_name="topicexplorerindexpage",
            old_name="sub_heading",
            new_name="intro",
        ),
        migrations.RenameField(
            model_name="topicexplorerpage",
            old_name="sub_heading",
            new_name="intro",
        ),
    ]
