# Generated by Django 4.1.8 on 2023-04-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collections", "0041_alter_timeperiodexplorerindexpage_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="highlight",
            name="alt_text",
            field=models.CharField(
                help_text='Alternative (alt) text describes images when they fail to load, and is read aloud by assistive technologies. Use a maximum of 100 characters to describe your image. <a href="https://html.spec.whatwg.org/multipage/images.html#alt" target="_blank">Check the guidance for tips on writing alt text</a>.',
                max_length=100,
                null=True,
                verbose_name="alternative text",
            ),
        ),
    ]
