# Generated by Django 4.1.8 on 2023-04-27 15:27

from django.db import migrations
import app.core.blocks.promoted_links
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("collections", "0044_remove_resultspagerecord_page_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeperiodexplorerpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "promoted_pages",
                        wagtail.blocks.StructBlock(
                            [
                                ("heading", wagtail.blocks.CharBlock(max_length=100)),
                                (
                                    "sub_heading",
                                    wagtail.blocks.CharBlock(max_length=200),
                                ),
                                (
                                    "promoted_items",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.TextBlock,
                                        max=3,
                                        min=3,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="topicexplorerpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "promoted_pages",
                        wagtail.blocks.StructBlock(
                            [
                                ("heading", wagtail.blocks.CharBlock(max_length=100)),
                                (
                                    "sub_heading",
                                    wagtail.blocks.CharBlock(max_length=200),
                                ),
                                (
                                    "promoted_items",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.TextBlock,
                                        max=3,
                                        min=3,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
    ]
