# Generated by Django 4.1.8 on 2023-04-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collections", "0047_set_skos_id_for_topicexplorerpages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topicexplorerpage",
            name="skos_id",
            field=models.CharField(
                db_index=True,
                blank=True,
                help_text="Used as the identifier for this topic when sending page metadata to the CIIM API.",
                max_length=100,
                unique=True,
                verbose_name="SKOS identifier",
            ),
        ),
    ]
