# Generated by Django 4.1.8 on 2023-04-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collections", "0048_alter_topicexplorerpage_skos_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="explorerindexpage",
            name="uuid",
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name="highlightgallerypage",
            name="uuid",
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name="timeperiodexplorerindexpage",
            name="uuid",
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name="timeperiodexplorerpage",
            name="uuid",
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name="topicexplorerindexpage",
            name="uuid",
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name="topicexplorerpage",
            name="uuid",
            field=models.UUIDField(null=True),
        ),
    ]
