# Generated by Django 4.2.1 on 2023-05-24 11:54

from django.db import migrations, models
import django.db.models.deletion
import app.core.blocks.page_list
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("collections", "0050_make_page_uuid_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="explorerindexpage",
            name="articles_introduction",
            field=models.CharField(
                blank=True,
                help_text="The introduction to display for the articles section.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="explorerindexpage",
            name="articles_title",
            field=models.CharField(
                blank=True,
                default="Stories from the collection",
                help_text="The title to display for the articles section.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="explorerindexpage",
            name="featured_article",
            field=models.ForeignKey(
                blank=True,
                help_text="Select a page to display in the featured area. This can be an Article, or Record Article.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
        migrations.AddField(
            model_name="explorerindexpage",
            name="featured_articles",
            field=wagtail.fields.StreamField(
                [
                    (
                        "featuredarticles",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "items",
                                    app.core.blocks.page_list.PageListBlock(
                                        "articles.ArticlePage",
                                        "articles.RecordArticlePage",
                                        max_num=6,
                                        min_num=3,
                                    ),
                                )
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="explorerindexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "large_card_links",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        max_length=100, required=False
                                    ),
                                ),
                                (
                                    "page_1",
                                    wagtail.blocks.PageChooserBlock(
                                        label="Link one target"
                                    ),
                                ),
                                (
                                    "page_2",
                                    wagtail.blocks.PageChooserBlock(
                                        label="Link two target"
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="timeperiodexplorerindexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "large_card_links",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        max_length=100, required=False
                                    ),
                                ),
                                (
                                    "page_1",
                                    wagtail.blocks.PageChooserBlock(
                                        label="Link one target"
                                    ),
                                ),
                                (
                                    "page_2",
                                    wagtail.blocks.PageChooserBlock(
                                        label="Link two target"
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="topicexplorerindexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "large_card_links",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        max_length=100, required=False
                                    ),
                                ),
                                (
                                    "page_1",
                                    wagtail.blocks.PageChooserBlock(
                                        label="Link one target"
                                    ),
                                ),
                                (
                                    "page_2",
                                    wagtail.blocks.PageChooserBlock(
                                        label="Link two target"
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
    ]
