# Generated by Django 5.2.4 on 2025-07-15 17:07
# etna:allowRemoveField

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0063_highlight_description_highlight_record_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlight',
            name='alt_text',
        ),
        migrations.RemoveField(
            model_name='timeperiodexplorerpage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='topicexplorerpage',
            name='body',
        ),
    ]
