# Generated by Django 5.2.4 on 2025-07-17 10:08

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0064_remove_highlight_alt_text_and_more'),
        ('images', '0013_alter_customimage_description'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='explorerindexpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage'),
        ),
        migrations.AddField(
            model_name='explorerindexpage',
            name='hero_image_caption',
            field=wagtail.fields.RichTextField(blank=True, help_text='An optional caption for hero images. This could be used for image sources or for other useful metadata.', verbose_name='hero image caption (optional)'),
        ),
        migrations.CreateModel(
            name='ExplorerIndexPageSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(blank=True, help_text='Optional title for the selected page. If left blank, the page title will be used.', max_length=255)),
                ('teaser_text', models.CharField(blank=True, help_text="Optional teaser text for the selected page. If left blank, the page's teaser text will be displayed.", max_length=255)),
                ('cta_label', models.CharField(blank=True, help_text="Optional label for the call to action button. If left blank, 'Read more' will be used.", max_length=50, verbose_name='CTA label')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='explorer_index_page_selections', to='collections.explorerindexpage')),
                ('selected_page', models.ForeignKey(help_text='Select a page to display in the Explorer Index Page.', on_delete=django.db.models.deletion.CASCADE, related_name='explorer_index_page_selected_pages', to='wagtailcore.page')),
                ('teaser_image', models.ForeignKey(blank=True, help_text="Optional image to display in the teaser for the selected page. If left blank, the page's teaser image will be displayed.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
