# Generated by Django 5.2.4 on 2025-08-20 14:31

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0067_alter_explorerindexpage_stories_hero_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explorerindexpage',
            name='articles_introduction',
        ),
        migrations.RemoveField(
            model_name='explorerindexpage',
            name='articles_title',
        ),
        migrations.RemoveField(
            model_name='explorerindexpage',
            name='featured_article',
        ),
        migrations.RemoveField(
            model_name='explorerindexpage',
            name='featured_articles',
        ),
        migrations.AddField(
            model_name='explorerindexpage',
            name='explorer_index_page_selections_title',
            field=models.CharField(blank=True, help_text='The title to display for the Explorer Index Page selections.', max_length=100),
        ),
        migrations.AddField(
            model_name='explorerindexpage',
            name='stories_hero_image_caption',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
