# Generated by Django 5.2.5 on 2025-08-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0068_remove_explorerindexpage_articles_introduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='explorerindexpage',
            name='stories_introduction',
            field=models.CharField(blank=True, help_text='The introduction to display for the articles section.', max_length=200),
        ),
        migrations.AddField(
            model_name='explorerindexpage',
            name='stories_title',
            field=models.CharField(blank=True, default='Stories from the collection', help_text='The title to display for the articles section.', max_length=100),
        ),
    ]
