# Generated by Django 5.2.6 on 2025-10-20 16:41
# etna:allowAlterField

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0069_explorerindexpage_stories_introduction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explorerindexpage',
            name='short_title',
            field=models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=46, null=True, verbose_name='short title'),
        ),
        migrations.AlterField(
            model_name='highlightgallerypage',
            name='short_title',
            field=models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=46, null=True, verbose_name='short title'),
        ),
        migrations.AlterField(
            model_name='timeperiodexplorerindexpage',
            name='short_title',
            field=models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=46, null=True, verbose_name='short title'),
        ),
        migrations.AlterField(
            model_name='timeperiodexplorerpage',
            name='short_title',
            field=models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=46, null=True, verbose_name='short title'),
        ),
        migrations.AlterField(
            model_name='topicexplorerindexpage',
            name='short_title',
            field=models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=46, null=True, verbose_name='short title'),
        ),
        migrations.AlterField(
            model_name='topicexplorerpage',
            name='short_title',
            field=models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=46, null=True, verbose_name='short title'),
        ),
    ]
