# Generated by Django 3.1.8 on 2021-07-09 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0002_insightsindexpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insightspage',
            old_name='content',
            new_name='body',
        ),
    ]
