# Generated by Django 3.1.8 on 2021-07-20 15:57

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0004_insightspage_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insightspage',
            name='body',
            field=wagtail.core.fields.StreamField([('quote', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(max_length=100, required=True)), ('quote', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link'], required=True)), ('attribution', wagtail.core.blocks.CharBlock(max_length=100, required=False))])), ('paragraph_with_heading', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(max_length=100, required=True)), ('paragraph', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link'], required=True))])), ('link_list', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(max_length=100, required=True)), ('category', wagtail.snippets.blocks.SnippetChooserBlock('categories.Category')), ('summary', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link'], required=False)), ('link_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(max_length=100, required=True)), ('summary', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link'], required=False)), ('url', wagtail.core.blocks.URLBlock(required=True))]), label='Links'))]))], blank=True, null=True),
        ),
    ]
