# Generated by Django 3.1.8 on 2021-07-19 12:11

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0004_insightspage_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insightspage',
            name='body',
            field=wagtail.core.fields.StreamField([('quote', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(max_length=100, required=True)), ('quote', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link'], required=True)), ('attribution', wagtail.core.blocks.CharBlock(max_length=100, required=False))])), ('paragraph_with_heading', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(max_length=100, required=True)), ('paragraph', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link'], required=True))])), ('media_embed_audio', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(max_length=100, required=True)), ('date', wagtail.core.blocks.DateBlock(required=False)), ('description', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link'], required=False)), ('media_file_url', wagtail.core.blocks.URLBlock(label='Audio file URL', required=True)), ('transcript', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link'], required=False))])), ('media_embed_video', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(max_length=100, required=True)), ('date', wagtail.core.blocks.DateBlock(required=False)), ('description', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link'], required=False)), ('media_file_url', wagtail.core.blocks.URLBlock(label='Video file URL', required=True)), ('transcript', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link'], required=False))]))], blank=True, null=True),
        ),
    ]
