# Generated by Django 3.1.8 on 2021-07-15 14:12

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0005_auto_20210715_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insightspage',
            name='body',
            field=wagtail.core.fields.StreamField([('quote', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(max_length=100, required=True)), ('quote', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link'], required=True)), ('attribution', wagtail.core.blocks.CharBlock(max_length=100, required=False))])), ('paragraph_with_heading', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(max_length=100, required=True)), ('paragraph', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link'], required=True))])), ('media_embed_audio', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.TextBlock(max_length=100)), ('datetime', wagtail.core.blocks.DateTimeBlock(required=False)), ('description', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link'], required=False)), ('transcript', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link'], required=False))])), ('media_embed_video', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.TextBlock(max_length=100)), ('datetime', wagtail.core.blocks.DateTimeBlock(required=False)), ('description', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link'], required=False)), ('transcript', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link'], required=False))]))], blank=True, null=True),
        ),
    ]
