# Generated by Django 3.1.8 on 2021-07-23 14:01

from django.db import migrations, models
import django.db.models.deletion
import etna.records.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('insights', '0006_record_embed_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='insightsindexpage',
            name='teaser_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='insightspage',
            name='body',
            field=wagtail.core.fields.StreamField([('quote', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(max_length=100, required=True)), ('quote', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link'], required=True)), ('attribution', wagtail.core.blocks.CharBlock(max_length=100, required=False))])), ('paragraph_with_heading', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(max_length=100, required=True)), ('paragraph', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link'], required=True))])), ('section_heading', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(help_text='Section headings must be unique within the page.', max_length=100, required=True))])), ('featured_record', wagtail.core.blocks.StructBlock([('record', etna.records.blocks.RecordChooserBlock())])), ('featured_records', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(max_length=100, required=True)), ('introduction', wagtail.core.blocks.CharBlock(max_length=200, required=True)), ('records', wagtail.core.blocks.ListBlock(etna.records.blocks.RecordChooserBlock))]))], blank=True, null=True),
        ),
    ]
