# Generated by Django 3.1.8 on 2021-11-11 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0024_promoted_item_target_blank_options'),
        ('insights', '0024_fix_heading_help_text'),
    ]

    operations = [
    ]
