# Generated by Django 3.2.12 on 2022-03-05 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("insights", "0033_auto_20220304_2226"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="insightspagetag",
            options={"verbose_name": "name", "verbose_name_plural": "slug"},
        ),
    ]
