# Generated by Django 3.2.12 on 2022-03-05 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0030_insightsindexpage_featured_insight'),
        ('insights', '0034_alter_insightspagetag_options'),
    ]

    operations = [
    ]
