# Generated by Django 4.0.8 on 2022-11-03 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("insights", "0045_add_search_image_fields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="insightsindexpage",
            old_name="featured_insight",
            new_name="featured_story",
        ),
    ]
