# Generated by Django 4.0.8 on 2022-12-16 14:21

from django.db import migrations
import etna.core.blocks.page_list
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0025_timeperiodexplorerindexpage_sub_heading_and_more'),
        ('home', '0015_alter_homepage_featured_pages'),
        ('wagtailimages', '0024_index_image_file_hash'),
        ('wagtailcore', '0077_alter_revision_user'),
        ('insights', '0046_remove_insightsindexpage_featured_collections_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InsightsPage',
            new_name='StoriesPage',
        ),
        migrations.AlterField(
            model_name='insightsindexpage',
            name='featured_pages',
            field=wagtail.fields.StreamField([('featuredpages', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(max_length=100)), ('description', wagtail.blocks.TextBlock(max_length=200)), ('items', etna.core.blocks.page_list.PageListBlock('insights.StoriesPage', max_num=9, min_num=3))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
