# Generated by Django 4.0.8 on 2022-12-16 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0051_alter_storiestag_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaggedInsights',
            new_name='TaggedStories',
        ),
    ]
