name: Check migrations

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: 3.13
    - run: python .github/scripts/check_migrations.py
      shell: bash
