# Generated by Django 6.0.7 on 2026-07-30 13:11

import app.core.models.mixins
import django.core.validators
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('images', '0001_initial'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveSearchComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name to identify this search component (not shown to users)', max_length=255, verbose_name='name')),
                ('heading', models.CharField(help_text="The heading text displayed above the search bar (e.g. 'Web Archive Search')", max_length=255, verbose_name='heading')),
                ('help_text', models.TextField(blank=True, help_text='Optional guidance text displayed below the search box to help users understand what they can search for', verbose_name='help text')),
                ('button_text', models.CharField(default='Search', help_text='The text displayed on the search button', max_length=50, verbose_name='button text')),
                ('archive_type', models.CharField(choices=[('web', 'Web Archive'), ('social', 'Social Media Archive')], help_text='Select whether this component searches the Web Archive or Social Media Archive', max_length=20, verbose_name='archive type')),
            ],
            options={
                'verbose_name': 'Archive Search Component',
                'verbose_name_plural': 'Archive Search Components',
            },
        ),
        migrations.CreateModel(
            name='AToZArchivePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('twitter_og_title', models.CharField(blank=True, help_text='If left blank, the OpenGraph title will be used.', max_length=255, null=True, verbose_name='Twitter OpenGraph title')),
                ('twitter_og_description', models.TextField(blank=True, help_text='If left blank, the OpenGraph description will be used.', null=True, verbose_name='Twitter OpenGraph description')),
                ('short_title', models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=45, null=True, verbose_name='short title')),
                ('teaser_text', models.TextField(help_text='A short, enticing description of this page. This will appear in promos and under thumbnails around the site.', max_length=160, verbose_name='teaser text')),
                ('intro', wagtail.fields.RichTextField(help_text='1-2 sentences introducing the subject of the page, and explaining why a user should read on.', max_length=300, verbose_name='introductory text')),
                ('featured_links_heading', models.CharField(blank=True, help_text='A short heading for the featured links section', max_length=100, verbose_name='featured links heading text')),
                ('featured_links', wagtail.fields.StreamField([('link', 3)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "Leave blank to use the page's own title", 'label': 'Link text', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('page', 0), ('title', 1), ('external_link', 2)]], {})}, help_text='Exactly three links, or leave empty to hide this section. Each link can be to an internal page or an external URL.', verbose_name='featured links')),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='alerts.alert')),
                ('search_image', models.ForeignKey(blank=True, help_text='Image that will appear when this page is shared on social media. This will default to the teaser image if left blank.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='OpenGraph image')),
                ('teaser_image', models.ForeignKey(blank=True, help_text='Image that will appear on thumbnails and promos around the site.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
                ('themed_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='alerts.themedalert')),
                ('twitter_og_image', models.ForeignKey(blank=True, help_text='If left blank, the OpenGraph image will be used.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Twitter OpenGraph image')),
            ],
            options={
                'verbose_name': 'A-Z Archive Page',
            },
            bases=(app.core.models.mixins.CustomHeadlessPreviewMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='BookmarkletCTASnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name to identify this bookmarklet snippet (not shown to users)', max_length=255, verbose_name='name')),
                ('heading', models.CharField(help_text='The heading text displayed at the top of the component', max_length=255, verbose_name='heading')),
                ('body', models.TextField(help_text='Description text displayed below the heading', verbose_name='body')),
                ('button_text', models.CharField(default='Check UKGWA', help_text='The text displayed on the CTA button', max_length=50, verbose_name='button text')),
                ('button_link', models.ForeignKey(help_text='The internal page the button will take users to', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Bookmarklet CTA',
                'verbose_name_plural': 'Bookmarklet CTA',
            },
        ),
        migrations.CreateModel(
            name='FeaturedLinksSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(help_text='A short heading for the featured links section', max_length=100, verbose_name='featured links heading text')),
                ('links', wagtail.fields.StreamField([('link', 3)], block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "Leave blank to use the page's own title", 'label': 'Link text', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('page', 0), ('title', 1), ('external_link', 2)]], {})}, help_text='Contains exactly three links. Each link can be to an internal page or an external URL.', verbose_name='featured links')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_links_sections', to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Featured links section',
                'verbose_name_plural': 'Featured links sections',
            },
        ),
        migrations.CreateModel(
            name='InformationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('twitter_og_title', models.CharField(blank=True, help_text='If left blank, the OpenGraph title will be used.', max_length=255, null=True, verbose_name='Twitter OpenGraph title')),
                ('twitter_og_description', models.TextField(blank=True, help_text='If left blank, the OpenGraph description will be used.', null=True, verbose_name='Twitter OpenGraph description')),
                ('short_title', models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=45, null=True, verbose_name='short title')),
                ('teaser_text', models.TextField(help_text='A short, enticing description of this page. This will appear in promos and under thumbnails around the site.', max_length=160, verbose_name='teaser text')),
                ('intro', wagtail.fields.RichTextField(help_text='1-2 sentences introducing the subject of the page, and explaining why a user should read on.', max_length=300, verbose_name='introductory text')),
                ('featured_links_heading', models.CharField(blank=True, help_text='A short heading for the featured links section', max_length=100, verbose_name='featured links heading text')),
                ('featured_links', wagtail.fields.StreamField([('link', 3)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "Leave blank to use the page's own title", 'label': 'Link text', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('page', 0), ('title', 1), ('external_link', 2)]], {})}, help_text='Exactly three links, or leave empty to hide this section. Each link can be to an internal page or an external URL.', verbose_name='featured links')),
                ('show_sidebar_navigation', models.BooleanField(default=True, help_text='Show a navigation sidebar of sibling pages within this section. Only applies to direct children of a section index.')),
                ('body', wagtail.fields.StreamField([('bookmarklet', 0), ('call_to_action', 7), ('document', 11), ('image', 14), ('paragraph', 16), ('quote', 24), ('youtube_video', 30), ('content_section', 37)], blank=True, block_lookup={0: ('wagtail.blocks.StructBlock', [[]], {}), 1: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link', 'code', 'ol', 'ul'], 'max_length': 100}), 2: ('wagtail.blocks.CharBlock', (), {}), 3: ('app.core.blocks.page_chooser.APIPageChooserBlock', (), {'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'required': False}), 5: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Use the accented button style', 'label': 'Accented', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('label', 2), ('link', 3), ('external_link', 4), ('accented', 5)]], {}), 7: ('wagtail.blocks.StructBlock', [[('body', 1), ('button', 6)]], {}), 8: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': True}), 9: ('wagtail.blocks.StructBlock', [[('file', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'min_num': 1}), 11: ('wagtail.blocks.StructBlock', [[('documents', 10)]], {}), 12: ('app.core.blocks.image.APIImageChooserBlock', (), {'rendition_size': 'max-900x900', 'required': True}), 13: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'help_text': 'If provided, displays directly below the image. Can be used to specify sources, transcripts or other useful metadata.', 'label': 'Caption (optional)', 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('image', 12), ('caption', 13)]], {}), 15: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link', 'code', 'ol', 'ul']}), 16: ('wagtail.blocks.StructBlock', [[('text', 15)]], {}), 17: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link', 'code', 'ol', 'ul'], 'required': True}), 18: ('wagtail.blocks.CharBlock', (), {'help_text': 'The name of the person being quoted. e.g. King Edward VIII', 'max_length': 100}), 19: ('wagtail.blocks.CharBlock', (), {'help_text': 'The title of the work or document from which the quote is taken. e.g. The Telegraph, 23 June 1986', 'max_length': 100, 'required': False}), 20: ('app.core.blocks.page_chooser.APIPageChooserBlock', (), {'help_text': 'Reference another page published on the site', 'label': 'Internal page', 'required': False}), 21: ('wagtail.blocks.URLBlock', (), {'help_text': 'Add a URL here to refer to an external source', 'label': 'External link', 'required': False}), 22: ('wagtail.blocks.StructBlock', [[('citation_internal_link', 20), ('citation_external_link', 21)]], {}), 23: ('wagtail.blocks.StructBlock', [[('citation', 19), ('source_link', 22)]], {}), 24: ('wagtail.blocks.StructBlock', [[('quote', 17), ('attribution', 18), ('source', 23)]], {}), 25: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 100, 'required': True}), 26: ('wagtail.blocks.CharBlock', (), {'label': 'YouTube Video ID', 'max_length': 11, 'required': True, 'validators': [django.core.validators.RegexValidator(message='Invalid YouTube Video ID', regex='^[a-zA-Z0-9_-]{11}$')]}), 27: ('app.core.blocks.image.APIImageChooserBlock', (), {'label': 'Preview Image', 'rendition_size': 'fill-640x360', 'required': True}), 28: ('wagtail.blocks.RichTextBlock', (), {'label': 'Transcript', 'required': False}), 29: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Tick if the video has captions on YouTube', 'label': 'Captions available', 'required': False}), 30: ('wagtail.blocks.StructBlock', [[('title', 25), ('video_id', 26), ('preview_image', 27), ('transcript', 28), ('captions_available', 29)]], {}), 31: ('wagtail.blocks.CharBlock', (), {'label': 'Heading', 'max_length': 100}), 32: ('wagtail.blocks.CharBlock', (), {'label': 'Sub-heading', 'max_length': 100}), 33: ('wagtail.blocks.StructBlock', [[('heading', 32)]], {}), 34: ('wagtail.blocks.CharBlock', (), {'label': 'Sub-sub-heading', 'max_length': 100}), 35: ('wagtail.blocks.StructBlock', [[('heading', 34)]], {}), 36: ('wagtail.blocks.StreamBlock', [[('bookmarklet', 0), ('call_to_action', 7), ('document', 11), ('image', 14), ('paragraph', 16), ('quote', 24), ('sub_heading', 33), ('sub_sub_heading', 35), ('youtube_video', 30)]], {'required': False}), 37: ('wagtail.blocks.StructBlock', [[('heading', 31), ('content', 36)]], {})}, null=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='alerts.alert')),
                ('bookmarklet_cta', models.ForeignKey(blank=True, help_text='Select a bookmarklet CTA snippet to display on this page', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ukgwa.bookmarkletctasnippet')),
                ('search_image', models.ForeignKey(blank=True, help_text='Image that will appear when this page is shared on social media. This will default to the teaser image if left blank.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='OpenGraph image')),
                ('teaser_image', models.ForeignKey(blank=True, help_text='Image that will appear on thumbnails and promos around the site.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
                ('themed_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='alerts.themedalert')),
                ('twitter_og_image', models.ForeignKey(blank=True, help_text='If left blank, the OpenGraph image will be used.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Twitter OpenGraph image')),
            ],
            options={
                'abstract': False,
            },
            bases=(app.core.models.mixins.CustomHeadlessPreviewMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='ListingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('twitter_og_title', models.CharField(blank=True, help_text='If left blank, the OpenGraph title will be used.', max_length=255, null=True, verbose_name='Twitter OpenGraph title')),
                ('twitter_og_description', models.TextField(blank=True, help_text='If left blank, the OpenGraph description will be used.', null=True, verbose_name='Twitter OpenGraph description')),
                ('short_title', models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=45, null=True, verbose_name='short title')),
                ('teaser_text', models.TextField(help_text='A short, enticing description of this page. This will appear in promos and under thumbnails around the site.', max_length=160, verbose_name='teaser text')),
                ('intro', wagtail.fields.RichTextField(help_text='1-2 sentences introducing the subject of the page, and explaining why a user should read on.', max_length=300, verbose_name='introductory text')),
                ('show_sidebar_navigation', models.BooleanField(default=True, help_text='Show a navigation sidebar of sibling pages within this section. Only applies to direct children of a section index.')),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='alerts.alert')),
                ('bookmarklet_cta', models.ForeignKey(blank=True, help_text='Select a bookmarklet CTA snippet to display on this page', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ukgwa.bookmarkletctasnippet')),
                ('search_image', models.ForeignKey(blank=True, help_text='Image that will appear when this page is shared on social media. This will default to the teaser image if left blank.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='OpenGraph image')),
                ('teaser_image', models.ForeignKey(blank=True, help_text='Image that will appear on thumbnails and promos around the site.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
                ('themed_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='alerts.themedalert')),
                ('twitter_og_image', models.ForeignKey(blank=True, help_text='If left blank, the OpenGraph image will be used.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Twitter OpenGraph image')),
            ],
            options={
                'abstract': False,
            },
            bases=(app.core.models.mixins.CustomHeadlessPreviewMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='SectionIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('twitter_og_title', models.CharField(blank=True, help_text='If left blank, the OpenGraph title will be used.', max_length=255, null=True, verbose_name='Twitter OpenGraph title')),
                ('twitter_og_description', models.TextField(blank=True, help_text='If left blank, the OpenGraph description will be used.', null=True, verbose_name='Twitter OpenGraph description')),
                ('short_title', models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=45, null=True, verbose_name='short title')),
                ('teaser_text', models.TextField(help_text='A short, enticing description of this page. This will appear in promos and under thumbnails around the site.', max_length=160, verbose_name='teaser text')),
                ('intro', wagtail.fields.RichTextField(help_text='1-2 sentences introducing the subject of the page, and explaining why a user should read on.', max_length=300, verbose_name='introductory text')),
                ('additional_links', wagtail.fields.StreamField([('link', 4)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "Leave blank to use the page's own title", 'label': 'Link text', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Required description shown beneath the link', 'label': 'Description', 'required': True}), 4: ('wagtail.blocks.StructBlock', [[('page', 0), ('title', 1), ('external_link', 2), ('description', 3)]], {})}, help_text='Optional links appended to the list of child pages. Each link can be to an internal page or an external URL.')),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='alerts.alert')),
                ('search_configuration', models.ForeignKey(blank=True, help_text='Select an archive search component to display on this page', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ukgwa.archivesearchcomponent')),
                ('search_image', models.ForeignKey(blank=True, help_text='Image that will appear when this page is shared on social media. This will default to the teaser image if left blank.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='OpenGraph image')),
                ('teaser_image', models.ForeignKey(blank=True, help_text='Image that will appear on thumbnails and promos around the site.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
                ('themed_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='alerts.themedalert')),
                ('twitter_og_image', models.ForeignKey(blank=True, help_text='If left blank, the OpenGraph image will be used.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Twitter OpenGraph image')),
            ],
            options={
                'abstract': False,
            },
            bases=(app.core.models.mixins.CustomHeadlessPreviewMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='UKGWAHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_image_caption', wagtail.fields.RichTextField(blank=True, help_text='An optional caption for hero images. This could be used for image sources or for other useful metadata.', verbose_name='hero image caption (optional)')),
                ('twitter_og_title', models.CharField(blank=True, help_text='If left blank, the OpenGraph title will be used.', max_length=255, null=True, verbose_name='Twitter OpenGraph title')),
                ('twitter_og_description', models.TextField(blank=True, help_text='If left blank, the OpenGraph description will be used.', null=True, verbose_name='Twitter OpenGraph description')),
                ('short_title', models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=45, null=True, verbose_name='short title')),
                ('teaser_text', models.TextField(help_text='A short, enticing description of this page. This will appear in promos and under thumbnails around the site.', max_length=160, verbose_name='teaser text')),
                ('intro', wagtail.fields.RichTextField(help_text='1-2 sentences introducing the subject of the page, and explaining why a user should read on.', max_length=300, verbose_name='introductory text')),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='alerts.alert')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
                ('search_configuration', models.ForeignKey(blank=True, help_text='Select an archive search component to display on this page', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ukgwa.archivesearchcomponent')),
                ('search_image', models.ForeignKey(blank=True, help_text='Image that will appear when this page is shared on social media. This will default to the teaser image if left blank.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='OpenGraph image')),
                ('teaser_image', models.ForeignKey(blank=True, help_text='Image that will appear on thumbnails and promos around the site.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
                ('themed_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='alerts.themedalert')),
                ('twitter_og_image', models.ForeignKey(blank=True, help_text='If left blank, the OpenGraph image will be used.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Twitter OpenGraph image')),
            ],
            options={
                'verbose_name': 'UKGWA Home Page',
            },
            bases=(app.core.models.mixins.CustomHeadlessPreviewMixin, 'wagtailcore.page', models.Model),
        ),
    ]
