# Generated by Django 6.0 on 2026-01-09 10:44
# Manually edited by Ian Meigh on 2026-01-09 11:30

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


def noop(apps, schema_editor):
    """No-op for forward migration"""
    pass


def populate_defaults_on_reverse(apps, schema_editor):
    """
    When rolling back this migration, populate default values for the
    featured_links_heading and featured_links fields that are being re-added.
    This prevents integrity errors when reverting to the old schema.
    """
    UKGWAHomePage = apps.get_model("ukgwa", "UKGWAHomePage")

    for page in UKGWAHomePage.objects.all():
        page.featured_links_heading = "Featured Links"
        page.featured_links = "[]"  # Empty JSON array for StreamField
        page.save(update_fields=["featured_links_heading", "featured_links"])


class Migration(migrations.Migration):
    dependencies = [
        ("ukgwa", "0001_initial"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        # Step 1: Make fields nullable so they can be safely re-added on rollback
        migrations.AlterField(
            model_name="ukgwahomepage",
            name="featured_links_heading",
            field=models.CharField(
                blank=True,
                null=True,
                help_text="A short heading for the featured links section",
                max_length=100,
                verbose_name="featured links heading text",
            ),
        ),
        migrations.AlterField(
            model_name="ukgwahomepage",
            name="featured_links",
            field=wagtail.fields.StreamField(
                [("link", 3)],
                block_lookup={
                    0: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave blank to use the page's own title",
                            "label": "Link text",
                            "required": False,
                        },
                    ),
                    2: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 0), ("title", 1), ("external_link", 2)]],
                        {},
                    ),
                },
                blank=True,
                null=True,
                help_text="Contains exactly three links. Each link can be to an internal page or an external URL.",
                verbose_name="featured links",
            ),
        ),
        # Step 2: Create the new model
        migrations.CreateModel(
            name="FeaturedLinksSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        help_text="A short heading for the featured links section",
                        max_length=100,
                        verbose_name="featured links heading text",
                    ),
                ),
                (
                    "links",
                    wagtail.fields.StreamField(
                        [("link", 3)],
                        block_lookup={
                            0: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Leave blank to use the page's own title",
                                    "label": "Link text",
                                    "required": False,
                                },
                            ),
                            2: ("wagtail.blocks.URLBlock", (), {"required": False}),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("page", 0), ("title", 1), ("external_link", 2)]],
                                {},
                            ),
                        },
                        help_text="Contains exactly three links. Each link can be to an internal page or an external URL.",
                        verbose_name="featured links",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="featured_links_sections",
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Featured links section",
                "verbose_name_plural": "Featured links sections",
            },
        ),
        # Step 3: Populate defaults if rolling back
        # Position BEFORE RemoveField so it runs AFTER AddField when reversed
        migrations.RunPython(noop, reverse_code=populate_defaults_on_reverse),
        # Step 4: Remove old fields (now nullable, so safe to re-add on rollback)
        migrations.RemoveField(
            model_name="ukgwahomepage",
            name="featured_links_heading",
        ),
        migrations.RemoveField(
            model_name="ukgwahomepage",
            name="featured_links",
        ),
    ]
