# Generated by Django 6.0 on 2026-01-07 11:25

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ukgwa", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ukgwahomepage",
            name="featured_links",
            field=wagtail.fields.StreamField(
                [("link", 3)],
                block_lookup={
                    0: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave blank to use the page's own title",
                            "label": "Link text",
                            "required": False,
                        },
                    ),
                    2: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 0), ("title", 1), ("external_link", 2)]],
                        {},
                    ),
                },
                help_text="Contains exactly three links. Each link can be to an internal page or an external URL.",
                verbose_name="featured links",
            ),
        ),
    ]
