# Generated by Django 6.0.8 on 2026-09-14 11:31
# etna:allowRemoveField

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ukgwa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atozarchivepage',
            name='twitter_og_description',
        ),
        migrations.RemoveField(
            model_name='atozarchivepage',
            name='twitter_og_image',
        ),
        migrations.RemoveField(
            model_name='atozarchivepage',
            name='twitter_og_title',
        ),
        migrations.RemoveField(
            model_name='informationpage',
            name='twitter_og_description',
        ),
        migrations.RemoveField(
            model_name='informationpage',
            name='twitter_og_image',
        ),
        migrations.RemoveField(
            model_name='informationpage',
            name='twitter_og_title',
        ),
        migrations.RemoveField(
            model_name='listingpage',
            name='twitter_og_description',
        ),
        migrations.RemoveField(
            model_name='listingpage',
            name='twitter_og_image',
        ),
        migrations.RemoveField(
            model_name='listingpage',
            name='twitter_og_title',
        ),
        migrations.RemoveField(
            model_name='sectionindexpage',
            name='twitter_og_description',
        ),
        migrations.RemoveField(
            model_name='sectionindexpage',
            name='twitter_og_image',
        ),
        migrations.RemoveField(
            model_name='sectionindexpage',
            name='twitter_og_title',
        ),
        migrations.RemoveField(
            model_name='ukgwahomepage',
            name='twitter_og_description',
        ),
        migrations.RemoveField(
            model_name='ukgwahomepage',
            name='twitter_og_image',
        ),
        migrations.RemoveField(
            model_name='ukgwahomepage',
            name='twitter_og_title',
        ),
    ]
