# Generated by Django 6.0 on 2026-01-12 14:18
# etna:allowRemoveField

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ukgwa", "0003_set_featured_header_and_links_to_empty_values"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ukgwahomepage",
            name="featured_links",
        ),
        migrations.RemoveField(
            model_name="ukgwahomepage",
            name="featured_links_heading",
        ),
        migrations.CreateModel(
            name="FeaturedLinksSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        help_text="A short heading for the featured links section",
                        max_length=100,
                        verbose_name="featured links heading text",
                    ),
                ),
                (
                    "links",
                    wagtail.fields.StreamField(
                        [("link", 3)],
                        block_lookup={
                            0: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Leave blank to use the page's own title",
                                    "label": "Link text",
                                    "required": False,
                                },
                            ),
                            2: ("wagtail.blocks.URLBlock", (), {"required": False}),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("page", 0), ("title", 1), ("external_link", 2)]],
                                {},
                            ),
                        },
                        help_text="Contains exactly three links. Each link can be to an internal page or an external URL.",
                        verbose_name="featured links",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="featured_links_sections",
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Featured links section",
                "verbose_name_plural": "Featured links sections",
            },
        ),
    ]
