# Generated by Django 6.0.1 on 2026-01-13 11:49

import app.core.models.mixins
import django.core.validators
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0003_alert_name_alter_alert_title"),
        ("images", "0013_alter_customimage_description"),
        ("ukgwa", "0005_sectionindexpage"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InformationPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "twitter_og_title",
                    models.CharField(
                        blank=True,
                        help_text="If left blank, the OpenGraph title will be used.",
                        max_length=255,
                        null=True,
                        verbose_name="Twitter OpenGraph title",
                    ),
                ),
                (
                    "twitter_og_description",
                    models.TextField(
                        blank=True,
                        help_text="If left blank, the OpenGraph description will be used.",
                        null=True,
                        verbose_name="Twitter OpenGraph description",
                    ),
                ),
                (
                    "short_title",
                    models.CharField(
                        blank=True,
                        help_text="A shorter title for use in breadcrumbs and other navigational elements, where applicable.",
                        max_length=45,
                        null=True,
                        verbose_name="short title",
                    ),
                ),
                (
                    "teaser_text",
                    models.TextField(
                        help_text="A short, enticing description of this page. This will appear in promos and under thumbnails around the site.",
                        max_length=160,
                        verbose_name="teaser text",
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(
                        help_text="1-2 sentences introducing the subject of the page, and explaining why a user should read on.",
                        max_length=300,
                        verbose_name="introductory text",
                    ),
                ),
                (
                    "featured_links_heading",
                    models.CharField(
                        help_text="A short heading for the featured links section",
                        max_length=100,
                        verbose_name="featured links heading text",
                    ),
                ),
                (
                    "featured_links",
                    wagtail.fields.StreamField(
                        [("link", 3)],
                        block_lookup={
                            0: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Leave blank to use the page's own title",
                                    "label": "Link text",
                                    "required": False,
                                },
                            ),
                            2: ("wagtail.blocks.URLBlock", (), {"required": False}),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("page", 0), ("title", 1), ("external_link", 2)]],
                                {},
                            ),
                        },
                        help_text="Contains exactly three links. Each link can be to an internal page or an external URL.",
                        verbose_name="featured links",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("sub_heading", 1),
                            ("paragraph", 3),
                            ("image", 6),
                            ("quote", 9),
                            ("youtube_video", 15),
                            ("call_to_action", 22),
                        ],
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Sub-heading", "max_length": 100},
                            ),
                            1: ("wagtail.blocks.StructBlock", [[("heading", 0)]], {}),
                            2: (
                                "app.core.blocks.paragraph.APIRichTextBlock",
                                (),
                                {"features": ["bold", "italic", "link", "ol", "ul"]},
                            ),
                            3: ("wagtail.blocks.StructBlock", [[("text", 2)]], {}),
                            4: (
                                "app.core.blocks.image.APIImageChooserBlock",
                                (),
                                {"rendition_size": "max-900x900", "required": True},
                            ),
                            5: (
                                "app.core.blocks.paragraph.APIRichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link"],
                                    "help_text": "If provided, displays directly below the image. Can be used to specify sources, transcripts or other useful metadata.",
                                    "label": "Caption (optional)",
                                    "required": False,
                                },
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 4), ("caption", 5)]],
                                {},
                            ),
                            7: (
                                "app.core.blocks.paragraph.APIRichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link", "ol", "ul"],
                                    "required": True,
                                },
                            ),
                            8: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 100, "required": False},
                            ),
                            9: (
                                "wagtail.blocks.StructBlock",
                                [[("quote", 7), ("attribution", 8)]],
                                {},
                            ),
                            10: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Title", "max_length": 100, "required": True},
                            ),
                            11: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "YouTube Video ID",
                                    "max_length": 11,
                                    "required": True,
                                    "validators": [
                                        django.core.validators.RegexValidator(
                                            message="Invalid YouTube Video ID",
                                            regex="^[a-zA-Z0-9_-]{11}$",
                                        )
                                    ],
                                },
                            ),
                            12: (
                                "app.core.blocks.image.APIImageChooserBlock",
                                (),
                                {
                                    "label": "Preview Image",
                                    "rendition_size": "fill-640x360",
                                    "required": True,
                                },
                            ),
                            13: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"label": "Transcript", "required": False},
                            ),
                            14: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "help_text": "Tick if the video has captions on YouTube",
                                    "label": "Captions available",
                                    "required": False,
                                },
                            ),
                            15: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 10),
                                        ("video_id", 11),
                                        ("preview_image", 12),
                                        ("transcript", 13),
                                        ("captions_available", 14),
                                    ]
                                ],
                                {},
                            ),
                            16: (
                                "app.core.blocks.paragraph.APIRichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link", "ol", "ul"],
                                    "max_length": 100,
                                },
                            ),
                            17: ("wagtail.blocks.CharBlock", (), {}),
                            18: (
                                "app.core.blocks.page_chooser.APIPageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            19: ("wagtail.blocks.URLBlock", (), {"required": False}),
                            20: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "help_text": "Use the accented button style",
                                    "label": "Accented",
                                    "required": False,
                                },
                            ),
                            21: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("label", 17),
                                        ("link", 18),
                                        ("external_link", 19),
                                        ("accented", 20),
                                    ]
                                ],
                                {},
                            ),
                            22: (
                                "wagtail.blocks.StructBlock",
                                [[("body", 16), ("button", 21)]],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "alert",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="alerts.alert",
                    ),
                ),
                (
                    "search_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image that will appear when this page is shared on social media. This will default to the teaser image if left blank.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                        verbose_name="OpenGraph image",
                    ),
                ),
                (
                    "teaser_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image that will appear on thumbnails and promos around the site.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
                (
                    "twitter_og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="If left blank, the OpenGraph image will be used.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                        verbose_name="Twitter OpenGraph image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                app.core.models.mixins.CustomHeadlessPreviewMixin,
                "wagtailcore.page",
                models.Model,
            ),
        ),
    ]
