# Generated by Django 6.0.1 on 2026-01-14 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0004_themedalert"),
        ("ukgwa", "0006_informationpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="informationpage",
            name="themed_alert",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="alerts.themedalert",
            ),
        ),
        migrations.AddField(
            model_name="sectionindexpage",
            name="themed_alert",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="alerts.themedalert",
            ),
        ),
        migrations.AddField(
            model_name="ukgwahomepage",
            name="themed_alert",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="alerts.themedalert",
            ),
        ),
    ]
