# Generated by Django 6.0.1 on 2026-01-20 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ukgwa", "0008_informationpage_themed_alert_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchiveSearchComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal name to identify this search component (not shown to users)",
                        max_length=255,
                        verbose_name="name",
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        help_text="The heading text displayed above the search bar (e.g. 'Web Archive Search')",
                        max_length=255,
                        verbose_name="heading",
                    ),
                ),
                (
                    "help_text",
                    models.TextField(
                        blank=True,
                        help_text="Optional guidance text displayed below the search box to help users understand what they can search for",
                        verbose_name="help text",
                    ),
                ),
                (
                    "button_text",
                    models.CharField(
                        default="Search",
                        help_text="The text displayed on the search button",
                        max_length=50,
                        verbose_name="button text",
                    ),
                ),
                (
                    "archive_type",
                    models.CharField(
                        choices=[
                            ("web", "Web Archive"),
                            ("social", "Social Media Archive"),
                        ],
                        help_text="Select whether this component searches the Web Archive or Social Media Archive",
                        max_length=20,
                        verbose_name="archive type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Archive Search Component",
                "verbose_name_plural": "Archive Search Components",
            },
        ),
        migrations.AddField(
            model_name="sectionindexpage",
            name="search_configuration",
            field=models.ForeignKey(
                blank=True,
                help_text="Select an archive search component to display on this page",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ukgwa.archivesearchcomponent",
            ),
        ),
    ]
