# Generated by Django 6.0.1 on 2026-01-20 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ukgwa", "0009_archivesearchcomponent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ukgwahomepage",
            name="search_configuration",
            field=models.ForeignKey(
                blank=True,
                help_text="Select an archive search component to display on this page",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ukgwa.archivesearchcomponent",
            ),
        ),
    ]
