# Generated by Django 6.0.1 on 2026-01-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ukgwa", "0010_ukgwahomepage_search_configuration"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchiveRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wam_id",
                    models.IntegerField(
                        db_index=True,
                        help_text="WAM database ID (unique identifier)",
                        unique=True,
                    ),
                ),
                (
                    "profile_name",
                    models.TextField(help_text="Display name of the archive record"),
                ),
                (
                    "record_url",
                    models.TextField(help_text="Original URL of the archived site"),
                ),
                (
                    "archive_link",
                    models.TextField(help_text="Link to the archived version"),
                ),
                (
                    "domain_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of domain (e.g., Domain, SocialMedia)",
                        max_length=50,
                    ),
                ),
                (
                    "first_capture_display",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable first capture date",
                        max_length=100,
                    ),
                ),
                (
                    "latest_capture_display",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable latest capture date",
                        max_length=100,
                    ),
                ),
                (
                    "ongoing",
                    models.BooleanField(
                        default=False, help_text="Whether archiving is ongoing"
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of archive record"),
                ),
                (
                    "sort_name",
                    models.TextField(
                        db_index=True,
                        help_text="Normalized name for sorting (strips 'The' prefix)",
                    ),
                ),
                (
                    "first_character",
                    models.CharField(
                        db_index=True,
                        help_text="First character for navigation: a-z, 0-9, or 'other' for symbols",
                        max_length=5,
                    ),
                ),
                (
                    "record_hash",
                    models.CharField(
                        help_text="MD5 hash of record data for change detection",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Archive record",
                "verbose_name_plural": "Archive records",
                "ordering": ["sort_name"],
                "indexes": [
                    models.Index(
                        fields=["first_character", "sort_name"],
                        name="ukgwa_archi_first_c_ef72fa_idx",
                    )
                ],
            },
        ),
    ]
