# Generated by Django 6.0.1 on 2026-01-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ukgwa", "0011_listingpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="informationpage",
            name="show_sidebar_navigation",
            field=models.BooleanField(
                default=True,
                help_text="Show a navigation sidebar of sibling pages within this section",
            ),
        ),
    ]
