# Generated by Django 6.0.1 on 2026-01-22 15:58

import app.core.models.mixins
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0004_themedalert"),
        ("images", "0013_alter_customimage_description"),
        ("ukgwa", "0011_archiverecord"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AtoZArchivePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "twitter_og_title",
                    models.CharField(
                        blank=True,
                        help_text="If left blank, the OpenGraph title will be used.",
                        max_length=255,
                        null=True,
                        verbose_name="Twitter OpenGraph title",
                    ),
                ),
                (
                    "twitter_og_description",
                    models.TextField(
                        blank=True,
                        help_text="If left blank, the OpenGraph description will be used.",
                        null=True,
                        verbose_name="Twitter OpenGraph description",
                    ),
                ),
                (
                    "short_title",
                    models.CharField(
                        blank=True,
                        help_text="A shorter title for use in breadcrumbs and other navigational elements, where applicable.",
                        max_length=45,
                        null=True,
                        verbose_name="short title",
                    ),
                ),
                (
                    "teaser_text",
                    models.TextField(
                        help_text="A short, enticing description of this page. This will appear in promos and under thumbnails around the site.",
                        max_length=160,
                        verbose_name="teaser text",
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(
                        help_text="1-2 sentences introducing the subject of the page, and explaining why a user should read on.",
                        max_length=300,
                        verbose_name="introductory text",
                    ),
                ),
                (
                    "alert",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="alerts.alert",
                    ),
                ),
                (
                    "search_configuration",
                    models.ForeignKey(
                        blank=True,
                        help_text="Select an archive search component to display on this page",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ukgwa.archivesearchcomponent",
                    ),
                ),
                (
                    "search_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image that will appear when this page is shared on social media. This will default to the teaser image if left blank.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                        verbose_name="OpenGraph image",
                    ),
                ),
                (
                    "teaser_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image that will appear on thumbnails and promos around the site.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
                (
                    "themed_alert",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="alerts.themedalert",
                    ),
                ),
                (
                    "twitter_og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="If left blank, the OpenGraph image will be used.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                        verbose_name="Twitter OpenGraph image",
                    ),
                ),
            ],
            options={
                "verbose_name": "A-Z Archive Page",
            },
            bases=(
                app.core.models.mixins.CustomHeadlessPreviewMixin,
                "wagtailcore.page",
                models.Model,
            ),
        ),
    ]
