# Generated by Django 6.0.1 on 2026-01-22 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ukgwa", "0012_atozarchivepage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="atozarchivepage",
            name="search_configuration",
        ),
    ]
