# Generated by Django 6.0.2 on 2026-02-18 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ukgwa", "0012_informationpage_show_sidebar_navigation"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookmarkletCTASnippet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal name to identify this bookmarklet snippet (not shown to users)",
                        max_length=255,
                        verbose_name="name",
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        help_text="The heading text displayed at the top of the component",
                        max_length=255,
                        verbose_name="heading",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Description text displayed below the heading",
                        verbose_name="body",
                    ),
                ),
                (
                    "button_text",
                    models.CharField(
                        default="Check UKGWA",
                        help_text="The text displayed on the CTA button",
                        max_length=50,
                        verbose_name="button text",
                    ),
                ),
                (
                    "button_link",
                    models.ForeignKey(
                        help_text="The internal page the button will take users to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bookmarklet CTA",
                "verbose_name_plural": "Bookmarklet CTA",
            },
        ),
        migrations.AddField(
            model_name="informationpage",
            name="bookmarklet_cta",
            field=models.ForeignKey(
                blank=True,
                help_text="Select a bookmarklet CTA snippet to display on this page",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ukgwa.bookmarkletctasnippet",
            ),
        ),
        migrations.AddField(
            model_name="listingpage",
            name="bookmarklet_cta",
            field=models.ForeignKey(
                blank=True,
                help_text="Select a bookmarklet CTA snippet to display on this page",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ukgwa.bookmarkletctasnippet",
            ),
        ),
    ]
