# Generated by Django 6.0.1 on 2026-01-23 12:28
# etna:allowAlterField

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ukgwa", "0013_atozarchivepage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archiverecord",
            name="first_character",
            field=models.CharField(
                db_index=True,
                help_text="First character for navigation: a-z or '0-9' for digits and symbols",
                max_length=5,
            ),
        ),
    ]
