# Generated by Django 6.0.3 on 2026-03-04 12:01
# etna:allowAlterField

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ukgwa", "0014_atozarchivepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="listingpage",
            name="show_sidebar_navigation",
            field=models.BooleanField(
                default=True,
                help_text="Show a navigation sidebar of sibling pages within this section. Only applies to direct children of a section index.",
            ),
        ),
        migrations.AlterField(
            model_name="atozarchivepage",
            name="featured_links",
            field=wagtail.fields.StreamField(
                [("link", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave blank to use the page's own title",
                            "label": "Link text",
                            "required": False,
                        },
                    ),
                    2: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 0), ("title", 1), ("external_link", 2)]],
                        {},
                    ),
                },
                help_text="Exactly three links, or leave empty to hide this section. Each link can be to an internal page or an external URL.",
                verbose_name="featured links",
            ),
        ),
        migrations.AlterField(
            model_name="atozarchivepage",
            name="featured_links_heading",
            field=models.CharField(
                blank=True,
                help_text="A short heading for the featured links section",
                max_length=100,
                verbose_name="featured links heading text",
            ),
        ),
        migrations.AlterField(
            model_name="informationpage",
            name="featured_links",
            field=wagtail.fields.StreamField(
                [("link", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave blank to use the page's own title",
                            "label": "Link text",
                            "required": False,
                        },
                    ),
                    2: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 0), ("title", 1), ("external_link", 2)]],
                        {},
                    ),
                },
                help_text="Exactly three links, or leave empty to hide this section. Each link can be to an internal page or an external URL.",
                verbose_name="featured links",
            ),
        ),
        migrations.AlterField(
            model_name="informationpage",
            name="featured_links_heading",
            field=models.CharField(
                blank=True,
                help_text="A short heading for the featured links section",
                max_length=100,
                verbose_name="featured links heading text",
            ),
        ),
        migrations.AlterField(
            model_name="informationpage",
            name="show_sidebar_navigation",
            field=models.BooleanField(
                default=True,
                help_text="Show a navigation sidebar of sibling pages within this section. Only applies to direct children of a section index.",
            ),
        ),
    ]
