# Generated by Django 6.0.2 on 2026-03-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ukgwa", "0015_alter_atozarchivepage_featured_links_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listingpage",
            name="show_sidebar_navigation",
            field=models.BooleanField(
                default=True,
                help_text="Show a navigation sidebar of sibling pages within this section",
            ),
        ),
    ]
