# Generated by Django 6.0.2 on 2026-03-04 10:33
# etna:allowAlterField

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ukgwa", "0016_listingpage_show_sidebar_navigation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="informationpage",
            name="show_sidebar_navigation",
            field=models.BooleanField(
                default=True,
                help_text="Show a navigation sidebar of sibling pages within this section. Only applies to direct children of a section index.",
            ),
        ),
        migrations.AlterField(
            model_name="listingpage",
            name="show_sidebar_navigation",
            field=models.BooleanField(
                default=True,
                help_text="Show a navigation sidebar of sibling pages within this section. Only applies to direct children of a section index.",
            ),
        ),
    ]
