# Generated by Django 6.0.2 on 2026-03-24 15:33

import django.core.validators
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ukgwa", "0016_alter_informationpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="informationpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("call_to_action", 6),
                    ("image", 9),
                    ("paragraph", 11),
                    ("quote", 17),
                    ("youtube_video", 23),
                    ("bookmarklet", 24),
                    ("content_section", 31),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "ol", "ul"],
                            "max_length": 100,
                        },
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {}),
                    2: (
                        "app.core.blocks.page_chooser.APIPageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    3: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    4: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "Use the accented button style",
                            "label": "Accented",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 1),
                                ("link", 2),
                                ("external_link", 3),
                                ("accented", 4),
                            ]
                        ],
                        {},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("body", 0), ("button", 5)]],
                        {},
                    ),
                    7: (
                        "app.core.blocks.image.APIImageChooserBlock",
                        (),
                        {"rendition_size": "max-900x900", "required": True},
                    ),
                    8: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "If provided, displays directly below the image. Can be used to specify sources, transcripts or other useful metadata.",
                            "label": "Caption (optional)",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 7), ("caption", 8)]],
                        {},
                    ),
                    10: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link", "ol", "ul"]},
                    ),
                    11: ("wagtail.blocks.StructBlock", [[("text", 10)]], {}),
                    12: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "ol", "ul"],
                            "required": True,
                        },
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "e.g. Author",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "e.g. Some Book",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    15: (
                        "app.core.blocks.page_chooser.APIPageChooserBlock",
                        (),
                        {
                            "help_text": "Reference another page published on the site",
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Add a URL here to refer to an external source",
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("quote", 12),
                                ("attribution", 13),
                                ("citation", 14),
                                ("citation_internal_link", 15),
                                ("citation_external_link", 16),
                            ]
                        ],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Title", "max_length": 100, "required": True},
                    ),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "YouTube Video ID",
                            "max_length": 11,
                            "required": True,
                            "validators": [
                                django.core.validators.RegexValidator(
                                    message="Invalid YouTube Video ID",
                                    regex="^[a-zA-Z0-9_-]{11}$",
                                )
                            ],
                        },
                    ),
                    20: (
                        "app.core.blocks.image.APIImageChooserBlock",
                        (),
                        {
                            "label": "Preview Image",
                            "rendition_size": "fill-640x360",
                            "required": True,
                        },
                    ),
                    21: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Transcript", "required": False},
                    ),
                    22: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "Tick if the video has captions on YouTube",
                            "label": "Captions available",
                            "required": False,
                        },
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 18),
                                ("video_id", 19),
                                ("preview_image", 20),
                                ("transcript", 21),
                                ("captions_available", 22),
                            ]
                        ],
                        {},
                    ),
                    24: ("wagtail.blocks.StructBlock", [[]], {}),
                    25: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Heading", "max_length": 100},
                    ),
                    26: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Sub-heading", "max_length": 100},
                    ),
                    27: ("wagtail.blocks.StructBlock", [[("heading", 26)]], {}),
                    28: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Sub-sub-heading", "max_length": 100},
                    ),
                    29: ("wagtail.blocks.StructBlock", [[("heading", 28)]], {}),
                    30: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("call_to_action", 6),
                                ("image", 9),
                                ("paragraph", 11),
                                ("quote", 17),
                                ("sub_heading", 27),
                                ("sub_sub_heading", 29),
                                ("youtube_video", 23),
                                ("bookmarklet", 24),
                            ]
                        ],
                        {"required": False},
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 25), ("content", 30)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
