# Generated by Django 6.0.1 on 2026-01-25 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ukgwa", "0017_bookmarkletctasnippet"),
    ]

    operations = [
        migrations.AddField(
            model_name="informationpage",
            name="bookmarklet_cta",
            field=models.ForeignKey(
                blank=True,
                help_text="Select a bookmarklet CTA snippet to display on this page",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ukgwa.bookmarkletctasnippet",
            ),
        ),
        migrations.AddField(
            model_name="listingpage",
            name="bookmarklet_cta",
            field=models.ForeignKey(
                blank=True,
                help_text="Select a bookmarklet CTA snippet to display on this page",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ukgwa.bookmarkletctasnippet",
            ),
        ),
    ]
