# Generated by Django 6.0.3 on 2026-03-30 14:24
# etna:allowAlterField

import django.core.validators
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ukgwa", "0018_alter_informationpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="informationpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("bookmarklet", 0),
                    ("call_to_action", 7),
                    ("document", 11),
                    ("image", 14),
                    ("paragraph", 16),
                    ("quote", 19),
                    ("youtube_video", 25),
                    ("content_section", 32),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.StructBlock", [[]], {}),
                    1: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "ol", "ul"],
                            "max_length": 100,
                        },
                    ),
                    2: ("wagtail.blocks.CharBlock", (), {}),
                    3: (
                        "app.core.blocks.page_chooser.APIPageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    4: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    5: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "Use the accented button style",
                            "label": "Accented",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 2),
                                ("link", 3),
                                ("external_link", 4),
                                ("accented", 5),
                            ]
                        ],
                        {},
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("body", 1), ("button", 6)]],
                        {},
                    ),
                    8: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": True},
                    ),
                    9: ("wagtail.blocks.StructBlock", [[("file", 8)]], {}),
                    10: ("wagtail.blocks.ListBlock", (9,), {"min_num": 1}),
                    11: ("wagtail.blocks.StructBlock", [[("documents", 10)]], {}),
                    12: (
                        "app.core.blocks.image.APIImageChooserBlock",
                        (),
                        {"rendition_size": "max-900x900", "required": True},
                    ),
                    13: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "If provided, displays directly below the image. Can be used to specify sources, transcripts or other useful metadata.",
                            "label": "Caption (optional)",
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 12), ("caption", 13)]],
                        {},
                    ),
                    15: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link", "ol", "ul"]},
                    ),
                    16: ("wagtail.blocks.StructBlock", [[("text", 15)]], {}),
                    17: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "ol", "ul"],
                            "required": True,
                        },
                    ),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 100, "required": False},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 17), ("attribution", 18)]],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Title", "max_length": 100, "required": True},
                    ),
                    21: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "YouTube Video ID",
                            "max_length": 11,
                            "required": True,
                            "validators": [
                                django.core.validators.RegexValidator(
                                    message="Invalid YouTube Video ID",
                                    regex="^[a-zA-Z0-9_-]{11}$",
                                )
                            ],
                        },
                    ),
                    22: (
                        "app.core.blocks.image.APIImageChooserBlock",
                        (),
                        {
                            "label": "Preview Image",
                            "rendition_size": "fill-640x360",
                            "required": True,
                        },
                    ),
                    23: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Transcript", "required": False},
                    ),
                    24: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "Tick if the video has captions on YouTube",
                            "label": "Captions available",
                            "required": False,
                        },
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 20),
                                ("video_id", 21),
                                ("preview_image", 22),
                                ("transcript", 23),
                                ("captions_available", 24),
                            ]
                        ],
                        {},
                    ),
                    26: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Heading", "max_length": 100},
                    ),
                    27: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Sub-heading", "max_length": 100},
                    ),
                    28: ("wagtail.blocks.StructBlock", [[("heading", 27)]], {}),
                    29: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Sub-sub-heading", "max_length": 100},
                    ),
                    30: ("wagtail.blocks.StructBlock", [[("heading", 29)]], {}),
                    31: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("bookmarklet", 0),
                                ("call_to_action", 7),
                                ("document", 11),
                                ("image", 14),
                                ("paragraph", 16),
                                ("quote", 19),
                                ("sub_heading", 28),
                                ("sub_sub_heading", 30),
                                ("youtube_video", 25),
                            ]
                        ],
                        {"required": False},
                    ),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 26), ("content", 31)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
