# Generated by Django 6.0.3 on 2026-04-09 12:20
# etna:allowAlterField

import django.core.validators
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ukgwa", "0020_alter_informationpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="informationpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("bookmarklet", 0),
                    ("call_to_action", 7),
                    ("document", 11),
                    ("image", 14),
                    ("paragraph", 16),
                    ("quote", 24),
                    ("youtube_video", 30),
                    ("content_section", 37),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.StructBlock", [[]], {}),
                    1: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "code", "ol", "ul"],
                            "max_length": 100,
                        },
                    ),
                    2: ("wagtail.blocks.CharBlock", (), {}),
                    3: (
                        "app.core.blocks.page_chooser.APIPageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    4: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    5: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "Use the accented button style",
                            "label": "Accented",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 2),
                                ("link", 3),
                                ("external_link", 4),
                                ("accented", 5),
                            ]
                        ],
                        {},
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("body", 1), ("button", 6)]],
                        {},
                    ),
                    8: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": True},
                    ),
                    9: ("wagtail.blocks.StructBlock", [[("file", 8)]], {}),
                    10: ("wagtail.blocks.ListBlock", (9,), {"min_num": 1}),
                    11: ("wagtail.blocks.StructBlock", [[("documents", 10)]], {}),
                    12: (
                        "app.core.blocks.image.APIImageChooserBlock",
                        (),
                        {"rendition_size": "max-900x900", "required": True},
                    ),
                    13: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "If provided, displays directly below the image. Can be used to specify sources, transcripts or other useful metadata.",
                            "label": "Caption (optional)",
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 12), ("caption", 13)]],
                        {},
                    ),
                    15: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link", "code", "ol", "ul"]},
                    ),
                    16: ("wagtail.blocks.StructBlock", [[("text", 15)]], {}),
                    17: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "code", "ol", "ul"],
                            "required": True,
                        },
                    ),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The name of the person being quoted. e.g. King Edward VIII",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The title of the work or document from which the quote is taken. e.g. Instrument of Abdication, 10 December 1936. Catalogue reference: PC 11/1",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    20: (
                        "app.core.blocks.page_chooser.APIPageChooserBlock",
                        (),
                        {
                            "help_text": "Reference another page published on the site",
                            "label": "Internal page",
                            "required": False,
                        },
                    ),
                    21: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Add a URL here to refer to an external source",
                            "label": "External link",
                            "required": False,
                        },
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("citation_internal_link", 20),
                                ("citation_external_link", 21),
                            ]
                        ],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("attribution", 18), ("citation", 19), ("source_link", 22)]],
                        {},
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 17), ("source", 23)]],
                        {},
                    ),
                    25: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Title", "max_length": 100, "required": True},
                    ),
                    26: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "YouTube Video ID",
                            "max_length": 11,
                            "required": True,
                            "validators": [
                                django.core.validators.RegexValidator(
                                    message="Invalid YouTube Video ID",
                                    regex="^[a-zA-Z0-9_-]{11}$",
                                )
                            ],
                        },
                    ),
                    27: (
                        "app.core.blocks.image.APIImageChooserBlock",
                        (),
                        {
                            "label": "Preview Image",
                            "rendition_size": "fill-640x360",
                            "required": True,
                        },
                    ),
                    28: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Transcript", "required": False},
                    ),
                    29: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "Tick if the video has captions on YouTube",
                            "label": "Captions available",
                            "required": False,
                        },
                    ),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 25),
                                ("video_id", 26),
                                ("preview_image", 27),
                                ("transcript", 28),
                                ("captions_available", 29),
                            ]
                        ],
                        {},
                    ),
                    31: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Heading", "max_length": 100},
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Sub-heading", "max_length": 100},
                    ),
                    33: ("wagtail.blocks.StructBlock", [[("heading", 32)]], {}),
                    34: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Sub-sub-heading", "max_length": 100},
                    ),
                    35: ("wagtail.blocks.StructBlock", [[("heading", 34)]], {}),
                    36: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("bookmarklet", 0),
                                ("call_to_action", 7),
                                ("document", 11),
                                ("image", 14),
                                ("paragraph", 16),
                                ("quote", 24),
                                ("sub_heading", 33),
                                ("sub_sub_heading", 35),
                                ("youtube_video", 30),
                            ]
                        ],
                        {"required": False},
                    ),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 31), ("content", 36)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
