# Generated by Django 5.2 on 2025-05-01 13:46

import django.db.models.deletion
import etna.ciim.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('articles', '0004_insightspage_hero_image'), ('articles', '0005_rename_title_to_heading'), ('articles', '0006_record_embed_blocks'), ('articles', '0007_add_section_block')]

    dependencies = [
        ('articles', '0003_auto_20210712_1558'),
        ('wagtailimages', '0023_add_choose_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='insightspage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='insightspage',
            name='body',
            field=wagtail.fields.StreamField([('quote', 3), ('paragraph_with_heading', 4), ('section', 6), ('featured_record', 8), ('featured_records', 11)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('heading', 0), ('quote', 1), ('attribution', 2)]], {}), 4: ('wagtail.blocks.StructBlock', [[('heading', 0), ('paragraph', 1)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Section headings must be unique within the page.', 'max_length': 100, 'required': True}), 6: ('wagtail.blocks.StructBlock', [[('heading', 5)]], {}), 7: ('etna.ciim.blocks.RecordChooserBlock', (), {}), 8: ('wagtail.blocks.StructBlock', [[('record', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': True}), 10: ('wagtail.blocks.ListBlock', (etna.ciim.blocks.RecordChooserBlock,), {}), 11: ('wagtail.blocks.StructBlock', [[('heading', 0), ('introduction', 9), ('records', 10)]], {})}, null=True),
        ),
    ]
