# Generated by Django 5.2 on 2025-05-01 13:46

import django.db.models.deletion
import etna.ciim.blocks
import etna.core.blocks.featured_content
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('articles', '0008_add_teaser_image'), ('articles', '0009_add_author_block'), ('articles', '0010_add_promoted_item'), ('articles', '0011_add_promoted_list'), ('articles', '0012_add_related_items'), ('articles', '0013_rename_introduction_to_sub_heading'), ('articles', '0014_alter_field_body')]

    dependencies = [
        ('articles', '0007_add_section_block'),
        ('wagtailimages', '0023_add_choose_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='insightsindexpage',
            name='teaser_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.RenameField(
            model_name='insightsindexpage',
            old_name='introduction',
            new_name='sub_heading',
        ),
        migrations.RenameField(
            model_name='insightspage',
            old_name='introduction',
            new_name='sub_heading',
        ),
        migrations.AlterField(
            model_name='insightspage',
            name='body',
            field=wagtail.fields.StreamField([('author', 1), ('featured_record', 3), ('featured_records', 7), ('media', 10), ('paragraph_with_heading', 12), ('promoted_item', 21), ('promoted_list', 28), ('quote', 30), ('related_items', 32), ('section', 34)], blank=True, block_lookup={0: ('wagtail.snippets.blocks.SnippetChooserBlock', ('people.Author',), {}), 1: ('wagtail.blocks.StructBlock', [[('author', 0)]], {}), 2: ('etna.ciim.blocks.RecordChooserBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('record', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': True}), 6: ('wagtail.blocks.ListBlock', (etna.ciim.blocks.RecordChooserBlock,), {}), 7: ('wagtail.blocks.StructBlock', [[('heading', 4), ('introduction', 5), ('records', 6)]], {}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'A background image for the media block'}), 9: ('etna.media.blocks.MediaChooserBlock', (), {}), 10: ('wagtail.blocks.StructBlock', [[('background_image', 8), ('media', 9)]], {}), 11: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'required': True}), 12: ('wagtail.blocks.StructBlock', [[('heading', 4), ('paragraph', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'Title of the promoted page', 'max_length': 100}), 14: ('wagtail.snippets.blocks.SnippetChooserBlock', ('categories.Category',), {}), 15: ('wagtail.blocks.DateBlock', (), {}), 16: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL for the external page', 'label': 'external URL'}), 17: ('wagtail.blocks.CharBlock', (), {'help_text': 'The button label', 'label': 'CTA label', 'max_length': 50}), 18: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'An image used to create a teaser for the promoted page'}), 19: ('wagtail.blocks.CharBlock', (), {'help_text': 'Alt text of the teaser image', 'max_length': 100}), 20: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'help_text': 'A description of the promoted page'}), 21: ('wagtail.blocks.StructBlock', [[('title', 13), ('category', 14), ('publication_date', 15), ('url', 16), ('cta_label', 17), ('teaser_image', 18), ('teaser_alt_text', 19), ('description', 20)]], {}), 22: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'required': False}), 23: ('wagtail.blocks.CharBlock', (), {'help_text': 'Title of the promoted page', 'max_length': 100, 'required': True}), 24: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'help_text': 'A description of the promoted page', 'required': False}), 25: ('wagtail.blocks.URLBlock', (), {'required': True}), 26: ('wagtail.blocks.StructBlock', [[('title', 23), ('description', 24), ('url', 25)]], {}), 27: ('wagtail.blocks.ListBlock', (26,), {}), 28: ('wagtail.blocks.StructBlock', [[('heading', 4), ('category', 14), ('summary', 22), ('promoted_items', 27)]], {}), 29: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 30: ('wagtail.blocks.StructBlock', [[('heading', 4), ('quote', 11), ('attribution', 29)]], {}), 31: ('wagtail.blocks.ListBlock', (etna.core.blocks.featured_content.RelatedItemBlock,), {}), 32: ('wagtail.blocks.StructBlock', [[('heading', 4), ('description', 4), ('related_items', 31)]], {}), 33: ('wagtail.blocks.CharBlock', (), {'help_text': 'Section headings must be unique within the page.', 'max_length': 100, 'required': True}), 34: ('wagtail.blocks.StructBlock', [[('heading', 33)]], {})}, null=True),
        ),
    ]
