# Generated by Django 3.2.9 on 2021-11-18 14:10
# etna:allowAlterField

from django.db import migrations, models
import etna.articles.blocks
import etna.media.blocks
import etna.ciim.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0026_add_accessible_image_block"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insightspage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "featured_record",
                        wagtail.blocks.StructBlock(
                            [
                                ("record", etna.ciim.blocks.RecordChooserBlock()),
                                (
                                    "image",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "image",
                                                wagtail.images.blocks.ImageChooserBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "decorative",
                                                wagtail.blocks.BooleanBlock(
                                                    default=False,
                                                    help_text='Decorative images are used for visual effect and do not add information to the content of a page. <a href="https://www.w3.org/WAI/tutorials/images/decorative/" target="_blank">"Check the guidance to see if your image is decorative</a>.',
                                                    label="Is this image decorative? <p class='field-title__subheading'>Tick the box if 'yes'</p>",
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "alt_text",
                                                wagtail.blocks.CharBlock(
                                                    help_text='Alternative (alt) text describes images when they fail to load, and is read aloud by assistive technologies. Use a maximum of 100 characters to describe your image. Decorative images do not require alt text. <a href="https://html.spec.whatwg.org/multipage/images.html#alt" target="_blank">Check the guidance for tips on writing alt text</a>.',
                                                    label="Image alternative text",
                                                    max_length=100,
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "caption",
                                                wagtail.blocks.RichTextBlock(
                                                    features=["link"],
                                                    help_text="An optional caption for non-decorative images, which will be displayed directly below the image. This could be used for image sources or for other useful metadata.",
                                                    label="Caption (optional)",
                                                    required=False,
                                                ),
                                            ),
                                        ],
                                        help_text="Add an image to be displayed with the selected record.",
                                        label="Teaser image",
                                        required=False,
                                        template="insights/blocks/images/blog-embed__image-container.html",
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "featured_records",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        label="Heading (heading level 3)",
                                        max_length=100,
                                        required=True,
                                    ),
                                ),
                                (
                                    "introduction",
                                    wagtail.blocks.CharBlock(
                                        max_length=200, required=True
                                    ),
                                ),
                                (
                                    "records",
                                    wagtail.blocks.ListBlock(
                                        etna.ciim.blocks.RecordChooserBlock
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "media",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "background_image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        help_text="A background image for the media block"
                                    ),
                                ),
                                ("media", etna.media.blocks.MediaChooserBlock()),
                            ]
                        ),
                    ),
                    (
                        "paragraph_with_heading",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading_level",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("h2", "Heading level 2"),
                                            ("h3", "Heading level 3"),
                                            ("h4", "Heading level 4"),
                                        ],
                                        help_text="Use this field to select the appropriate heading tag. Check where this component will sit in the page to ensure that it follows the correct heading order and avoids skipping levels e.g. an &lt;h4&gt; should not follow an &lt;h2&gt;. For further information, see: <a href=https://www.w3.org/WAI/tutorials/page-structure/headings target=_blank>https://www.w3.org/WAI/tutorials/page-structure/headings/</a>",
                                    ),
                                ),
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        max_length=100, required=True
                                    ),
                                ),
                                (
                                    "paragraph",
                                    wagtail.blocks.RichTextBlock(
                                        features=["bold", "italic", "link", "ul"],
                                        required=True,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "promoted_item",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Title of the promoted page",
                                        label="Title (heading level 3)",
                                        max_length=100,
                                    ),
                                ),
                                (
                                    "category",
                                    wagtail.snippets.blocks.SnippetChooserBlock(
                                        "categories.Category"
                                    ),
                                ),
                                (
                                    "publication_date",
                                    wagtail.blocks.DateBlock(required=False),
                                ),
                                (
                                    "duration",
                                    wagtail.blocks.CharBlock(
                                        help_text="Podcast or video duration. Or estimated read time of article.",
                                        label="Duration/Read time",
                                        max_length=50,
                                        required=False,
                                    ),
                                ),
                                (
                                    "url",
                                    wagtail.blocks.URLBlock(
                                        help_text="URL for the external page",
                                        label="External URL",
                                    ),
                                ),
                                (
                                    "target_blank",
                                    wagtail.blocks.BooleanBlock(
                                        label="Should this URL open in a new tab? <p style='font-size: 11px;'>Tick the box if 'yes'</p>",
                                        required=False,
                                    ),
                                ),
                                (
                                    "cta_label",
                                    wagtail.blocks.CharBlock(
                                        help_text="The text displayed on the button for your URL. If your URL links to an external site, please add the name of the site users will land on, and what they will find on this page. For example 'Watch our short film  <strong>about Shakespeare on YouTube</strong>'.",
                                        label="Call to action label",
                                        max_length=50,
                                    ),
                                ),
                                (
                                    "image",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "image",
                                                wagtail.images.blocks.ImageChooserBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "decorative",
                                                wagtail.blocks.BooleanBlock(
                                                    default=False,
                                                    help_text='Decorative images are used for visual effect and do not add information to the content of a page. <a href="https://www.w3.org/WAI/tutorials/images/decorative/" target="_blank">"Check the guidance to see if your image is decorative</a>.',
                                                    label="Is this image decorative? <p class='field-title__subheading'>Tick the box if 'yes'</p>",
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "alt_text",
                                                wagtail.blocks.CharBlock(
                                                    help_text='Alternative (alt) text describes images when they fail to load, and is read aloud by assistive technologies. Use a maximum of 100 characters to describe your image. Decorative images do not require alt text. <a href="https://html.spec.whatwg.org/multipage/images.html#alt" target="_blank">Check the guidance for tips on writing alt text</a>.',
                                                    label="Image alternative text",
                                                    max_length=100,
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "caption",
                                                wagtail.blocks.RichTextBlock(
                                                    features=["link"],
                                                    help_text="An optional caption for non-decorative images, which will be displayed directly below the image. This could be used for image sources or for other useful metadata.",
                                                    label="Caption (optional)",
                                                    required=False,
                                                ),
                                            ),
                                        ],
                                        help_text="An image used to create a teaser for the promoted page",
                                        label="Teaser image",
                                        template="insights/blocks/images/blog-embed__image-container.html",
                                    ),
                                ),
                                (
                                    "description",
                                    wagtail.blocks.RichTextBlock(
                                        features=["bold", "italic", "link"],
                                        help_text="A description of the promoted page",
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "promoted_list",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        label="Heading (heading level 3)",
                                        max_length=100,
                                        required=True,
                                    ),
                                ),
                                (
                                    "category",
                                    wagtail.snippets.blocks.SnippetChooserBlock(
                                        "categories.Category"
                                    ),
                                ),
                                (
                                    "summary",
                                    wagtail.blocks.RichTextBlock(
                                        features=["bold", "italic", "link"],
                                        required=False,
                                    ),
                                ),
                                (
                                    "promoted_items",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "title",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Title of the promoted page",
                                                        label="Heading (heading level 4)",
                                                        max_length=100,
                                                        required=True,
                                                    ),
                                                ),
                                                (
                                                    "description",
                                                    wagtail.blocks.RichTextBlock(
                                                        features=[
                                                            "bold",
                                                            "italic",
                                                            "link",
                                                        ],
                                                        help_text="A description of the promoted page",
                                                        required=False,
                                                    ),
                                                ),
                                                (
                                                    "url",
                                                    wagtail.blocks.URLBlock(
                                                        required=True
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "quote",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        max_length=100, required=False
                                    ),
                                ),
                                (
                                    "quote",
                                    wagtail.blocks.RichTextBlock(
                                        features=["bold", "italic", "link"],
                                        required=True,
                                    ),
                                ),
                                (
                                    "attribution",
                                    wagtail.blocks.CharBlock(
                                        max_length=100, required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "related_items",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        label="Heading (heading level 3)",
                                        max_length=100,
                                        required=True,
                                    ),
                                ),
                                (
                                    "description",
                                    wagtail.blocks.CharBlock(
                                        max_length=100, required=True
                                    ),
                                ),
                                (
                                    "related_items",
                                    wagtail.blocks.ListBlock(
                                        etna.core.blocks.RelatedItemBlock
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "section",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        label="Section heading (heading level 2)",
                                        max_length=100,
                                        required=True,
                                    ),
                                )
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="insightspage",
            name="hero_image_alt_text",
            field=models.CharField(
                blank=True,
                help_text='Alternative (alt) text describes images when they fail to load, and is read aloud by assistive technologies. Use a maximum of 100 characters to describe your image. Decorative images do not require alt text. <a href="https://html.spec.whatwg.org/multipage/images.html#alt" target="_blank">Check the guidance for tips on writing alt text</a>.',
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="insightspage",
            name="hero_image_caption",
            field=wagtail.fields.RichTextField(
                blank=True,
                verbose_name="hero image caption (optional)",
                help_text="An optional caption for non-decorative images, which will be displayed directly below the image. This could be used for image sources or for other useful metadata.",
            ),
        ),
    ]
