# Generated by Django 3.2.12 on 2022-03-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0032_auto_20220304_2226"),
    ]

    operations = [
        migrations.AddField(
            model_name="insightspage",
            name="insight_tag_names",
            field=models.TextField(default="", editable=False),
            preserve_default=False,
        ),
    ]
