# Generated by Django 4.0.8 on 2023-02-16 16:40

from django.db import migrations
from django.db.models import F


PAGE_MODEL_NAMES = (
    "articles.ArticleIndexPage",
    "articles.ArticlePage",
)


def migrate_forwards(apps, schema_editor):
    for model_name in PAGE_MODEL_NAMES:
        model_class = apps.get_model(*model_name.split("."))

        # update the page objects themselves
        model_class.objects.update(teaser_text=F("intro"))

        # update latest revision content
        for page in model_class.objects.all().select_related("latest_revision"):
            rev = page.latest_revision
            content = rev.content
            if "intro" not in content:
                content["intro"] = content.get("sub_heading", "")
            content["teaser_text"] = content["intro"]
            rev.content = content
            rev.save(update_fields=["content"])


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0055_rename_sub_heading_fields"),
    ]

    operations = [
        migrations.RunPython(migrate_forwards, migrations.RunPython.noop),
    ]
