# Generated by Django 4.0.8 on 2023-02-22 11:19

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0057_rename_standfirst_recordarticlepage_intro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recordarticlepage",
            name="intro",
            field=wagtail.fields.RichTextField(
                help_text="1-2 sentences introducing the subject of the page, and explaining why a user should read on.",
                max_length=300,
                verbose_name="introductory text",
            ),
        ),
    ]
