# Generated by Django 4.0.8 on 2023-02-16 16:40

from django.db import migrations


def migrate_forwards(apps, schema_editor):
    RecordArticlePage = apps.get_model("articles", "RecordArticlePage")

    for page in RecordArticlePage.objects.all().select_related("latest_revision"):
        rev = page.latest_revision
        content = rev.content
        if "intro" not in content:
            content["intro"] = content.get("standfirst", "")
        content["teaser_text"] = content["intro"]
        rev.content = content
        rev.save(update_fields=["content"])


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0058_alter_recordarticlepage_intro"),
    ]

    operations = [
        migrations.RunPython(migrate_forwards, migrations.RunPython.noop),
    ]
