# Generated by Django 4.0.8 on 2023-02-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0066_alter_articleindexpage_search_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlepage",
            name="mark_new_on_next_publish",
            field=models.BooleanField(
                default=False,
                help_text="Mark this as true before publishing, if you want to display the 'new label' for 3 weeks",
                verbose_name="display a new label on the card of this page",
            ),
        ),
        migrations.AddField(
            model_name="articlepage",
            name="newly_published_at",
            field=models.DateField(default=None, editable=False, null=True),
        ),
    ]
