# Generated by Django 4.1.7 on 2023-03-29 17:50

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0070_alter_articlepage_mark_new_on_next_publish"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordarticlepage",
            name="promoted_links",
            field=wagtail.fields.StreamField(
                [
                    (
                        "promoted_link",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "url",
                                    wagtail.blocks.URLBlock(
                                        help_text="URL for the external page",
                                        label="External URL",
                                    ),
                                ),
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Title of the promoted page",
                                        max_length=100,
                                    ),
                                ),
                                (
                                    "teaser_image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        help_text="Image that will appear on thumbnails and promos around the site."
                                    ),
                                ),
                                (
                                    "description",
                                    wagtail.blocks.CharBlock(
                                        help_text="A description of the promoted page",
                                        max_length=200,
                                    ),
                                ),
                                (
                                    "publication_date",
                                    wagtail.blocks.DateBlock(required=False),
                                ),
                                ("author", wagtail.blocks.CharBlock(required=False)),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
