# Generated by Django 4.1.7 on 2023-04-06 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("collections", "0040_timeperiodexplorerindexpage_hero_image_and_more"),
        ("articles", "0071_recordarticlepage_promoted_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordarticlepage",
            name="featured_highlight_gallery",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="collections.highlightgallerypage",
                verbose_name="featured highlight gallery",
            ),
        ),
    ]
