# Generated by Django 4.2.1 on 2023-05-30 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("articles", "0086_alter_articlepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articleindexpage",
            name="featured_article",
            field=models.ForeignKey(
                blank=True,
                help_text="Select a page to display in the featured area. This can be an Article, or Record Article.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
    ]
