# Generated by Django 4.2.1 on 2023-06-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0089_alter_articleindexpage_featured_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordarticlepage",
            name="gallery_heading",
            field=models.CharField(
                blank=True,
                help_text="Optional heading for the gallery",
                max_length=250,
                null=True,
                verbose_name="gallery heading",
            ),
        ),
    ]
