# Generated by Django 4.2.4 on 2023-08-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0096_focusedarticlepage_article_tag_names_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlepage",
            name="newly_published_at",
            field=models.DateField(
                default=None, null=True, verbose_name="Page marked as new on"
            ),
        ),
        migrations.AlterField(
            model_name="focusedarticlepage",
            name="newly_published_at",
            field=models.DateField(
                default=None, null=True, verbose_name="Page marked as new on"
            ),
        ),
        migrations.AlterField(
            model_name="recordarticlepage",
            name="newly_published_at",
            field=models.DateField(
                default=None, null=True, verbose_name="Page marked as new on"
            ),
        ),
    ]
