# Generated by Django 5.0.2 on 2024-02-22 14:20

from django.db import migrations


def set_newly_published_at(apps, schema_editor):
    models = ["ArticlePage", "FocusedArticlePage", "RecordArticlePage"]

    for model_name in models:
        Model = apps.get_model("articles", model_name)
        for page in Model.objects.all():
            if not page.newly_published_at:
                page.newly_published_at = page.first_published_at
                page.save()


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0100_remove_focusedarticlepage_author"),
        ("wagtailcore", "0091_remove_revision_submitted_for_moderation"),
    ]

    operations = [
        migrations.RunPython(set_newly_published_at),
    ]
