# Generated by Django 5.0.2 on 2024-03-19 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0102_add_record_series_block_on_article_pages"),
        ("articles", "0102_alter_articlepage_body_alter_focusedarticlepage_body"),
    ]

    operations = []
