# Generated by Django 5.0.2 on 2024-02-15 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0103_articlepage_text_field"),
        ("wagtailcore", "0091_remove_revision_submitted_for_moderation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articlepage",
            name="text_field",
        ),
        migrations.AddField(
            model_name="articlepage",
            name="super_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
                verbose_name="featured article",
            ),
        ),
    ]
