# Generated by Django 5.0.3 on 2024-03-25 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0103_alter_articlepage_body_alter_focusedarticlepage_body"),
        ("articles", "0104_alter_articlepage_body_alter_focusedarticlepage_body"),
    ]

    operations = []
