# Generated by Django 5.0.9 on 2024-09-03 15:10

import etna.records.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0109_articleindexpage_twitter_og_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("content_section", 42)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Heading", "max_length": 100},
                    ),
                    1: (
                        "etna.core.blocks.page_chooser.APIPageChooserBlock",
                        (),
                        {
                            "label": "Page",
                            "page_type": ["articles.RecordArticlePage"],
                            "required_api_fields": ["teaser_image"],
                        },
                    ),
                    2: ("wagtail.blocks.StructBlock", [[("page", 1)]], {}),
                    3: (
                        "etna.core.blocks.image.APIImageChooserBlock",
                        (),
                        {"rendition_size": "max-900x900", "required": True},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Alternative (alt) text describes images when they fail to load, and is read aloud by assistive technologies. Use a maximum of 100 characters to describe your image. <a href="https://html.spec.whatwg.org/multipage/images.html#alt" target="_blank">Check the guidance for tips on writing alt text</a>.',
                            "label": "Alternative text",
                            "max_length": 100,
                        },
                    ),
                    5: (
                        "etna.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "If provided, displays directly below the image. Can be used to specify sources, transcripts or other useful metadata.",
                            "label": "Caption (optional)",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 3), ("alt_text", 4), ("caption", 5)]],
                        {},
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "A descriptive title for the media block",
                            "required": True,
                        },
                    ),
                    8: (
                        "etna.core.blocks.image.APIImageChooserBlock",
                        (),
                        {"help_text": "A background image for the media block"},
                    ),
                    9: ("etna.media.blocks.MediaChooserBlock", (), {}),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 7), ("background_image", 8), ("media", 9)]],
                        {},
                    ),
                    11: (
                        "etna.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "link",
                                "footnotes",
                                "ol",
                                "ul",
                            ]
                        },
                    ),
                    12: ("wagtail.blocks.StructBlock", [[("text", 11)]], {}),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Title of the promoted page",
                            "label": "Title",
                            "max_length": 100,
                        },
                    ),
                    14: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("blog", "Blog post"),
                                ("podcast", "Podcast"),
                                ("video", "Video"),
                                ("video-external", "External video"),
                                ("external-link", "External link"),
                            ],
                            "label": "Category",
                        },
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "This is a free text field. Please enter date as per agreed format: 14 April 2021",
                            "required": False,
                        },
                    ),
                    16: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Podcast or video duration.",
                            "label": "Duration",
                            "max_length": 50,
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "URL for the external page",
                            "label": "External URL",
                        },
                    ),
                    19: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "label": "Should this URL open in a new tab? <p style='font-size: 11px;'>Tick the box if 'yes'</p>",
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The text displayed on the button for your URL. If your URL links to an external site, please add the name of the site users will land on, and what they will find on this page. For example 'Watch our short film  <strong>about Shakespeare on YouTube</strong>'.",
                            "label": "Call to action label",
                            "max_length": 50,
                        },
                    ),
                    21: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": 'Decorative images are used for visual effect and do not add information to the content of a page. <a href="https://www.w3.org/WAI/tutorials/images/decorative/" target="_blank">"Check the guidance to see if your image is decorative</a>.',
                            "label": "Is this image decorative? <p class='field-title__subheading'>Tick the box if 'yes'</p>",
                            "required": False,
                        },
                    ),
                    22: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Alternative (alt) text describes images when they fail to load, and is read aloud by assistive technologies. Use a maximum of 100 characters to describe your image. Decorative images do not require alt text. <a href="https://html.spec.whatwg.org/multipage/images.html#alt" target="_blank">Check the guidance for tips on writing alt text</a>.',
                            "label": "Image alternative text",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 3), ("decorative", 21), ("alt_text", 22)]],
                        {
                            "label": "Teaser image",
                            "template": "articles/blocks/images/blog-embed__image-container.html",
                        },
                    ),
                    24: (
                        "etna.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "footnotes"],
                            "help_text": "A description of the promoted page",
                        },
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 13),
                                ("category", 14),
                                ("publication_date", 15),
                                ("author", 16),
                                ("duration", 17),
                                ("url", 18),
                                ("target_blank", 19),
                                ("cta_label", 20),
                                ("image", 23),
                                ("description", 24),
                            ]
                        ],
                        {},
                    ),
                    26: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("categories.Category",),
                        {},
                    ),
                    27: (
                        "etna.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "footnotes"],
                            "required": False,
                        },
                    ),
                    28: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The title of the target page",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    29: (
                        "etna.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "footnotes"],
                            "help_text": "A description of the target page",
                            "required": False,
                        },
                    ),
                    30: ("wagtail.blocks.URLBlock", (), {"required": True}),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 28), ("description", 29), ("url", 30)]],
                        {},
                    ),
                    32: ("wagtail.blocks.ListBlock", (31,), {}),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [[("category", 26), ("summary", 27), ("promoted_items", 32)]],
                        {},
                    ),
                    34: (
                        "etna.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "footnotes"],
                            "required": True,
                        },
                    ),
                    35: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 100, "required": False},
                    ),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 34), ("attribution", 35)]],
                        {},
                    ),
                    37: (
                        "wagtail.blocks.ListBlock",
                        (etna.records.blocks.RecordLinkBlock,),
                        {"label": "Items"},
                    ),
                    38: ("wagtail.blocks.StructBlock", [[("items", 37)]], {}),
                    39: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Sub-heading", "max_length": 100},
                    ),
                    40: ("wagtail.blocks.StructBlock", [[("heading", 39)]], {}),
                    41: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("featured_record_article", 2),
                                ("image", 6),
                                ("media", 10),
                                ("paragraph", 12),
                                ("promoted_item", 25),
                                ("promoted_list", 33),
                                ("quote", 36),
                                ("record_links", 38),
                                ("sub_heading", 40),
                            ]
                        ],
                        {"required": False},
                    ),
                    42: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("content", 41)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="focusedarticlepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("content_section", 42)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Heading", "max_length": 100},
                    ),
                    1: (
                        "etna.core.blocks.page_chooser.APIPageChooserBlock",
                        (),
                        {
                            "label": "Page",
                            "page_type": ["articles.RecordArticlePage"],
                            "required_api_fields": ["teaser_image"],
                        },
                    ),
                    2: ("wagtail.blocks.StructBlock", [[("page", 1)]], {}),
                    3: (
                        "etna.core.blocks.image.APIImageChooserBlock",
                        (),
                        {"rendition_size": "max-900x900", "required": True},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Alternative (alt) text describes images when they fail to load, and is read aloud by assistive technologies. Use a maximum of 100 characters to describe your image. <a href="https://html.spec.whatwg.org/multipage/images.html#alt" target="_blank">Check the guidance for tips on writing alt text</a>.',
                            "label": "Alternative text",
                            "max_length": 100,
                        },
                    ),
                    5: (
                        "etna.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "If provided, displays directly below the image. Can be used to specify sources, transcripts or other useful metadata.",
                            "label": "Caption (optional)",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 3), ("alt_text", 4), ("caption", 5)]],
                        {},
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "A descriptive title for the media block",
                            "required": True,
                        },
                    ),
                    8: (
                        "etna.core.blocks.image.APIImageChooserBlock",
                        (),
                        {"help_text": "A background image for the media block"},
                    ),
                    9: ("etna.media.blocks.MediaChooserBlock", (), {}),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 7), ("background_image", 8), ("media", 9)]],
                        {},
                    ),
                    11: (
                        "etna.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "link",
                                "footnotes",
                                "ol",
                                "ul",
                            ]
                        },
                    ),
                    12: ("wagtail.blocks.StructBlock", [[("text", 11)]], {}),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Title of the promoted page",
                            "label": "Title",
                            "max_length": 100,
                        },
                    ),
                    14: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("blog", "Blog post"),
                                ("podcast", "Podcast"),
                                ("video", "Video"),
                                ("video-external", "External video"),
                                ("external-link", "External link"),
                            ],
                            "label": "Category",
                        },
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "This is a free text field. Please enter date as per agreed format: 14 April 2021",
                            "required": False,
                        },
                    ),
                    16: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Podcast or video duration.",
                            "label": "Duration",
                            "max_length": 50,
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "URL for the external page",
                            "label": "External URL",
                        },
                    ),
                    19: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "label": "Should this URL open in a new tab? <p style='font-size: 11px;'>Tick the box if 'yes'</p>",
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The text displayed on the button for your URL. If your URL links to an external site, please add the name of the site users will land on, and what they will find on this page. For example 'Watch our short film  <strong>about Shakespeare on YouTube</strong>'.",
                            "label": "Call to action label",
                            "max_length": 50,
                        },
                    ),
                    21: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": 'Decorative images are used for visual effect and do not add information to the content of a page. <a href="https://www.w3.org/WAI/tutorials/images/decorative/" target="_blank">"Check the guidance to see if your image is decorative</a>.',
                            "label": "Is this image decorative? <p class='field-title__subheading'>Tick the box if 'yes'</p>",
                            "required": False,
                        },
                    ),
                    22: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Alternative (alt) text describes images when they fail to load, and is read aloud by assistive technologies. Use a maximum of 100 characters to describe your image. Decorative images do not require alt text. <a href="https://html.spec.whatwg.org/multipage/images.html#alt" target="_blank">Check the guidance for tips on writing alt text</a>.',
                            "label": "Image alternative text",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 3), ("decorative", 21), ("alt_text", 22)]],
                        {
                            "label": "Teaser image",
                            "template": "articles/blocks/images/blog-embed__image-container.html",
                        },
                    ),
                    24: (
                        "etna.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "footnotes"],
                            "help_text": "A description of the promoted page",
                        },
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 13),
                                ("category", 14),
                                ("publication_date", 15),
                                ("author", 16),
                                ("duration", 17),
                                ("url", 18),
                                ("target_blank", 19),
                                ("cta_label", 20),
                                ("image", 23),
                                ("description", 24),
                            ]
                        ],
                        {},
                    ),
                    26: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("categories.Category",),
                        {},
                    ),
                    27: (
                        "etna.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "footnotes"],
                            "required": False,
                        },
                    ),
                    28: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The title of the target page",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    29: (
                        "etna.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "footnotes"],
                            "help_text": "A description of the target page",
                            "required": False,
                        },
                    ),
                    30: ("wagtail.blocks.URLBlock", (), {"required": True}),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 28), ("description", 29), ("url", 30)]],
                        {},
                    ),
                    32: ("wagtail.blocks.ListBlock", (31,), {}),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [[("category", 26), ("summary", 27), ("promoted_items", 32)]],
                        {},
                    ),
                    34: (
                        "etna.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "footnotes"],
                            "required": True,
                        },
                    ),
                    35: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 100, "required": False},
                    ),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 34), ("attribution", 35)]],
                        {},
                    ),
                    37: (
                        "wagtail.blocks.ListBlock",
                        (etna.records.blocks.RecordLinkBlock,),
                        {"label": "Items"},
                    ),
                    38: ("wagtail.blocks.StructBlock", [[("items", 37)]], {}),
                    39: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Sub-heading", "max_length": 100},
                    ),
                    40: ("wagtail.blocks.StructBlock", [[("heading", 39)]], {}),
                    41: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("featured_record_article", 2),
                                ("image", 6),
                                ("media", 10),
                                ("paragraph", 12),
                                ("promoted_item", 25),
                                ("promoted_list", 33),
                                ("quote", 36),
                                ("record_links", 38),
                                ("sub_heading", 40),
                            ]
                        ],
                        {"required": False},
                    ),
                    42: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("content", 41)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
