# Generated by Django 5.0.8 on 2024-10-22 10:10
# etna:allowRemoveField

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0110_alter_articlepage_body_alter_focusedarticlepage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articleindexpage",
            name="uuid",
        ),
        migrations.RemoveField(
            model_name="articlepage",
            name="uuid",
        ),
        migrations.RemoveField(
            model_name="focusedarticlepage",
            name="uuid",
        ),
        migrations.RemoveField(
            model_name="recordarticlepage",
            name="uuid",
        ),
    ]
