# Generated by Django 5.1.2 on 2024-12-19 16:48
# etna:allowRemoveField

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0112_alter_articlepage_body_alter_focusedarticlepage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articlepage",
            name="mark_new_on_next_publish",
        ),
        migrations.RemoveField(
            model_name="articlepage",
            name="newly_published_at",
        ),
        migrations.RemoveField(
            model_name="focusedarticlepage",
            name="mark_new_on_next_publish",
        ),
        migrations.RemoveField(
            model_name="focusedarticlepage",
            name="newly_published_at",
        ),
        migrations.RemoveField(
            model_name="recordarticlepage",
            name="mark_new_on_next_publish",
        ),
        migrations.RemoveField(
            model_name="recordarticlepage",
            name="newly_published_at",
        ),
        migrations.AddField(
            model_name="articlepage",
            name="published_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="The date the page was published to the public.",
                verbose_name="Published date",
            ),
        ),
        migrations.AddField(
            model_name="focusedarticlepage",
            name="published_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="The date the page was published to the public.",
                verbose_name="Published date",
            ),
        ),
        migrations.AddField(
            model_name="recordarticlepage",
            name="published_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="The date the page was published to the public.",
                verbose_name="Published date",
            ),
        ),
    ]
