# Generated by Django 5.1.2 on 2024-12-19 17:51
# etna:allowRemoveField

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0113_remove_articlepage_mark_new_on_next_publish_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articlepage",
            name="mark_new_on_next_publish",
        ),
        migrations.RemoveField(
            model_name="articlepage",
            name="newly_published_at",
        ),
        migrations.RemoveField(
            model_name="focusedarticlepage",
            name="mark_new_on_next_publish",
        ),
        migrations.RemoveField(
            model_name="focusedarticlepage",
            name="newly_published_at",
        ),
        migrations.RemoveField(
            model_name="recordarticlepage",
            name="mark_new_on_next_publish",
        ),
        migrations.RemoveField(
            model_name="recordarticlepage",
            name="newly_published_at",
        ),
    ]
