# Generated by Django 5.0.8 on 2024-10-21 10:27

import django.core.validators
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="etnamedia",
            name="chapters",
            field=wagtail.fields.StreamField(
                [("chapter", 3)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "blank": True,
                            "default": 0,
                            "label": "Time in seconds",
                            "validators": [django.core.validators.MinValueValidator(0)],
                        },
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {"max_length": 20}),
                    2: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"features": ["bold", "italic"], "required": False},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("time", 0), ("heading", 1), ("transcript", 2)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
