# Generated by Django 6.0.7 on 2026-08-07 15:23
# etna:allowAlterField

import app.media.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etnamedia',
            name='duration',
            field=app.media.fields.MediaDurationField(blank=True, default=0, help_text='Enter duration as HH:MM:SS.', verbose_name='duration'),
        ),
    ]
