# Generated by Django 6.0.8 on 2026-08-17 09:50

import app.media.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etnamedia',
            name='duration',
            field=app.media.blocks.MediaTimeField(blank=True, help_text='Duration of the media in HH:MM:SS format.', max_length=8, null=True, verbose_name='duration'),
        ),
    ]
