# Generated by Django 5.2.4 on 2025-08-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_etnamedia_audio_described_file_etnamedia_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='etnamedia',
            name='alternate_version_link',
            field=models.URLField(blank=True, help_text='Link to an alternate version of the media.', null=True, verbose_name='alternate version link'),
        ),
        migrations.AddField(
            model_name='etnamedia',
            name='alternate_version_type',
            field=models.CharField(blank=True, choices=[('audio_described', 'Audio Described'), ('subtitled', 'Subtitled')], help_text='The type of the alternate version.', max_length=20, null=True, verbose_name='alternate version type'),
        ),
    ]
