# Generated by Django 6.0.6 on 2026-07-28 14:17
# etna:allowAlterField

import app.media.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_alter_etnamedia_chapters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etnamedia',
            name='duration',
            field=app.media.fields.MediaDurationField(blank=True, default=0, help_text='Enter duration as HH:MM:SS.', verbose_name='duration'),
        ),
    ]
