services:
  app:
    build:
      context: .
      args:
        IMAGE: ghcr.io/nationalarchives/tna-python-dev
        IMAGE_TAG: preview
    depends_on:
      - db
      - redis
    ports:
      - 8000:8080
    environment:
      - ALLOWED_HOSTS=localhost,host.docker.internal,wagtail.localhost
      - DEBUG=True
      - DATABASE_HOST=db
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DJANGO_SETTINGS_MODULE=config.settings.develop
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@tna.dev
      - ENVIRONMENT_NAME=local
      - EMAIL_HOST
      - EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD
      - MEDIA_PAGE_URL=https://localhost
      - NEW_LABEL_DISPLAY_FOR_DAYS=21
      - OIDC_PROVIDER_ID=entra
      - OIDC_CLIENT_ID=9f47d0b5-0fdc-43e2-9910-6eef19457ebf
      - OIDC_DISCOVERY_URL=https://login.microsoftonline.com/f99512c1-fd9f-4475-9896-9a0b3cdc50ec/v2.0/.well-known/openid-configuration
      - OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
      - OIDC_SCOPES=openid profile email
      - OIDC_REDIRECT_URI=https://dev-wagtail.nationalarchives.gov.uk/accounts/oidc/entra/login/callback/
      - OIDC_GROUP_CLAIM=groups
      - REDIS_URL=redis://redis:6379/0
      - ROSETTA_API_URL=${ROSETTA_API_URL}
      - SECRET_KEY=abc123
      - WAGTAIL_2FA_REQUIRED=False
      - WAGTAILAPI_AUTHENTICATION
      - WAGTAILADMIN_BASE_URL=http://localhost:8000
      - WAGTAILAPI_BASE_URL=http://host.docker.internal:8000
      - WAGTAILAPI_MEDIA_BASE_URL=https://localhost
    volumes:
      - ./:/app
      - media:/media
    healthcheck:
      start_period: 10s
      start_interval: 2s

  db:
    image: postgres:15.18
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql

  redis:
    image: redis:latest

  docs:
    image: squidfunk/mkdocs-material
    volumes:
      - .:/docs
    ports:
      - 8001:8000

  schemas:
    image: nginx:latest
    volumes:
      - ./schemas:/usr/share/nginx/html:ro
    ports:
      - 65493:80

volumes:
  media:
  pgdata:
