[tool.poetry]
name = "ds-wagtail"
version = "0.1.0"
description = ""
authors = ["James Biggs <james.biggs@nationalarchives.gov.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
django = "6.0.8"
django-allauth = "65.19.1"
django-birdbath = "2.0.1"
django-redis = "7.0.0"
django-taggit = "6.1.0"
pillow-heif = "1.5.0"
psycopg2-binary = "2.9.12"
python = "^3.14"
python-magic = "0.4.27"
sentry-sdk = "2.68.0"
wagtail = "7.4.3"
wagtail-factories = "4.5.0"
wagtail-font-awesome-svg = "2.0.0"
wagtailmedia = "0.18.1"
wagtail-headless-preview = "0.9.0"
whitenoise = "6.12.0"
boto3 = "1.43.74"
wagtail-2fa = "1.8.0"
tna-frontend-jinja = "1.2.0"
tna-utilities = "1.6.0"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
responses = "0.26.2"
pytest-django = "4.14.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings.test"

[solver]
min-release-age = 7