# Generated by Django 4.2.5 on 2023-09-28 15:08

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0008_alter_customimagerendition_file"),
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("whatson", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Speaker",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "speaker_name",
                    models.CharField(
                        blank=True,
                        help_text="The name of the speaker.",
                        max_length=100,
                        null=True,
                        verbose_name="speaker name",
                    ),
                ),
                (
                    "speaker_description",
                    models.CharField(
                        blank=True,
                        help_text="The description of the speaker.",
                        max_length=200,
                        null=True,
                        verbose_name="speaker description",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speaker_information",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "speaker_image",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Host",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "host_name",
                    models.CharField(
                        blank=True,
                        help_text="The name of the host.",
                        max_length=100,
                        null=True,
                        verbose_name="host name",
                    ),
                ),
                (
                    "host_description",
                    models.CharField(
                        blank=True,
                        help_text="The description of the host.",
                        max_length=200,
                        null=True,
                        verbose_name="host description",
                    ),
                ),
                (
                    "host_image",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="host_information",
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
