# Generated by Django 4.2.5 on 2023-10-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("whatson", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventpage",
            name="registration_cost",
        ),
        migrations.AddField(
            model_name="eventpage",
            name="eventbrite_id",
            field=models.CharField(
                blank=True, editable=False, max_length=255, verbose_name="eventbrite ID"
            ),
        ),
        migrations.AddField(
            model_name="eventpage",
            name="max_price",
            field=models.IntegerField(
                default=0, editable=False, verbose_name="maximum price"
            ),
        ),
        migrations.AddField(
            model_name="eventpage",
            name="min_price",
            field=models.IntegerField(
                default=0, editable=False, verbose_name="minimum price"
            ),
        ),
    ]
