# Generated by Django 4.2.6 on 2023-10-24 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0008_alter_customimagerendition_file"),
        ("whatson", "0002_whatsonpage_featured_event"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventpage",
            name="registration_cost",
        ),
        migrations.AddField(
            model_name="eventpage",
            name="eventbrite_id",
            field=models.CharField(
                editable=False, max_length=255, null=True, verbose_name="eventbrite ID"
            ),
        ),
        migrations.AddField(
            model_name="eventpage",
            name="max_price",
            field=models.IntegerField(
                default=0, editable=False, verbose_name="maximum price"
            ),
        ),
        migrations.AddField(
            model_name="eventpage",
            name="min_price",
            field=models.IntegerField(
                default=0, editable=False, verbose_name="minimum price"
            ),
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="event_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="whatson.eventtype",
            ),
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="lead_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
            ),
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="short_title",
            field=models.CharField(
                blank=True,
                help_text="A short title for the event. This will be used in the event listings.",
                max_length=50,
                verbose_name="short title",
            ),
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="venue_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("online", "Online"),
                    ("in_person", "In person"),
                    ("hybrid", "Hybrid"),
                ],
                default="in_person",
                max_length=15,
                verbose_name="venue type",
            ),
        ),
    ]
