# Generated by Django 4.2.5 on 2023-09-28 15:18

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("whatson", "0002_speaker_host"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventpage",
            name="venue_address",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="The address of the venue.",
                null=True,
                verbose_name="venue address",
            ),
        ),
        migrations.AddField(
            model_name="eventpage",
            name="venue_space_name",
            field=models.CharField(
                blank=True,
                help_text="The name of the venue space.",
                max_length=255,
                null=True,
                verbose_name="venue space name",
            ),
        ),
        migrations.AddField(
            model_name="eventpage",
            name="venue_type",
            field=models.CharField(
                choices=[
                    ("online", "Online"),
                    ("in_person", "In person"),
                    ("hybrid", "Hybrid"),
                ],
                default="in_person",
                help_text="The type of venue for the event.",
                max_length=15,
                verbose_name="venue type",
            ),
        ),
        migrations.AddField(
            model_name="eventpage",
            name="venue_website",
            field=models.URLField(
                blank=True,
                help_text="The website for the venue.",
                max_length=255,
                null=True,
                verbose_name="venue website",
            ),
        ),
        migrations.AddField(
            model_name="eventpage",
            name="video_conference_info",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Information about the video conference.",
                null=True,
                verbose_name="video conference info",
            ),
        ),
    ]
