# Generated by Django 4.2.5 on 2023-09-29 13:10

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        (
            "whatson",
            "0002_rename_access_type_audiencetypeorderable_audience_type_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="EventSession",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "session_start_date",
                    models.DateTimeField(
                        help_text="The date and time the session starts.",
                        null=True,
                        verbose_name="session start date",
                    ),
                ),
                (
                    "session_end_date",
                    models.DateTimeField(
                        help_text="The date and time the session ends.",
                        null=True,
                        verbose_name="session end date",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_sessions",
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
