# Generated by Django 4.2.5 on 2023-09-28 15:22

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("whatson", "0003_eventpage_venue_address_eventpage_venue_space_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "paragraph",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "text",
                                    wagtail.blocks.RichTextBlock(
                                        features=["bold", "italic", "link", "ol", "ul"]
                                    ),
                                )
                            ]
                        ),
                    )
                ],
                blank=True,
                help_text="Add content for this page",
                null=True,
                use_json_field=True,
            ),
        ),
    ]
