# Generated by Django 4.2.7 on 2023-11-08 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authors", "0002_authorindexpage_authorpage_authortag_delete_author"),
        ("whatson", "0004_eventsession_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventhost",
            name="host_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="authors.authorpage",
            ),
        ),
        migrations.AddField(
            model_name="eventspeaker",
            name="speaker_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="authors.authorpage",
            ),
        ),
        migrations.AlterField(
            model_name="eventhost",
            name="name",
            field=models.CharField(blank=True, max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="eventspeaker",
            name="name",
            field=models.CharField(blank=True, max_length=100, verbose_name="name"),
        ),
    ]
