# Generated by Django 4.2.7 on 2023-11-22 15:49

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("authors", "0002_authorindexpage_authorpage_authortag_delete_author"),
        ("whatson", "0004_eventsession_session_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventhost",
            options={},
        ),
        migrations.AlterModelOptions(
            name="eventspeaker",
            options={},
        ),
        migrations.RemoveField(
            model_name="eventhost",
            name="sort_order",
        ),
        migrations.RemoveField(
            model_name="eventspeaker",
            name="sort_order",
        ),
        migrations.AddField(
            model_name="eventhost",
            name="person_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="authors.authorpage",
            ),
        ),
        migrations.AddField(
            model_name="eventspeaker",
            name="person_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="authors.authorpage",
            ),
        ),
        migrations.AlterField(
            model_name="eventhost",
            name="name",
            field=models.CharField(blank=True, max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="eventhost",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hosts",
                to="whatson.eventpage",
            ),
        ),
        migrations.AlterField(
            model_name="eventspeaker",
            name="name",
            field=models.CharField(blank=True, max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="eventspeaker",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="speakers",
                to="whatson.eventpage",
            ),
        ),
    ]
