# Generated by Django 4.2.5 on 2023-09-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("whatson", "0004_eventpage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventpage",
            name="event_end_date",
            field=models.DateTimeField(
                help_text="The date and time the event ends.",
                null=True,
                verbose_name="event end date",
            ),
        ),
        migrations.AddField(
            model_name="eventpage",
            name="event_start_date",
            field=models.DateTimeField(
                help_text="The date and time the event starts.",
                null=True,
                verbose_name="event start date",
            ),
        ),
    ]
