# Generated by Django 4.2.7 on 2023-11-22 15:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("whatson", "0005_alter_eventpage_venue_type"),
        ("whatson", "0005_exhibitionpage_exhibitionhighlight"),
    ]

    operations = []
