# Generated by Django 5.0.2 on 2024-02-28 13:16

import etna.core.blocks.paragraph
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("whatson", "0008_eventpage_need_to_know_button_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventpage",
            name="contact_info",
            field=etna.core.blocks.paragraph.APIRichTextField(
                blank=True,
                help_text="Information about who to contact regarding the event.",
                verbose_name="contact info",
            ),
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="description",
            field=etna.core.blocks.paragraph.APIRichTextField(
                blank=True,
                help_text="A description of the event.",
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="intro",
            field=etna.core.blocks.paragraph.APIRichTextField(
                help_text="1-2 sentences introducing the subject of the page, and explaining why a user should read on.",
                max_length=300,
                verbose_name="introductory text",
            ),
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="registration_info",
            field=etna.core.blocks.paragraph.APIRichTextField(
                blank=True,
                help_text="Additional information about how to register for the event.",
                verbose_name="registration info",
            ),
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="target_audience",
            field=etna.core.blocks.paragraph.APIRichTextField(
                blank=True,
                help_text="Info about the target audience for the event.",
                verbose_name="who it's for",
            ),
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="useful_info",
            field=etna.core.blocks.paragraph.APIRichTextField(
                blank=True,
                help_text="Useful information about the event.",
                verbose_name="need to know",
            ),
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="venue_address",
            field=etna.core.blocks.paragraph.APIRichTextField(
                blank=True,
                help_text="The address of the venue.",
                verbose_name="venue address",
            ),
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="video_conference_info",
            field=etna.core.blocks.paragraph.APIRichTextField(
                blank=True,
                help_text="Useful information about the video conference.",
                verbose_name="video conference info",
            ),
        ),
        migrations.AlterField(
            model_name="exhibitionpage",
            name="description",
            field=etna.core.blocks.paragraph.APIRichTextField(
                help_text="A description of the exhibition.", verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="exhibitionpage",
            name="intro",
            field=etna.core.blocks.paragraph.APIRichTextField(
                help_text="1-2 sentences introducing the subject of the page, and explaining why a user should read on.",
                max_length=300,
                verbose_name="introductory text",
            ),
        ),
        migrations.AlterField(
            model_name="exhibitionpage",
            name="need_to_know",
            field=etna.core.blocks.paragraph.APIRichTextField(
                blank=True,
                help_text="Useful information about the exhibition.",
                verbose_name="need to know",
            ),
        ),
        migrations.AlterField(
            model_name="whatsonpage",
            name="intro",
            field=etna.core.blocks.paragraph.APIRichTextField(
                help_text="1-2 sentences introducing the subject of the page, and explaining why a user should read on.",
                max_length=300,
                verbose_name="introductory text",
            ),
        ),
    ]
