# Generated by Django 5.1.2 on 2024-11-26 16:32

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatson", "0015_exhibitionpage_related_pages_exhibitionpage_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="exhibitionpage",
            name="open_days",
            field=models.CharField(
                blank=True,
                help_text="The days the exhibition is open, e.g. Tuesday - Sunday.",
                max_length=255,
                verbose_name="open days",
            ),
        ),
        migrations.AddField(
            model_name="exhibitionpage",
            name="shop",
            field=wagtail.fields.StreamField(
                [("shop", 4)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Title", "max_length": 100},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Description", "max_length": 255},
                    ),
                    2: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "The URL to the shop collection", "label": "URL"},
                    ),
                    3: (
                        "etna.core.blocks.image.APIImageChooserBlock",
                        (),
                        {"label": "Background image", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("description", 1),
                                ("url", 2),
                                ("background_image", 3),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
