# Generated by Django 5.1.5 on 2025-01-29 16:14
# etna:allowAlterField

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatson', '0017_remove_exhibitionpage_location_link_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitionpage',
            name='short_title',
            field=models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=30, null=True, verbose_name='short title'),
        ),
        migrations.AddField(
            model_name='whatsonpage',
            name='short_title',
            field=models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=30, null=True, verbose_name='short title'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='short_title',
            field=models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=30, null=True, verbose_name='short title'),
        ),
    ]
