# Generated by Django 5.1.6 on 2025-03-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatson', '0019_exhibitionpage_related_pages_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='eventbrite_id',
            field=models.CharField(max_length=255, null=True, verbose_name='eventbrite ID'),
        ),
    ]
