# Generated by Django 5.1.6 on 2025-03-19 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatson', '0020_alter_eventpage_eventbrite_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='min_price',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='start_date',
        ),
        migrations.DeleteModel(
            name='EventSession',
        ),
    ]
