# Generated by Django 5.2 on 2025-05-15 12:56

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatson', '0021_alter_exhibitionpage_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventaccesstype',
            name='access_type',
        ),
        migrations.RemoveField(
            model_name='eventaccesstype',
            name='page',
        ),
        migrations.RenameField(
            model_name='eventpage',
            old_name='lead_image',
            new_name='hero_image',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='need_to_know_button_link',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='need_to_know_button_text',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='registration_info',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='registration_url',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='target_audience',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='useful_info',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='venue_address',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='venue_directions',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='venue_space_name',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='venue_type',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='venue_website',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='video_conference_info',
        ),
        migrations.AddField(
            model_name='eventpage',
            name='audience_detail',
            field=models.CharField(blank=True, help_text='The text for the audience detail section.', max_length=40, verbose_name='audience detail'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='audience_heading',
            field=models.CharField(blank=True, help_text='The heading for the audience detail section.', max_length=40, verbose_name='audience heading'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='booking_details',
            field=wagtail.fields.RichTextField(help_text='Information about how to book tickets for the exhibition.', max_length=40, null=True, verbose_name='booking details'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='hero_image_caption',
            field=wagtail.fields.RichTextField(blank=True, help_text='An optional caption for hero images. This could be used for image sources or for other useful metadata.', verbose_name='hero image caption (optional)'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='max_price',
            field=models.FloatField(default=0, verbose_name='maximum price'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='min_price',
            field=models.FloatField(default=0, verbose_name='minimum price'),
        ),
        migrations.DeleteModel(
            name='AccessType',
        ),
        migrations.DeleteModel(
            name='EventAccessType',
        ),
    ]
