# Generated by Django 5.2 on 2025-05-15 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_location'),
        ('whatson', '0022_remove_eventaccesstype_access_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='location',
            field=models.ForeignKey(blank=True, help_text='The location of the event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.location', verbose_name='location'),
        ),
    ]
