# Generated by Django 5.2.1 on 2025-06-16 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('whatson', '0023_displaypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsoncategorypage',
            name='featured_page',
            field=models.ForeignKey(blank=True, help_text='The page to feature on the category page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='featured page'),
        ),
        migrations.AddField(
            model_name='whatsonseriespage',
            name='featured_page',
            field=models.ForeignKey(blank=True, help_text='The page to feature on the series page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='featured page'),
        ),
    ]
