# Generated by Django 5.2 on 2025-07-09 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('whatson', '0023_rename_eventcategory_eventtype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='displaypage',
            name='audience_detail',
        ),
        migrations.RemoveField(
            model_name='displaypage',
            name='audience_heading',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='audience_detail',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='audience_heading',
        ),
        migrations.RemoveField(
            model_name='exhibitionpage',
            name='audience_detail',
        ),
        migrations.RemoveField(
            model_name='exhibitionpage',
            name='audience_heading',
        ),
        migrations.RemoveField(
            model_name='whatsonpageselection',
            name='featured_page',
        ),
        migrations.AddField(
            model_name='displaypage',
            name='age_detail',
            field=models.CharField(blank=True, help_text='The text for the age detail section.', max_length=40, verbose_name='age detail'),
        ),
        migrations.AddField(
            model_name='displaypage',
            name='all_year',
            field=models.BooleanField(default=False, help_text='Check this box if the display is available all year round.', verbose_name='all year'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='age_detail',
            field=models.CharField(blank=True, help_text='The text for the age detail section.', max_length=40, verbose_name='age detail'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='various_dates',
            field=models.BooleanField(default=False, help_text='Check this box if the event has multiple sessions with different dates and times.', verbose_name='various dates and times'),
        ),
        migrations.AddField(
            model_name='eventslistingpage',
            name='featured_page',
            field=models.ForeignKey(blank=True, help_text='The page to feature at the top of the Events page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='whatson.eventpage', verbose_name='featured page'),
        ),
        migrations.AddField(
            model_name='exhibitionpage',
            name='age_detail',
            field=models.CharField(blank=True, help_text='The text for the age detail section.', max_length=40, verbose_name='age detail'),
        ),
        migrations.AddField(
            model_name='exhibitionslistingpage',
            name='featured_page',
            field=models.ForeignKey(blank=True, help_text='The page to feature at the top of the Exhibitions page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='featured page'),
        ),
    ]
