# Generated by Django 5.2 on 2025-05-20 11:08

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0017_personpage_archived_blog'),
        ('whatson', '0023_eventpage_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventaudiencetype',
            name='audience_type',
        ),
        migrations.RemoveField(
            model_name='eventaudiencetype',
            name='page',
        ),
        migrations.RemoveField(
            model_name='eventhost',
            name='image',
        ),
        migrations.RemoveField(
            model_name='eventhost',
            name='page',
        ),
        migrations.RemoveField(
            model_name='eventsession',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='eventspeaker',
            name='description',
        ),
        migrations.AddField(
            model_name='eventspeaker',
            name='biography',
            field=wagtail.fields.RichTextField(blank=True, help_text='A short biography of the speaker.', verbose_name='biography'),
        ),
        migrations.AddField(
            model_name='eventspeaker',
            name='person_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='people.personpage'),
        ),
        migrations.AddField(
            model_name='eventspeaker',
            name='role',
            field=models.CharField(blank=True, help_text='The role of the speaker.', max_length=200, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='eventspeaker',
            name='name',
            field=models.CharField(blank=True, help_text='The name of the speaker.', max_length=100, verbose_name='name'),
        ),
        migrations.DeleteModel(
            name='AudienceType',
        ),
        migrations.DeleteModel(
            name='EventAudienceType',
        ),
        migrations.DeleteModel(
            name='EventHost',
        ),
    ]
