# Generated by Django 5.2 on 2025-05-21 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatson', '0024_remove_eventaudiencetype_audience_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='article_tag_names',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='tags',
        ),
    ]
