# Generated by Django 5.2 on 2025-05-29 12:46

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('whatson', '0026_remove_whatsonpage_featured_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_series_tags', to='wagtailcore.page')),
                ('series', models.ForeignKey(help_text='The series to include the page in.', on_delete=django.db.models.deletion.CASCADE, related_name='series_pages', to='whatson.whatsonseriespage', verbose_name='series')),
            ],
            options={
                'verbose_name': 'category listing',
                'verbose_name_plural': 'category listings',
            },
        ),
    ]
