# Generated by Django 5.2 on 2025-06-04 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatson', '0028_alter_seriestag_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryselection',
            name='category',
            field=models.ForeignKey(help_text='The category of events to display on the Category page.', on_delete=django.db.models.deletion.CASCADE, related_name='selected_category', to='whatson.eventcategory', verbose_name='category'),
        ),
        migrations.DeleteModel(
            name='CategoryListing',
        ),
    ]
