# Generated by Django 5.2 on 2025-06-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatson', '0029_alter_categoryselection_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='eventbrite_id',
        ),
        migrations.AddField(
            model_name='eventpage',
            name='booking_link',
            field=models.URLField(blank=True, help_text='Link to booking page', null=True, verbose_name='Booking link'),
        ),
    ]
