# Generated by Django 5.2 on 2025-06-10 09:43

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_location_online_detail'),
        ('whatson', '0030_remove_eventpage_eventbrite_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='booking_details',
            field=wagtail.fields.RichTextField(blank=True, help_text='Information about how to book tickets for the exhibition.', max_length=40, null=True, verbose_name='booking details'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='location',
            field=models.ForeignKey(help_text='The location of the event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.location', verbose_name='location'),
        ),
    ]
