# Generated by Django 5.2 on 2025-06-10 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatson', '0031_alter_eventpage_booking_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='event_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='whatson.eventcategory'),
        ),
    ]
