# Generated by Django 5.2 on 2025-06-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatson', '0033_alter_eventcategory_options_eventslistingpage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsession',
            name='sold_out',
            field=models.BooleanField(default=False, help_text='Check this box if the session is sold out.', verbose_name='sold out'),
        ),
    ]
