# Generated by Django 6.0.5 on 2026-06-08 14:39

import django.db.models.deletion
import django.utils.timezone
import modelsearch.index
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('base_url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('type_label', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('first_published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_published_at', models.DateTimeField(auto_now=True)),
                ('last_updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalApplicationPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('teaser_image', models.URLField(blank=True, null=True)),
                ('short_title', models.CharField(blank=True, max_length=45, null=True)),
                ('url_path', models.CharField(max_length=255)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='search.externalapplication')),
            ],
            options={
                'ordering': ['title'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
    ]
