# Generated by Django 5.1.5 on 2025-01-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blogpostpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='short_title',
            field=models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=30, null=True, verbose_name='short title'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='short_title',
            field=models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=30, null=True, verbose_name='short title'),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='short_title',
            field=models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=30, null=True, verbose_name='short title'),
        ),
    ]
