# Generated by Django 5.1.4 on 2025-01-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blogpostpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='custom_type_label',
            field=models.CharField(blank=True, help_text='Override the chip for child blog posts. If left blank, the chip will be the title of the blog.', max_length=255, null=True, verbose_name='Chip override'),
        ),
    ]
