# Generated by Django 5.0.7 on 2024-07-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="uid",
            field=models.BigIntegerField(blank=True, default=0, editable=False),
            preserve_default=False,
        ),
    ]
