# Generated by Django 6.0.1 on 2026-01-14 12:00

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0003_alert_name_alter_alert_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThemedAlert",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the alert to display in the CMS, for easier identification.",
                        max_length=100,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The short title of your alert which will show in bold at the top of the notification banner. E.g. 'Please note' or 'Important information'",
                        max_length=50,
                    ),
                ),
                ("message", wagtail.fields.RichTextField()),
                ("active", models.BooleanField(default=False)),
                (
                    "cascade",
                    models.BooleanField(
                        default=False,
                        verbose_name="Show on current and all child pages",
                    ),
                ),
                ("uid", models.BigIntegerField(blank=True, editable=False)),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("green", "Green"),
                            ("yellow", "Yellow"),
                            ("red", "Red"),
                        ],
                        default="yellow",
                        max_length=6,
                    ),
                ),
            ],
            options={
                "verbose_name": "Themed Alert",
                "verbose_name_plural": "Themed Alerts",
            },
        ),
    ]
