# Generated by Django 6.0.2 on 2026-03-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0004_themedalert"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="themedalert",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
