# Generated by Django 6.0.2 on 2026-03-30 15:14
# etna:allowAlterField

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0005_alert_expires_at_themedalert_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="schedule_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set a start date for this banner. The banner will automatically be activated from this date. If left blank, the banner will remain inactive until manually activated.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="themedalert",
            name="schedule_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set a start date for this banner. The banner will automatically be activated from this date. If left blank, the banner will remain inactive until manually activated.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set an expiry date for this banner. The banner will automatically be deactivated after this date. If left blank, the banner will remain active until manually deactivated.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="themedalert",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set an expiry date for this banner. The banner will automatically be deactivated after this date. If left blank, the banner will remain active until manually deactivated.",
                null=True,
            ),
        ),
    ]
