#!/bin/bash

set -e

if [ -z "$1" ]
then
    export ENVIRONMENT=dev
else
    export ENVIRONMENT="$1"
fi

export DUMP_DIR=./dumps
export MEDIA_DUMP="$ENVIRONMENT-$(date +%s).zip"
export DATABASE_DUMP="$ENVIRONMENT-$(date +%s)-db.sql"

echo "Pulling from $ENVIRONMENT..."

if [ ! -d "$DUMP_DIR" ];
then
    echo "Creating a directory for dumps..."
    mkdir $DUMP_DIR
fi
