#!/bin/bash

set -e

SCRIPTDIR=$(dirname $0)
. $SCRIPTDIR/pre-pull

DATABASE_DUMP="$ENVIRONMENT-$(date +%s)-db.sql"

echo "Pulling database snapshot..."
aws s3 cp s3://ds-$ENVIRONMENT-database-backups/etna/$(aws s3 ls s3://ds-$ENVIRONMENT-database-backups/etna/ | awk '{print $2}' | sort -r | head -n1 | tr -d '/')/etna_backup.sql.gz $DUMP_DIR/$DATABASE_DUMP.gz

echo "Unzipping database dump..."
gzip -d $DUMP_DIR/$DATABASE_DUMP.gz

echo "Copying the database dump to the db container..."
docker compose up db -d --wait
docker compose cp $DUMP_DIR/$DATABASE_DUMP db:/home/$DATABASE_DUMP
docker compose exec db chmod 777 /home/$DATABASE_DUMP

echo "Replacing values in the database dump..."
docker compose exec db sed -i -r -e 's/(dev-|staging-)?www.nationalarchives.gov.uk([[:space:]])443/localhost\2443/g' /home/$DATABASE_DUMP
docker compose exec db sed -i -r -e 's/(dev-|staging-)?wagtail.nationalarchives.gov.uk([[:space:]])443/wagtail.localhost\2443/g' /home/$DATABASE_DUMP

echo "Dropping the old database..."
docker compose exec db psql -U postgres -c "DROP SCHEMA public CASCADE; CREATE SCHEMA public;"

echo "Dumping the database..."
docker compose exec -i db sh -c "psql -U postgres < /home/$DATABASE_DUMP"

echo "Starting the app container..."
docker compose restart app

echo "Running migrations..."
docker compose exec app poetry run python /app/manage.py migrate

echo "Running birdbath..."
docker compose exec app poetry run python /app/manage.py run_birdbath

echo "Creating a superuser..."
docker compose exec app poetry run python /app/manage.py createsuperuser --no-input

echo "Removing database dump from local..."
rm $DUMP_DIR/$DATABASE_DUMP
