#!/bin/bash

set -e

. platformsh-pull-setup

echo "Pulling media from $ENVIRONMENT..."

echo "Downloading media..."
platform mount:download -e "$ENVIRONMENT" -p "$PLATFORM_PROJECT_ID" -m media --target=/media --exclude='/images/*' --yes
docker compose -p ds-wagtail exec app chmod -fR 777 /media

echo "Deleting image renditions..."
psql --host db -d "$DATABASE_NAME" --username="$DATABASE_USER" -c "TRUNCATE images_customimagerendition;"
