#!/bin/bash

set -e

. pre-pull

echo "Pulling database snapshot..."
aws s3 cp s3://ds-$ENVIRONMENT-database-backups/etna/$(aws s3 ls s3://ds-$ENVIRONMENT-database-backups/etna/ | awk '{print $2}' | sort -r | head -n1 | tr -d '/')/etna_backup.sql.gz $DUMP_DIR/$DATABASE_DUMP.gz

echo "Unzipping database dump..."
gzip -d $DUMP_DIR/$DATABASE_DUMP.gz

echo "Replacing values in the database dump..."
sed -i -r -e 's/(dev-|staging-)?www.nationalarchives.gov.uk([[:space:]])443/localhost\2443/g' $DUMP_DIR/$DATABASE_DUMP
sed -i -r -e 's/(dev-|staging-)?wagtail.nationalarchives.gov.uk([[:space:]])443/wagtail.localhost\2443/g' $DUMP_DIR/$DATABASE_DUMP

echo "Starting the db container..."
docker compose up db -d

echo "Stopping the app container..."
docker compose stop app

echo "Dropping the old database..."
psql "postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@db/$POSTGRES_DB" -c "DROP SCHEMA public CASCADE; CREATE SCHEMA public;"

echo "Dumping the database..."
psql "postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@db/$POSTGRES_DB" < $DUMP_DIR/$DATABASE_DUMP

echo "Starting the app container..."
docker compose restart app

echo "Running migrations..."
docker compose exec app manage migrate

echo "Running birdbath..."
docker compose exec app manage run_birdbath

echo "Creating a superuser..."
docker compose exec app manage createsuperuser --no-input

echo "Removing database dump..."
rm $DUMP_DIR/$DATABASE_DUMP
