# Generated by Django 4.0.8 on 2022-12-16 14:21

from django.db import migrations
import etna.core.blocks.page_list
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='featured_pages',
            field=wagtail.fields.StreamField([('featuredpages', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(max_length=100)), ('description', wagtail.blocks.TextBlock(max_length=200)), ('items', etna.core.blocks.page_list.PageListBlock('insights.StoriesPage', max_num=9, min_num=3))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
