# Generated by Django 4.0.8 on 2022-11-10 13:53

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('time_period', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(default='Explore by time period', max_length=100)), ('page', wagtail.blocks.PageChooserBlock(page_type=['collections.TimePeriodExplorerIndexPage']))])), ('topic_explorer', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(default='Explore by topic', max_length=100)), ('page', wagtail.blocks.PageChooserBlock(page_type=['collections.TopicExplorerIndexPage']))])), ('paragraph', wagtail.blocks.StructBlock([('text', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ul']))])), ('paragraph_with_heading', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(max_length=100, required=True)), ('paragraph', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ul'], required=True))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
