# Generated by Django 4.0.8 on 2022-12-16 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_homepage_featured_pages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='featured_insight',
            new_name='featured_story',
        ),
    ]
