# Generated by Django 5.0.7 on 2024-08-01 07:24
# etna:allowAlterField
# etna:allowRemoveField

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0027_mourningnotice"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mourningnotice",
            old_name="name",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="mourningnotice",
            name="birth_date",
        ),
        migrations.RemoveField(
            model_name="mourningnotice",
            name="death_date",
        ),
        migrations.AddField(
            model_name="mourningnotice",
            name="message",
            field=wagtail.fields.RichTextField(default="default"),
            preserve_default=False,
        ),
    ]
