# Generated by Django 4.0.8 on 2023-01-20 13:04

from django.db import migrations, models
import django.db.models.deletion
import app.ciim.fields
import wagtail.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailimages", "0024_index_image_file_hash"),
    ]

    operations = [
        migrations.CreateModel(
            name="Highlight",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, null=True)),
                (
                    "record",
                    app.ciim.fields.RecordField(verbose_name="record"),
                ),
                (
                    "date_text",
                    models.CharField(
                        help_text="Date(s) related to the record (max. character length: 100)",
                        max_length=100,
                        verbose_name="date text",
                    ),
                ),
                (
                    "description",
                    wagtail.fields.RichTextField(verbose_name="description"),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "highlight",
                "verbose_name_plural": "highlights",
            },
        ),
    ]
