# Generated by Django 4.0.8 on 2023-02-01 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0002_migrate_old_image_data_to_new_model"),
        ("highlights", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="highlight",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
            ),
        ),
    ]
