# Generated by Django 6.0.7 on 2026-07-30 13:11

import app.ciim.blocks
import app.ciim.fields
import app.collections.models
import app.core.models.mixins
import app.people.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('custom_warning_text', wagtail.fields.RichTextField(blank=True, help_text='If specified, will be used for the content warning.', verbose_name='custom content warning text (optional)')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, help_text='The date the page was published to the public.', verbose_name='Published date')),
                ('hero_image_caption', wagtail.fields.RichTextField(blank=True, help_text='An optional caption for hero images. This could be used for image sources or for other useful metadata.', verbose_name='hero image caption (optional)')),
                ('twitter_og_title', models.CharField(blank=True, help_text='If left blank, the OpenGraph title will be used.', max_length=255, null=True, verbose_name='Twitter OpenGraph title')),
                ('twitter_og_description', models.TextField(blank=True, help_text='If left blank, the OpenGraph description will be used.', null=True, verbose_name='Twitter OpenGraph description')),
                ('short_title', models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=45, null=True, verbose_name='short title')),
                ('teaser_text', models.TextField(help_text='A short, enticing description of this page. This will appear in promos and under thumbnails around the site.', max_length=160, verbose_name='teaser text')),
                ('intro', wagtail.fields.RichTextField(help_text='1-2 sentences introducing the subject of the page, and explaining why a user should read on.', max_length=300, verbose_name='introductory text')),
                ('article_tag_names', models.TextField(editable=False, null=True)),
                ('body', wagtail.fields.StreamField([('content_section', 47)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Heading', 'max_length': 100}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Display a filename with the extension e.g. example.html', 'label': 'Code block title', 'max_length': 100, 'required': False}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('html', 'HTML'), ('javascript', 'JavaScript'), ('python', 'Python'), ('xml', 'XML'), ('json', 'JSON'), ('bash', 'Bash'), ('git', 'git'), ('markdown', 'Markdown'), ('graphql', 'GraphQL'), ('powershell', 'PowerShell'), ('yaml', 'YAML')], 'label': 'Code language', 'required': False}), 3: ('wagtail.blocks.TextBlock', (), {'max_length': 500}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Allow copy to clipboard', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('filename', 1), ('language', 2), ('code', 3), ('allow_copying', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Supertitle', 'max_length': 20, 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 100}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Description'}), 9: ('wagtail.blocks.URLBlock', (), {'label': 'URL'}), 10: ('app.core.blocks.image.APIImageChooserBlock', (), {'label': 'Image', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('supertitle', 6), ('title', 7), ('description', 8), ('url', 9), ('image', 10)]], {}), 12: ('app.core.blocks.page_chooser.APIPageChooserBlock', (), {'label': 'Page', 'page_type': ['wagtailcore.Page'], 'required': True}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional override for the teaser text', 'label': 'Teaser text override', 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('page', 12), ('teaser_text', 13)]], {}), 15: ('app.core.blocks.image.APIImageChooserBlock', (), {'rendition_size': 'max-900x900', 'required': True}), 16: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'help_text': 'If provided, displays directly below the image. Can be used to specify sources, transcripts or other useful metadata.', 'label': 'Caption (optional)', 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('image', 15), ('caption', 16)]], {}), 18: ('wagtail.blocks.CharBlock', (), {'required': False}), 19: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link', 'code'], 'required': False}), 20: ('wagtail.blocks.ListBlock', (17,), {}), 21: ('wagtail.blocks.StructBlock', [[('title', 18), ('description', 19), ('images', 20)]], {}), 22: ('wagtail.blocks.CharBlock', (), {'help_text': 'A descriptive title for the media block', 'required': True}), 23: ('app.core.blocks.image.APIImageChooserBlock', (), {'help_text': 'A thumbnail image for the media block', 'rendition_size': 'fill-960x540', 'required': False}), 24: ('app.media.blocks.MediaChooserBlock', (), {}), 25: ('wagtail.blocks.StructBlock', [[('title', 22), ('thumbnail', 23), ('media', 24)]], {}), 26: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link', 'code', 'ol', 'ul']}), 27: ('wagtail.blocks.StructBlock', [[('text', 26)]], {}), 28: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link', 'code', 'ol', 'ul'], 'required': True}), 29: ('wagtail.blocks.CharBlock', (), {'help_text': 'The name of the person being quoted. e.g. King Edward VIII', 'max_length': 100}), 30: ('wagtail.blocks.CharBlock', (), {'help_text': 'The title of the work or document from which the quote is taken. e.g. The Telegraph, 23 June 1986', 'max_length': 100, 'required': False}), 31: ('app.core.blocks.page_chooser.APIPageChooserBlock', (), {'help_text': 'Reference another page published on the site', 'label': 'Internal page', 'required': False}), 32: ('wagtail.blocks.URLBlock', (), {'help_text': 'Add a URL here to refer to an external source', 'label': 'External link', 'required': False}), 33: ('wagtail.blocks.StructBlock', [[('citation_internal_link', 31), ('citation_external_link', 32)]], {}), 34: ('wagtail.blocks.StructBlock', [[('citation', 30), ('source_link', 33)]], {}), 35: ('wagtail.blocks.StructBlock', [[('quote', 28), ('attribution', 29), ('source', 34)]], {}), 36: ('wagtail.blocks.ListBlock', (app.ciim.blocks.RecordLinkBlock,), {'label': 'Items'}), 37: ('wagtail.blocks.StructBlock', [[('items', 36)]], {}), 38: ('wagtail.blocks.CharBlock', (), {'label': 'Sub-heading', 'max_length': 100}), 39: ('wagtail.blocks.StructBlock', [[('heading', 38)]], {}), 40: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 100, 'required': True}), 41: ('wagtail.blocks.CharBlock', (), {'label': 'YouTube Video ID', 'max_length': 11, 'required': True, 'validators': [django.core.validators.RegexValidator(message='Invalid YouTube Video ID', regex='^[a-zA-Z0-9_-]{11}$')]}), 42: ('app.core.blocks.image.APIImageChooserBlock', (), {'label': 'Preview Image', 'rendition_size': 'fill-640x360', 'required': True}), 43: ('wagtail.blocks.RichTextBlock', (), {'label': 'Transcript', 'required': False}), 44: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Tick if the video has captions on YouTube', 'label': 'Captions available', 'required': False}), 45: ('wagtail.blocks.StructBlock', [[('title', 40), ('video_id', 41), ('preview_image', 42), ('transcript', 43), ('captions_available', 44)]], {}), 46: ('wagtail.blocks.StreamBlock', [[('code', 5), ('featured_external_link', 11), ('featured_page', 14), ('image', 17), ('image_gallery', 21), ('media', 25), ('paragraph', 27), ('quote', 35), ('record_links', 37), ('sub_heading', 39), ('youtube_video', 45)]], {'required': False}), 47: ('wagtail.blocks.StructBlock', [[('heading', 0), ('content', 46)]], {})}, null=True)),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
            },
            bases=(app.collections.models.TopicalPageMixin, app.core.models.mixins.CustomHeadlessPreviewMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug')),
                ('skos_id', models.CharField(blank=True, db_index=True, help_text='Used as the identifier for this tag when sending page metatdata to the CIIM API.', max_length=100, unique=True, verbose_name='SKOS identifier')),
            ],
            options={
                'verbose_name': 'article tag',
                'verbose_name_plural': 'article tags',
            },
        ),
        migrations.CreateModel(
            name='FocusedArticlePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('custom_warning_text', wagtail.fields.RichTextField(blank=True, help_text='If specified, will be used for the content warning.', verbose_name='custom content warning text (optional)')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, help_text='The date the page was published to the public.', verbose_name='Published date')),
                ('hero_image_caption', wagtail.fields.RichTextField(blank=True, help_text='An optional caption for hero images. This could be used for image sources or for other useful metadata.', verbose_name='hero image caption (optional)')),
                ('twitter_og_title', models.CharField(blank=True, help_text='If left blank, the OpenGraph title will be used.', max_length=255, null=True, verbose_name='Twitter OpenGraph title')),
                ('twitter_og_description', models.TextField(blank=True, help_text='If left blank, the OpenGraph description will be used.', null=True, verbose_name='Twitter OpenGraph description')),
                ('short_title', models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=45, null=True, verbose_name='short title')),
                ('teaser_text', models.TextField(help_text='A short, enticing description of this page. This will appear in promos and under thumbnails around the site.', max_length=160, verbose_name='teaser text')),
                ('intro', wagtail.fields.RichTextField(help_text='1-2 sentences introducing the subject of the page, and explaining why a user should read on.', max_length=300, verbose_name='introductory text')),
                ('article_tag_names', models.TextField(editable=False, null=True)),
                ('body', wagtail.fields.StreamField([('content_section', 47)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Heading', 'max_length': 100}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Display a filename with the extension e.g. example.html', 'label': 'Code block title', 'max_length': 100, 'required': False}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('html', 'HTML'), ('javascript', 'JavaScript'), ('python', 'Python'), ('xml', 'XML'), ('json', 'JSON'), ('bash', 'Bash'), ('git', 'git'), ('markdown', 'Markdown'), ('graphql', 'GraphQL'), ('powershell', 'PowerShell'), ('yaml', 'YAML')], 'label': 'Code language', 'required': False}), 3: ('wagtail.blocks.TextBlock', (), {'max_length': 500}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Allow copy to clipboard', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('filename', 1), ('language', 2), ('code', 3), ('allow_copying', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Supertitle', 'max_length': 20, 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 100}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Description'}), 9: ('wagtail.blocks.URLBlock', (), {'label': 'URL'}), 10: ('app.core.blocks.image.APIImageChooserBlock', (), {'label': 'Image', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('supertitle', 6), ('title', 7), ('description', 8), ('url', 9), ('image', 10)]], {}), 12: ('app.core.blocks.page_chooser.APIPageChooserBlock', (), {'label': 'Page', 'page_type': ['wagtailcore.Page'], 'required': True}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional override for the teaser text', 'label': 'Teaser text override', 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('page', 12), ('teaser_text', 13)]], {}), 15: ('app.core.blocks.image.APIImageChooserBlock', (), {'rendition_size': 'max-900x900', 'required': True}), 16: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'help_text': 'If provided, displays directly below the image. Can be used to specify sources, transcripts or other useful metadata.', 'label': 'Caption (optional)', 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('image', 15), ('caption', 16)]], {}), 18: ('wagtail.blocks.CharBlock', (), {'required': False}), 19: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link', 'code'], 'required': False}), 20: ('wagtail.blocks.ListBlock', (17,), {}), 21: ('wagtail.blocks.StructBlock', [[('title', 18), ('description', 19), ('images', 20)]], {}), 22: ('wagtail.blocks.CharBlock', (), {'help_text': 'A descriptive title for the media block', 'required': True}), 23: ('app.core.blocks.image.APIImageChooserBlock', (), {'help_text': 'A thumbnail image for the media block', 'rendition_size': 'fill-960x540', 'required': False}), 24: ('app.media.blocks.MediaChooserBlock', (), {}), 25: ('wagtail.blocks.StructBlock', [[('title', 22), ('thumbnail', 23), ('media', 24)]], {}), 26: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link', 'code', 'ol', 'ul']}), 27: ('wagtail.blocks.StructBlock', [[('text', 26)]], {}), 28: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link', 'code', 'ol', 'ul'], 'required': True}), 29: ('wagtail.blocks.CharBlock', (), {'help_text': 'The name of the person being quoted. e.g. King Edward VIII', 'max_length': 100}), 30: ('wagtail.blocks.CharBlock', (), {'help_text': 'The title of the work or document from which the quote is taken. e.g. The Telegraph, 23 June 1986', 'max_length': 100, 'required': False}), 31: ('app.core.blocks.page_chooser.APIPageChooserBlock', (), {'help_text': 'Reference another page published on the site', 'label': 'Internal page', 'required': False}), 32: ('wagtail.blocks.URLBlock', (), {'help_text': 'Add a URL here to refer to an external source', 'label': 'External link', 'required': False}), 33: ('wagtail.blocks.StructBlock', [[('citation_internal_link', 31), ('citation_external_link', 32)]], {}), 34: ('wagtail.blocks.StructBlock', [[('citation', 30), ('source_link', 33)]], {}), 35: ('wagtail.blocks.StructBlock', [[('quote', 28), ('attribution', 29), ('source', 34)]], {}), 36: ('wagtail.blocks.ListBlock', (app.ciim.blocks.RecordLinkBlock,), {'label': 'Items'}), 37: ('wagtail.blocks.StructBlock', [[('items', 36)]], {}), 38: ('wagtail.blocks.CharBlock', (), {'label': 'Sub-heading', 'max_length': 100}), 39: ('wagtail.blocks.StructBlock', [[('heading', 38)]], {}), 40: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 100, 'required': True}), 41: ('wagtail.blocks.CharBlock', (), {'label': 'YouTube Video ID', 'max_length': 11, 'required': True, 'validators': [django.core.validators.RegexValidator(message='Invalid YouTube Video ID', regex='^[a-zA-Z0-9_-]{11}$')]}), 42: ('app.core.blocks.image.APIImageChooserBlock', (), {'label': 'Preview Image', 'rendition_size': 'fill-640x360', 'required': True}), 43: ('wagtail.blocks.RichTextBlock', (), {'label': 'Transcript', 'required': False}), 44: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Tick if the video has captions on YouTube', 'label': 'Captions available', 'required': False}), 45: ('wagtail.blocks.StructBlock', [[('title', 40), ('video_id', 41), ('preview_image', 42), ('transcript', 43), ('captions_available', 44)]], {}), 46: ('wagtail.blocks.StreamBlock', [[('code', 5), ('featured_external_link', 11), ('featured_page', 14), ('image', 17), ('image_gallery', 21), ('media', 25), ('paragraph', 27), ('quote', 35), ('record_links', 37), ('sub_heading', 39), ('youtube_video', 45)]], {'required': False}), 47: ('wagtail.blocks.StructBlock', [[('heading', 0), ('content', 46)]], {})}, null=True)),
            ],
            options={
                'verbose_name': 'focused article',
                'verbose_name_plural': 'focused articles',
            },
            bases=(app.collections.models.TopicalPageMixin, app.people.models.AuthorPageMixin, app.core.models.mixins.CustomHeadlessPreviewMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='PageGalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', wagtail.fields.RichTextField(blank=True, help_text='An optional caption, which will be displayed directly below the image. This could be used for image sources or for other useful metadata.')),
            ],
            options={
                'verbose_name': 'gallery image',
                'verbose_name_plural': 'gallery images',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecordArticlePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('custom_warning_text', wagtail.fields.RichTextField(blank=True, help_text='If specified, will be used for the content warning.', verbose_name='custom content warning text (optional)')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, help_text='The date the page was published to the public.', verbose_name='Published date')),
                ('twitter_og_title', models.CharField(blank=True, help_text='If left blank, the OpenGraph title will be used.', max_length=255, null=True, verbose_name='Twitter OpenGraph title')),
                ('twitter_og_description', models.TextField(blank=True, help_text='If left blank, the OpenGraph description will be used.', null=True, verbose_name='Twitter OpenGraph description')),
                ('short_title', models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=45, null=True, verbose_name='short title')),
                ('teaser_text', models.TextField(help_text='A short, enticing description of this page. This will appear in promos and under thumbnails around the site.', max_length=160, verbose_name='teaser text')),
                ('intro', wagtail.fields.RichTextField(help_text='1-2 sentences introducing the subject of the page, and explaining why a user should read on.', max_length=300, verbose_name='introductory text')),
                ('article_tag_names', models.TextField(editable=False, null=True)),
                ('record', app.ciim.fields.RecordField(db_index=True, max_length=50, null=True, verbose_name='record')),
                ('date_text', models.CharField(help_text='Date(s) related to the record (max. character length: 100)', max_length=100, verbose_name='date text')),
                ('about', wagtail.fields.RichTextField(verbose_name='why this record matters')),
                ('image_library_link', models.URLField(blank=True, help_text='Link to an external image library', verbose_name='Image library link')),
                ('print_on_demand_link', models.URLField(blank=True, help_text='Link to an external print on demand service', verbose_name='Print on demand link')),
                ('gallery_heading', models.CharField(blank=True, help_text='Optional heading for the gallery', max_length=250, null=True, verbose_name='gallery heading')),
            ],
            options={
                'verbose_name': 'record article',
                'verbose_name_plural': 'record articles',
            },
            bases=(app.collections.models.TopicalPageMixin, app.core.models.mixins.CustomHeadlessPreviewMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='TaggedArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('twitter_og_title', models.CharField(blank=True, help_text='If left blank, the OpenGraph title will be used.', max_length=255, null=True, verbose_name='Twitter OpenGraph title')),
                ('twitter_og_description', models.TextField(blank=True, help_text='If left blank, the OpenGraph description will be used.', null=True, verbose_name='Twitter OpenGraph description')),
                ('short_title', models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=45, null=True, verbose_name='short title')),
                ('teaser_text', models.TextField(help_text='A short, enticing description of this page. This will appear in promos and under thumbnails around the site.', max_length=160, verbose_name='teaser text')),
                ('intro', wagtail.fields.RichTextField(help_text='1-2 sentences introducing the subject of the page, and explaining why a user should read on.', max_length=300, verbose_name='introductory text')),
                ('featured_pages', wagtail.fields.StreamField([('featuredpages', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 1: ('wagtail.blocks.TextBlock', (), {'max_length': 200}), 2: ('app.core.blocks.page_list.PageListBlock', ('articles.ArticlePage', 'articles.RecordArticlePage', 'articles.FocusedArticlePage'), {'max_num': 9, 'min_num': 3}), 3: ('wagtail.blocks.StructBlock', [[('heading', 0), ('description', 1), ('items', 2)]], {})}, null=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='alerts.alert')),
                ('featured_article', models.ForeignKey(blank=True, help_text='Select a page to display in the featured area. This can be an Article, Focused Article or Record Article.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='featured article')),
            ],
            options={
                'verbose_name': 'article index page',
            },
            bases=(app.core.models.mixins.CustomHeadlessPreviewMixin, 'wagtailcore.page', models.Model),
        ),
    ]
