# Generated by Django 6.0.8 on 2026-09-14 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleindexpage',
            name='twitter_og_description',
        ),
        migrations.RemoveField(
            model_name='articleindexpage',
            name='twitter_og_image',
        ),
        migrations.RemoveField(
            model_name='articleindexpage',
            name='twitter_og_title',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='twitter_og_description',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='twitter_og_image',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='twitter_og_title',
        ),
        migrations.RemoveField(
            model_name='focusedarticlepage',
            name='twitter_og_description',
        ),
        migrations.RemoveField(
            model_name='focusedarticlepage',
            name='twitter_og_image',
        ),
        migrations.RemoveField(
            model_name='focusedarticlepage',
            name='twitter_og_title',
        ),
        migrations.RemoveField(
            model_name='recordarticlepage',
            name='twitter_og_description',
        ),
        migrations.RemoveField(
            model_name='recordarticlepage',
            name='twitter_og_image',
        ),
        migrations.RemoveField(
            model_name='recordarticlepage',
            name='twitter_og_title',
        ),
    ]
