# Generated by Django 3.1.8 on 2021-08-10 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0023_add_choose_permissions"),
        ("articles", "0014_alter_field_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="insightspage",
            name="teaser_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
