# Generated by Django 4.0.8 on 2023-02-03 13:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0051_remove_pagegalleryimage_is_sensitive_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pagegalleryimage",
            name="transcription_header",
        ),
        migrations.RemoveField(
            model_name="pagegalleryimage",
            name="translation_header",
        ),
    ]
