# Generated by Django 4.0.8 on 2023-02-16 16:40

from django.db import migrations


def migrate_forwards(apps, schema_editor):
    ArticlePage = apps.get_model("articles", "ArticlePage")
    PageTimePeriod = apps.get_model("collections", "PageTimePeriod")
    PageTopic = apps.get_model("collections", "PageTopic")
    page_topics_to_create = []
    page_timeperiods_to_create = []

    for page in ArticlePage.objects.all().select_related("latest_revision"):
        rev = page.latest_revision
        if page.time_period_id:
            page_timeperiods_to_create.append(
                PageTimePeriod(page_id=page.id, time_period_id=page.time_period_id)
            )
            rev.content["page_time_periods"] = [page.time_period_id]
        if page.topic_id:
            page_topics_to_create.append(
                PageTopic(page_id=page.id, topic_id=page.topic_id)
            )
            rev.content["page_topics"] = [page.topic_id]
        if page.topic_id or page.time_period_id:
            rev.save(update_fields=["content"])

    PageTimePeriod.objects.bulk_create(page_timeperiods_to_create)
    PageTopic.objects.bulk_create(page_topics_to_create)


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0059_update_revisions_to_reflect_intro_field_change"),
        ("collections", "0030_add_teaser_text"),
    ]

    operations = [
        migrations.RunPython(migrate_forwards, migrations.RunPython.noop),
    ]
