# Generated by Django 4.0.8 on 2023-03-03 16:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "articles",
            "0060_copy_articlepage_topic_and_timeperiod_values_to_link_tables",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articlepage",
            name="time_period",
        ),
        migrations.RemoveField(
            model_name="articlepage",
            name="topic",
        ),
    ]
