# Generated by Django 4.1.7 on 2023-03-15 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0005_alter_customimage_file_and_more"),
        ("articles", "0065_alter_articleindexpage_search_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articleindexpage",
            name="search_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
                verbose_name="Search image",
            ),
        ),
        migrations.AlterField(
            model_name="articlepage",
            name="search_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
                verbose_name="Search image",
            ),
        ),
        migrations.AlterField(
            model_name="recordarticlepage",
            name="search_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
                verbose_name="Search image",
            ),
        ),
    ]
