# Generated by Django 4.0.8 on 2023-02-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0068_alter_articlepage_mark_new_on_next_publish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlepage",
            name="mark_new_on_next_publish",
            field=models.BooleanField(
                default=True,
                help_text="Mark this as true before publishing, to display the 'new label'",
                verbose_name="mark this page as 'new' when published",
            ),
        ),
    ]
