# Generated by Django 4.0.8 on 2023-03-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0069_alter_articlepage_mark_new_on_next_publish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlepage",
            name="mark_new_on_next_publish",
            field=models.BooleanField(
                default=True, verbose_name="mark this page as 'new' when published"
            ),
        ),
    ]
