# Generated by Django 4.1.7 on 2023-04-04 14:50

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0070_alter_articlepage_mark_new_on_next_publish"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordarticlepage",
            name="promoted_links",
            field=wagtail.fields.StreamField(
                [
                    (
                        "promoted_link",
                        wagtail.blocks.StructBlock(
                            [
                                ("heading", wagtail.blocks.CharBlock(max_length=100)),
                                (
                                    "promoted_items",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.TextBlock(),
                                        max=3,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
