# Generated by Django 4.1.8 on 2023-04-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0075_alter_articlepage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="articletag",
            name="skos_id",
            field=models.CharField(
                blank=True,
                help_text="Used as the identifier for this tag when sending page metatdata to the CIIM API.",
                max_length=100,
                verbose_name="SKOS identifier",
            ),
        ),
    ]
