# Generated by Django 4.1.8 on 2023-04-21 14:25

from django.db import migrations
from app.core.utils import skos_id_from_text


def migrate_forwards(apps, schema_editor):
    ArticleTag = apps.get_model("articles.ArticleTag")
    to_update = []
    for obj in ArticleTag.objects.all():
        base_value = skos_id_from_text(obj.name[:100])
        obj.skos_id = base_value
        i = 2
        while obj.skos_id in (other.skos_id for other in to_update):
            # NOTE: Trimming base_value to ensure there are 3 chars left over for the suffix
            obj.skos_id = f"{base_value[:97]}_{i}"
            i += 1
        to_update.append(obj)
    ArticleTag.objects.bulk_update(to_update, fields=["skos_id"])


def migrate_backwards(apps, schema_editor):
    ArticleTag = apps.get_model("articles.ArticleTag")
    ArticleTag.objects.all().update(skos_id="")


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0076_articletag_skos_id"),
    ]

    operations = [migrations.RunPython(migrate_forwards, migrate_backwards)]
