# Generated by Django 4.1.8 on 2023-04-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0077_set_skos_id_for_articletags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articletag",
            name="skos_id",
            field=models.CharField(
                db_index=True,
                blank=True,
                help_text="Used as the identifier for this tag when sending page metatdata to the CIIM API.",
                max_length=100,
                unique=True,
                verbose_name="SKOS identifier",
            ),
        ),
    ]
