# Generated by Django 4.2.1 on 2023-05-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0086_alter_articlepage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordarticlepage",
            name="mark_new_on_next_publish",
            field=models.BooleanField(
                default=False, verbose_name="mark this page as 'new' when published"
            ),
        ),
        migrations.AddField(
            model_name="recordarticlepage",
            name="newly_published_at",
            field=models.DateField(default=None, editable=False, null=True),
        ),
    ]
