# Generated by Django 4.2.1 on 2023-05-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0087_recordarticlepage_mark_new_on_next_publish_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recordarticlepage",
            name="mark_new_on_next_publish",
            field=models.BooleanField(
                default=True, verbose_name="mark this page as 'new' when published"
            ),
        ),
    ]
