# Generated by Django 4.2.1 on 2023-06-15 12:37

from django.db import migrations, models
import django.db.models.deletion
import app.analytics.mixins
import app.articles.blocks
import app.collections.models
import app.media.blocks
import app.ciim.blocks
import uuid
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtail.snippets.blocks
import wagtailmetadata.models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0008_alter_customimagerendition_file"),
        ("wagtailcore", "0083_workflowcontenttype"),
        ("articles", "0090_recordarticlepage_gallery_heading"),
    ]

    operations = [
        migrations.CreateModel(
            name="FocusedArticlePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "teaser_text",
                    models.TextField(
                        help_text="A short, enticing description of this page. This will appear in promos and under thumbnails around the site.",
                        max_length=160,
                        verbose_name="teaser text",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(
                        help_text="1-2 sentences introducing the subject of the page, and explaining why a user should read on.",
                        max_length=300,
                        verbose_name="introductory text",
                    ),
                ),
                (
                    "display_content_warning",
                    models.BooleanField(
                        default=False,
                        verbose_name="display a content warning on this page",
                    ),
                ),
                (
                    "custom_warning_text",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="If specified, will be used for the content warning. Otherwise the default text will be used.",
                        verbose_name="custom content warning text (optional)",
                    ),
                ),
                (
                    "mark_new_on_next_publish",
                    models.BooleanField(
                        default=True,
                        verbose_name="mark this page as 'new' when published",
                    ),
                ),
                (
                    "newly_published_at",
                    models.DateField(default=None, editable=False, null=True),
                ),
                (
                    "hero_image_caption",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="An optional caption for hero images. This could be used for image sources or for other useful metadata.",
                        verbose_name="hero image caption (optional)",
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True,
                        help_text="The author of this article.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            (
                                "content_section",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.blocks.CharBlock(
                                                label="Heading", max_length=100
                                            ),
                                        ),
                                        (
                                            "content",
                                            wagtail.blocks.StreamBlock(
                                                [
                                                    (
                                                        "paragraph",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "text",
                                                                    wagtail.blocks.RichTextBlock(
                                                                        features=[
                                                                            "bold",
                                                                            "italic",
                                                                            "link",
                                                                            "ol",
                                                                            "ul",
                                                                        ]
                                                                    ),
                                                                )
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "quote",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "quote",
                                                                    wagtail.blocks.RichTextBlock(
                                                                        features=[
                                                                            "bold",
                                                                            "italic",
                                                                            "link",
                                                                        ],
                                                                        required=True,
                                                                    ),
                                                                ),
                                                                (
                                                                    "attribution",
                                                                    wagtail.blocks.CharBlock(
                                                                        max_length=100,
                                                                        required=False,
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "sub_heading",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "heading",
                                                                    wagtail.blocks.CharBlock(
                                                                        label="Sub-heading",
                                                                        max_length=100,
                                                                    ),
                                                                )
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "image",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "image",
                                                                    wagtail.images.blocks.ImageChooserBlock(
                                                                        required=False
                                                                    ),
                                                                ),
                                                                (
                                                                    "alt_text",
                                                                    wagtail.blocks.CharBlock(
                                                                        help_text='Alternative (alt) text describes images when they fail to load, and is read aloud by assistive technologies. Use a maximum of 100 characters to describe your image. <a href="https://html.spec.whatwg.org/multipage/images.html#alt" target="_blank">Check the guidance for tips on writing alt text</a>.',
                                                                        label="Alternative text",
                                                                        max_length=100,
                                                                    ),
                                                                ),
                                                                (
                                                                    "caption",
                                                                    wagtail.blocks.RichTextBlock(
                                                                        features=[
                                                                            "bold",
                                                                            "italic",
                                                                            "link",
                                                                        ],
                                                                        help_text="If provided, displays directly below the image. Can be used to specify sources, transcripts or other useful metadata.",
                                                                        label="Caption (optional)",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "media",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "title",
                                                                    wagtail.blocks.CharBlock(
                                                                        help_text="A descriptive title for the media block",
                                                                        required=True,
                                                                    ),
                                                                ),
                                                                (
                                                                    "background_image",
                                                                    wagtail.images.blocks.ImageChooserBlock(
                                                                        help_text="A background image for the media block"
                                                                    ),
                                                                ),
                                                                (
                                                                    "media",
                                                                    app.media.blocks.MediaChooserBlock(),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "featured_record_article",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "page",
                                                                    wagtail.blocks.PageChooserBlock(
                                                                        label="Page",
                                                                        page_type=[
                                                                            "articles.RecordArticlePage"
                                                                        ],
                                                                    ),
                                                                )
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "featured_record",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "title",
                                                                    wagtail.blocks.CharBlock(
                                                                        help_text="A short description (max 200 characters) to add 'relevancy' to the record details. For example: 'Entry for Alice Hawkins in the index to suffragettes arrested'.",
                                                                        label="Descriptive title",
                                                                        max_length=200,
                                                                    ),
                                                                ),
                                                                (
                                                                    "record",
                                                                    app.ciim.blocks.RecordChooserBlock(),
                                                                ),
                                                                (
                                                                    "image",
                                                                    wagtail.blocks.StructBlock(
                                                                        [
                                                                            (
                                                                                "image",
                                                                                wagtail.images.blocks.ImageChooserBlock(
                                                                                    required=False
                                                                                ),
                                                                            ),
                                                                            (
                                                                                "decorative",
                                                                                wagtail.blocks.BooleanBlock(
                                                                                    default=False,
                                                                                    help_text='Decorative images are used for visual effect and do not add information to the content of a page. <a href="https://www.w3.org/WAI/tutorials/images/decorative/" target="_blank">"Check the guidance to see if your image is decorative</a>.',
                                                                                    label="Is this image decorative? <p class='field-title__subheading'>Tick the box if 'yes'</p>",
                                                                                    required=False,
                                                                                ),
                                                                            ),
                                                                            (
                                                                                "alt_text",
                                                                                wagtail.blocks.CharBlock(
                                                                                    help_text='Alternative (alt) text describes images when they fail to load, and is read aloud by assistive technologies. Use a maximum of 100 characters to describe your image. Decorative images do not require alt text. <a href="https://html.spec.whatwg.org/multipage/images.html#alt" target="_blank">Check the guidance for tips on writing alt text</a>.',
                                                                                    label="Image alternative text",
                                                                                    max_length=100,
                                                                                    required=False,
                                                                                ),
                                                                            ),
                                                                            (
                                                                                "caption",
                                                                                wagtail.blocks.RichTextBlock(
                                                                                    features=[
                                                                                        "bold",
                                                                                        "italic",
                                                                                        "link",
                                                                                    ],
                                                                                    help_text="An optional caption for non-decorative images, which will be displayed directly below the image. This could be used for image sources or for other useful metadata.",
                                                                                    label="Caption (optional)",
                                                                                    required=False,
                                                                                ),
                                                                            ),
                                                                        ],
                                                                        help_text="Add an image to be displayed with the selected record.",
                                                                        label="Teaser image",
                                                                        required=False,
                                                                        template="articles/blocks/images/blog-embed__image-container.html",
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "featured_records",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "introduction",
                                                                    wagtail.blocks.CharBlock(
                                                                        max_length=200,
                                                                        required=False,
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "promoted_item",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "title",
                                                                    wagtail.blocks.CharBlock(
                                                                        help_text="Title of the promoted page",
                                                                        label="Title",
                                                                        max_length=100,
                                                                    ),
                                                                ),
                                                                (
                                                                    "category",
                                                                    wagtail.blocks.ChoiceBlock(
                                                                        choices=[
                                                                            (
                                                                                "blog",
                                                                                "Blog post",
                                                                            ),
                                                                            (
                                                                                "podcast",
                                                                                "Podcast",
                                                                            ),
                                                                            (
                                                                                "video",
                                                                                "Video",
                                                                            ),
                                                                            (
                                                                                "video-external",
                                                                                "External video",
                                                                            ),
                                                                            (
                                                                                "external-link",
                                                                                "External link",
                                                                            ),
                                                                        ],
                                                                        label="Category",
                                                                    ),
                                                                ),
                                                                (
                                                                    "publication_date",
                                                                    wagtail.blocks.DateBlock(
                                                                        required=False
                                                                    ),
                                                                ),
                                                                (
                                                                    "author",
                                                                    wagtail.blocks.CharBlock(
                                                                        required=False
                                                                    ),
                                                                ),
                                                                (
                                                                    "duration",
                                                                    wagtail.blocks.CharBlock(
                                                                        help_text="Podcast or video duration.",
                                                                        label="Duration",
                                                                        max_length=50,
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "url",
                                                                    wagtail.blocks.URLBlock(
                                                                        help_text="URL for the external page",
                                                                        label="External URL",
                                                                    ),
                                                                ),
                                                                (
                                                                    "target_blank",
                                                                    wagtail.blocks.BooleanBlock(
                                                                        label="Should this URL open in a new tab? <p style='font-size: 11px;'>Tick the box if 'yes'</p>",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "cta_label",
                                                                    wagtail.blocks.CharBlock(
                                                                        help_text="The text displayed on the button for your URL. If your URL links to an external site, please add the name of the site users will land on, and what they will find on this page. For example 'Watch our short film  <strong>about Shakespeare on YouTube</strong>'.",
                                                                        label="Call to action label",
                                                                        max_length=50,
                                                                    ),
                                                                ),
                                                                (
                                                                    "image",
                                                                    wagtail.blocks.StructBlock(
                                                                        [
                                                                            (
                                                                                "image",
                                                                                wagtail.images.blocks.ImageChooserBlock(
                                                                                    required=False
                                                                                ),
                                                                            ),
                                                                            (
                                                                                "decorative",
                                                                                wagtail.blocks.BooleanBlock(
                                                                                    default=False,
                                                                                    help_text='Decorative images are used for visual effect and do not add information to the content of a page. <a href="https://www.w3.org/WAI/tutorials/images/decorative/" target="_blank">"Check the guidance to see if your image is decorative</a>.',
                                                                                    label="Is this image decorative? <p class='field-title__subheading'>Tick the box if 'yes'</p>",
                                                                                    required=False,
                                                                                ),
                                                                            ),
                                                                            (
                                                                                "alt_text",
                                                                                wagtail.blocks.CharBlock(
                                                                                    help_text='Alternative (alt) text describes images when they fail to load, and is read aloud by assistive technologies. Use a maximum of 100 characters to describe your image. Decorative images do not require alt text. <a href="https://html.spec.whatwg.org/multipage/images.html#alt" target="_blank">Check the guidance for tips on writing alt text</a>.',
                                                                                    label="Image alternative text",
                                                                                    max_length=100,
                                                                                    required=False,
                                                                                ),
                                                                            ),
                                                                        ],
                                                                        label="Teaser image",
                                                                        template="articles/blocks/images/blog-embed__image-container.html",
                                                                    ),
                                                                ),
                                                                (
                                                                    "description",
                                                                    wagtail.blocks.RichTextBlock(
                                                                        features=[
                                                                            "bold",
                                                                            "italic",
                                                                            "link",
                                                                        ],
                                                                        help_text="A description of the promoted page",
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "promoted_list",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "category",
                                                                    wagtail.snippets.blocks.SnippetChooserBlock(
                                                                        "categories.Category"
                                                                    ),
                                                                ),
                                                                (
                                                                    "summary",
                                                                    wagtail.blocks.RichTextBlock(
                                                                        features=[
                                                                            "bold",
                                                                            "italic",
                                                                            "link",
                                                                        ],
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "promoted_items",
                                                                    wagtail.blocks.ListBlock(
                                                                        wagtail.blocks.StructBlock(
                                                                            [
                                                                                (
                                                                                    "title",
                                                                                    wagtail.blocks.CharBlock(
                                                                                        help_text="The title of the target page",
                                                                                        max_length=100,
                                                                                        required=True,
                                                                                    ),
                                                                                ),
                                                                                (
                                                                                    "description",
                                                                                    wagtail.blocks.RichTextBlock(
                                                                                        features=[
                                                                                            "bold",
                                                                                            "italic",
                                                                                            "link",
                                                                                        ],
                                                                                        help_text="A description of the target page",
                                                                                        required=False,
                                                                                    ),
                                                                                ),
                                                                                (
                                                                                    "url",
                                                                                    wagtail.blocks.URLBlock(
                                                                                        required=True
                                                                                    ),
                                                                                ),
                                                                            ]
                                                                        )
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "record_links",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "items",
                                                                    wagtail.blocks.ListBlock(
                                                                        app.ciim.blocks.RecordLinkBlock,
                                                                        label="Items",
                                                                    ),
                                                                )
                                                            ]
                                                        ),
                                                    ),
                                                ],
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        blank=True,
                        null=True,
                        use_json_field=True,
                    ),
                ),
                (
                    "hero_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
                (
                    "search_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                        verbose_name="Search image",
                    ),
                ),
                (
                    "teaser_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image that will appear on thumbnails and promos around the site.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "focused article",
                "verbose_name_plural": "focused articles",
            },
            bases=(
                app.collections.models.TopicalPageMixin,
                wagtailmetadata.models.WagtailImageMetadataMixin,
                app.analytics.mixins.DataLayerMixin,
                "wagtailcore.page",
                models.Model,
            ),
        ),
    ]
