# Generated by Django 4.2.2 on 2023-07-03 12:23

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("articles", "0095_alter_articlepage_body_alter_focusedarticlepage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="focusedarticlepage",
            name="article_tag_names",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="focusedarticlepage",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="articles.TaggedArticle",
                to="articles.ArticleTag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="recordarticlepage",
            name="article_tag_names",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="recordarticlepage",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="articles.TaggedArticle",
                to="articles.ArticleTag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="articlepage",
            name="article_tag_names",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="taggedarticle",
            name="content_object",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tagged_items",
                to="wagtailcore.page",
            ),
        ),
    ]
