# Generated by Django 5.2.6 on 2025-10-21 12:59
# etna:allowAlterField

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0122_alter_articlepage_body_alter_focusedarticlepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleindexpage',
            name='short_title',
            field=models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=45, null=True, verbose_name='short title'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='short_title',
            field=models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=45, null=True, verbose_name='short title'),
        ),
        migrations.AlterField(
            model_name='focusedarticlepage',
            name='short_title',
            field=models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=45, null=True, verbose_name='short title'),
        ),
        migrations.AlterField(
            model_name='recordarticlepage',
            name='short_title',
            field=models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=45, null=True, verbose_name='short title'),
        ),
    ]
