# Generated by Django 6.0.3 on 2026-04-09 08:51
# etna:allowAlterField

import app.ciim.blocks
import django.core.validators
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0126_alter_articlepage_body_alter_focusedarticlepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("content_section", 43)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Heading", "max_length": 100},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Display a filename with the extension e.g. example.html",
                            "label": "Code block title",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("html", "HTML"),
                                ("javascript", "JavaScript"),
                                ("python", "Python"),
                                ("xml", "XML"),
                                ("json", "JSON"),
                                ("bash", "Bash"),
                                ("git", "git"),
                                ("markdown", "Markdown"),
                                ("graphql", "GraphQL"),
                                ("powershell", "PowerShell"),
                                ("yaml", "YAML"),
                            ],
                            "label": "Code language",
                            "required": False,
                        },
                    ),
                    3: ("wagtail.blocks.TextBlock", (), {"max_length": 500}),
                    4: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Allow copy to clipboard",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("filename", 1),
                                ("language", 2),
                                ("code", 3),
                                ("allow_copying", 4),
                            ]
                        ],
                        {"group": "Structured and collapsible content"},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Supertitle", "max_length": 20, "required": False},
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Title", "max_length": 100},
                    ),
                    8: ("wagtail.blocks.CharBlock", (), {"label": "Description"}),
                    9: ("wagtail.blocks.URLBlock", (), {"label": "URL"}),
                    10: (
                        "app.core.blocks.image.APIImageChooserBlock",
                        (),
                        {"label": "Image", "required": False},
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("supertitle", 6),
                                ("title", 7),
                                ("description", 8),
                                ("url", 9),
                                ("image", 10),
                            ]
                        ],
                        {"group": "Onward journeys"},
                    ),
                    12: (
                        "app.core.blocks.page_chooser.APIPageChooserBlock",
                        (),
                        {
                            "label": "Page",
                            "page_type": ["wagtailcore.Page"],
                            "required": True,
                        },
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional override for the teaser text",
                            "label": "Teaser text override",
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 12), ("teaser_text", 13)]],
                        {"group": "Onward journeys"},
                    ),
                    15: (
                        "app.core.blocks.image.APIImageChooserBlock",
                        (),
                        {"rendition_size": "max-900x900", "required": True},
                    ),
                    16: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "If provided, displays directly below the image. Can be used to specify sources, transcripts or other useful metadata.",
                            "label": "Caption (optional)",
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 15), ("caption", 16)]],
                        {"group": "Images"},
                    ),
                    18: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    19: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "code"],
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 15), ("caption", 16)]],
                        {},
                    ),
                    21: ("wagtail.blocks.ListBlock", (20,), {}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 18), ("description", 19), ("images", 21)]],
                        {"group": "Images"},
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "A descriptive title for the media block",
                            "required": True,
                        },
                    ),
                    24: (
                        "app.core.blocks.image.APIImageChooserBlock",
                        (),
                        {
                            "help_text": "A thumbnail image for the media block",
                            "rendition_size": "fill-960x540",
                            "required": False,
                        },
                    ),
                    25: ("app.media.blocks.MediaChooserBlock", (), {}),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 23), ("thumbnail", 24), ("media", 25)]],
                        {"group": "Video, audio and downloads"},
                    ),
                    27: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link", "code", "ol", "ul"]},
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 27)]],
                        {"group": "Basic text"},
                    ),
                    29: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "code", "ol", "ul"],
                            "required": True,
                        },
                    ),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 100, "required": False},
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 29), ("attribution", 30)]],
                        {"group": "Basic text"},
                    ),
                    32: (
                        "wagtail.blocks.ListBlock",
                        (app.ciim.blocks.RecordLinkBlock,),
                        {"label": "Items"},
                    ),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [[("items", 32)]],
                        {"group": "Onward journeys"},
                    ),
                    34: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Sub-heading", "max_length": 100},
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 34)]],
                        {"group": "Basic text"},
                    ),
                    36: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Title", "max_length": 100, "required": True},
                    ),
                    37: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "YouTube Video ID",
                            "max_length": 11,
                            "required": True,
                            "validators": [
                                django.core.validators.RegexValidator(
                                    message="Invalid YouTube Video ID",
                                    regex="^[a-zA-Z0-9_-]{11}$",
                                )
                            ],
                        },
                    ),
                    38: (
                        "app.core.blocks.image.APIImageChooserBlock",
                        (),
                        {
                            "label": "Preview Image",
                            "rendition_size": "fill-640x360",
                            "required": True,
                        },
                    ),
                    39: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Transcript", "required": False},
                    ),
                    40: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "Tick if the video has captions on YouTube",
                            "label": "Captions available",
                            "required": False,
                        },
                    ),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 36),
                                ("video_id", 37),
                                ("preview_image", 38),
                                ("transcript", 39),
                                ("captions_available", 40),
                            ]
                        ],
                        {"group": "Video, audio and downloads"},
                    ),
                    42: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("code", 5),
                                ("featured_external_link", 11),
                                ("featured_page", 14),
                                ("image", 17),
                                ("image_gallery", 22),
                                ("media", 26),
                                ("paragraph", 28),
                                ("quote", 31),
                                ("record_links", 33),
                                ("sub_heading", 35),
                                ("youtube_video", 41),
                            ]
                        ],
                        {"required": False},
                    ),
                    43: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("content", 42)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="focusedarticlepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("content_section", 43)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Heading", "max_length": 100},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Display a filename with the extension e.g. example.html",
                            "label": "Code block title",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("html", "HTML"),
                                ("javascript", "JavaScript"),
                                ("python", "Python"),
                                ("xml", "XML"),
                                ("json", "JSON"),
                                ("bash", "Bash"),
                                ("git", "git"),
                                ("markdown", "Markdown"),
                                ("graphql", "GraphQL"),
                                ("powershell", "PowerShell"),
                                ("yaml", "YAML"),
                            ],
                            "label": "Code language",
                            "required": False,
                        },
                    ),
                    3: ("wagtail.blocks.TextBlock", (), {"max_length": 500}),
                    4: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Allow copy to clipboard",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("filename", 1),
                                ("language", 2),
                                ("code", 3),
                                ("allow_copying", 4),
                            ]
                        ],
                        {"group": "Structured and collapsible content"},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Supertitle", "max_length": 20, "required": False},
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Title", "max_length": 100},
                    ),
                    8: ("wagtail.blocks.CharBlock", (), {"label": "Description"}),
                    9: ("wagtail.blocks.URLBlock", (), {"label": "URL"}),
                    10: (
                        "app.core.blocks.image.APIImageChooserBlock",
                        (),
                        {"label": "Image", "required": False},
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("supertitle", 6),
                                ("title", 7),
                                ("description", 8),
                                ("url", 9),
                                ("image", 10),
                            ]
                        ],
                        {"group": "Onward journeys"},
                    ),
                    12: (
                        "app.core.blocks.page_chooser.APIPageChooserBlock",
                        (),
                        {
                            "label": "Page",
                            "page_type": ["wagtailcore.Page"],
                            "required": True,
                        },
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional override for the teaser text",
                            "label": "Teaser text override",
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 12), ("teaser_text", 13)]],
                        {"group": "Onward journeys"},
                    ),
                    15: (
                        "app.core.blocks.image.APIImageChooserBlock",
                        (),
                        {"rendition_size": "max-900x900", "required": True},
                    ),
                    16: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "If provided, displays directly below the image. Can be used to specify sources, transcripts or other useful metadata.",
                            "label": "Caption (optional)",
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 15), ("caption", 16)]],
                        {"group": "Images"},
                    ),
                    18: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    19: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "code"],
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 15), ("caption", 16)]],
                        {},
                    ),
                    21: ("wagtail.blocks.ListBlock", (20,), {}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 18), ("description", 19), ("images", 21)]],
                        {"group": "Images"},
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "A descriptive title for the media block",
                            "required": True,
                        },
                    ),
                    24: (
                        "app.core.blocks.image.APIImageChooserBlock",
                        (),
                        {
                            "help_text": "A thumbnail image for the media block",
                            "rendition_size": "fill-960x540",
                            "required": False,
                        },
                    ),
                    25: ("app.media.blocks.MediaChooserBlock", (), {}),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 23), ("thumbnail", 24), ("media", 25)]],
                        {"group": "Video, audio and downloads"},
                    ),
                    27: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link", "code", "ol", "ul"]},
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 27)]],
                        {"group": "Basic text"},
                    ),
                    29: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "code", "ol", "ul"],
                            "required": True,
                        },
                    ),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 100, "required": False},
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 29), ("attribution", 30)]],
                        {"group": "Basic text"},
                    ),
                    32: (
                        "wagtail.blocks.ListBlock",
                        (app.ciim.blocks.RecordLinkBlock,),
                        {"label": "Items"},
                    ),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [[("items", 32)]],
                        {"group": "Onward journeys"},
                    ),
                    34: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Sub-heading", "max_length": 100},
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 34)]],
                        {"group": "Basic text"},
                    ),
                    36: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Title", "max_length": 100, "required": True},
                    ),
                    37: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "YouTube Video ID",
                            "max_length": 11,
                            "required": True,
                            "validators": [
                                django.core.validators.RegexValidator(
                                    message="Invalid YouTube Video ID",
                                    regex="^[a-zA-Z0-9_-]{11}$",
                                )
                            ],
                        },
                    ),
                    38: (
                        "app.core.blocks.image.APIImageChooserBlock",
                        (),
                        {
                            "label": "Preview Image",
                            "rendition_size": "fill-640x360",
                            "required": True,
                        },
                    ),
                    39: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Transcript", "required": False},
                    ),
                    40: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "Tick if the video has captions on YouTube",
                            "label": "Captions available",
                            "required": False,
                        },
                    ),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 36),
                                ("video_id", 37),
                                ("preview_image", 38),
                                ("transcript", 39),
                                ("captions_available", 40),
                            ]
                        ],
                        {"group": "Video, audio and downloads"},
                    ),
                    42: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("code", 5),
                                ("featured_external_link", 11),
                                ("featured_page", 14),
                                ("image", 17),
                                ("image_gallery", 22),
                                ("media", 26),
                                ("paragraph", 28),
                                ("quote", 31),
                                ("record_links", 33),
                                ("sub_heading", 35),
                                ("youtube_video", 41),
                            ]
                        ],
                        {"required": False},
                    ),
                    43: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("content", 42)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
