# Generated by Django 5.0.2 on 2024-03-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recordseries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordseries",
            name="catalogue_search_query",
            field=models.CharField(
                default="",
                help_text="The query to use in the catalogue search to filter the records.",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
