# Generated by Django 4.1.7 on 2023-03-30 10:08

from django.db import migrations, models
import django.db.models.deletion
import uuid
import wagtail.blocks
import wagtail.fields
import wagtail.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackPrompt",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="public ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        default="What did you think of this page?",
                        max_length=200,
                        verbose_name="prompt text",
                    ),
                ),
                (
                    "response_options",
                    wagtail.fields.StreamField(
                        [
                            (
                                "option",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "icon",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    (
                                                        "images/thumb-up.png",
                                                        "Thumbs up",
                                                    ),
                                                    (
                                                        "images/thumb-down.png",
                                                        "Thumbs down",
                                                    ),
                                                ],
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "label",
                                            wagtail.blocks.CharBlock(
                                                label="label", max_length=100
                                            ),
                                        ),
                                        (
                                            "sentiment",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    (-2, "Very negative"),
                                                    (-1, "Negative"),
                                                    (0, "Neutral"),
                                                    (1, "Positive"),
                                                    (2, "Very positive"),
                                                ],
                                                label="sentiment",
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        use_json_field=True,
                        verbose_name="response options",
                    ),
                ),
                (
                    "thank_you_heading",
                    models.CharField(
                        default="Thank you for your valuable feedback",
                        help_text="Displayed to users after succesfully submitting feedback.",
                        max_length=100,
                        verbose_name="thank you heading",
                    ),
                ),
                (
                    "thank_you_message",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="If supplied, displayed below the 'Thank you heading' when a user succesfully submits feedback.",
                        max_length=200,
                        verbose_name="thank you message",
                    ),
                ),
                (
                    "continue_link_text",
                    models.CharField(
                        default="Return to the previous page",
                        help_text='After submitting feedback, non-JS users are taken to a success page, where the thank you headding and text are displayed, followed by a link to return to the previous page. This field can be used to change the text of that link. For example, "Continue with your search" might make more sense to users.',
                        max_length=200,
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        db_index=True,
                        help_text='The URL path this prompt should be displayed on. For example: "/search/catalogue/".',
                        max_length=255,
                        verbose_name="use for path",
                    ),
                ),
                (
                    "startswith_path",
                    models.BooleanField(
                        default=False,
                        verbose_name="also match paths that start with the above",
                    ),
                ),
                (
                    "latest_revision",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.revision",
                        verbose_name="latest revision",
                    ),
                ),
            ],
            options={
                "ordering": ("path", "startswith_path"),
                "unique_together": {("path", "startswith_path")},
            },
        ),
    ]
