# Generated by Django 4.1.7 on 2023-03-30 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("feedback", "0002_add_default_prompt"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackSubmission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="received at"),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="public ID",
                    ),
                ),
                ("full_url", models.TextField(verbose_name="full URL")),
                (
                    "path",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="path"
                    ),
                ),
                (
                    "query_params",
                    models.JSONField(default=dict, verbose_name="query params"),
                ),
                (
                    "prompt_text",
                    models.CharField(max_length=200, verbose_name="prompt text"),
                ),
                (
                    "response_sentiment",
                    models.SmallIntegerField(
                        db_index=True, verbose_name="response sentiment"
                    ),
                ),
                (
                    "response_label",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="response label"
                    ),
                ),
                ("comment", models.TextField(verbose_name="comment")),
                (
                    "page_revision_published",
                    models.DateTimeField(
                        null=True, verbose_name="page revision published at"
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wagtailcore.page",
                        verbose_name="wagtail page",
                    ),
                ),
                (
                    "page_revision",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.revision",
                        verbose_name="page revision",
                    ),
                ),
                (
                    "prompt",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submissions",
                        to="feedback.feedbackprompt",
                        verbose_name="prompt",
                    ),
                ),
                (
                    "prompt_revision",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.revision",
                        verbose_name="prompt revision",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="wagtailcore.site",
                        verbose_name="site",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "ordering": ("-received_at", "-id"),
            },
        ),
    ]
