# Generated by Django 4.2.2 on 2023-06-30 15:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("feedback", "0007_alter_feedbacksubmission"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="feedbackprompt",
            unique_together=set(),
        ),
    ]
