# Generated by Django 5.0.2 on 2024-02-28 13:16

import etna.core.blocks.paragraph
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0011_feedbacksubmission_page_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbackprompt",
            name="thank_you_message",
            field=etna.core.blocks.paragraph.APIRichTextField(
                blank=True,
                help_text="If supplied, displayed below the 'Thank you heading' when a user succesfully submits feedback.",
                max_length=200,
                verbose_name="thank you message",
            ),
        ),
    ]
