# Generated by Django 5.0.8 on 2024-10-14 14:10

import django.db.models.deletion
import django.utils.timezone
import app.analytics.mixins
import app.people.models
import uuid
import wagtail.fields
import wagtail_headless_preview.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alerts", "0003_alert_name_alter_alert_title"),
        ("images", "0009_alter_customimage_custom_sensitive_image_warning"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "hero_image_caption",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="An optional caption for hero images. This could be used for image sources or for other useful metadata.",
                        verbose_name="hero image caption (optional)",
                    ),
                ),
                (
                    "twitter_og_title",
                    models.CharField(
                        blank=True,
                        help_text="If left blank, the OpenGraph title will be used.",
                        max_length=255,
                        null=True,
                        verbose_name="Twitter OpenGraph title",
                    ),
                ),
                (
                    "twitter_og_description",
                    models.TextField(
                        blank=True,
                        help_text="If left blank, the OpenGraph description will be used.",
                        null=True,
                        verbose_name="Twitter OpenGraph description",
                    ),
                ),
                (
                    "teaser_text",
                    models.TextField(
                        help_text="A short, enticing description of this page. This will appear in promos and under thumbnails around the site.",
                        max_length=160,
                        verbose_name="teaser text",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(
                        help_text="1-2 sentences introducing the subject of the page, and explaining why a user should read on.",
                        max_length=300,
                        verbose_name="introductory text",
                    ),
                ),
                (
                    "alert",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="alerts.alert",
                    ),
                ),
                (
                    "hero_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
                (
                    "search_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image that will appear when this page is shared on social media. This will default to the teaser image if left blank.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                        verbose_name="OpenGraph image",
                    ),
                ),
                (
                    "teaser_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image that will appear on thumbnails and promos around the site.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
                (
                    "twitter_og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="If left blank, the OpenGraph image will be used.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                        verbose_name="Twitter OpenGraph image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                app.analytics.mixins.DataLayerMixin,
                wagtail_headless_preview.models.HeadlessPreviewMixin,
                "wagtailcore.page",
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="BlogPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "hero_image_caption",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="An optional caption for hero images. This could be used for image sources or for other useful metadata.",
                        verbose_name="hero image caption (optional)",
                    ),
                ),
                (
                    "twitter_og_title",
                    models.CharField(
                        blank=True,
                        help_text="If left blank, the OpenGraph title will be used.",
                        max_length=255,
                        null=True,
                        verbose_name="Twitter OpenGraph title",
                    ),
                ),
                (
                    "twitter_og_description",
                    models.TextField(
                        blank=True,
                        help_text="If left blank, the OpenGraph description will be used.",
                        null=True,
                        verbose_name="Twitter OpenGraph description",
                    ),
                ),
                (
                    "teaser_text",
                    models.TextField(
                        help_text="A short, enticing description of this page. This will appear in promos and under thumbnails around the site.",
                        max_length=160,
                        verbose_name="teaser text",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(
                        help_text="1-2 sentences introducing the subject of the page, and explaining why a user should read on.",
                        max_length=300,
                        verbose_name="introductory text",
                    ),
                ),
                (
                    "alert",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="alerts.alert",
                    ),
                ),
                (
                    "hero_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
                (
                    "search_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image that will appear when this page is shared on social media. This will default to the teaser image if left blank.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                        verbose_name="OpenGraph image",
                    ),
                ),
                (
                    "teaser_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image that will appear on thumbnails and promos around the site.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
                (
                    "twitter_og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="If left blank, the OpenGraph image will be used.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                        verbose_name="Twitter OpenGraph image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                app.analytics.mixins.DataLayerMixin,
                wagtail_headless_preview.models.HeadlessPreviewMixin,
                "wagtailcore.page",
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="BlogPostPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "display_content_warning",
                    models.BooleanField(
                        default=False,
                        verbose_name="display a content warning on this page",
                    ),
                ),
                (
                    "custom_warning_text",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="If specified, will be used for the content warning. Otherwise the default text will be used.",
                        verbose_name="custom content warning text (optional)",
                    ),
                ),
                (
                    "twitter_og_title",
                    models.CharField(
                        blank=True,
                        help_text="If left blank, the OpenGraph title will be used.",
                        max_length=255,
                        null=True,
                        verbose_name="Twitter OpenGraph title",
                    ),
                ),
                (
                    "twitter_og_description",
                    models.TextField(
                        blank=True,
                        help_text="If left blank, the OpenGraph description will be used.",
                        null=True,
                        verbose_name="Twitter OpenGraph description",
                    ),
                ),
                (
                    "teaser_text",
                    models.TextField(
                        help_text="A short, enticing description of this page. This will appear in promos and under thumbnails around the site.",
                        max_length=160,
                        verbose_name="teaser text",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(
                        help_text="1-2 sentences introducing the subject of the page, and explaining why a user should read on.",
                        max_length=300,
                        verbose_name="introductory text",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("content_section", 39)],
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Heading", "max_length": 100},
                            ),
                            1: ("wagtail.blocks.CharBlock", (), {}),
                            2: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link"],
                                    "required": False,
                                },
                            ),
                            3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            4: ("wagtail.blocks.URLBlock", (), {"required": False}),
                            5: (
                                "app.core.blocks.paragraph.APIRichTextBlock",
                                (),
                                {"required": False},
                            ),
                            6: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                            7: (
                                "app.core.blocks.paragraph.APIRichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link"],
                                    "required": False,
                                },
                            ),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 1),
                                        ("address", 2),
                                        ("telephone", 3),
                                        ("chat_link", 4),
                                        ("chat_note", 5),
                                        ("email", 6),
                                        ("website_link", 4),
                                        ("social_media", 7),
                                    ]
                                ],
                                {},
                            ),
                            9: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {"required": True},
                            ),
                            10: ("wagtail.blocks.StructBlock", [[("file", 9)]], {}),
                            11: ("wagtail.blocks.ListBlock", (10,), {}),
                            12: (
                                "wagtail.blocks.StructBlock",
                                [[("documents", 11)]],
                                {},
                            ),
                            13: (
                                "app.core.blocks.page_chooser.APIPageChooserBlock",
                                (),
                                {
                                    "label": "Page",
                                    "page_type": ["wagtailcore.Page"],
                                    "required": True,
                                },
                            ),
                            14: ("wagtail.blocks.StructBlock", [[("page", 13)]], {}),
                            15: (
                                "app.core.blocks.image.APIImageChooserBlock",
                                (),
                                {"rendition_size": "max-900x900", "required": True},
                            ),
                            16: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": 'Alternative (alt) text describes images when they fail to load, and is read aloud by assistive technologies. Use a maximum of 100 characters to describe your image. <a href="https://html.spec.whatwg.org/multipage/images.html#alt" target="_blank">Check the guidance for tips on writing alt text</a>.',
                                    "label": "Alternative text",
                                    "max_length": 100,
                                },
                            ),
                            17: (
                                "app.core.blocks.paragraph.APIRichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link"],
                                    "help_text": "If provided, displays directly below the image. Can be used to specify sources, transcripts or other useful metadata.",
                                    "label": "Caption (optional)",
                                    "required": False,
                                },
                            ),
                            18: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 15), ("alt_text", 16), ("caption", 17)]],
                                {},
                            ),
                            19: ("wagtail.blocks.ListBlock", (18,), {}),
                            20: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 3), ("description", 7), ("images", 19)]],
                                {},
                            ),
                            21: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "A descriptive title for the media block",
                                    "required": True,
                                },
                            ),
                            22: (
                                "app.core.blocks.image.APIImageChooserBlock",
                                (),
                                {"help_text": "A background image for the media block"},
                            ),
                            23: ("app.media.blocks.MediaChooserBlock", (), {}),
                            24: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 21),
                                        ("background_image", 22),
                                        ("media", 23),
                                    ]
                                ],
                                {},
                            ),
                            25: (
                                "app.core.blocks.paragraph.APIRichTextBlock",
                                (),
                                {"features": ["bold", "italic", "link", "ol", "ul"]},
                            ),
                            26: ("wagtail.blocks.StructBlock", [[("text", 25)]], {}),
                            27: (
                                "app.core.blocks.paragraph.APIRichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link"],
                                    "required": True,
                                },
                            ),
                            28: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 100, "required": False},
                            ),
                            29: (
                                "wagtail.blocks.StructBlock",
                                [[("quote", 27), ("attribution", 28)]],
                                {},
                            ),
                            30: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Sub-heading", "max_length": 100},
                            ),
                            31: ("wagtail.blocks.StructBlock", [[("heading", 30)]], {}),
                            32: (
                                "wagtail.contrib.table_block.blocks.TableBlock",
                                (),
                                {
                                    "table_options": {
                                        "contextMenu": [
                                            "row_above",
                                            "row_below",
                                            "---------",
                                            "col_left",
                                            "col_right",
                                            "---------",
                                            "remove_row",
                                            "remove_col",
                                            "---------",
                                            "undo",
                                            "redo",
                                            "---------",
                                            "alignment",
                                        ]
                                    }
                                },
                            ),
                            33: ("wagtail.blocks.StructBlock", [[("table", 32)]], {}),
                            34: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Title", "max_length": 100, "required": True},
                            ),
                            35: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "YouTube Video ID",
                                    "max_length": 11,
                                    "required": True,
                                },
                            ),
                            36: (
                                "app.core.blocks.image.APIImageChooserBlock",
                                (),
                                {
                                    "label": "Preview Image",
                                    "rendition_size": "max-640x360",
                                    "required": False,
                                },
                            ),
                            37: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 34),
                                        ("video_id", 35),
                                        ("preview_image", 36),
                                    ]
                                ],
                                {},
                            ),
                            38: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("contact", 8),
                                        ("document", 12),
                                        ("featured_page", 14),
                                        ("image", 18),
                                        ("image_gallery", 20),
                                        ("media", 24),
                                        ("paragraph", 26),
                                        ("quote", 29),
                                        ("sub_heading", 31),
                                        ("table", 33),
                                        ("youtube_video", 37),
                                    ]
                                ],
                                {"required": False},
                            ),
                            39: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 0), ("content", 38)]],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "published_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="The date the blog post was published.",
                        verbose_name="Published date",
                    ),
                ),
                (
                    "alert",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="alerts.alert",
                    ),
                ),
                (
                    "search_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image that will appear when this page is shared on social media. This will default to the teaser image if left blank.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                        verbose_name="OpenGraph image",
                    ),
                ),
                (
                    "teaser_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image that will appear on thumbnails and promos around the site.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
                (
                    "twitter_og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="If left blank, the OpenGraph image will be used.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                        verbose_name="Twitter OpenGraph image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                app.people.models.AuthorPageMixin,
                app.analytics.mixins.DataLayerMixin,
                wagtail_headless_preview.models.HeadlessPreviewMixin,
                "wagtailcore.page",
                models.Model,
            ),
        ),
    ]
