# Generated by Django 6.0.7 on 2026-07-30 13:11

import app.ciim.blocks
import app.core.models.mixins
import app.people.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('twitter_og_title', models.CharField(blank=True, help_text='If left blank, the OpenGraph title will be used.', max_length=255, null=True, verbose_name='Twitter OpenGraph title')),
                ('twitter_og_description', models.TextField(blank=True, help_text='If left blank, the OpenGraph description will be used.', null=True, verbose_name='Twitter OpenGraph description')),
                ('short_title', models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=45, null=True, verbose_name='short title')),
                ('teaser_text', models.TextField(help_text='A short, enticing description of this page. This will appear in promos and under thumbnails around the site.', max_length=160, verbose_name='teaser text')),
                ('intro', wagtail.fields.RichTextField(help_text='1-2 sentences introducing the subject of the page, and explaining why a user should read on.', max_length=300, verbose_name='introductory text')),
            ],
            options={
                'abstract': False,
            },
            bases=(app.core.models.mixins.CustomHeadlessPreviewMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_image_caption', wagtail.fields.RichTextField(blank=True, help_text='An optional caption for hero images. This could be used for image sources or for other useful metadata.', verbose_name='hero image caption (optional)')),
                ('twitter_og_title', models.CharField(blank=True, help_text='If left blank, the OpenGraph title will be used.', max_length=255, null=True, verbose_name='Twitter OpenGraph title')),
                ('twitter_og_description', models.TextField(blank=True, help_text='If left blank, the OpenGraph description will be used.', null=True, verbose_name='Twitter OpenGraph description')),
                ('short_title', models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=45, null=True, verbose_name='short title')),
                ('teaser_text', models.TextField(help_text='A short, enticing description of this page. This will appear in promos and under thumbnails around the site.', max_length=160, verbose_name='teaser text')),
                ('intro', wagtail.fields.RichTextField(help_text='1-2 sentences introducing the subject of the page, and explaining why a user should read on.', max_length=300, verbose_name='introductory text')),
                ('custom_type_label', models.CharField(blank=True, help_text='Override the chip for child blog posts. If left blank, the chip will be the title of the blog.', max_length=20, null=True, verbose_name='Chip override')),
            ],
            options={
                'abstract': False,
            },
            bases=(app.core.models.mixins.CustomHeadlessPreviewMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='BlogPostPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('custom_warning_text', wagtail.fields.RichTextField(blank=True, help_text='If specified, will be used for the content warning.', verbose_name='custom content warning text (optional)')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, help_text='The date the page was published to the public.', verbose_name='Published date')),
                ('hero_image_caption', wagtail.fields.RichTextField(blank=True, help_text='An optional caption for hero images. This could be used for image sources or for other useful metadata.', verbose_name='hero image caption (optional)')),
                ('twitter_og_title', models.CharField(blank=True, help_text='If left blank, the OpenGraph title will be used.', max_length=255, null=True, verbose_name='Twitter OpenGraph title')),
                ('twitter_og_description', models.TextField(blank=True, help_text='If left blank, the OpenGraph description will be used.', null=True, verbose_name='Twitter OpenGraph description')),
                ('short_title', models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=45, null=True, verbose_name='short title')),
                ('teaser_text', models.TextField(help_text='A short, enticing description of this page. This will appear in promos and under thumbnails around the site.', max_length=160, verbose_name='teaser text')),
                ('intro', wagtail.fields.RichTextField(help_text='1-2 sentences introducing the subject of the page, and explaining why a user should read on.', max_length=300, verbose_name='introductory text')),
                ('body', wagtail.fields.StreamField([('call_to_action', 6), ('code', 11), ('contact', 18), ('document', 22), ('featured_external_link', 28), ('featured_page', 31), ('image', 34), ('image_gallery', 36), ('inset_text', 38), ('media', 42), ('paragraph', 38), ('partner_logos', 46), ('quote', 54), ('record_links', 56), ('table', 58), ('youtube_video', 64), ('content_section', 71)], block_lookup={0: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link', 'code', 'ol', 'ul'], 'max_length': 100}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('app.core.blocks.page_chooser.APIPageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Use the accented button style', 'label': 'Accented', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('label', 1), ('link', 2), ('external_link', 3), ('accented', 4)]], {}), 6: ('wagtail.blocks.StructBlock', [[('body', 0), ('button', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Display a filename with the extension e.g. example.html', 'label': 'Code block title', 'max_length': 100, 'required': False}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('html', 'HTML'), ('javascript', 'JavaScript'), ('python', 'Python'), ('xml', 'XML'), ('json', 'JSON'), ('bash', 'Bash'), ('git', 'git'), ('markdown', 'Markdown'), ('graphql', 'GraphQL'), ('powershell', 'PowerShell'), ('yaml', 'YAML')], 'label': 'Code language', 'required': False}), 9: ('wagtail.blocks.TextBlock', (), {'max_length': 500}), 10: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Allow copy to clipboard', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('filename', 7), ('language', 8), ('code', 9), ('allow_copying', 10)]], {}), 12: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['link'], 'required': False}), 13: ('wagtail.blocks.TextBlock', (), {'features': ['bold', 'italic', 'link', 'code'], 'required': False}), 14: ('wagtail.blocks.CharBlock', (), {'required': False}), 15: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'required': False}), 16: ('wagtail.blocks.EmailBlock', (), {'required': False}), 17: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link', 'code'], 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('title', 1), ('body', 12), ('address', 13), ('telephone', 14), ('chat_link', 3), ('chat_note', 15), ('email', 16), ('website_link', 3), ('social_media', 17)]], {}), 19: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': True}), 20: ('wagtail.blocks.StructBlock', [[('file', 19)]], {}), 21: ('wagtail.blocks.ListBlock', (20,), {'min_num': 1}), 22: ('wagtail.blocks.StructBlock', [[('documents', 21)]], {}), 23: ('wagtail.blocks.CharBlock', (), {'label': 'Supertitle', 'max_length': 20, 'required': False}), 24: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 100}), 25: ('wagtail.blocks.CharBlock', (), {'label': 'Description'}), 26: ('wagtail.blocks.URLBlock', (), {'label': 'URL'}), 27: ('app.core.blocks.image.APIImageChooserBlock', (), {'label': 'Image', 'required': False}), 28: ('wagtail.blocks.StructBlock', [[('supertitle', 23), ('title', 24), ('description', 25), ('url', 26), ('image', 27)]], {}), 29: ('app.core.blocks.page_chooser.APIPageChooserBlock', (), {'label': 'Page', 'page_type': ['wagtailcore.Page'], 'required': True}), 30: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional override for the teaser text', 'label': 'Teaser text override', 'required': False}), 31: ('wagtail.blocks.StructBlock', [[('page', 29), ('teaser_text', 30)]], {}), 32: ('app.core.blocks.image.APIImageChooserBlock', (), {'rendition_size': 'max-900x900', 'required': True}), 33: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'help_text': 'If provided, displays directly below the image. Can be used to specify sources, transcripts or other useful metadata.', 'label': 'Caption (optional)', 'required': False}), 34: ('wagtail.blocks.StructBlock', [[('image', 32), ('caption', 33)]], {}), 35: ('wagtail.blocks.ListBlock', (34,), {}), 36: ('wagtail.blocks.StructBlock', [[('title', 14), ('description', 17), ('images', 35)]], {}), 37: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link', 'code', 'ol', 'ul']}), 38: ('wagtail.blocks.StructBlock', [[('text', 37)]], {}), 39: ('wagtail.blocks.CharBlock', (), {'help_text': 'A descriptive title for the media block', 'required': True}), 40: ('app.core.blocks.image.APIImageChooserBlock', (), {'help_text': 'A thumbnail image for the media block', 'rendition_size': 'fill-960x540', 'required': False}), 41: ('app.media.blocks.MediaChooserBlock', (), {}), 42: ('wagtail.blocks.StructBlock', [[('title', 39), ('thumbnail', 40), ('media', 41)]], {}), 43: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional override for the partner logos section lead text. Will display a default if not provided.', 'max_length': 40, 'required': False}), 44: ('app.core.blocks.image.PartnerLogoChooserBlock', (), {}), 45: ('wagtail.blocks.ListBlock', (44,), {'max_num': 4, 'required': True}), 46: ('wagtail.blocks.StructBlock', [[('lead_text', 43), ('logos', 45)]], {}), 47: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link', 'code', 'ol', 'ul'], 'required': True}), 48: ('wagtail.blocks.CharBlock', (), {'help_text': 'The name of the person being quoted. e.g. King Edward VIII', 'max_length': 100}), 49: ('wagtail.blocks.CharBlock', (), {'help_text': 'The title of the work or document from which the quote is taken. e.g. The Telegraph, 23 June 1986', 'max_length': 100, 'required': False}), 50: ('app.core.blocks.page_chooser.APIPageChooserBlock', (), {'help_text': 'Reference another page published on the site', 'label': 'Internal page', 'required': False}), 51: ('wagtail.blocks.URLBlock', (), {'help_text': 'Add a URL here to refer to an external source', 'label': 'External link', 'required': False}), 52: ('wagtail.blocks.StructBlock', [[('citation_internal_link', 50), ('citation_external_link', 51)]], {}), 53: ('wagtail.blocks.StructBlock', [[('citation', 49), ('source_link', 52)]], {}), 54: ('wagtail.blocks.StructBlock', [[('quote', 47), ('attribution', 48), ('source', 53)]], {}), 55: ('wagtail.blocks.ListBlock', (app.ciim.blocks.RecordLinkBlock,), {'label': 'Items'}), 56: ('wagtail.blocks.StructBlock', [[('items', 55)]], {}), 57: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'table_options': {'contextMenu': ['row_above', 'row_below', '---------', 'col_left', 'col_right', '---------', 'remove_row', 'remove_col', '---------', 'undo', 'redo', '---------', 'alignment']}}), 58: ('wagtail.blocks.StructBlock', [[('table', 57)]], {}), 59: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 100, 'required': True}), 60: ('wagtail.blocks.CharBlock', (), {'label': 'YouTube Video ID', 'max_length': 11, 'required': True, 'validators': [django.core.validators.RegexValidator(message='Invalid YouTube Video ID', regex='^[a-zA-Z0-9_-]{11}$')]}), 61: ('app.core.blocks.image.APIImageChooserBlock', (), {'label': 'Preview Image', 'rendition_size': 'fill-640x360', 'required': True}), 62: ('wagtail.blocks.RichTextBlock', (), {'label': 'Transcript', 'required': False}), 63: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Tick if the video has captions on YouTube', 'label': 'Captions available', 'required': False}), 64: ('wagtail.blocks.StructBlock', [[('title', 59), ('video_id', 60), ('preview_image', 61), ('transcript', 62), ('captions_available', 63)]], {}), 65: ('wagtail.blocks.CharBlock', (), {'label': 'Heading', 'max_length': 100}), 66: ('wagtail.blocks.CharBlock', (), {'label': 'Sub-heading', 'max_length': 100}), 67: ('wagtail.blocks.StructBlock', [[('heading', 66)]], {}), 68: ('wagtail.blocks.CharBlock', (), {'label': 'Sub-sub-heading', 'max_length': 100}), 69: ('wagtail.blocks.StructBlock', [[('heading', 68)]], {}), 70: ('wagtail.blocks.StreamBlock', [[('call_to_action', 6), ('code', 11), ('contact', 18), ('document', 22), ('featured_external_link', 28), ('featured_page', 31), ('image', 34), ('image_gallery', 36), ('inset_text', 38), ('media', 42), ('paragraph', 38), ('partner_logos', 46), ('quote', 54), ('record_links', 56), ('sub_heading', 67), ('sub_sub_heading', 69), ('table', 58), ('youtube_video', 64)]], {'required': False}), 71: ('wagtail.blocks.StructBlock', [[('heading', 65), ('content', 70)]], {})})),
            ],
            options={
                'verbose_name': 'Blog post page',
                'verbose_name_plural': 'Blog post pages',
            },
            bases=(app.people.models.AuthorPageMixin, app.people.models.ExternalAuthorMixin, app.core.models.mixins.CustomHeadlessPreviewMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='BlogFeedsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('twitter_og_title', models.CharField(blank=True, help_text='If left blank, the OpenGraph title will be used.', max_length=255, null=True, verbose_name='Twitter OpenGraph title')),
                ('twitter_og_description', models.TextField(blank=True, help_text='If left blank, the OpenGraph description will be used.', null=True, verbose_name='Twitter OpenGraph description')),
                ('short_title', models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=45, null=True, verbose_name='short title')),
                ('teaser_text', models.TextField(help_text='A short, enticing description of this page. This will appear in promos and under thumbnails around the site.', max_length=160, verbose_name='teaser text')),
                ('body', wagtail.fields.RichTextField(blank=True, help_text='Body text to appear above the list of feeds.')),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='alerts.alert')),
            ],
            options={
                'abstract': False,
            },
            bases=(app.core.models.mixins.CustomHeadlessPreviewMixin, 'wagtailcore.page', models.Model),
        ),
    ]
