# Generated by Django 5.0.8 on 2024-10-15 10:11
# etna:allowAlterField

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpostpage",
            options={
                "verbose_name": "Blog post page",
                "verbose_name_plural": "Blog post pages",
            },
        ),
        migrations.AlterField(
            model_name="blogpostpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("content_section", 40)],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Heading", "max_length": 100},
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {}),
                    2: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"features": ["bold", "italic", "link"], "required": False},
                    ),
                    3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    4: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    5: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"required": False},
                    ),
                    6: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    7: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link"], "required": False},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 1),
                                ("address", 2),
                                ("telephone", 3),
                                ("chat_link", 4),
                                ("chat_note", 5),
                                ("email", 6),
                                ("website_link", 4),
                                ("social_media", 7),
                            ]
                        ],
                        {},
                    ),
                    9: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": True},
                    ),
                    10: ("wagtail.blocks.StructBlock", [[("file", 9)]], {}),
                    11: ("wagtail.blocks.ListBlock", (10,), {}),
                    12: ("wagtail.blocks.StructBlock", [[("documents", 11)]], {}),
                    13: (
                        "app.core.blocks.page_chooser.APIPageChooserBlock",
                        (),
                        {
                            "label": "Page",
                            "page_type": ["wagtailcore.Page"],
                            "required": True,
                        },
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional override for the teaser text",
                            "label": "Teaser text override",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 13), ("teaser_text", 14)]],
                        {},
                    ),
                    16: (
                        "app.core.blocks.image.APIImageChooserBlock",
                        (),
                        {"rendition_size": "max-900x900", "required": True},
                    ),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Alternative (alt) text describes images when they fail to load, and is read aloud by assistive technologies. Use a maximum of 100 characters to describe your image. <a href="https://html.spec.whatwg.org/multipage/images.html#alt" target="_blank">Check the guidance for tips on writing alt text</a>.',
                            "label": "Alternative text",
                            "max_length": 100,
                        },
                    ),
                    18: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "If provided, displays directly below the image. Can be used to specify sources, transcripts or other useful metadata.",
                            "label": "Caption (optional)",
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 16), ("alt_text", 17), ("caption", 18)]],
                        {},
                    ),
                    20: ("wagtail.blocks.ListBlock", (19,), {}),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 3), ("description", 7), ("images", 20)]],
                        {},
                    ),
                    22: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "A descriptive title for the media block",
                            "required": True,
                        },
                    ),
                    23: (
                        "app.core.blocks.image.APIImageChooserBlock",
                        (),
                        {"help_text": "A background image for the media block"},
                    ),
                    24: ("app.media.blocks.MediaChooserBlock", (), {}),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 22), ("background_image", 23), ("media", 24)]],
                        {},
                    ),
                    26: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link", "ol", "ul"]},
                    ),
                    27: ("wagtail.blocks.StructBlock", [[("text", 26)]], {}),
                    28: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link"], "required": True},
                    ),
                    29: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 100, "required": False},
                    ),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 28), ("attribution", 29)]],
                        {},
                    ),
                    31: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Sub-heading", "max_length": 100},
                    ),
                    32: ("wagtail.blocks.StructBlock", [[("heading", 31)]], {}),
                    33: (
                        "wagtail.contrib.table_block.blocks.TableBlock",
                        (),
                        {
                            "table_options": {
                                "contextMenu": [
                                    "row_above",
                                    "row_below",
                                    "---------",
                                    "col_left",
                                    "col_right",
                                    "---------",
                                    "remove_row",
                                    "remove_col",
                                    "---------",
                                    "undo",
                                    "redo",
                                    "---------",
                                    "alignment",
                                ]
                            }
                        },
                    ),
                    34: ("wagtail.blocks.StructBlock", [[("table", 33)]], {}),
                    35: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Title", "max_length": 100, "required": True},
                    ),
                    36: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "YouTube Video ID",
                            "max_length": 11,
                            "required": True,
                        },
                    ),
                    37: (
                        "app.core.blocks.image.APIImageChooserBlock",
                        (),
                        {
                            "label": "Preview Image",
                            "rendition_size": "max-640x360",
                            "required": False,
                        },
                    ),
                    38: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 35), ("video_id", 36), ("preview_image", 37)]],
                        {},
                    ),
                    39: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("contact", 8),
                                ("document", 12),
                                ("featured_page", 15),
                                ("image", 19),
                                ("image_gallery", 21),
                                ("media", 25),
                                ("paragraph", 27),
                                ("quote", 30),
                                ("sub_heading", 32),
                                ("table", 34),
                                ("youtube_video", 38),
                            ]
                        ],
                        {"required": False},
                    ),
                    40: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("content", 39)]],
                        {},
                    ),
                },
            ),
        ),
    ]
