# Generated by Django 5.0.8 on 2024-10-17 11:12
# etna:allowAlterField

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blogpostpage_options_alter_blogpostpage_body"),
        ("images", "0009_alter_customimage_custom_sensitive_image_warning"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpostpage",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
            ),
        ),
        migrations.AddField(
            model_name="blogpostpage",
            name="hero_image_caption",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="An optional caption for hero images. This could be used for image sources or for other useful metadata.",
                verbose_name="hero image caption (optional)",
            ),
        ),
        migrations.AlterField(
            model_name="blogpostpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("call_to_action", 6),
                    ("contact", 12),
                    ("document", 16),
                    ("featured_external_link", 21),
                    ("featured_page", 24),
                    ("image", 28),
                    ("image_gallery", 30),
                    ("inset_text", 32),
                    ("media", 36),
                    ("paragraph", 32),
                    ("quote", 39),
                    ("table", 41),
                    ("youtube_video", 45),
                    ("content_section", 50),
                ],
                block_lookup={
                    0: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "ol", "ul"],
                            "max_length": 100,
                        },
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {}),
                    2: (
                        "app.core.blocks.page_chooser.APIPageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    3: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    4: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "Use the accented button style",
                            "label": "Accented",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 1),
                                ("link", 2),
                                ("external_link", 3),
                                ("accented", 4),
                            ]
                        ],
                        {},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("body", 0), ("button", 5)]],
                        {},
                    ),
                    7: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"features": ["bold", "italic", "link"], "required": False},
                    ),
                    8: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    9: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"required": False},
                    ),
                    10: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    11: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link"], "required": False},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 1),
                                ("address", 7),
                                ("telephone", 8),
                                ("chat_link", 3),
                                ("chat_note", 9),
                                ("email", 10),
                                ("website_link", 3),
                                ("social_media", 11),
                            ]
                        ],
                        {},
                    ),
                    13: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": True},
                    ),
                    14: ("wagtail.blocks.StructBlock", [[("file", 13)]], {}),
                    15: ("wagtail.blocks.ListBlock", (14,), {}),
                    16: ("wagtail.blocks.StructBlock", [[("documents", 15)]], {}),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Title", "max_length": 100},
                    ),
                    18: ("wagtail.blocks.CharBlock", (), {"label": "Description"}),
                    19: ("wagtail.blocks.URLBlock", (), {"label": "URL"}),
                    20: (
                        "app.core.blocks.image.APIImageChooserBlock",
                        (),
                        {"label": "Image", "required": False},
                    ),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 17),
                                ("description", 18),
                                ("url", 19),
                                ("image", 20),
                            ]
                        ],
                        {},
                    ),
                    22: (
                        "app.core.blocks.page_chooser.APIPageChooserBlock",
                        (),
                        {
                            "label": "Page",
                            "page_type": ["wagtailcore.Page"],
                            "required": True,
                        },
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional override for the teaser text",
                            "label": "Teaser text override",
                            "required": False,
                        },
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 22), ("teaser_text", 23)]],
                        {},
                    ),
                    25: (
                        "app.core.blocks.image.APIImageChooserBlock",
                        (),
                        {"rendition_size": "max-900x900", "required": True},
                    ),
                    26: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Alternative (alt) text describes images when they fail to load, and is read aloud by assistive technologies. Use a maximum of 100 characters to describe your image. <a href="https://html.spec.whatwg.org/multipage/images.html#alt" target="_blank">Check the guidance for tips on writing alt text</a>.',
                            "label": "Alternative text",
                            "max_length": 100,
                        },
                    ),
                    27: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "If provided, displays directly below the image. Can be used to specify sources, transcripts or other useful metadata.",
                            "label": "Caption (optional)",
                            "required": False,
                        },
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 25), ("alt_text", 26), ("caption", 27)]],
                        {},
                    ),
                    29: ("wagtail.blocks.ListBlock", (28,), {}),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 8), ("description", 11), ("images", 29)]],
                        {},
                    ),
                    31: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link", "ol", "ul"]},
                    ),
                    32: ("wagtail.blocks.StructBlock", [[("text", 31)]], {}),
                    33: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "A descriptive title for the media block",
                            "required": True,
                        },
                    ),
                    34: (
                        "app.core.blocks.image.APIImageChooserBlock",
                        (),
                        {"help_text": "A background image for the media block"},
                    ),
                    35: ("app.media.blocks.MediaChooserBlock", (), {}),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 33), ("background_image", 34), ("media", 35)]],
                        {},
                    ),
                    37: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link"], "required": True},
                    ),
                    38: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 100, "required": False},
                    ),
                    39: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 37), ("attribution", 38)]],
                        {},
                    ),
                    40: (
                        "wagtail.contrib.table_block.blocks.TableBlock",
                        (),
                        {
                            "table_options": {
                                "contextMenu": [
                                    "row_above",
                                    "row_below",
                                    "---------",
                                    "col_left",
                                    "col_right",
                                    "---------",
                                    "remove_row",
                                    "remove_col",
                                    "---------",
                                    "undo",
                                    "redo",
                                    "---------",
                                    "alignment",
                                ]
                            }
                        },
                    ),
                    41: ("wagtail.blocks.StructBlock", [[("table", 40)]], {}),
                    42: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Title", "max_length": 100, "required": True},
                    ),
                    43: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "YouTube Video ID",
                            "max_length": 11,
                            "required": True,
                        },
                    ),
                    44: (
                        "app.core.blocks.image.APIImageChooserBlock",
                        (),
                        {
                            "label": "Preview Image",
                            "rendition_size": "max-640x360",
                            "required": False,
                        },
                    ),
                    45: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 42), ("video_id", 43), ("preview_image", 44)]],
                        {},
                    ),
                    46: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Heading", "max_length": 100},
                    ),
                    47: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Sub-heading", "max_length": 100},
                    ),
                    48: ("wagtail.blocks.StructBlock", [[("heading", 47)]], {}),
                    49: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("call_to_action", 6),
                                ("contact", 12),
                                ("document", 16),
                                ("featured_external_link", 21),
                                ("featured_page", 24),
                                ("image", 28),
                                ("image_gallery", 30),
                                ("inset_text", 32),
                                ("media", 36),
                                ("paragraph", 32),
                                ("quote", 39),
                                ("sub_heading", 48),
                                ("table", 41),
                                ("youtube_video", 45),
                            ]
                        ],
                        {"required": False},
                    ),
                    50: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 46), ("content", 49)]],
                        {},
                    ),
                },
            ),
        ),
    ]
