# Generated by Django 6.0.8 on 2026-09-14 11:31
# etna:allowRemoveField

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpostpage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogfeedspage',
            name='twitter_og_description',
        ),
        migrations.RemoveField(
            model_name='blogfeedspage',
            name='twitter_og_image',
        ),
        migrations.RemoveField(
            model_name='blogfeedspage',
            name='twitter_og_title',
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='twitter_og_description',
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='twitter_og_image',
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='twitter_og_title',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='twitter_og_description',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='twitter_og_image',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='twitter_og_title',
        ),
        migrations.RemoveField(
            model_name='blogpostpage',
            name='twitter_og_description',
        ),
        migrations.RemoveField(
            model_name='blogpostpage',
            name='twitter_og_image',
        ),
        migrations.RemoveField(
            model_name='blogpostpage',
            name='twitter_og_title',
        ),
    ]
