# Generated by Django 5.0.8 on 2024-10-22 10:10
# etna:allowRemoveField

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_blogpostpage_hero_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogindexpage",
            name="uuid",
        ),
        migrations.RemoveField(
            model_name="blogpage",
            name="uuid",
        ),
        migrations.RemoveField(
            model_name="blogpostpage",
            name="uuid",
        ),
    ]
