# Generated by Django 6.0.3 on 2026-04-09 08:51
# etna:allowAlterField

import app.ciim.blocks
import django.core.validators
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0025_alter_blogpostpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpostpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("call_to_action", 6),
                    ("code", 11),
                    ("contact", 18),
                    ("document", 22),
                    ("featured_external_link", 28),
                    ("featured_page", 31),
                    ("image", 34),
                    ("image_gallery", 37),
                    ("inset_text", 39),
                    ("media", 43),
                    ("paragraph", 44),
                    ("partner_logos", 48),
                    ("quote", 51),
                    ("record_links", 53),
                    ("table", 55),
                    ("youtube_video", 61),
                    ("content_section", 66),
                ],
                block_lookup={
                    0: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "code", "ol", "ul"],
                            "max_length": 100,
                        },
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {}),
                    2: (
                        "app.core.blocks.page_chooser.APIPageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    3: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    4: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "Use the accented button style",
                            "label": "Accented",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 1),
                                ("link", 2),
                                ("external_link", 3),
                                ("accented", 4),
                            ]
                        ],
                        {},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("body", 0), ("button", 5)]],
                        {"group": "Onward journeys"},
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Display a filename with the extension e.g. example.html",
                            "label": "Code block title",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("html", "HTML"),
                                ("javascript", "JavaScript"),
                                ("python", "Python"),
                                ("xml", "XML"),
                                ("json", "JSON"),
                                ("bash", "Bash"),
                                ("git", "git"),
                                ("markdown", "Markdown"),
                                ("graphql", "GraphQL"),
                                ("powershell", "PowerShell"),
                                ("yaml", "YAML"),
                            ],
                            "label": "Code language",
                            "required": False,
                        },
                    ),
                    9: ("wagtail.blocks.TextBlock", (), {"max_length": 500}),
                    10: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Allow copy to clipboard",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("filename", 7),
                                ("language", 8),
                                ("code", 9),
                                ("allow_copying", 10),
                            ]
                        ],
                        {"group": "Structured and collapsible content"},
                    ),
                    12: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"features": ["link"], "required": False},
                    ),
                    13: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "code"],
                            "required": False,
                        },
                    ),
                    14: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    15: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"required": False},
                    ),
                    16: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    17: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "code"],
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 1),
                                ("body", 12),
                                ("address", 13),
                                ("telephone", 14),
                                ("chat_link", 3),
                                ("chat_note", 15),
                                ("email", 16),
                                ("website_link", 3),
                                ("social_media", 17),
                            ]
                        ],
                        {"group": "Onward journeys"},
                    ),
                    19: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": True},
                    ),
                    20: ("wagtail.blocks.StructBlock", [[("file", 19)]], {}),
                    21: ("wagtail.blocks.ListBlock", (20,), {"min_num": 1}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("documents", 21)]],
                        {"group": "Video, audio and downloads"},
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Supertitle", "max_length": 20, "required": False},
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Title", "max_length": 100},
                    ),
                    25: ("wagtail.blocks.CharBlock", (), {"label": "Description"}),
                    26: ("wagtail.blocks.URLBlock", (), {"label": "URL"}),
                    27: (
                        "app.core.blocks.image.APIImageChooserBlock",
                        (),
                        {"label": "Image", "required": False},
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("supertitle", 23),
                                ("title", 24),
                                ("description", 25),
                                ("url", 26),
                                ("image", 27),
                            ]
                        ],
                        {"group": "Onward journeys"},
                    ),
                    29: (
                        "app.core.blocks.page_chooser.APIPageChooserBlock",
                        (),
                        {
                            "label": "Page",
                            "page_type": ["wagtailcore.Page"],
                            "required": True,
                        },
                    ),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional override for the teaser text",
                            "label": "Teaser text override",
                            "required": False,
                        },
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 29), ("teaser_text", 30)]],
                        {"group": "Onward journeys"},
                    ),
                    32: (
                        "app.core.blocks.image.APIImageChooserBlock",
                        (),
                        {"rendition_size": "max-900x900", "required": True},
                    ),
                    33: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "If provided, displays directly below the image. Can be used to specify sources, transcripts or other useful metadata.",
                            "label": "Caption (optional)",
                            "required": False,
                        },
                    ),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 32), ("caption", 33)]],
                        {"group": "Images"},
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 32), ("caption", 33)]],
                        {},
                    ),
                    36: ("wagtail.blocks.ListBlock", (35,), {}),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 14), ("description", 17), ("images", 36)]],
                        {"group": "Images"},
                    ),
                    38: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link", "code", "ol", "ul"]},
                    ),
                    39: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 38)]],
                        {"group": "Emphasis"},
                    ),
                    40: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "A descriptive title for the media block",
                            "required": True,
                        },
                    ),
                    41: (
                        "app.core.blocks.image.APIImageChooserBlock",
                        (),
                        {
                            "help_text": "A thumbnail image for the media block",
                            "rendition_size": "fill-960x540",
                            "required": False,
                        },
                    ),
                    42: ("app.media.blocks.MediaChooserBlock", (), {}),
                    43: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 40), ("thumbnail", 41), ("media", 42)]],
                        {"group": "Video, audio and downloads"},
                    ),
                    44: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 38)]],
                        {"group": "Basic text"},
                    ),
                    45: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional override for the partner logos section lead text. Will display a default if not provided.",
                            "max_length": 40,
                            "required": False,
                        },
                    ),
                    46: ("app.core.blocks.image.PartnerLogoChooserBlock", (), {}),
                    47: (
                        "wagtail.blocks.ListBlock",
                        (46,),
                        {"max_num": 4, "required": True},
                    ),
                    48: (
                        "wagtail.blocks.StructBlock",
                        [[("lead_text", 45), ("logos", 47)]],
                        {"group": "Images"},
                    ),
                    49: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "code", "ol", "ul"],
                            "required": True,
                        },
                    ),
                    50: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 100, "required": False},
                    ),
                    51: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 49), ("attribution", 50)]],
                        {"group": "Basic text"},
                    ),
                    52: (
                        "wagtail.blocks.ListBlock",
                        (app.ciim.blocks.RecordLinkBlock,),
                        {"label": "Items"},
                    ),
                    53: (
                        "wagtail.blocks.StructBlock",
                        [[("items", 52)]],
                        {"group": "Onward journeys"},
                    ),
                    54: (
                        "wagtail.contrib.table_block.blocks.TableBlock",
                        (),
                        {
                            "table_options": {
                                "contextMenu": [
                                    "row_above",
                                    "row_below",
                                    "---------",
                                    "col_left",
                                    "col_right",
                                    "---------",
                                    "remove_row",
                                    "remove_col",
                                    "---------",
                                    "undo",
                                    "redo",
                                    "---------",
                                    "alignment",
                                ]
                            }
                        },
                    ),
                    55: (
                        "wagtail.blocks.StructBlock",
                        [[("table", 54)]],
                        {"group": "Structured and collapsible content"},
                    ),
                    56: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Title", "max_length": 100, "required": True},
                    ),
                    57: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "YouTube Video ID",
                            "max_length": 11,
                            "required": True,
                            "validators": [
                                django.core.validators.RegexValidator(
                                    message="Invalid YouTube Video ID",
                                    regex="^[a-zA-Z0-9_-]{11}$",
                                )
                            ],
                        },
                    ),
                    58: (
                        "app.core.blocks.image.APIImageChooserBlock",
                        (),
                        {
                            "label": "Preview Image",
                            "rendition_size": "fill-640x360",
                            "required": True,
                        },
                    ),
                    59: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Transcript", "required": False},
                    ),
                    60: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "Tick if the video has captions on YouTube",
                            "label": "Captions available",
                            "required": False,
                        },
                    ),
                    61: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 56),
                                ("video_id", 57),
                                ("preview_image", 58),
                                ("transcript", 59),
                                ("captions_available", 60),
                            ]
                        ],
                        {"group": "Video, audio and downloads"},
                    ),
                    62: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Heading", "max_length": 100},
                    ),
                    63: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Sub-heading", "max_length": 100},
                    ),
                    64: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 63)]],
                        {"group": "Basic text"},
                    ),
                    65: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("call_to_action", 6),
                                ("code", 11),
                                ("contact", 18),
                                ("document", 22),
                                ("featured_external_link", 28),
                                ("featured_page", 31),
                                ("image", 34),
                                ("image_gallery", 37),
                                ("inset_text", 39),
                                ("media", 43),
                                ("paragraph", 44),
                                ("partner_logos", 48),
                                ("quote", 51),
                                ("record_links", 53),
                                ("sub_heading", 64),
                                ("table", 55),
                                ("youtube_video", 61),
                            ]
                        ],
                        {"required": False},
                    ),
                    66: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 62), ("content", 65)]],
                        {},
                    ),
                },
            ),
        ),
    ]
