# Generated by Django 6.0.4 on 2026-04-23 12:51
# etna:allowAlterField

import app.core.models.mixins
import django.core.validators
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models

KEY_STAGES = [
    ("key-stage-1", "Key Stage 1 (ages 5–7)"),
    ("key-stage-2", "Key Stage 2 (ages 7–11)"),
    ("key-stage-3", "Key Stage 3 (ages 11–14)"),
    ("key-stage-4", "Key Stage 4 (ages 14–16)"),
    ("key-stage-5", "Key Stage 5 (ages 16-18)"),
]


def seed_key_stages(apps, schema_editor):
    KeyStage = apps.get_model("education", "KeyStage")

    for slug, name in KEY_STAGES:
        KeyStage.objects.update_or_create(
            slug=slug,
            defaults={"name": name},
        )


def noop_reverse(apps, schema_editor):
    """Keep seeded key stages when rolling back to avoid data loss."""

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alerts", "0005_alert_active_from_alert_active_to_and_more"),
        ("images", "0013_alter_customimage_description"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="KeyStage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Key Stage 1 (ages 5–7)", "Key Stage 1 (ages 5–7)"),
                            ("Key Stage 2 (ages 7–11)", "Key Stage 2 (ages 7–11)"),
                            ("Key Stage 3 (ages 11–14)", "Key Stage 3 (ages 11–14)"),
                            ("Key Stage 4 (ages 14–16)", "Key Stage 4 (ages 14–16)"),
                            ("Key Stage 5 (ages 16-18)", "Key Stage 5 (ages 16-18)"),
                        ],
                        max_length=255,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        choices=[
                            ("key-stage-1", "Key Stage 1 (ages 5–7)"),
                            ("key-stage-2", "Key Stage 2 (ages 7–11)"),
                            ("key-stage-3", "Key Stage 3 (ages 11–14)"),
                            ("key-stage-4", "Key Stage 4 (ages 14–16)"),
                            ("key-stage-5", "Key Stage 5 (ages 16-18)"),
                        ],
                        max_length=255,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
            ],
            options={
                "verbose_name": "Key stage",
                "verbose_name_plural": "Key stages",
            },
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="slug"),
                ),
            ],
            options={
                "verbose_name": "Theme",
                "verbose_name_plural": "Themes",
            },
        ),
        migrations.CreateModel(
            name="TimePeriod",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="slug"),
                ),
            ],
            options={
                "verbose_name": "Time period",
                "verbose_name_plural": "Time periods",
            },
        ),
        migrations.CreateModel(
            name="EducationPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "twitter_og_title",
                    models.CharField(
                        blank=True,
                        help_text="If left blank, the OpenGraph title will be used.",
                        max_length=255,
                        null=True,
                        verbose_name="Twitter OpenGraph title",
                    ),
                ),
                (
                    "twitter_og_description",
                    models.TextField(
                        blank=True,
                        help_text="If left blank, the OpenGraph description will be used.",
                        null=True,
                        verbose_name="Twitter OpenGraph description",
                    ),
                ),
                (
                    "short_title",
                    models.CharField(
                        blank=True,
                        help_text="A shorter title for use in breadcrumbs and other navigational elements, where applicable.",
                        max_length=45,
                        null=True,
                        verbose_name="short title",
                    ),
                ),
                (
                    "teaser_text",
                    models.TextField(
                        help_text="A short, enticing description of this page. This will appear in promos and under thumbnails around the site.",
                        max_length=160,
                        verbose_name="teaser text",
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(
                        help_text="1-2 sentences introducing the subject of the page, and explaining why a user should read on.",
                        max_length=300,
                        verbose_name="introductory text",
                    ),
                ),
                (
                    "teaching_resources_teaser",
                    models.TextField(
                        blank=True,
                        help_text="Short text under Explore teaching resources title to entice users to click through",
                        verbose_name="teaching resources teaser text",
                    ),
                ),
                (
                    "featured_teaching_resource_teaser_override",
                    models.TextField(
                        blank=True,
                        help_text="Override text for the featured teaching resource",
                        verbose_name="Featured teaching resource teaser text override",
                    ),
                ),
                (
                    "education_sessions_teaser",
                    models.TextField(
                        blank=True,
                        help_text="Short text under Explore education sessions title to entice users to click through",
                        verbose_name="education sessions teaser text",
                    ),
                ),
                (
                    "featured_education_session_teaser_override",
                    models.TextField(
                        blank=True,
                        help_text="Override text for the featured education session",
                        verbose_name="Featured education session teaser text override",
                    ),
                ),
                (
                    "alert",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="alerts.alert",
                    ),
                ),
                (
                    "search_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image that will appear when this page is shared on social media. This will default to the teaser image if left blank.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                        verbose_name="OpenGraph image",
                    ),
                ),
                (
                    "teaser_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image that will appear on thumbnails and promos around the site.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
                (
                    "twitter_og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="If left blank, the OpenGraph image will be used.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                        verbose_name="Twitter OpenGraph image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Education landing page",
            },
            bases=(
                app.core.models.mixins.CustomHeadlessPreviewMixin,
                "wagtailcore.page",
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="EducationReadMoreLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education_read_more_links",
                        to="education.educationpage",
                    ),
                ),
                (
                    "selected_page",
                    models.ForeignKey(
                        help_text="Navigation to other sections within Education",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailcore.page",
                        verbose_name="selected page",
                    ),
                ),
            ],
            options={
                "verbose_name": "read more link",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="EducationSessionPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "twitter_og_title",
                    models.CharField(
                        blank=True,
                        help_text="If left blank, the OpenGraph title will be used.",
                        max_length=255,
                        null=True,
                        verbose_name="Twitter OpenGraph title",
                    ),
                ),
                (
                    "twitter_og_description",
                    models.TextField(
                        blank=True,
                        help_text="If left blank, the OpenGraph description will be used.",
                        null=True,
                        verbose_name="Twitter OpenGraph description",
                    ),
                ),
                (
                    "short_title",
                    models.CharField(
                        blank=True,
                        help_text="A shorter title for use in breadcrumbs and other navigational elements, where applicable.",
                        max_length=45,
                        null=True,
                        verbose_name="short title",
                    ),
                ),
                (
                    "teaser_text",
                    models.TextField(
                        help_text="A short, enticing description of this page. This will appear in promos and under thumbnails around the site.",
                        max_length=160,
                        verbose_name="teaser text",
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(
                        help_text="1-2 sentences introducing the subject of the page, and explaining why a user should read on.",
                        max_length=300,
                        verbose_name="introductory text",
                    ),
                ),
                (
                    "alert",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="alerts.alert",
                    ),
                ),
                (
                    "search_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image that will appear when this page is shared on social media. This will default to the teaser image if left blank.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                        verbose_name="OpenGraph image",
                    ),
                ),
                (
                    "teaser_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image that will appear on thumbnails and promos around the site.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
                (
                    "twitter_og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="If left blank, the OpenGraph image will be used.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                        verbose_name="Twitter OpenGraph image",
                    ),
                ),
                (
                    "key_stage",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={
                            "slug__in": [
                                "key-stage-1",
                                "key-stage-2",
                                "key-stage-3",
                                "key-stage-4",
                                "key-stage-5",
                            ]
                        },
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="education.keystage",
                        verbose_name="key stage",
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="education.theme",
                        verbose_name="theme",
                    ),
                ),
                (
                    "time_period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="education.timeperiod",
                        verbose_name="time period",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                app.core.models.mixins.CustomHeadlessPreviewMixin,
                "wagtailcore.page",
                models.Model,
            ),
        ),
        migrations.AddField(
            model_name="educationpage",
            name="featured_education_session",
            field=models.ForeignKey(
                blank=True,
                help_text="Page picker to highlight a featured education session",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="education.educationsessionpage",
                verbose_name="featured education session",
            ),
        ),
        migrations.CreateModel(
            name="EducationSessionsListingPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "twitter_og_title",
                    models.CharField(
                        blank=True,
                        help_text="If left blank, the OpenGraph title will be used.",
                        max_length=255,
                        null=True,
                        verbose_name="Twitter OpenGraph title",
                    ),
                ),
                (
                    "twitter_og_description",
                    models.TextField(
                        blank=True,
                        help_text="If left blank, the OpenGraph description will be used.",
                        null=True,
                        verbose_name="Twitter OpenGraph description",
                    ),
                ),
                (
                    "short_title",
                    models.CharField(
                        blank=True,
                        help_text="A shorter title for use in breadcrumbs and other navigational elements, where applicable.",
                        max_length=45,
                        null=True,
                        verbose_name="short title",
                    ),
                ),
                (
                    "teaser_text",
                    models.TextField(
                        help_text="A short, enticing description of this page. This will appear in promos and under thumbnails around the site.",
                        max_length=160,
                        verbose_name="teaser text",
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(
                        help_text="1-2 sentences introducing the subject of the page, and explaining why a user should read on.",
                        max_length=300,
                        verbose_name="introductory text",
                    ),
                ),
                (
                    "featured_education_session_teaser_override",
                    models.TextField(
                        blank=True,
                        help_text="Override text for the featured education session",
                        verbose_name="Featured education session teaser text override",
                    ),
                ),
                (
                    "newsletter_sign_up_text",
                    models.TextField(
                        blank=True,
                        help_text="Text block encouraging users to sign up for the education newsletter.",
                        verbose_name="newsletter sign up text",
                    ),
                ),
                (
                    "alert",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="alerts.alert",
                    ),
                ),
                (
                    "featured_education_session",
                    models.ForeignKey(
                        blank=True,
                        help_text="Page picker to highlight a featured education session",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="education.educationsessionpage",
                        verbose_name="featured education session",
                    ),
                ),
                (
                    "search_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image that will appear when this page is shared on social media. This will default to the teaser image if left blank.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                        verbose_name="OpenGraph image",
                    ),
                ),
                (
                    "teaser_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image that will appear on thumbnails and promos around the site.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
                (
                    "twitter_og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="If left blank, the OpenGraph image will be used.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                        verbose_name="Twitter OpenGraph image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Education Sessions listing page",
            },
            bases=(
                app.core.models.mixins.CustomHeadlessPreviewMixin,
                "wagtailcore.page",
                models.Model,
            ),
        ),
        migrations.AddField(
            model_name="educationpage",
            name="education_sessions_listing_page",
            field=models.ForeignKey(
                blank=True,
                help_text="The education sessions listing page to display on the Education landing page.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="education.educationsessionslistingpage",
                verbose_name="education sessions listing page",
            ),
        ),
        migrations.CreateModel(
            name="TeachingResourcePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "twitter_og_title",
                    models.CharField(
                        blank=True,
                        help_text="If left blank, the OpenGraph title will be used.",
                        max_length=255,
                        null=True,
                        verbose_name="Twitter OpenGraph title",
                    ),
                ),
                (
                    "twitter_og_description",
                    models.TextField(
                        blank=True,
                        help_text="If left blank, the OpenGraph description will be used.",
                        null=True,
                        verbose_name="Twitter OpenGraph description",
                    ),
                ),
                (
                    "short_title",
                    models.CharField(
                        blank=True,
                        help_text="A shorter title for use in breadcrumbs and other navigational elements, where applicable.",
                        max_length=45,
                        null=True,
                        verbose_name="short title",
                    ),
                ),
                (
                    "teaser_text",
                    models.TextField(
                        help_text="A short, enticing description of this page. This will appear in promos and under thumbnails around the site.",
                        max_length=160,
                        verbose_name="teaser text",
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(
                        help_text="1-2 sentences introducing the subject of the page, and explaining why a user should read on.",
                        max_length=300,
                        verbose_name="introductory text",
                    ),
                ),
                (
                    "hero_image",
                    wagtail.fields.StreamField(
                        [("hero_image", 2)],
                        block_lookup={
                            0: (
                                "app.core.blocks.image.APIImageChooserBlock",
                                (),
                                {"rendition_size": "max-900x900", "required": True},
                            ),
                            1: (
                                "app.core.blocks.paragraph.APIRichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link"],
                                    "help_text": "If provided, displays directly below the image. Can be used to specify sources, transcripts or other useful metadata.",
                                    "label": "Caption (optional)",
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 0), ("caption", 1)]],
                                {
                                    "blank": True,
                                    "rendition_size": "max-900x900",
                                    "verbose_name": "hero image",
                                },
                            ),
                        },
                        null=True,
                    ),
                ),
                (
                    "enquiry_question",
                    models.TextField(blank=True, verbose_name="enquiry question"),
                ),
                (
                    "introduction_text",
                    models.TextField(blank=True, verbose_name="introduction text"),
                ),
                (
                    "sources_title",
                    models.TextField(
                        blank=True,
                        help_text="Title of the main section of the page. In most cases ‘Investigate the sources’",
                        verbose_name="sources title",
                    ),
                ),
                (
                    "sources_introduction",
                    wagtail.fields.StreamField(
                        [("sources_introduction", 0)],
                        blank=True,
                        block_lookup={
                            0: (
                                "app.core.blocks.paragraph.APIRichTextBlock",
                                (),
                                {"features": ["bold", "italic", "link"]},
                            )
                        },
                        help_text="Optional text field to provide an introduction to the sources.",
                        null=True,
                        verbose_name="sources introduction",
                    ),
                ),
                (
                    "teachers_notes",
                    wagtail.fields.StreamField(
                        [("teachers_notes", 0)],
                        blank=True,
                        block_lookup={
                            0: (
                                "app.core.blocks.paragraph.APIRichTextBlock",
                                (),
                                {"features": ["bold", "italic", "link", "ol", "ul"]},
                            )
                        },
                        help_text="A general overview of what the resource contains and how it can be used.",
                        null=True,
                        verbose_name="teachers notes",
                    ),
                ),
                (
                    "extension_activities",
                    wagtail.fields.StreamField(
                        [
                            ("paragraph", 0),
                            ("sub_heading", 2),
                            ("featured_page", 5),
                            ("featured_external_link", 11),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "app.core.blocks.paragraph.APIRichTextBlock",
                                (),
                                {"features": ["bold", "italic", "link", "ol", "ul"]},
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Sub-heading", "max_length": 100},
                            ),
                            2: ("wagtail.blocks.StructBlock", [[("heading", 1)]], {}),
                            3: (
                                "app.core.blocks.page_chooser.APIPageChooserBlock",
                                (),
                                {
                                    "label": "Page",
                                    "page_type": ["wagtailcore.Page"],
                                    "required": True,
                                },
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Optional override for the teaser text",
                                    "label": "Teaser text override",
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [[("page", 3), ("teaser_text", 4)]],
                                {},
                            ),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Supertitle",
                                    "max_length": 20,
                                    "required": False,
                                },
                            ),
                            7: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Title", "max_length": 100},
                            ),
                            8: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Description"},
                            ),
                            9: ("wagtail.blocks.URLBlock", (), {"label": "URL"}),
                            10: (
                                "app.core.blocks.image.APIImageChooserBlock",
                                (),
                                {"label": "Image", "required": False},
                            ),
                            11: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("supertitle", 6),
                                        ("title", 7),
                                        ("description", 8),
                                        ("url", 9),
                                        ("image", 10),
                                    ]
                                ],
                                {},
                            ),
                        },
                        help_text="Optional section where editors can add extra activities for teachers to try with their pupils.",
                        null=True,
                        verbose_name="extension activities",
                    ),
                ),
                (
                    "background_information",
                    wagtail.fields.StreamField(
                        [("paragraph", 0), ("sub_heading", 2)],
                        blank=True,
                        block_lookup={
                            0: (
                                "app.core.blocks.paragraph.APIRichTextBlock",
                                (),
                                {"features": ["bold", "italic", "link", "ol", "ul"]},
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Sub-heading", "max_length": 100},
                            ),
                            2: ("wagtail.blocks.StructBlock", [[("heading", 1)]], {}),
                        },
                        help_text="Section providing historical context to the teaching resource.",
                        null=True,
                        verbose_name="background information",
                    ),
                ),
                (
                    "further_information_title",
                    models.CharField(
                        blank=True,
                        help_text="Title of the further information section (required).",
                        max_length=255,
                        null=True,
                        verbose_name="further information title",
                    ),
                ),
                (
                    "further_information",
                    wagtail.fields.StreamField(
                        [
                            ("paragraph", 0),
                            ("sub_heading", 2),
                            ("featured_external_link", 8),
                            ("featured_page", 11),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "app.core.blocks.paragraph.APIRichTextBlock",
                                (),
                                {"features": ["bold", "italic", "link", "ol", "ul"]},
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Sub-heading", "max_length": 100},
                            ),
                            2: ("wagtail.blocks.StructBlock", [[("heading", 1)]], {}),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Supertitle",
                                    "max_length": 20,
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Title", "max_length": 100},
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Description"},
                            ),
                            6: ("wagtail.blocks.URLBlock", (), {"label": "URL"}),
                            7: (
                                "app.core.blocks.image.APIImageChooserBlock",
                                (),
                                {"label": "Image", "required": False},
                            ),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("supertitle", 3),
                                        ("title", 4),
                                        ("description", 5),
                                        ("url", 6),
                                        ("image", 7),
                                    ]
                                ],
                                {},
                            ),
                            9: (
                                "app.core.blocks.page_chooser.APIPageChooserBlock",
                                (),
                                {
                                    "label": "Page",
                                    "page_type": ["wagtailcore.Page"],
                                    "required": True,
                                },
                            ),
                            10: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Optional override for the teaser text",
                                    "label": "Teaser text override",
                                    "required": False,
                                },
                            ),
                            11: (
                                "wagtail.blocks.StructBlock",
                                [[("page", 9), ("teaser_text", 10)]],
                                {},
                            ),
                        },
                        help_text="Section providing links to other useful information.",
                        null=True,
                        verbose_name="further information",
                    ),
                ),
                (
                    "alert",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="alerts.alert",
                    ),
                ),
                (
                    "key_stage",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={
                            "slug__in": [
                                "key-stage-1",
                                "key-stage-2",
                                "key-stage-3",
                                "key-stage-4",
                                "key-stage-5",
                            ]
                        },
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="education.keystage",
                        verbose_name="key stage",
                    ),
                ),
                (
                    "search_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image that will appear when this page is shared on social media. This will default to the teaser image if left blank.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                        verbose_name="OpenGraph image",
                    ),
                ),
                (
                    "teaser_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image that will appear on thumbnails and promos around the site.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
                (
                    "twitter_og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="If left blank, the OpenGraph image will be used.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                        verbose_name="Twitter OpenGraph image",
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="education.theme",
                        verbose_name="theme",
                    ),
                ),
                (
                    "time_period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="education.timeperiod",
                        verbose_name="time period",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                app.core.models.mixins.CustomHeadlessPreviewMixin,
                "wagtailcore.page",
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "source_title",
                    models.TextField(
                        blank=True,
                        help_text="A unique, descriptive title for the source.",
                        verbose_name="source title",
                    ),
                ),
                (
                    "source_image",
                    wagtail.fields.StreamField(
                        [("source_image", 0)],
                        block_lookup={
                            0: (
                                "app.core.blocks.image.APIImageChooserBlock",
                                (),
                                {
                                    "blank": True,
                                    "help_text": "An image for the source.",
                                    "rendition_size": "max-900x900",
                                    "verbose_name": "source image",
                                },
                            )
                        },
                    ),
                ),
                (
                    "source_media",
                    wagtail.fields.StreamField(
                        [("source_media", 2)],
                        block_lookup={
                            0: (
                                "app.core.blocks.image.APIImageChooserBlock",
                                (),
                                {
                                    "help_text": "A thumbnail image for the media block",
                                    "rendition_size": "fill-960x540",
                                    "required": False,
                                },
                            ),
                            1: ("app.media.blocks.MediaChooserBlock", (), {}),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("thumbnail", 0), ("media", 1)]],
                                {
                                    "blank": True,
                                    "help_text": "A piece of media for the source.",
                                    "verbose_name": "source media",
                                },
                            ),
                        },
                    ),
                ),
                (
                    "source_youtube",
                    wagtail.fields.StreamField(
                        [("source_youtube", 5)],
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Title", "max_length": 100, "required": True},
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "YouTube Video ID",
                                    "max_length": 11,
                                    "required": True,
                                    "validators": [
                                        django.core.validators.RegexValidator(
                                            message="Invalid YouTube Video ID",
                                            regex="^[a-zA-Z0-9_-]{11}$",
                                        )
                                    ],
                                },
                            ),
                            2: (
                                "app.core.blocks.image.APIImageChooserBlock",
                                (),
                                {
                                    "label": "Preview Image",
                                    "rendition_size": "fill-640x360",
                                    "required": True,
                                },
                            ),
                            3: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"label": "Transcript", "required": False},
                            ),
                            4: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "help_text": "Tick if the video has captions on YouTube",
                                    "label": "Captions available",
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 0),
                                        ("video_id", 1),
                                        ("preview_image", 2),
                                        ("transcript", 3),
                                        ("captions_available", 4),
                                    ]
                                ],
                                {
                                    "blank": True,
                                    "help_text": "A youtube video for the source.",
                                    "verbose_name": "source youtube video",
                                },
                            ),
                        },
                    ),
                ),
                (
                    "source_media_caption",
                    wagtail.fields.StreamField(
                        [("source_media_caption", 0)],
                        blank=True,
                        block_lookup={
                            0: (
                                "app.core.blocks.paragraph.APIRichTextBlock",
                                (),
                                {"features": ["bold", "italic"]},
                            )
                        },
                        help_text="If provided, displays directly below the source.",
                        null=True,
                        verbose_name="source caption",
                    ),
                ),
                (
                    "source_media_featured_link",
                    wagtail.fields.StreamField(
                        [("source_media_featured_link", 0)],
                        blank=True,
                        block_lookup={
                            0: (
                                "app.core.blocks.page_chooser.APIPageChooserBlock",
                                (),
                                {
                                    "label": "Internal page",
                                    "page_type": ["wagtailcore.Page"],
                                    "required": False,
                                },
                            )
                        },
                        help_text="Reference another page published on the site",
                        verbose_name="source media featured link",
                    ),
                ),
                (
                    "source_media_featured_external_link",
                    models.URLField(
                        blank=True,
                        help_text="Option to add link to a resource on a 3rd party platform (e.g. mapping tool)",
                        verbose_name="source media featured link",
                    ),
                ),
                (
                    "source_description",
                    wagtail.fields.StreamField(
                        [("source_description", 0)],
                        blank=True,
                        block_lookup={
                            0: (
                                "app.core.blocks.paragraph.APIRichTextBlock",
                                (),
                                {"features": ["bold", "italic", "link", "ol", "ul"]},
                            )
                        },
                        help_text="An optional free text field to add in a fuller description of the source.",
                        null=True,
                        verbose_name="source description",
                    ),
                ),
                (
                    "source_question",
                    wagtail.fields.StreamField(
                        [("question", 2)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 255, "required": False},
                            ),
                            1: (
                                "app.core.blocks.paragraph.APIRichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link", "ul"],
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("question_heading", 0),
                                        ("guidance_for_teachers", 1),
                                    ]
                                ],
                                {"icon": "help"},
                            ),
                        },
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="education.teachingresourcepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="educationpage",
            name="featured_teaching_resource",
            field=models.ForeignKey(
                blank=True,
                help_text="Option to add a highlighted teaching resource, particularly for history months etc",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="education.teachingresourcepage",
                verbose_name="featured teaching resource",
            ),
        ),
        migrations.CreateModel(
            name="CurriculumConnection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "curriculum_connection_description",
                    wagtail.fields.StreamField(
                        [("curriculum_connection_description", 0)],
                        blank=True,
                        block_lookup={
                            0: (
                                "app.core.blocks.paragraph.APIRichTextBlock",
                                (),
                                {"features": ["bold", "italic", "link", "ul"]},
                            )
                        },
                        help_text="Add the curriculum connection description.",
                        null=True,
                        verbose_name="curriculum connection description",
                    ),
                ),
                (
                    "key_stage",
                    models.ForeignKey(
                        help_text="The key stage for this curriculum connection.",
                        limit_choices_to={
                            "slug__in": [
                                "key-stage-1",
                                "key-stage-2",
                                "key-stage-3",
                                "key-stage-4",
                                "key-stage-5",
                            ]
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="education.keystage",
                        verbose_name="Key stage",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curriculum_connections",
                        to="education.teachingresourcepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TeachingResourcesListingPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "twitter_og_title",
                    models.CharField(
                        blank=True,
                        help_text="If left blank, the OpenGraph title will be used.",
                        max_length=255,
                        null=True,
                        verbose_name="Twitter OpenGraph title",
                    ),
                ),
                (
                    "twitter_og_description",
                    models.TextField(
                        blank=True,
                        help_text="If left blank, the OpenGraph description will be used.",
                        null=True,
                        verbose_name="Twitter OpenGraph description",
                    ),
                ),
                (
                    "short_title",
                    models.CharField(
                        blank=True,
                        help_text="A shorter title for use in breadcrumbs and other navigational elements, where applicable.",
                        max_length=45,
                        null=True,
                        verbose_name="short title",
                    ),
                ),
                (
                    "teaser_text",
                    models.TextField(
                        help_text="A short, enticing description of this page. This will appear in promos and under thumbnails around the site.",
                        max_length=160,
                        verbose_name="teaser text",
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(
                        help_text="1-2 sentences introducing the subject of the page, and explaining why a user should read on.",
                        max_length=300,
                        verbose_name="introductory text",
                    ),
                ),
                (
                    "featured_teaching_resource_teaser_override",
                    models.TextField(
                        blank=True,
                        help_text="Override text for the featured teaching resource",
                        verbose_name="Featured teaching resource teaser text override",
                    ),
                ),
                (
                    "web_archive_promo",
                    wagtail.fields.StreamField(
                        [("web_archive_promo", 0)],
                        blank=True,
                        block_lookup={
                            0: (
                                "app.core.blocks.paragraph.APIRichTextBlock",
                                (),
                                {"features": ["bold", "italic", "link"]},
                            )
                        },
                        help_text="Text block highlighting that old resources can be found in the web archive with a link to the archived old Education site. ",
                        null=True,
                        verbose_name="web archive promo text",
                    ),
                ),
                (
                    "newsletter_sign_up_text",
                    models.TextField(
                        blank=True,
                        help_text="Text block encouraging users to sign up for the education newsletter.",
                        verbose_name="newsletter sign up text",
                    ),
                ),
                (
                    "alert",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="alerts.alert",
                    ),
                ),
                (
                    "featured_teaching_resource",
                    models.ForeignKey(
                        blank=True,
                        help_text="Option to add a highlighted teaching resource, particularly for history months etc",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="education.teachingresourcepage",
                        verbose_name="featured teaching resource",
                    ),
                ),
                (
                    "search_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image that will appear when this page is shared on social media. This will default to the teaser image if left blank.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                        verbose_name="OpenGraph image",
                    ),
                ),
                (
                    "teaser_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image that will appear on thumbnails and promos around the site.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
                (
                    "twitter_og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="If left blank, the OpenGraph image will be used.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                        verbose_name="Twitter OpenGraph image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teaching Resources listing page",
            },
            bases=(
                app.core.models.mixins.CustomHeadlessPreviewMixin,
                "wagtailcore.page",
                models.Model,
            ),
        ),
        migrations.AddField(
            model_name="educationpage",
            name="teaching_resources_listing_page",
            field=models.ForeignKey(
                blank=True,
                help_text="The teaching resource listing page to display on the Education landing page.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="education.teachingresourceslistingpage",
                verbose_name="teaching resource listing page",
            ),
        ),
        migrations.RunPython(seed_key_stages, noop_reverse),
    ]
