# Generated by Django 6.0.5 on 2026-05-19 11:53

import app.core.models.mixins
import app.education.models.mixins
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0005_alert_active_from_alert_active_to_and_more'),
        ('images', '0013_alter_customimage_description'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('stage', models.PositiveSmallIntegerField(blank=True, help_text='Numeric key stage value, e.g. 2, 3, 4.', null=True, verbose_name='stage')),
                ('age_range', models.CharField(blank=True, help_text='Age range text, e.g. 5-7 or 7-11.', max_length=64, verbose_name='age range')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Key stage',
                'verbose_name_plural': 'Key stages',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Theme',
                'verbose_name_plural': 'Themes',
            },
        ),
        migrations.CreateModel(
            name='TimePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('year_from', models.PositiveIntegerField(blank=True, help_text='Starting year, e.g. 1485', null=True, verbose_name='year from')),
                ('year_to', models.PositiveIntegerField(blank=True, help_text='Ending year, e.g. 1750', null=True, verbose_name='year to')),
                ('available_for_resources', models.BooleanField(default=True, help_text='Whether this time period can be tagged on teaching resources.', verbose_name='available for resources')),
            ],
            options={
                'verbose_name': 'Time period',
                'verbose_name_plural': 'Time periods',
            },
        ),
        migrations.CreateModel(
            name='EducationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('twitter_og_title', models.CharField(blank=True, help_text='If left blank, the OpenGraph title will be used.', max_length=255, null=True, verbose_name='Twitter OpenGraph title')),
                ('twitter_og_description', models.TextField(blank=True, help_text='If left blank, the OpenGraph description will be used.', null=True, verbose_name='Twitter OpenGraph description')),
                ('short_title', models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=45, null=True, verbose_name='short title')),
                ('teaser_text', models.TextField(help_text='A short, enticing description of this page. This will appear in promos and under thumbnails around the site.', max_length=160, verbose_name='teaser text')),
                ('intro', wagtail.fields.RichTextField(help_text='1-2 sentences introducing the subject of the page, and explaining why a user should read on.', max_length=300, verbose_name='introductory text')),
                ('teaching_resources_teaser_override', models.CharField(blank=True, help_text='Short text under Explore teaching resources title to entice users to click through', max_length=160, verbose_name='teaching resources teaser text')),
                ('featured_teaching_resource_teaser_override', models.CharField(blank=True, help_text='Override text for the featured teaching resource', max_length=160, verbose_name='Featured teaching resource teaser text override')),
                ('education_sessions_teaser_override', models.CharField(blank=True, help_text='Short text under Explore education sessions title to entice users to click through', max_length=160, verbose_name='education sessions teaser text')),
                ('featured_education_session_teaser_override', models.CharField(blank=True, help_text='Override text for the featured education session', max_length=160, verbose_name='Featured education session teaser text override')),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='alerts.alert')),
                ('search_image', models.ForeignKey(blank=True, help_text='Image that will appear when this page is shared on social media. This will default to the teaser image if left blank.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='OpenGraph image')),
                ('teaser_image', models.ForeignKey(blank=True, help_text='Image that will appear on thumbnails and promos around the site.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
                ('twitter_og_image', models.ForeignKey(blank=True, help_text='If left blank, the OpenGraph image will be used.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Twitter OpenGraph image')),
            ],
            options={
                'verbose_name': 'Education landing page',
            },
            bases=(app.core.models.mixins.CustomHeadlessPreviewMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='EducationReadMoreLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_read_more_links', to='education.educationpage')),
                ('selected_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page', verbose_name='selected page')),
            ],
            options={
                'verbose_name': 'read more link',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='EducationSessionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, help_text='The date the page was published to the public.', verbose_name='Published date')),
                ('hero_image_caption', wagtail.fields.RichTextField(blank=True, help_text='An optional caption for hero images. This could be used for image sources or for other useful metadata.', verbose_name='hero image caption (optional)')),
                ('twitter_og_title', models.CharField(blank=True, help_text='If left blank, the OpenGraph title will be used.', max_length=255, null=True, verbose_name='Twitter OpenGraph title')),
                ('twitter_og_description', models.TextField(blank=True, help_text='If left blank, the OpenGraph description will be used.', null=True, verbose_name='Twitter OpenGraph description')),
                ('short_title', models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=45, null=True, verbose_name='short title')),
                ('teaser_text', models.TextField(help_text='A short, enticing description of this page. This will appear in promos and under thumbnails around the site.', max_length=160, verbose_name='teaser text')),
                ('intro', wagtail.fields.RichTextField(help_text='1-2 sentences introducing the subject of the page, and explaining why a user should read on.', max_length=300, verbose_name='introductory text')),
                ('start_date', models.DateField(blank=True, help_text="If neither start nor end date is added this will default to 'All Year'", null=True, verbose_name='start date')),
                ('end_date', models.DateField(blank=True, help_text="If neither start nor end date is added this will default to 'All Year'", null=True, verbose_name='end date')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='price')),
                ('price_detail', models.CharField(blank=True, help_text='An explanation of the price. Required if price is filled in.', max_length=160, verbose_name='price detail')),
                ('booking_link', models.URLField(blank=True, help_text='Link to booking page', null=True, verbose_name='Booking link')),
                ('description', wagtail.fields.StreamField([('description', 13)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Heading', 'max_length': 100}), 1: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link', 'code', 'ol', 'ul']}), 2: ('wagtail.blocks.StructBlock', [[('text', 1)]], {}), 3: ('app.core.blocks.image.PartnerLogoChooserBlock', (), {}), 4: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link', 'code', 'ol', 'ul'], 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'The name of the person being quoted. e.g. King Edward VIII', 'max_length': 100}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'The title of the work or document from which the quote is taken. e.g. The Telegraph, 23 June 1986', 'max_length': 100, 'required': False}), 7: ('app.core.blocks.page_chooser.APIPageChooserBlock', (), {'help_text': 'Reference another page published on the site', 'label': 'Internal page', 'required': False}), 8: ('wagtail.blocks.URLBlock', (), {'help_text': 'Add a URL here to refer to an external source', 'label': 'External link', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('citation_internal_link', 7), ('citation_external_link', 8)]], {}), 10: ('wagtail.blocks.StructBlock', [[('citation', 6), ('source_link', 9)]], {}), 11: ('wagtail.blocks.StructBlock', [[('quote', 4), ('attribution', 5), ('source', 10)]], {}), 12: ('wagtail.blocks.StreamBlock', [[('description', 2), ('partner_logo', 3), ('quote', 11), ('inset_text', 2)]], {'required': False}), 13: ('wagtail.blocks.StructBlock', [[('heading', 0), ('content', 12)]], {})}, null=True, verbose_name='description')),
                ('curriculum_connection_description', wagtail.fields.RichTextField(blank=True, help_text='A description of how the session connects to the curriculum. This is optional but can help teachers understand the relevance of the session to their teaching.', null=True, verbose_name='curriculum connection description')),
                ('highlights', wagtail.fields.StreamField([('highlights', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link', 'code'], 'required': False}), 2: ('app.core.blocks.image.APIImageChooserBlock', (), {'rendition_size': 'max-900x900', 'required': True}), 3: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'help_text': 'If provided, displays directly below the image. Can be used to specify sources, transcripts or other useful metadata.', 'label': 'Caption (optional)', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {}), 6: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('images', 5)]], {})}, help_text='Optional image gallery to show what to expect from the session.')),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='alerts.alert')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
                ('search_image', models.ForeignKey(blank=True, help_text='Image that will appear when this page is shared on social media. This will default to the teaser image if left blank.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='OpenGraph image')),
                ('teaser_image', models.ForeignKey(blank=True, help_text='Image that will appear on thumbnails and promos around the site.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
                ('twitter_og_image', models.ForeignKey(blank=True, help_text='If left blank, the OpenGraph image will be used.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Twitter OpenGraph image')),
            ],
            options={
                'abstract': False,
            },
            bases=(app.education.models.mixins.EducationTaxonomyMixin, app.core.models.mixins.CustomHeadlessPreviewMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.AddField(
            model_name='educationpage',
            name='featured_education_session',
            field=models.ForeignKey(blank=True, help_text='Page picker to highlight a featured education session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='education.educationsessionpage', verbose_name='featured education session'),
        ),
        migrations.CreateModel(
            name='EducationSessionsListingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('twitter_og_title', models.CharField(blank=True, help_text='If left blank, the OpenGraph title will be used.', max_length=255, null=True, verbose_name='Twitter OpenGraph title')),
                ('twitter_og_description', models.TextField(blank=True, help_text='If left blank, the OpenGraph description will be used.', null=True, verbose_name='Twitter OpenGraph description')),
                ('short_title', models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=45, null=True, verbose_name='short title')),
                ('teaser_text', models.TextField(help_text='A short, enticing description of this page. This will appear in promos and under thumbnails around the site.', max_length=160, verbose_name='teaser text')),
                ('intro', wagtail.fields.RichTextField(help_text='1-2 sentences introducing the subject of the page, and explaining why a user should read on.', max_length=300, verbose_name='introductory text')),
                ('featured_education_session_teaser_override', models.CharField(blank=True, help_text='Override text for the featured education session', max_length=160, verbose_name='Featured education session teaser text override')),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='alerts.alert')),
                ('featured_education_session', models.ForeignKey(blank=True, help_text='Page picker to highlight a featured education session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='education.educationsessionpage', verbose_name='featured education session')),
                ('search_image', models.ForeignKey(blank=True, help_text='Image that will appear when this page is shared on social media. This will default to the teaser image if left blank.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='OpenGraph image')),
                ('teaser_image', models.ForeignKey(blank=True, help_text='Image that will appear on thumbnails and promos around the site.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
                ('twitter_og_image', models.ForeignKey(blank=True, help_text='If left blank, the OpenGraph image will be used.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Twitter OpenGraph image')),
            ],
            options={
                'verbose_name': 'Education Sessions listing page',
            },
            bases=(app.core.models.mixins.CustomHeadlessPreviewMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.AddField(
            model_name='educationpage',
            name='education_sessions_listing_page',
            field=models.ForeignKey(blank=True, help_text='The education sessions listing page to display on the Education landing page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='education.educationsessionslistingpage', verbose_name='education sessions listing page'),
        ),
        migrations.CreateModel(
            name='EducationSessionPageKeyStageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_keystage_tags', to='education.educationsessionpage')),
                ('key_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='education.keystage', verbose_name='key stage')),
            ],
            options={
                'abstract': False,
            },
            bases=(app.education.models.mixins.TagDuplicateCheckMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RelatedEducationSessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_education_sessions', to='education.educationsessionpage')),
                ('selected_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='education.educationsessionpage', verbose_name='selected page')),
            ],
            options={
                'verbose_name': 'related education session',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SessionLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('location_type', models.CharField(choices=[('online', 'Online'), ('national_archives', 'At The National Archives'), ('your_school', 'At your school'), ('custom', 'Custom venue')], help_text='Choose a standard location or Custom venue.', max_length=32, null=True, verbose_name='location type')),
                ('duration', models.CharField(blank=True, help_text='A clear description of the session duration for this location, e.g. 1 hour, 1 to 2 hours.', max_length=160, null=True, verbose_name='duration')),
                ('region', models.CharField(blank=True, choices=[('south_east', 'South East and London'), ('south_west', 'South West'), ('midlands', 'Midlands'), ('north_east', 'North East'), ('north_west', 'North West')], help_text='The region where the session is offered. Required for schools and custom venues.', max_length=32, null=True, verbose_name='region')),
                ('venue_name', models.CharField(blank=True, help_text='Required only when location type is Custom venue.', max_length=255, null=True, verbose_name='Venue name')),
                ('address_line_1', models.CharField(blank=True, help_text='Required only when location type is Custom venue.', max_length=255, null=True, verbose_name='Address line 1')),
                ('address_line_2', models.CharField(blank=True, help_text='Required only when location type is Custom venue.', max_length=255, null=True, verbose_name='Address line 2')),
                ('postcode', models.CharField(blank=True, help_text='Required only when location type is Custom venue.', max_length=20, null=True, verbose_name='Postcode')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_locations', to='education.educationsessionpage')),
            ],
            options={
                'verbose_name': 'session location',
                'verbose_name_plural': 'session locations',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='TeachingResourcePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('custom_warning_text', wagtail.fields.RichTextField(blank=True, help_text='If specified, will be used for the content warning.', verbose_name='custom content warning text (optional)')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, help_text='The date the page was published to the public.', verbose_name='Published date')),
                ('hero_image_caption', wagtail.fields.RichTextField(blank=True, help_text='An optional caption for hero images. This could be used for image sources or for other useful metadata.', verbose_name='hero image caption (optional)')),
                ('twitter_og_title', models.CharField(blank=True, help_text='If left blank, the OpenGraph title will be used.', max_length=255, null=True, verbose_name='Twitter OpenGraph title')),
                ('twitter_og_description', models.TextField(blank=True, help_text='If left blank, the OpenGraph description will be used.', null=True, verbose_name='Twitter OpenGraph description')),
                ('short_title', models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=45, null=True, verbose_name='short title')),
                ('teaser_text', models.TextField(help_text='A short, enticing description of this page. This will appear in promos and under thumbnails around the site.', max_length=160, verbose_name='teaser text')),
                ('intro', wagtail.fields.RichTextField(help_text='1-2 sentences introducing the subject of the page, and explaining why a user should read on.', max_length=300, verbose_name='introductory text')),
                ('enquiry_question', models.CharField(blank=True, max_length=160, verbose_name='enquiry question')),
                ('sources_title', models.CharField(blank=True, help_text='Title of the main section of the page. In most cases ‘Investigate the sources’', max_length=160, verbose_name='sources title')),
                ('sources_introduction', wagtail.fields.RichTextField(blank=True, help_text='Optional text field to provide an introduction to the sources.', null=True, verbose_name='sources introduction')),
                ('teachers_notes', wagtail.fields.RichTextField(blank=True, help_text='A general overview of what the resource contains and how it can be used.', null=True, verbose_name='teachers notes')),
                ('extension_activities', wagtail.fields.StreamField([('paragraph', 0), ('sub_heading', 2), ('featured_page', 5), ('featured_external_link', 11)], blank=True, block_lookup={0: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link', 'code', 'ol', 'ul']}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Sub-heading', 'max_length': 100}), 2: ('wagtail.blocks.StructBlock', [[('heading', 1)]], {}), 3: ('app.core.blocks.page_chooser.APIPageChooserBlock', (), {'label': 'Page', 'page_type': ['wagtailcore.Page'], 'required': True}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional override for the teaser text', 'label': 'Teaser text override', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('page', 3), ('teaser_text', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Supertitle', 'max_length': 20, 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 100}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Description'}), 9: ('wagtail.blocks.URLBlock', (), {'label': 'URL'}), 10: ('app.core.blocks.image.APIImageChooserBlock', (), {'label': 'Image', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('supertitle', 6), ('title', 7), ('description', 8), ('url', 9), ('image', 10)]], {})}, help_text='Optional section where editors can add extra activities for teachers to try with their pupils.', null=True, verbose_name='extension activities')),
                ('background_information', wagtail.fields.StreamField([('paragraph', 0), ('sub_heading', 2)], blank=True, block_lookup={0: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link', 'code', 'ol', 'ul']}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Sub-heading', 'max_length': 100}), 2: ('wagtail.blocks.StructBlock', [[('heading', 1)]], {})}, help_text='Section providing historical context to the teaching resource.', null=True, verbose_name='background information')),
                ('further_information_title', models.CharField(blank=True, help_text='Title of the further information section.', max_length=255, null=True, verbose_name='further information title')),
                ('further_information', wagtail.fields.StreamField([('paragraph', 0), ('sub_heading', 2), ('featured_external_link', 8), ('featured_page', 11)], blank=True, block_lookup={0: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link', 'code', 'ol', 'ul']}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Sub-heading', 'max_length': 100}), 2: ('wagtail.blocks.StructBlock', [[('heading', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Supertitle', 'max_length': 20, 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 100}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Description'}), 6: ('wagtail.blocks.URLBlock', (), {'label': 'URL'}), 7: ('app.core.blocks.image.APIImageChooserBlock', (), {'label': 'Image', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('supertitle', 3), ('title', 4), ('description', 5), ('url', 6), ('image', 7)]], {}), 9: ('app.core.blocks.page_chooser.APIPageChooserBlock', (), {'label': 'Page', 'page_type': ['wagtailcore.Page'], 'required': True}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional override for the teaser text', 'label': 'Teaser text override', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('page', 9), ('teaser_text', 10)]], {})}, help_text='Section providing links to other useful information.', null=True, verbose_name='further information')),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='alerts.alert')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
                ('search_image', models.ForeignKey(blank=True, help_text='Image that will appear when this page is shared on social media. This will default to the teaser image if left blank.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='OpenGraph image')),
                ('teaser_image', models.ForeignKey(blank=True, help_text='Image that will appear on thumbnails and promos around the site.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
                ('twitter_og_image', models.ForeignKey(blank=True, help_text='If left blank, the OpenGraph image will be used.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Twitter OpenGraph image')),
            ],
            options={
                'abstract': False,
            },
            bases=(app.education.models.mixins.EducationTaxonomyMixin, app.core.models.mixins.CustomHeadlessPreviewMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(blank=True, help_text='A unique, descriptive title for the source.', max_length=160, verbose_name='source title')),
                ('media', wagtail.fields.StreamField([('image', 2), ('video', 5), ('youtube', 13)], blank=True, block_lookup={0: ('app.core.blocks.image.APIImageChooserBlock', (), {'help_text': 'An image for the source.', 'rendition_size': 'max-900x900'}), 1: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic'], 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('caption', 1)]], {}), 3: ('app.core.blocks.image.APIImageChooserBlock', (), {'help_text': 'A thumbnail image for the media block', 'rendition_size': 'fill-960x540', 'required': False}), 4: ('app.media.blocks.MediaChooserBlock', (), {}), 5: ('wagtail.blocks.StructBlock', [[('thumbnail', 3), ('media', 4), ('caption', 1)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'A descriptive title for the media block', 'required': True}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 100, 'required': True}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'YouTube Video ID', 'max_length': 11, 'required': True, 'validators': [django.core.validators.RegexValidator(message='Invalid YouTube Video ID', regex='^[a-zA-Z0-9_-]{11}$')]}), 9: ('app.core.blocks.image.APIImageChooserBlock', (), {'label': 'Preview Image', 'rendition_size': 'fill-640x360', 'required': True}), 10: ('wagtail.blocks.RichTextBlock', (), {'label': 'Transcript', 'required': False}), 11: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Tick if the video has captions on YouTube', 'label': 'Captions available', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('title', 7), ('video_id', 8), ('preview_image', 9), ('transcript', 10), ('captions_available', 11)]], {}), 13: ('wagtail.blocks.StructBlock', [[('title', 6), ('thumbnail', 3), ('media', 4), ('youtube', 12), ('caption', 1)]], {})}, help_text='Choose one media type for this source. A caption can be added for each.', null=True, verbose_name='source media')),
                ('featured_link', wagtail.fields.StreamField([('external_link', 5), ('internal_link', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Supertitle', 'max_length': 20, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 100}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Description'}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'URL'}), 4: ('app.core.blocks.image.APIImageChooserBlock', (), {'label': 'Image', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('supertitle', 0), ('title', 1), ('description', 2), ('url', 3), ('image', 4)]], {}), 6: ('app.core.blocks.page_chooser.APIPageChooserBlock', (), {'label': 'Page', 'page_type': ['wagtailcore.Page'], 'required': True}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional override for the teaser text', 'label': 'Teaser text override', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('page', 6), ('teaser_text', 7)]], {})}, help_text='Choose internal or external link for this source', verbose_name='source media featured link')),
                ('description', wagtail.fields.RichTextField(blank=True, help_text='An optional free text field to add in a fuller description of the source.', null=True, verbose_name='source description')),
                ('question', wagtail.fields.StreamField([('question', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 1: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link', 'code', 'ol', 'ul'], 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('question_heading', 0), ('question_description', 1)]], {})})),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='education.teachingresourcepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='educationpage',
            name='featured_teaching_resource',
            field=models.ForeignKey(blank=True, help_text='Option to add a highlighted teaching resource, particularly for history months etc', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='education.teachingresourcepage', verbose_name='featured teaching resource'),
        ),
        migrations.CreateModel(
            name='CurriculumConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('description', wagtail.fields.RichTextField(blank=True, help_text='Add the curriculum connection description.', null=True, verbose_name='curriculum connection description')),
                ('key_stage', models.ForeignKey(help_text='The key stage for this curriculum connection.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='education.keystage', verbose_name='Key stage')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_connections', to='education.teachingresourcepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeachingResourcePageKeyStageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('key_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='education.keystage', verbose_name='key stage')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_keystage_tags', to='education.teachingresourcepage')),
            ],
            options={
                'abstract': False,
            },
            bases=(app.education.models.mixins.TagDuplicateCheckMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TeachingResourcesListingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('twitter_og_title', models.CharField(blank=True, help_text='If left blank, the OpenGraph title will be used.', max_length=255, null=True, verbose_name='Twitter OpenGraph title')),
                ('twitter_og_description', models.TextField(blank=True, help_text='If left blank, the OpenGraph description will be used.', null=True, verbose_name='Twitter OpenGraph description')),
                ('short_title', models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=45, null=True, verbose_name='short title')),
                ('teaser_text', models.TextField(help_text='A short, enticing description of this page. This will appear in promos and under thumbnails around the site.', max_length=160, verbose_name='teaser text')),
                ('intro', wagtail.fields.RichTextField(help_text='1-2 sentences introducing the subject of the page, and explaining why a user should read on.', max_length=300, verbose_name='introductory text')),
                ('featured_teaching_resource_teaser_override', models.CharField(blank=True, help_text='Override text for the featured teaching resource', max_length=160, verbose_name='Featured teaching resource teaser text override')),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='alerts.alert')),
                ('featured_teaching_resource', models.ForeignKey(blank=True, help_text='Option to add a highlighted teaching resource, particularly for history months etc', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='education.teachingresourcepage', verbose_name='featured teaching resource')),
                ('search_image', models.ForeignKey(blank=True, help_text='Image that will appear when this page is shared on social media. This will default to the teaser image if left blank.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='OpenGraph image')),
                ('teaser_image', models.ForeignKey(blank=True, help_text='Image that will appear on thumbnails and promos around the site.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
                ('twitter_og_image', models.ForeignKey(blank=True, help_text='If left blank, the OpenGraph image will be used.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Twitter OpenGraph image')),
            ],
            options={
                'verbose_name': 'Teaching Resources listing page',
            },
            bases=(app.core.models.mixins.CustomHeadlessPreviewMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.AddField(
            model_name='educationpage',
            name='teaching_resources_listing_page',
            field=models.ForeignKey(blank=True, help_text='The teaching resource listing page to display on the Education landing page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='education.teachingresourceslistingpage', verbose_name='teaching resource listing page'),
        ),
        migrations.CreateModel(
            name='TeachingResourcePageThemeTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_theme_tags', to='education.teachingresourcepage')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='education.theme', verbose_name='theme')),
            ],
            options={
                'abstract': False,
            },
            bases=(app.education.models.mixins.TagDuplicateCheckMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EducationSessionPageThemeTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_theme_tags', to='education.educationsessionpage')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='education.theme', verbose_name='theme')),
            ],
            options={
                'abstract': False,
            },
            bases=(app.education.models.mixins.TagDuplicateCheckMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TeachingResourcePageTimePeriodTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_time_period_tags', to='education.teachingresourcepage')),
                ('time_period', models.ForeignKey(limit_choices_to={'available_for_resources': True}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='education.timeperiod', verbose_name='time period')),
            ],
            options={
                'abstract': False,
            },
            bases=(app.education.models.mixins.TagDuplicateCheckMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EducationSessionPageTimePeriodTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_time_period_tags', to='education.educationsessionpage')),
                ('time_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='education.timeperiod', verbose_name='time period')),
            ],
            options={
                'abstract': False,
            },
            bases=(app.education.models.mixins.TagDuplicateCheckMixin, models.Model),
        ),
    ]
