# Generated by Django 6.0.7 on 2026-07-30 13:11

import app.core.models.mixins
import app.education.models.mixins
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('description', wagtail.fields.RichTextField(help_text='Add the curriculum connection description.', verbose_name='curriculum connection description')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EducationReadMoreLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'read more link',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='EducationSessionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, help_text='The date the page was published to the public.', verbose_name='Published date')),
                ('hero_image_caption', wagtail.fields.RichTextField(blank=True, help_text='An optional caption for hero images. This could be used for image sources or for other useful metadata.', verbose_name='hero image caption (optional)')),
                ('twitter_og_title', models.CharField(blank=True, help_text='If left blank, the OpenGraph title will be used.', max_length=255, null=True, verbose_name='Twitter OpenGraph title')),
                ('twitter_og_description', models.TextField(blank=True, help_text='If left blank, the OpenGraph description will be used.', null=True, verbose_name='Twitter OpenGraph description')),
                ('short_title', models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=45, null=True, verbose_name='short title')),
                ('teaser_text', models.TextField(help_text='A short, enticing description of this page. This will appear in promos and under thumbnails around the site.', max_length=160, verbose_name='teaser text')),
                ('intro', wagtail.fields.RichTextField(help_text='1-2 sentences introducing the subject of the page, and explaining why a user should read on.', max_length=300, verbose_name='introductory text')),
                ('start_date', models.DateField(blank=True, help_text="If neither start nor end date is added this will default to 'All Year'", null=True, verbose_name='start date')),
                ('end_date', models.DateField(blank=True, help_text="If neither start nor end date is added this will default to 'All Year'", null=True, verbose_name='end date')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='price')),
                ('price_detail', models.CharField(blank=True, help_text='An explanation of the price. Required if price is filled in.', max_length=160, null=True, verbose_name='price detail')),
                ('booking_link', models.URLField(blank=True, help_text='Link to booking page', null=True, verbose_name='Booking link')),
                ('description', wagtail.fields.StreamField([('content_section', 34)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Heading', 'max_length': 100}), 1: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link', 'code', 'ol', 'ul']}), 2: ('wagtail.blocks.StructBlock', [[('text', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional override for the partner logos section lead text. Will display a default if not provided.', 'max_length': 40, 'required': False}), 4: ('app.core.blocks.image.PartnerLogoChooserBlock', (), {}), 5: ('wagtail.blocks.ListBlock', (4,), {'max_num': 4, 'required': True}), 6: ('wagtail.blocks.StructBlock', [[('lead_text', 3), ('logos', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {}), 8: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['link'], 'required': False}), 9: ('wagtail.blocks.TextBlock', (), {'features': ['bold', 'italic', 'link', 'code'], 'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'required': False}), 11: ('wagtail.blocks.URLBlock', (), {'required': False}), 12: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'required': False}), 13: ('wagtail.blocks.EmailBlock', (), {'required': False}), 14: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link', 'code'], 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('title', 7), ('body', 8), ('address', 9), ('telephone', 10), ('chat_link', 11), ('chat_note', 12), ('email', 13), ('website_link', 11), ('social_media', 14)]], {}), 16: ('app.core.blocks.page_chooser.APIPageChooserBlock', (), {'label': 'Page', 'page_type': ['wagtailcore.Page'], 'required': True}), 17: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional override for the teaser text', 'label': 'Teaser text override', 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('page', 16), ('teaser_text', 17)]], {}), 19: ('wagtail.blocks.CharBlock', (), {'label': 'Supertitle', 'max_length': 20, 'required': False}), 20: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 100}), 21: ('wagtail.blocks.CharBlock', (), {'label': 'Description'}), 22: ('wagtail.blocks.URLBlock', (), {'label': 'URL'}), 23: ('app.core.blocks.image.APIImageChooserBlock', (), {'label': 'Image', 'required': False}), 24: ('wagtail.blocks.StructBlock', [[('supertitle', 19), ('title', 20), ('description', 21), ('url', 22), ('image', 23)]], {}), 25: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link', 'code', 'ol', 'ul'], 'required': True}), 26: ('wagtail.blocks.CharBlock', (), {'help_text': 'The name of the person being quoted. e.g. King Edward VIII', 'max_length': 100}), 27: ('wagtail.blocks.CharBlock', (), {'help_text': 'The title of the work or document from which the quote is taken. e.g. The Telegraph, 23 June 1986', 'max_length': 100, 'required': False}), 28: ('app.core.blocks.page_chooser.APIPageChooserBlock', (), {'help_text': 'Reference another page published on the site', 'label': 'Internal page', 'required': False}), 29: ('wagtail.blocks.URLBlock', (), {'help_text': 'Add a URL here to refer to an external source', 'label': 'External link', 'required': False}), 30: ('wagtail.blocks.StructBlock', [[('citation_internal_link', 28), ('citation_external_link', 29)]], {}), 31: ('wagtail.blocks.StructBlock', [[('citation', 27), ('source_link', 30)]], {}), 32: ('wagtail.blocks.StructBlock', [[('quote', 25), ('attribution', 26), ('source', 31)]], {}), 33: ('wagtail.blocks.StreamBlock', [[('paragraph', 2), ('partner_logos', 6), ('contact', 15), ('featured_page', 18), ('featured_external_link', 24), ('quote', 32), ('inset_text', 2)]], {'required': False}), 34: ('wagtail.blocks.StructBlock', [[('heading', 0), ('content', 33)]], {})}, null=True, verbose_name='description')),
                ('curriculum_connection_description', wagtail.fields.RichTextField(blank=True, help_text='A description of how the session connects to the curriculum. This is optional but can help teachers understand the relevance of the session to their teaching.', null=True, verbose_name='curriculum connection description')),
                ('highlights', wagtail.fields.StreamField([('image_gallery', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link', 'code'], 'required': False}), 2: ('app.core.blocks.image.APIImageChooserBlock', (), {'rendition_size': 'max-900x900', 'required': True}), 3: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'help_text': 'If provided, displays directly below the image. Can be used to specify sources, transcripts or other useful metadata.', 'label': 'Caption (optional)', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {}), 6: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('images', 5)]], {})}, help_text='Optional image gallery to show what to expect from the session.')),
            ],
            options={
                'abstract': False,
            },
            bases=(app.education.models.mixins.EducationTaxonomyMixin, app.core.models.mixins.CustomHeadlessPreviewMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='EducationSessionPageKeyStageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(app.education.models.mixins.TagDuplicateCheckMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EducationSessionPageThemeTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(app.education.models.mixins.TagDuplicateCheckMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EducationSessionPageTimePeriodTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(app.education.models.mixins.TagDuplicateCheckMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EducationSessionsListingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('twitter_og_title', models.CharField(blank=True, help_text='If left blank, the OpenGraph title will be used.', max_length=255, null=True, verbose_name='Twitter OpenGraph title')),
                ('twitter_og_description', models.TextField(blank=True, help_text='If left blank, the OpenGraph description will be used.', null=True, verbose_name='Twitter OpenGraph description')),
                ('short_title', models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=45, null=True, verbose_name='short title')),
                ('teaser_text', models.TextField(help_text='A short, enticing description of this page. This will appear in promos and under thumbnails around the site.', max_length=160, verbose_name='teaser text')),
                ('intro', wagtail.fields.RichTextField(help_text='1-2 sentences introducing the subject of the page, and explaining why a user should read on.', max_length=300, verbose_name='introductory text')),
                ('featured_education_session_teaser_override', models.CharField(blank=True, help_text='Override text for the featured education session', max_length=160, verbose_name='Featured education session teaser text override')),
            ],
            options={
                'verbose_name': 'Education Sessions listing page',
            },
            bases=(app.core.models.mixins.CustomHeadlessPreviewMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='KeyStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('stage', models.PositiveSmallIntegerField(blank=True, help_text='Numeric key stage value, e.g. 2, 3, 4.', null=True, verbose_name='stage')),
                ('age_range', models.CharField(blank=True, help_text='Age range text, e.g. 5–7 or 7–11.', max_length=64, verbose_name='age range')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Key stage',
                'verbose_name_plural': 'Key stages',
                'ordering': ['stage', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RelatedEducationSessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'related education session',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SessionLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('location_type', models.CharField(choices=[('online', 'Online'), ('national_archives', 'At The National Archives'), ('your_school', 'At your school'), ('custom', 'Custom venue')], help_text='Choose a standard location or Custom venue.', max_length=32, null=True, verbose_name='location type')),
                ('duration', models.CharField(blank=True, help_text='A clear description of the session duration for this location, e.g. 1 hour, 1 to 2 hours.', max_length=160, null=True, verbose_name='duration')),
                ('region', models.CharField(blank=True, choices=[('south_east', 'South East and London'), ('south_west', 'South West'), ('midlands', 'Midlands'), ('north_east', 'North East'), ('north_west', 'North West')], help_text='The region where the session is offered. Required for schools and custom venues.', max_length=32, null=True, verbose_name='region')),
                ('venue_name', models.CharField(blank=True, help_text='Required only when location type is Custom venue.', max_length=255, null=True, verbose_name='Venue name')),
                ('address_line_1', models.CharField(blank=True, help_text='Required only when location type is Custom venue.', max_length=255, null=True, verbose_name='Address line 1')),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address line 2')),
                ('postcode', models.CharField(blank=True, help_text='Required only when location type is Custom venue.', max_length=20, null=True, verbose_name='Postcode')),
            ],
            options={
                'verbose_name': 'session location',
                'verbose_name_plural': 'session locations',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(help_text='A unique, descriptive title for the source.', max_length=160, verbose_name='source title')),
                ('media', wagtail.fields.StreamField([('image', 2), ('media', 6), ('youtube_video', 12)], blank=True, block_lookup={0: ('app.core.blocks.image.APIImageChooserBlock', (), {'rendition_size': 'max-900x900', 'required': True}), 1: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'help_text': 'If provided, displays directly below the image. Can be used to specify sources, transcripts or other useful metadata.', 'label': 'Caption (optional)', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('caption', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'A descriptive title for the media block', 'required': True}), 4: ('app.core.blocks.image.APIImageChooserBlock', (), {'help_text': 'A thumbnail image for the media block', 'rendition_size': 'fill-960x540', 'required': False}), 5: ('app.media.blocks.MediaChooserBlock', (), {}), 6: ('wagtail.blocks.StructBlock', [[('title', 3), ('thumbnail', 4), ('media', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 100, 'required': True}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'YouTube Video ID', 'max_length': 11, 'required': True, 'validators': [django.core.validators.RegexValidator(message='Invalid YouTube Video ID', regex='^[a-zA-Z0-9_-]{11}$')]}), 9: ('app.core.blocks.image.APIImageChooserBlock', (), {'label': 'Preview Image', 'rendition_size': 'fill-640x360', 'required': True}), 10: ('wagtail.blocks.RichTextBlock', (), {'label': 'Transcript', 'required': False}), 11: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Tick if the video has captions on YouTube', 'label': 'Captions available', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('title', 7), ('video_id', 8), ('preview_image', 9), ('transcript', 10), ('captions_available', 11)]], {})}, help_text='Choose one media type for this source. A caption can be added for each.', null=True, verbose_name='source media')),
                ('featured_link', wagtail.fields.StreamField([('external_link', 5), ('internal_link', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Supertitle', 'max_length': 20, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 100}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Description'}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'URL'}), 4: ('app.core.blocks.image.APIImageChooserBlock', (), {'label': 'Image', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('supertitle', 0), ('title', 1), ('description', 2), ('url', 3), ('image', 4)]], {}), 6: ('app.core.blocks.page_chooser.APIPageChooserBlock', (), {'label': 'Page', 'page_type': ['wagtailcore.Page'], 'required': True}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional override for the teaser text', 'label': 'Teaser text override', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('page', 6), ('teaser_text', 7)]], {})}, help_text='Choose internal or external link for this source', verbose_name='source media featured link')),
                ('description', wagtail.fields.RichTextField(blank=True, help_text='An optional free text field to add in a fuller description of the source.', null=True, verbose_name='source description')),
                ('question', wagtail.fields.StreamField([('question', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 1: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link', 'code', 'ol', 'ul'], 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('question_heading', 0), ('question_description', 1)]], {})})),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeachingResourcePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('custom_warning_text', wagtail.fields.RichTextField(blank=True, help_text='If specified, will be used for the content warning.', verbose_name='custom content warning text (optional)')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, help_text='The date the page was published to the public.', verbose_name='Published date')),
                ('hero_image_caption', wagtail.fields.RichTextField(blank=True, help_text='An optional caption for hero images. This could be used for image sources or for other useful metadata.', verbose_name='hero image caption (optional)')),
                ('twitter_og_title', models.CharField(blank=True, help_text='If left blank, the OpenGraph title will be used.', max_length=255, null=True, verbose_name='Twitter OpenGraph title')),
                ('twitter_og_description', models.TextField(blank=True, help_text='If left blank, the OpenGraph description will be used.', null=True, verbose_name='Twitter OpenGraph description')),
                ('short_title', models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=45, null=True, verbose_name='short title')),
                ('teaser_text', models.TextField(help_text='A short, enticing description of this page. This will appear in promos and under thumbnails around the site.', max_length=160, verbose_name='teaser text')),
                ('intro', wagtail.fields.RichTextField(help_text='1-2 sentences introducing the subject of the page, and explaining why a user should read on.', max_length=300, verbose_name='introductory text')),
                ('enquiry_question', models.CharField(blank=True, max_length=160, verbose_name='enquiry question')),
                ('sources_title', models.CharField(blank=True, help_text='Title of the main section of the page. In most cases ‘Investigate the sources’', max_length=160, verbose_name='sources title')),
                ('sources_introduction', wagtail.fields.RichTextField(blank=True, help_text='Optional text field to provide an introduction to the sources.', null=True, verbose_name='sources introduction')),
                ('teachers_notes', wagtail.fields.StreamField([('description_list', 8), ('paragraph', 10), ('sub_heading', 12), ('inset_text', 10), ('quote', 20)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link', 'code']}), 2: ('wagtail.blocks.StructBlock', [[('term', 0), ('detail', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'None'), ('lined', 'Lined'), ('zebra', 'Zebra')], 'help_text': 'Choose the style for this description list.', 'label': 'Style'}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'Auto (recommended)'), ('even', 'Even'), ('left-weighted', 'Left-weighted'), ('right-weighted', 'Right-weighted')], 'help_text': 'Choose the balancing for the columns of the description list.', 'label': 'Column balancing'}), 6: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'If enabled, the term and detail will be stacked vertically instead of displayed side by side.', 'label': 'Stacked layout', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('style', 4), ('column_balancing', 5), ('stacked', 6)]], {}), 8: ('wagtail.blocks.StructBlock', [[('items', 3), ('settings', 7)]], {}), 9: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link', 'code', 'ol', 'ul']}), 10: ('wagtail.blocks.StructBlock', [[('text', 9)]], {}), 11: ('wagtail.blocks.CharBlock', (), {'label': 'Sub-heading', 'max_length': 100}), 12: ('wagtail.blocks.StructBlock', [[('heading', 11)]], {}), 13: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link', 'code', 'ol', 'ul'], 'required': True}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'The name of the person being quoted. e.g. King Edward VIII', 'max_length': 100}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': 'The title of the work or document from which the quote is taken. e.g. The Telegraph, 23 June 1986', 'max_length': 100, 'required': False}), 16: ('app.core.blocks.page_chooser.APIPageChooserBlock', (), {'help_text': 'Reference another page published on the site', 'label': 'Internal page', 'required': False}), 17: ('wagtail.blocks.URLBlock', (), {'help_text': 'Add a URL here to refer to an external source', 'label': 'External link', 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('citation_internal_link', 16), ('citation_external_link', 17)]], {}), 19: ('wagtail.blocks.StructBlock', [[('citation', 15), ('source_link', 18)]], {}), 20: ('wagtail.blocks.StructBlock', [[('quote', 13), ('attribution', 14), ('source', 19)]], {})}, help_text='A general overview of what the resource contains and how it can be used.', verbose_name='teachers notes')),
                ('extension_activities', wagtail.fields.StreamField([('description_list', 8), ('paragraph', 10), ('quote', 18), ('sub_heading', 20), ('table', 22), ('featured_page', 25), ('featured_external_link', 31)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link', 'code']}), 2: ('wagtail.blocks.StructBlock', [[('term', 0), ('detail', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'None'), ('lined', 'Lined'), ('zebra', 'Zebra')], 'help_text': 'Choose the style for this description list.', 'label': 'Style'}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'Auto (recommended)'), ('even', 'Even'), ('left-weighted', 'Left-weighted'), ('right-weighted', 'Right-weighted')], 'help_text': 'Choose the balancing for the columns of the description list.', 'label': 'Column balancing'}), 6: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'If enabled, the term and detail will be stacked vertically instead of displayed side by side.', 'label': 'Stacked layout', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('style', 4), ('column_balancing', 5), ('stacked', 6)]], {}), 8: ('wagtail.blocks.StructBlock', [[('items', 3), ('settings', 7)]], {}), 9: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link', 'code', 'ol', 'ul']}), 10: ('wagtail.blocks.StructBlock', [[('text', 9)]], {}), 11: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link', 'code', 'ol', 'ul'], 'required': True}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': 'The name of the person being quoted. e.g. King Edward VIII', 'max_length': 100}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'The title of the work or document from which the quote is taken. e.g. The Telegraph, 23 June 1986', 'max_length': 100, 'required': False}), 14: ('app.core.blocks.page_chooser.APIPageChooserBlock', (), {'help_text': 'Reference another page published on the site', 'label': 'Internal page', 'required': False}), 15: ('wagtail.blocks.URLBlock', (), {'help_text': 'Add a URL here to refer to an external source', 'label': 'External link', 'required': False}), 16: ('wagtail.blocks.StructBlock', [[('citation_internal_link', 14), ('citation_external_link', 15)]], {}), 17: ('wagtail.blocks.StructBlock', [[('citation', 13), ('source_link', 16)]], {}), 18: ('wagtail.blocks.StructBlock', [[('quote', 11), ('attribution', 12), ('source', 17)]], {}), 19: ('wagtail.blocks.CharBlock', (), {'label': 'Sub-heading', 'max_length': 100}), 20: ('wagtail.blocks.StructBlock', [[('heading', 19)]], {}), 21: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'table_options': {'contextMenu': ['row_above', 'row_below', '---------', 'col_left', 'col_right', '---------', 'remove_row', 'remove_col', '---------', 'undo', 'redo', '---------', 'alignment']}}), 22: ('wagtail.blocks.StructBlock', [[('table', 21)]], {}), 23: ('app.core.blocks.page_chooser.APIPageChooserBlock', (), {'label': 'Page', 'page_type': ['wagtailcore.Page'], 'required': True}), 24: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional override for the teaser text', 'label': 'Teaser text override', 'required': False}), 25: ('wagtail.blocks.StructBlock', [[('page', 23), ('teaser_text', 24)]], {}), 26: ('wagtail.blocks.CharBlock', (), {'label': 'Supertitle', 'max_length': 20, 'required': False}), 27: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 100}), 28: ('wagtail.blocks.CharBlock', (), {'label': 'Description'}), 29: ('wagtail.blocks.URLBlock', (), {'label': 'URL'}), 30: ('app.core.blocks.image.APIImageChooserBlock', (), {'label': 'Image', 'required': False}), 31: ('wagtail.blocks.StructBlock', [[('supertitle', 26), ('title', 27), ('description', 28), ('url', 29), ('image', 30)]], {})}, help_text='Optional section where editors can add extra activities for teachers to try with their pupils.', null=True, verbose_name='extension activities')),
                ('background_information', wagtail.fields.StreamField([('inset_text', 1), ('paragraph', 1), ('sub_heading', 3)], blank=True, block_lookup={0: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link', 'code', 'ol', 'ul']}), 1: ('wagtail.blocks.StructBlock', [[('text', 0)]], {}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Sub-heading', 'max_length': 100}), 3: ('wagtail.blocks.StructBlock', [[('heading', 2)]], {})}, help_text='Section providing historical context to the teaching resource.', null=True, verbose_name='background information')),
                ('further_information_title', models.CharField(blank=True, help_text='Title of the further information section.', max_length=255, null=True, verbose_name='further information title')),
                ('further_information', wagtail.fields.StreamField([('paragraph', 1), ('sub_heading', 3), ('featured_external_link', 9), ('featured_page', 12)], blank=True, block_lookup={0: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link', 'code', 'ol', 'ul']}), 1: ('wagtail.blocks.StructBlock', [[('text', 0)]], {}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Sub-heading', 'max_length': 100}), 3: ('wagtail.blocks.StructBlock', [[('heading', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Supertitle', 'max_length': 20, 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 100}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Description'}), 7: ('wagtail.blocks.URLBlock', (), {'label': 'URL'}), 8: ('app.core.blocks.image.APIImageChooserBlock', (), {'label': 'Image', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('supertitle', 4), ('title', 5), ('description', 6), ('url', 7), ('image', 8)]], {}), 10: ('app.core.blocks.page_chooser.APIPageChooserBlock', (), {'label': 'Page', 'page_type': ['wagtailcore.Page'], 'required': True}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional override for the teaser text', 'label': 'Teaser text override', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('page', 10), ('teaser_text', 11)]], {})}, help_text='Section providing links to other useful information.', null=True, verbose_name='further information')),
                ('partner_logos', wagtail.fields.StreamField([('partner_logos', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional override for the partner logos section lead text. Will display a default if not provided.', 'max_length': 40, 'required': False}), 1: ('app.core.blocks.image.PartnerLogoChooserBlock', (), {}), 2: ('wagtail.blocks.ListBlock', (1,), {'max_num': 4, 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('lead_text', 0), ('logos', 2)]], {})}, help_text='Optional section to add logos of partner organisations.', null=True, verbose_name='partner logos')),
            ],
            options={
                'abstract': False,
            },
            bases=(app.education.models.mixins.EducationTaxonomyMixin, app.core.models.mixins.CustomHeadlessPreviewMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='TeachingResourcePageKeyStageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(app.education.models.mixins.TagDuplicateCheckMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TeachingResourcePageThemeTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(app.education.models.mixins.TagDuplicateCheckMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TeachingResourcePageTimePeriodTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(app.education.models.mixins.TagDuplicateCheckMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TeachingResourcesListingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_image_caption', wagtail.fields.RichTextField(blank=True, help_text='An optional caption for hero images. This could be used for image sources or for other useful metadata.', verbose_name='hero image caption (optional)')),
                ('twitter_og_title', models.CharField(blank=True, help_text='If left blank, the OpenGraph title will be used.', max_length=255, null=True, verbose_name='Twitter OpenGraph title')),
                ('twitter_og_description', models.TextField(blank=True, help_text='If left blank, the OpenGraph description will be used.', null=True, verbose_name='Twitter OpenGraph description')),
                ('short_title', models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=45, null=True, verbose_name='short title')),
                ('teaser_text', models.TextField(help_text='A short, enticing description of this page. This will appear in promos and under thumbnails around the site.', max_length=160, verbose_name='teaser text')),
                ('intro', wagtail.fields.RichTextField(help_text='1-2 sentences introducing the subject of the page, and explaining why a user should read on.', max_length=300, verbose_name='introductory text')),
                ('featured_teaching_resource_teaser_override', models.CharField(blank=True, help_text='Override text for the featured teaching resource', max_length=160, verbose_name='Featured teaching resource teaser text override')),
            ],
            options={
                'verbose_name': 'Teaching Resources listing page',
            },
            bases=(app.core.models.mixins.CustomHeadlessPreviewMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Theme',
                'verbose_name_plural': 'Themes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TimePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('year_from', models.PositiveIntegerField(blank=True, help_text='Starting year, e.g. 1485', null=True, verbose_name='year from')),
                ('year_to', models.PositiveIntegerField(blank=True, help_text='Ending year, e.g. 1750', null=True, verbose_name='year to')),
                ('available_for_resources', models.BooleanField(default=True, help_text='Whether this time period can be tagged on teaching resources.', verbose_name='available for resources')),
            ],
            options={
                'verbose_name': 'Time period',
                'verbose_name_plural': 'Time periods',
                'ordering': ['year_from', 'year_to', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EducationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_image_caption', wagtail.fields.RichTextField(blank=True, help_text='An optional caption for hero images. This could be used for image sources or for other useful metadata.', verbose_name='hero image caption (optional)')),
                ('twitter_og_title', models.CharField(blank=True, help_text='If left blank, the OpenGraph title will be used.', max_length=255, null=True, verbose_name='Twitter OpenGraph title')),
                ('twitter_og_description', models.TextField(blank=True, help_text='If left blank, the OpenGraph description will be used.', null=True, verbose_name='Twitter OpenGraph description')),
                ('short_title', models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=45, null=True, verbose_name='short title')),
                ('teaser_text', models.TextField(help_text='A short, enticing description of this page. This will appear in promos and under thumbnails around the site.', max_length=160, verbose_name='teaser text')),
                ('intro', wagtail.fields.RichTextField(help_text='1-2 sentences introducing the subject of the page, and explaining why a user should read on.', max_length=300, verbose_name='introductory text')),
                ('teaching_resources_teaser_override', models.CharField(blank=True, help_text='Short text under Explore teaching resources title to entice users to click through', max_length=160, verbose_name='teaching resources teaser text')),
                ('featured_teaching_resource_teaser_override', models.CharField(blank=True, help_text='Override text for the featured teaching resource', max_length=160, verbose_name='Featured teaching resource teaser text override')),
                ('education_sessions_teaser_override', models.CharField(blank=True, help_text='Short text under Explore education sessions title to entice users to click through', max_length=160, verbose_name='education sessions teaser text')),
                ('featured_education_session_teaser_override', models.CharField(blank=True, help_text='Override text for the featured education session', max_length=160, verbose_name='Featured education session teaser text override')),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='alerts.alert')),
            ],
            options={
                'verbose_name': 'Education landing page',
            },
            bases=(app.core.models.mixins.CustomHeadlessPreviewMixin, 'wagtailcore.page', models.Model),
        ),
    ]
