# Generated by Django 6.0.7 on 2026-07-30 13:11

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('education', '0001_initial'),
        ('images', '0001_initial'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage'),
        ),
        migrations.AddField(
            model_name='educationpage',
            name='search_image',
            field=models.ForeignKey(blank=True, help_text='Image that will appear when this page is shared on social media. This will default to the teaser image if left blank.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='OpenGraph image'),
        ),
        migrations.AddField(
            model_name='educationpage',
            name='teaser_image',
            field=models.ForeignKey(blank=True, help_text='Image that will appear on thumbnails and promos around the site.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage'),
        ),
        migrations.AddField(
            model_name='educationpage',
            name='twitter_og_image',
            field=models.ForeignKey(blank=True, help_text='If left blank, the OpenGraph image will be used.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Twitter OpenGraph image'),
        ),
        migrations.AddField(
            model_name='educationreadmorelink',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_read_more_links', to='education.educationpage'),
        ),
        migrations.AddField(
            model_name='educationreadmorelink',
            name='selected_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page', verbose_name='selected page'),
        ),
        migrations.AddField(
            model_name='educationsessionpage',
            name='alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='alerts.alert'),
        ),
        migrations.AddField(
            model_name='educationsessionpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage'),
        ),
        migrations.AddField(
            model_name='educationsessionpage',
            name='search_image',
            field=models.ForeignKey(blank=True, help_text='Image that will appear when this page is shared on social media. This will default to the teaser image if left blank.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='OpenGraph image'),
        ),
        migrations.AddField(
            model_name='educationsessionpage',
            name='teaser_image',
            field=models.ForeignKey(blank=True, help_text='Image that will appear on thumbnails and promos around the site.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage'),
        ),
        migrations.AddField(
            model_name='educationsessionpage',
            name='twitter_og_image',
            field=models.ForeignKey(blank=True, help_text='If left blank, the OpenGraph image will be used.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Twitter OpenGraph image'),
        ),
        migrations.AddField(
            model_name='educationpage',
            name='featured_education_session',
            field=models.ForeignKey(blank=True, help_text='Page picker to highlight a featured education session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='education.educationsessionpage', verbose_name='featured education session'),
        ),
        migrations.AddField(
            model_name='educationsessionpagekeystagetag',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_keystage_tags', to='education.educationsessionpage'),
        ),
        migrations.AddField(
            model_name='educationsessionpagethemetag',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_theme_tags', to='education.educationsessionpage'),
        ),
        migrations.AddField(
            model_name='educationsessionpagetimeperiodtag',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_time_period_tags', to='education.educationsessionpage'),
        ),
        migrations.AddField(
            model_name='educationsessionslistingpage',
            name='alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='alerts.alert'),
        ),
        migrations.AddField(
            model_name='educationsessionslistingpage',
            name='featured_education_session',
            field=models.ForeignKey(blank=True, help_text='Page picker to highlight a featured education session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='education.educationsessionpage', verbose_name='featured education session'),
        ),
        migrations.AddField(
            model_name='educationsessionslistingpage',
            name='search_image',
            field=models.ForeignKey(blank=True, help_text='Image that will appear when this page is shared on social media. This will default to the teaser image if left blank.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='OpenGraph image'),
        ),
        migrations.AddField(
            model_name='educationsessionslistingpage',
            name='teaser_image',
            field=models.ForeignKey(blank=True, help_text='Image that will appear on thumbnails and promos around the site.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage'),
        ),
        migrations.AddField(
            model_name='educationsessionslistingpage',
            name='twitter_og_image',
            field=models.ForeignKey(blank=True, help_text='If left blank, the OpenGraph image will be used.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Twitter OpenGraph image'),
        ),
        migrations.AddField(
            model_name='educationpage',
            name='education_sessions_listing_page',
            field=models.ForeignKey(blank=True, help_text='The education sessions listing page to display on the Education landing page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='education.educationsessionslistingpage', verbose_name='education sessions listing page'),
        ),
        migrations.AddField(
            model_name='educationsessionpagekeystagetag',
            name='key_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='education.keystage', verbose_name='key stage'),
        ),
        migrations.AddField(
            model_name='curriculumconnection',
            name='key_stage',
            field=models.ForeignKey(help_text='The key stage for this curriculum connection.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='education.keystage', verbose_name='Key stage'),
        ),
        migrations.AddField(
            model_name='relatededucationsessions',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_education_sessions', to='education.educationsessionpage'),
        ),
        migrations.AddField(
            model_name='relatededucationsessions',
            name='selected_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='education.educationsessionpage', verbose_name='selected page'),
        ),
        migrations.AddField(
            model_name='sessionlocation',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_locations', to='education.educationsessionpage'),
        ),
        migrations.AddField(
            model_name='teachingresourcepage',
            name='alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='alerts.alert'),
        ),
        migrations.AddField(
            model_name='teachingresourcepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage'),
        ),
        migrations.AddField(
            model_name='teachingresourcepage',
            name='search_image',
            field=models.ForeignKey(blank=True, help_text='Image that will appear when this page is shared on social media. This will default to the teaser image if left blank.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='OpenGraph image'),
        ),
        migrations.AddField(
            model_name='teachingresourcepage',
            name='teaser_image',
            field=models.ForeignKey(blank=True, help_text='Image that will appear on thumbnails and promos around the site.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage'),
        ),
        migrations.AddField(
            model_name='teachingresourcepage',
            name='twitter_og_image',
            field=models.ForeignKey(blank=True, help_text='If left blank, the OpenGraph image will be used.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Twitter OpenGraph image'),
        ),
        migrations.AddField(
            model_name='source',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='education.teachingresourcepage'),
        ),
        migrations.AddField(
            model_name='educationpage',
            name='featured_teaching_resource',
            field=models.ForeignKey(blank=True, help_text='Option to add a highlighted teaching resource, particularly for history months etc', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='education.teachingresourcepage', verbose_name='featured teaching resource'),
        ),
        migrations.AddField(
            model_name='curriculumconnection',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_connections', to='education.teachingresourcepage'),
        ),
        migrations.AddField(
            model_name='teachingresourcepagekeystagetag',
            name='key_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='education.keystage', verbose_name='key stage'),
        ),
        migrations.AddField(
            model_name='teachingresourcepagekeystagetag',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_keystage_tags', to='education.teachingresourcepage'),
        ),
        migrations.AddField(
            model_name='teachingresourcepagethemetag',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_theme_tags', to='education.teachingresourcepage'),
        ),
        migrations.AddField(
            model_name='teachingresourcepagetimeperiodtag',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_time_period_tags', to='education.teachingresourcepage'),
        ),
        migrations.AddField(
            model_name='teachingresourceslistingpage',
            name='alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='alerts.alert'),
        ),
        migrations.AddField(
            model_name='teachingresourceslistingpage',
            name='featured_teaching_resource',
            field=models.ForeignKey(blank=True, help_text='Option to add a highlighted teaching resource, particularly for history months etc', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='education.teachingresourcepage', verbose_name='featured teaching resource'),
        ),
        migrations.AddField(
            model_name='teachingresourceslistingpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage'),
        ),
        migrations.AddField(
            model_name='teachingresourceslistingpage',
            name='search_image',
            field=models.ForeignKey(blank=True, help_text='Image that will appear when this page is shared on social media. This will default to the teaser image if left blank.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='OpenGraph image'),
        ),
        migrations.AddField(
            model_name='teachingresourceslistingpage',
            name='teaser_image',
            field=models.ForeignKey(blank=True, help_text='Image that will appear on thumbnails and promos around the site.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage'),
        ),
        migrations.AddField(
            model_name='teachingresourceslistingpage',
            name='twitter_og_image',
            field=models.ForeignKey(blank=True, help_text='If left blank, the OpenGraph image will be used.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Twitter OpenGraph image'),
        ),
        migrations.AddField(
            model_name='educationpage',
            name='teaching_resources_listing_page',
            field=models.ForeignKey(blank=True, help_text='The teaching resource listing page to display on the Education landing page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='education.teachingresourceslistingpage', verbose_name='teaching resource listing page'),
        ),
        migrations.AddField(
            model_name='teachingresourcepagethemetag',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='education.theme', verbose_name='theme'),
        ),
        migrations.AddField(
            model_name='educationsessionpagethemetag',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='education.theme', verbose_name='theme'),
        ),
        migrations.AddField(
            model_name='teachingresourcepagetimeperiodtag',
            name='time_period',
            field=models.ForeignKey(limit_choices_to={'available_for_resources': True}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='education.timeperiod', verbose_name='time period'),
        ),
        migrations.AddField(
            model_name='educationsessionpagetimeperiodtag',
            name='time_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='education.timeperiod', verbose_name='time period'),
        ),
    ]
