# Generated by Django 6.0.6 on 2026-08-04 13:24
# etna:allowAlterField

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingresourcepage',
            name='teachers_notes',
            field=wagtail.fields.StreamField([('description_list', 8), ('paragraph', 10), ('sub_heading', 12), ('inset_text', 10), ('quote', 20)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link', 'code']}), 2: ('wagtail.blocks.StructBlock', [[('term', 0), ('detail', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'None'), ('lined', 'Lined'), ('zebra', 'Zebra')], 'help_text': 'Choose the style for this description list.', 'label': 'Style'}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'Auto (recommended)'), ('even', 'Even'), ('left-weighted', 'Left-weighted'), ('right-weighted', 'Right-weighted')], 'help_text': 'Choose the balancing for the columns of the description list.', 'label': 'Column balancing'}), 6: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'If enabled, the term and detail will be stacked vertically instead of displayed side by side.', 'label': 'Stacked layout', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('style', 4), ('column_balancing', 5), ('stacked', 6)]], {}), 8: ('wagtail.blocks.StructBlock', [[('items', 3), ('settings', 7)]], {}), 9: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link', 'code', 'ol', 'ul']}), 10: ('wagtail.blocks.StructBlock', [[('text', 9)]], {}), 11: ('wagtail.blocks.CharBlock', (), {'label': 'Sub-heading', 'max_length': 100}), 12: ('wagtail.blocks.StructBlock', [[('heading', 11)]], {}), 13: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link', 'code', 'ol', 'ul'], 'required': True}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'The name of the person being quoted. e.g. King Edward VIII', 'max_length': 100}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': 'The title of the work or document from which the quote is taken. e.g. The Telegraph, 23 June 1986', 'max_length': 100, 'required': False}), 16: ('app.core.blocks.page_chooser.APIPageChooserBlock', (), {'help_text': 'Reference another page published on the site', 'label': 'Internal page', 'required': False}), 17: ('wagtail.blocks.URLBlock', (), {'help_text': 'Add a URL here to refer to an external source', 'label': 'External link', 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('citation_internal_link', 16), ('citation_external_link', 17)]], {}), 19: ('wagtail.blocks.StructBlock', [[('citation', 15), ('source_link', 18)]], {}), 20: ('wagtail.blocks.StructBlock', [[('quote', 13), ('attribution', 14), ('source', 19)]], {})}, help_text='A general overview of what the resource contains and how it can be used.', verbose_name="teachers' notes"),
        ),
    ]
