# Generated by Django 6.0.5 on 2026-05-26 13:33
# etna:allowAlterField

import django.core.validators
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_seed_key_stage_and_taxonomies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='media',
            field=wagtail.fields.StreamField([('image', 2), ('video', 5), ('youtube', 12)], blank=True, block_lookup={0: ('app.core.blocks.image.APIImageChooserBlock', (), {'help_text': 'An image for the source.', 'rendition_size': 'max-900x900'}), 1: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic'], 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('caption', 1)]], {}), 3: ('app.core.blocks.image.APIImageChooserBlock', (), {'help_text': 'A thumbnail image for the media block', 'rendition_size': 'fill-960x540', 'required': False}), 4: ('app.media.blocks.MediaChooserBlock', (), {}), 5: ('wagtail.blocks.StructBlock', [[('thumbnail', 3), ('media', 4), ('caption', 1)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 100, 'required': True}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'YouTube Video ID', 'max_length': 11, 'required': True, 'validators': [django.core.validators.RegexValidator(message='Invalid YouTube Video ID', regex='^[a-zA-Z0-9_-]{11}$')]}), 8: ('app.core.blocks.image.APIImageChooserBlock', (), {'label': 'Preview Image', 'rendition_size': 'fill-640x360', 'required': True}), 9: ('wagtail.blocks.RichTextBlock', (), {'label': 'Transcript', 'required': False}), 10: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Tick if the video has captions on YouTube', 'label': 'Captions available', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('title', 6), ('video_id', 7), ('preview_image', 8), ('transcript', 9), ('captions_available', 10)]], {}), 12: ('wagtail.blocks.StructBlock', [[('youtube', 11), ('caption', 1)]], {})}, help_text='Choose one media type for this source. A caption can be added for each.', null=True, verbose_name='source media'),
        ),
    ]
