# Generated by Django 6.0.7 on 2026-08-07 18:25
# etna:allowAlterField

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_alter_source_featured_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachingresourceslistingpage',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='teachingresourceslistingpage',
            name='hero_image_caption',
        ),
    ]
