# Generated by Django 6.0.5 on 2026-06-10 08:44
# etna:allowAlterField

import django.core.validators
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_alter_curriculumconnection_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationsessionpage',
            name='description',
            field=wagtail.fields.StreamField([('content_section', 13)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Heading', 'max_length': 100}), 1: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link', 'code', 'ol', 'ul']}), 2: ('wagtail.blocks.StructBlock', [[('text', 1)]], {}), 3: ('app.core.blocks.image.PartnerLogoChooserBlock', (), {}), 4: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link', 'code', 'ol', 'ul'], 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'The name of the person being quoted. e.g. King Edward VIII', 'max_length': 100}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'The title of the work or document from which the quote is taken. e.g. The Telegraph, 23 June 1986', 'max_length': 100, 'required': False}), 7: ('app.core.blocks.page_chooser.APIPageChooserBlock', (), {'help_text': 'Reference another page published on the site', 'label': 'Internal page', 'required': False}), 8: ('wagtail.blocks.URLBlock', (), {'help_text': 'Add a URL here to refer to an external source', 'label': 'External link', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('citation_internal_link', 7), ('citation_external_link', 8)]], {}), 10: ('wagtail.blocks.StructBlock', [[('citation', 6), ('source_link', 9)]], {}), 11: ('wagtail.blocks.StructBlock', [[('quote', 4), ('attribution', 5), ('source', 10)]], {}), 12: ('wagtail.blocks.StreamBlock', [[('paragraph', 2), ('partner_logo', 3), ('quote', 11), ('inset_text', 2)]], {'required': False}), 13: ('wagtail.blocks.StructBlock', [[('heading', 0), ('content', 12)]], {})}, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='sessionlocation',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address line 2'),
        ),
        migrations.AlterField(
            model_name='source',
            name='media',
            field=wagtail.fields.StreamField([('image', 2), ('media', 6), ('youtube_video', 12)], blank=True, block_lookup={0: ('app.core.blocks.image.APIImageChooserBlock', (), {'rendition_size': 'max-900x900', 'required': True}), 1: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'help_text': 'If provided, displays directly below the image. Can be used to specify sources, transcripts or other useful metadata.', 'label': 'Caption (optional)', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('caption', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'A descriptive title for the media block', 'required': True}), 4: ('app.core.blocks.image.APIImageChooserBlock', (), {'help_text': 'A thumbnail image for the media block', 'rendition_size': 'fill-960x540', 'required': False}), 5: ('app.media.blocks.MediaChooserBlock', (), {}), 6: ('wagtail.blocks.StructBlock', [[('title', 3), ('thumbnail', 4), ('media', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 100, 'required': True}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'YouTube Video ID', 'max_length': 11, 'required': True, 'validators': [django.core.validators.RegexValidator(message='Invalid YouTube Video ID', regex='^[a-zA-Z0-9_-]{11}$')]}), 9: ('app.core.blocks.image.APIImageChooserBlock', (), {'label': 'Preview Image', 'rendition_size': 'fill-640x360', 'required': True}), 10: ('wagtail.blocks.RichTextBlock', (), {'label': 'Transcript', 'required': False}), 11: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Tick if the video has captions on YouTube', 'label': 'Captions available', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('title', 7), ('video_id', 8), ('preview_image', 9), ('transcript', 10), ('captions_available', 11)]], {})}, help_text='Choose one media type for this source. A caption can be added for each.', null=True, verbose_name='source media'),
        ),
    ]
