# Generated by Django 6.0.5 on 2026-06-09 17:37
# etna:allowAlterField

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_alter_curriculumconnection_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionlocation',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address line 2'),
        ),
    ]
