# Generated by Django 6.0.8 on 2026-08-28 12:13
# etna:allowAlterField

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_alter_teachingresourcepage_extension_activities'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationpage',
            name='featured_education_session',
        ),
        migrations.RemoveField(
            model_name='educationpage',
            name='featured_education_session_teaser_override',
        ),
        migrations.RemoveField(
            model_name='educationpage',
            name='featured_teaching_resource',
        ),
        migrations.RemoveField(
            model_name='educationpage',
            name='featured_teaching_resource_teaser_override',
        ),
        migrations.AddField(
            model_name='educationpage',
            name='featured_page',
            field=models.ForeignKey(blank=True, help_text='Page picker to highlight a featured education page (session, resource, or hub/general)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='featured education page'),
        ),
    ]
