# Generated by Django 6.0.5 on 2026-06-12 15:00
# etna:allowAlterField

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_alter_educationsessionpage_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationsessionpage',
            name='description',
            field=wagtail.fields.StreamField([('content_section', 34)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Heading', 'max_length': 100}), 1: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link', 'code', 'ol', 'ul']}), 2: ('wagtail.blocks.StructBlock', [[('text', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional override for the partner logos section lead text. Will display a default if not provided.', 'max_length': 40, 'required': False}), 4: ('app.core.blocks.image.PartnerLogoChooserBlock', (), {}), 5: ('wagtail.blocks.ListBlock', (4,), {'max_num': 4, 'required': True}), 6: ('wagtail.blocks.StructBlock', [[('lead_text', 3), ('logos', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {}), 8: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['link'], 'required': False}), 9: ('wagtail.blocks.TextBlock', (), {'features': ['bold', 'italic', 'link', 'code'], 'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'required': False}), 11: ('wagtail.blocks.URLBlock', (), {'required': False}), 12: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'required': False}), 13: ('wagtail.blocks.EmailBlock', (), {'required': False}), 14: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link', 'code'], 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('title', 7), ('body', 8), ('address', 9), ('telephone', 10), ('chat_link', 11), ('chat_note', 12), ('email', 13), ('website_link', 11), ('social_media', 14)]], {}), 16: ('app.core.blocks.page_chooser.APIPageChooserBlock', (), {'label': 'Page', 'page_type': ['wagtailcore.Page'], 'required': True}), 17: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional override for the teaser text', 'label': 'Teaser text override', 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('page', 16), ('teaser_text', 17)]], {}), 19: ('wagtail.blocks.CharBlock', (), {'label': 'Supertitle', 'max_length': 20, 'required': False}), 20: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 100}), 21: ('wagtail.blocks.CharBlock', (), {'label': 'Description'}), 22: ('wagtail.blocks.URLBlock', (), {'label': 'URL'}), 23: ('app.core.blocks.image.APIImageChooserBlock', (), {'label': 'Image', 'required': False}), 24: ('wagtail.blocks.StructBlock', [[('supertitle', 19), ('title', 20), ('description', 21), ('url', 22), ('image', 23)]], {}), 25: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link', 'code', 'ol', 'ul'], 'required': True}), 26: ('wagtail.blocks.CharBlock', (), {'help_text': 'The name of the person being quoted. e.g. King Edward VIII', 'max_length': 100}), 27: ('wagtail.blocks.CharBlock', (), {'help_text': 'The title of the work or document from which the quote is taken. e.g. The Telegraph, 23 June 1986', 'max_length': 100, 'required': False}), 28: ('app.core.blocks.page_chooser.APIPageChooserBlock', (), {'help_text': 'Reference another page published on the site', 'label': 'Internal page', 'required': False}), 29: ('wagtail.blocks.URLBlock', (), {'help_text': 'Add a URL here to refer to an external source', 'label': 'External link', 'required': False}), 30: ('wagtail.blocks.StructBlock', [[('citation_internal_link', 28), ('citation_external_link', 29)]], {}), 31: ('wagtail.blocks.StructBlock', [[('citation', 27), ('source_link', 30)]], {}), 32: ('wagtail.blocks.StructBlock', [[('quote', 25), ('attribution', 26), ('source', 31)]], {}), 33: ('wagtail.blocks.StreamBlock', [[('paragraph', 2), ('partner_logos', 6), ('contact', 15), ('featured_page', 18), ('featured_external_link', 24), ('quote', 32), ('inset_text', 2)]], {'required': False}), 34: ('wagtail.blocks.StructBlock', [[('heading', 0), ('content', 33)]], {})}, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='source',
            name='title',
            field=models.CharField(help_text='A unique, descriptive title for the source.', max_length=160, verbose_name='source title'),
        ),
    ]
