# Generated by Django 6.0.8 on 2026-09-17 09:05

import django.core.validators
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_alter_educationsessionpage_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationpage',
            name='twitter_og_description',
        ),
        migrations.RemoveField(
            model_name='educationpage',
            name='twitter_og_image',
        ),
        migrations.RemoveField(
            model_name='educationpage',
            name='twitter_og_title',
        ),
        migrations.RemoveField(
            model_name='educationsessionpage',
            name='twitter_og_description',
        ),
        migrations.RemoveField(
            model_name='educationsessionpage',
            name='twitter_og_image',
        ),
        migrations.RemoveField(
            model_name='educationsessionpage',
            name='twitter_og_title',
        ),
        migrations.RemoveField(
            model_name='educationsessionslistingpage',
            name='twitter_og_description',
        ),
        migrations.RemoveField(
            model_name='educationsessionslistingpage',
            name='twitter_og_image',
        ),
        migrations.RemoveField(
            model_name='educationsessionslistingpage',
            name='twitter_og_title',
        ),
        migrations.RemoveField(
            model_name='teachingresourcepage',
            name='twitter_og_description',
        ),
        migrations.RemoveField(
            model_name='teachingresourcepage',
            name='twitter_og_image',
        ),
        migrations.RemoveField(
            model_name='teachingresourcepage',
            name='twitter_og_title',
        ),
        migrations.RemoveField(
            model_name='teachingresourceslistingpage',
            name='twitter_og_description',
        ),
        migrations.RemoveField(
            model_name='teachingresourceslistingpage',
            name='twitter_og_image',
        ),
        migrations.RemoveField(
            model_name='teachingresourceslistingpage',
            name='twitter_og_title',
        ),
        migrations.AlterField(
            model_name='educationsessionpage',
            name='highlights',
            field=wagtail.fields.StreamField([('image_gallery', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link', 'code'], 'required': False}), 2: ('app.core.blocks.image.APIImageChooserBlock', (), {'rendition_size': 'max-1200x1200', 'required': True}), 3: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'help_text': 'If provided, displays directly below the image. Can be used to specify sources, transcripts or other useful metadata.', 'label': 'Caption (optional)', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {}), 6: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('images', 5)]], {})}, help_text='Optional image gallery to show what to expect from the session.'),
        ),
        migrations.AlterField(
            model_name='source',
            name='media',
            field=wagtail.fields.StreamField([('image', 2), ('media', 6), ('youtube_video', 12)], blank=True, block_lookup={0: ('app.core.blocks.image.APIImageChooserBlock', (), {'rendition_size': 'max-1200x1200', 'required': True}), 1: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'help_text': 'If provided, displays directly below the image. Can be used to specify sources, transcripts or other useful metadata.', 'label': 'Caption (optional)', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('caption', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'A descriptive title for the media block', 'required': True}), 4: ('app.core.blocks.image.APIImageChooserBlock', (), {'help_text': 'A thumbnail image for the media block', 'rendition_size': 'fill-960x540', 'required': False}), 5: ('app.media.blocks.MediaChooserBlock', (), {}), 6: ('wagtail.blocks.StructBlock', [[('title', 3), ('thumbnail', 4), ('media', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 100, 'required': True}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'YouTube Video ID', 'max_length': 11, 'required': True, 'validators': [django.core.validators.RegexValidator(message='Invalid YouTube Video ID', regex='^[a-zA-Z0-9_-]{11}$')]}), 9: ('app.core.blocks.image.APIImageChooserBlock', (), {'label': 'Preview Image', 'rendition_size': 'fill-640x360', 'required': True}), 10: ('wagtail.blocks.RichTextBlock', (), {'label': 'Transcript', 'required': False}), 11: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Tick if the video has captions on YouTube', 'label': 'Captions available', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('title', 7), ('video_id', 8), ('preview_image', 9), ('transcript', 10), ('captions_available', 11)]], {})}, help_text='Choose one media type for this source. A caption can be added for each.', null=True, verbose_name='source media'),
        ),
    ]
