# Generated by Django 6.0.7 on 2026-07-30 12:45
# etna:allowAlterField

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_update_keystage_age_ranges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingresourcepage',
            name='background_information',
            field=wagtail.fields.StreamField([('inset_text', 1), ('paragraph', 1), ('sub_heading', 3)], blank=True, block_lookup={0: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link', 'code', 'ol', 'ul']}), 1: ('wagtail.blocks.StructBlock', [[('text', 0)]], {}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Sub-heading', 'max_length': 100}), 3: ('wagtail.blocks.StructBlock', [[('heading', 2)]], {})}, help_text='Section providing historical context to the teaching resource.', null=True, verbose_name='background information'),
        ),
    ]
