# Generated by Django 3.2.13 on 2022-06-09 11:38

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="banner_text",
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
