# Generated by Django 4.1.8 on 2023-04-27 11:01
import uuid
from django.db import migrations

TARGET_PAGE_TYPES = (
    "articles.ArticleIndexPage",
    "articles.ArticlePage",
    "articles.RecordArticlePage",
    "collections.ExplorerIndexPage",
    "collections.TopicExplorerIndexPage",
    "collections.TopicExplorerPage",
    "collections.TimePeriodExplorerIndexPage",
    "collections.TimePeriodExplorerPage",
    "collections.HighlightGalleryPage",
    "generic_pages.GeneralPage",
    "home.HomePage",
)


def migrate_forwards(apps, schema_editor):
    uuid_base = uuid.UUID("53eabd25-b57c-40cc-a406-db7743527d8a")
    for page_type in TARGET_PAGE_TYPES:
        model = apps.get_model(page_type)
        to_update = []
        for obj in model.objects.all().only("id", "title").iterator():
            # Generate a value from the 'title' of existing pages
            obj.uuid = uuid.uuid5(uuid_base, obj.title)
            to_update.append(obj)
        model.objects.bulk_update(to_update, fields=["uuid"])


def migrate_backwards(apps, schema_editor):
    for page_type in TARGET_PAGE_TYPES:
        model = apps.get_model(page_type)
        model.objects.all().update(uuid=None)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_add_beta_banner_fields"),
        ("articles", "0079_add_page_uuid"),
        ("collections", "0049_add_page_uuid"),
        ("generic_pages", "0007_add_page_uuid"),
        ("home", "0023_add_page_uuid"),
    ]

    operations = [migrations.RunPython(migrate_forwards, migrate_backwards)]
