# Generated by Django 5.0.2 on 2024-02-28 13:16

import etna.core.blocks.paragraph
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_set_page_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="beta_banner_text",
            field=etna.core.blocks.paragraph.APIRichTextField(
                default="<p>This beta site contains new services and features currently in development. Many of these features are works in progress and are being updated regularly. You can help us improve them by providing feedback as you use the site.</p> ",
                verbose_name="text",
            ),
        ),
    ]
