# Generated by Django 5.0.6 on 2024-07-11 09:27
# etna:allowAlterField

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_customdocument"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customdocument",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="A short summary of what the document contains to help users understand what they are downloading.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customdocument",
            name="extent",
            field=models.CharField(
                blank=True,
                help_text="The volume of the file so that users understand how much there is to consume. E.g. '3 pages' or '120 images'.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customdocument",
            name="title",
            field=models.CharField(
                help_text="The name of the document as it will appear on the webpage. Please format this in sentence case with spaces between the words. e.g. Preservation policy part one.",
                max_length=255,
                verbose_name="title",
            ),
        ),
    ]
