# Generated by Django 5.1.2 on 2024-11-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_customdocument_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpeningTimes",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area", models.CharField(max_length=255)),
                ("monday_open", models.TimeField(blank=True, null=True)),
                ("monday_close", models.TimeField(blank=True, null=True)),
                ("tuesday_open", models.TimeField(blank=True, null=True)),
                ("tuesday_close", models.TimeField(blank=True, null=True)),
                ("wednesday_open", models.TimeField(blank=True, null=True)),
                ("wednesday_close", models.TimeField(blank=True, null=True)),
                ("thursday_open", models.TimeField(blank=True, null=True)),
                ("thursday_close", models.TimeField(blank=True, null=True)),
                ("friday_open", models.TimeField(blank=True, null=True)),
                ("friday_close", models.TimeField(blank=True, null=True)),
                ("saturday_open", models.TimeField(blank=True, null=True)),
                ("saturday_close", models.TimeField(blank=True, null=True)),
                ("sunday_open", models.TimeField(blank=True, null=True)),
                ("sunday_close", models.TimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Opening time",
                "verbose_name_plural": "Opening times",
            },
        ),
    ]
