# Generated by Django 5.2 on 2025-05-15 14:31

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_sitesettings_site_delete_mainmenuitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_name', models.CharField(max_length=255, verbose_name='Space name')),
                ('address', wagtail.fields.RichTextField(blank=True, help_text='Leave blank to default to TNA address.', null=True, verbose_name='location address')),
                ('details_title', models.CharField(blank=True, help_text="Leave blank to default to 'Plan your visit'.", max_length=100)),
                ('details', wagtail.fields.StreamField([('details', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('etna.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('body', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {})})),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
    ]
