# Generated by Django 5.2.1 on 2025-06-18 12:53

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_sitesettings_site_delete_mainmenuitem_and_more'),
        ('images', '0011_remove_customimage_custom_sensitive_image_warning_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_name', models.CharField(max_length=255, verbose_name='Space name')),
                ('at_tna', models.BooleanField(default=False, help_text='Check if this venue is at The National Archives.', verbose_name='at The National Archives')),
                ('online', models.BooleanField(default=False, help_text='Check if this is an online venue.', verbose_name='online venue')),
                ('address_line_1', models.CharField(blank=True, help_text='First line of address for the location, if applicable.', max_length=255, null=True, verbose_name='first line of address')),
                ('address_line_2', models.CharField(blank=True, help_text='Second line of address for the location, if applicable.', max_length=255, null=True, verbose_name='second line of address')),
                ('postcode', models.CharField(blank=True, help_text='Postcode for the location, if applicable.', max_length=20, null=True, verbose_name='postcode')),
                ('online_detail', models.CharField(blank=True, help_text='Additional detail for online venues, if applicable.', max_length=255, null=True, verbose_name='online detail')),
                ('details_title', models.CharField(blank=True, help_text="Leave blank to default to 'Plan your visit'.", max_length=100)),
                ('details', wagtail.fields.StreamField([('details', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('etna.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('body', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {})})),
                ('image', models.ForeignKey(blank=True, help_text='An image representing the location, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
    ]
