# Generated by Django 5.2 on 2025-07-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='venue_link',
            field=models.URLField(blank=True, help_text="A link to the venue's website or visit us page.", null=True, verbose_name='Venue link'),
        ),
        migrations.AddField(
            model_name='location',
            name='venue_link_text',
            field=models.CharField(blank=True, help_text='Text to display for the venue link, if applicable.', max_length=50, null=True, verbose_name='Venue link text'),
        ),
    ]
