# Generated by Django 5.2 on 2025-05-20 11:08

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='online',
            field=models.BooleanField(default=False, help_text='Check if this is an online venue.', verbose_name='online venue'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='location address'),
        ),
    ]
