# Generated by Django 5.2 on 2025-06-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_location_online_alter_location_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='address',
        ),
        migrations.AddField(
            model_name='location',
            name='at_tna',
            field=models.BooleanField(default=False, help_text='Check if this venue is at The National Archives.', verbose_name='at The National Archives'),
        ),
        migrations.AddField(
            model_name='location',
            name='first_line',
            field=models.CharField(blank=True, help_text='First line of address for the location, if applicable.', max_length=255, null=True, verbose_name='first line of address'),
        ),
        migrations.AddField(
            model_name='location',
            name='postcode',
            field=models.CharField(blank=True, help_text='Postcode for the location, if applicable.', max_length=20, null=True, verbose_name='postcode'),
        ),
        migrations.AddField(
            model_name='location',
            name='second_line',
            field=models.CharField(blank=True, help_text='Second line of address for the location, if applicable.', max_length=255, null=True, verbose_name='second line of address'),
        ),
    ]
