# Generated by Django 5.2 on 2025-06-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_location_address_location_at_tna_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='online_detail',
            field=models.CharField(blank=True, help_text='Additional detail for online venues, if applicable.', max_length=255, null=True, verbose_name='online detail'),
        ),
    ]
