# Generated by Django 4.0.8 on 2022-11-01 16:41

from django.db import migrations, models
import django.db.models.deletion
import etna.analytics.mixins
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insights', '0045_add_search_image_fields'),
        ('wagtailimages', '0024_index_image_file_hash'),
        ('collections', '0023_add_search_image_fields'),
        ('wagtailcore', '0077_alter_revision_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('short_description', models.CharField(max_length=200, null=True)),
                ('date', models.CharField(max_length=20)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'highlight',
                'verbose_name_plural': 'highlights',
            },
        ),
        migrations.CreateModel(
            name='HighlightsGalleryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('standfirst', models.CharField(max_length=250, null=True)),
                ('featured_insight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insights.insightspage')),
                ('highlight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='highlights.highlights')),
            ],
            options={
                'abstract': False,
            },
            bases=(etna.analytics.mixins.DataLayerMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='CloserLookPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('display_content_warning', models.BooleanField(default=False, verbose_name='display a content warning on this page')),
                ('custom_warning_text', wagtail.fields.RichTextField(blank=True, help_text='If specified, will be used for the content warning. Otherwise the default text will be used.', verbose_name='custom content warning text (optional)')),
                ('date', models.CharField(blank=True, max_length=30, null=True)),
                ('featured_insight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insights.insightspage')),
                ('time_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='collections.timeperiodexplorerpage')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='collections.topicexplorerpage')),
            ],
            options={
                'abstract': False,
            },
            bases=(etna.analytics.mixins.DataLayerMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='CloserLookGalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('alt_text', models.CharField(help_text='Alt text for the image', max_length=100, null=True)),
                ('sensitive_image', models.BooleanField(default=False, help_text='Apply the sensitive image filter to this image')),
                ('caption', models.CharField(blank=True, help_text='A caption for the image', max_length=100, null=True)),
                ('transcription', models.TextField(blank=True, help_text='A transcription of the image', max_length=400, null=True)),
                ('translation', models.TextField(blank=True, help_text='A translation of the transcription', max_length=400, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_gallery', to='highlights.closerlookpage')),
            ],
            options={
                'verbose_name': 'gallery image',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
