# Generated by Django 4.0.8 on 2022-10-27 11:20

from django.db import migrations, models
import django.db.models.deletion
import etna.analytics.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0045_add_search_image_fields'),
        ('wagtailcore', '0077_alter_revision_user'),
        ('highlights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlights',
            name='standfirst',
        ),
        migrations.AddField(
            model_name='highlights',
            name='short_description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='highlights',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='HighlightsGalleryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('standfirst', models.CharField(max_length=250, null=True)),
                ('featured_insight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insights.insightspage')),
                ('highlight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='highlights.highlights')),
            ],
            options={
                'abstract': False,
            },
            bases=(etna.analytics.mixins.DataLayerMixin, 'wagtailcore.page'),
        ),
    ]
