# Generated by Django 4.0.8 on 2022-11-01 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0023_add_search_image_fields'),
        ('insights', '0045_add_search_image_fields'),
        ('highlights', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='closerlookgalleryimage',
            old_name='translation',
            new_name='translation_text',
        ),
        migrations.AddField(
            model_name='closerlookgalleryimage',
            name='translation_header',
            field=models.CharField(blank=True, help_text='Header for the translation', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='closerlookpage',
            name='featured_insight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insights.insightspage', verbose_name='Featured insight'),
        ),
        migrations.AlterField(
            model_name='closerlookpage',
            name='time_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='collections.timeperiodexplorerpage', verbose_name='Promoted Time Period'),
        ),
        migrations.AlterField(
            model_name='closerlookpage',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='collections.topicexplorerpage', verbose_name='Promoted Topic'),
        ),
    ]
