# Generated by Django 4.0.8 on 2023-02-02 10:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("highlights", "0002_swap_image_reference_fields_to_new_model"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Highlight",
        ),
    ]
