# Generated by Django 4.0.8 on 2022-10-27 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0002_remove_highlights_standfirst_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='highlights',
            options={'verbose_name': 'highlight', 'verbose_name_plural': 'highlights'},
        ),
    ]
