# Generated by Django 4.0.8 on 2022-11-01 17:43

from django.db import migrations
import etna.records.blocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0002_rename_translation_closerlookgalleryimage_translation_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='closerlookpage',
            name='body',
            field=wagtail.fields.StreamField([('record', etna.records.blocks.RecordChooserBlock()), ('paragraph', wagtail.blocks.StructBlock([('text', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ul']))]))], null=True, use_json_field=True),
        ),
    ]
