# Generated by Django 4.0.8 on 2022-11-30 12:43

from django.db import migrations, models
import django.db.models.deletion
import etna.records.blocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0005_closerlookpage_promoted_pages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closerlookgalleryimage',
            name='alt_text',
            field=models.CharField(help_text='Alt text for the image (max. character length: 150)', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='closerlookgalleryimage',
            name='caption',
            field=models.CharField(blank=True, help_text='A caption for the image (max. character length: 200)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='closerlookgalleryimage',
            name='transcription_header',
            field=models.CharField(blank=True, help_text='Header for the transcription (max. character length: 50)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='closerlookgalleryimage',
            name='transcription_text',
            field=models.TextField(blank=True, help_text='A transcription of the image (max. character length: 1500)', max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='closerlookgalleryimage',
            name='translation_header',
            field=models.CharField(blank=True, help_text='Header for the translation (max. character length: 50)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='closerlookgalleryimage',
            name='translation_text',
            field=models.TextField(blank=True, help_text='A translation of the transcription (max. character length: 1500)', max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='closerlookpage',
            name='body',
            field=wagtail.fields.StreamField([('record_info', wagtail.blocks.StructBlock([('record', etna.records.blocks.RecordChooserBlock()), ('date', wagtail.blocks.CharBlock(help_text='Date(s) related to the record (max. character length: 100)', max_length=100, required=True)), ('paragraph', wagtail.blocks.StructBlock([('text', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ul']))]))]))], null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='closerlookpage',
            name='image_library_link',
            field=models.URLField(blank=True, help_text='Link to an external image library', null=True, verbose_name='Image library link'),
        ),
        migrations.AlterField(
            model_name='closerlookpage',
            name='print_on_demand_link',
            field=models.URLField(blank=True, help_text='Link to an external print on demand service', null=True, verbose_name='Print on demand link'),
        ),
        migrations.AlterField(
            model_name='closerlookpage',
            name='related_records',
            field=models.ForeignKey(blank=True, help_text='Displays the Highlights inside the selected Highlights Gallery page', null=True, on_delete=django.db.models.deletion.SET_NULL, to='highlights.highlightsgallerypage', verbose_name='Related records'),
        ),
        migrations.AlterField(
            model_name='closerlookpage',
            name='standfirst',
            field=models.CharField(help_text='(max. character length: 350)', max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='highlights',
            name='body',
            field=wagtail.fields.StreamField([('record_info', wagtail.blocks.StructBlock([('record', etna.records.blocks.RecordChooserBlock()), ('date', wagtail.blocks.CharBlock(help_text='Date(s) related to the record (max. character length: 100)', max_length=100, required=True)), ('paragraph', wagtail.blocks.StructBlock([('text', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ul']))]))]))], null=True, use_json_field=True),
        ),
    ]
