# Generated by Django 4.0.8 on 2022-11-01 19:42

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0025_alter_taggedtimeperiods_content_object_and_more'),
        ('highlights', '0006_closerlookpage_topic_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='closerlookpage',
            name='time_period_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='collections.TaggedTimePeriods', to='collections.TimePeriodTag', verbose_name='Time Period Tags'),
        ),
        migrations.AlterField(
            model_name='closerlookpage',
            name='topic_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='collections.TaggedTopics', to='collections.TopicTag', verbose_name='Topic Tags'),
        ),
    ]
