# Generated by Django 4.0.8 on 2022-11-01 19:59

from django.db import migrations
import etna.records.blocks
import modelcluster.contrib.taggit
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0025_alter_taggedtimeperiods_content_object_and_more'),
        ('highlights', '0007_closerlookpage_time_period_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlights',
            name='date',
        ),
        migrations.AddField(
            model_name='highlights',
            name='body',
            field=wagtail.fields.StreamField([('record_info', wagtail.blocks.StructBlock([('record', etna.records.blocks.RecordChooserBlock()), ('date', wagtail.blocks.CharBlock(max_length=30, required=False))]))], null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='highlightsgallerypage',
            name='time_period_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='collections.TaggedTimePeriods', to='collections.TimePeriodTag', verbose_name='Time Period Tags'),
        ),
        migrations.AddField(
            model_name='highlightsgallerypage',
            name='topic_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='collections.TaggedTopics', to='collections.TopicTag', verbose_name='Topic Tags'),
        ),
        migrations.AlterField(
            model_name='closerlookpage',
            name='body',
            field=wagtail.fields.StreamField([('record_info', wagtail.blocks.StructBlock([('record_and_date', wagtail.blocks.StructBlock([('record', etna.records.blocks.RecordChooserBlock()), ('date', wagtail.blocks.CharBlock(max_length=30, required=False))])), ('paragraph', wagtail.blocks.StructBlock([('text', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ul']))]))]))], null=True, use_json_field=True),
        ),
    ]
