# Generated by Django 4.0.8 on 2022-11-01 20:33

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0009_highlights_closer_look'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlightsgallerypage',
            name='highlight',
        ),
        migrations.CreateModel(
            name='HighlightsGalleryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('highlight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='highlights.highlights')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights_gallery', to='highlights.highlightsgallerypage')),
            ],
            options={
                'verbose_name': 'highlight',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
