# Generated by Django 4.0.8 on 2022-11-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0010_remove_highlightsgallerypage_highlight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='closerlookpage',
            name='image_library_link',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Link to external image library'),
        ),
        migrations.AddField(
            model_name='closerlookpage',
            name='print_on_demand_link',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Link to external print on demand'),
        ),
    ]
