# Generated by Django 4.0.8 on 2022-11-07 14:46

from django.db import migrations
import etna.records.blocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0012_closerlookpage_related_records'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlights',
            name='short_description',
        ),
        migrations.AlterField(
            model_name='closerlookpage',
            name='body',
            field=wagtail.fields.StreamField([('record_info', wagtail.blocks.StructBlock([('record', etna.records.blocks.RecordChooserBlock()), ('date', wagtail.blocks.CharBlock(max_length=30, required=False)), ('paragraph', wagtail.blocks.StructBlock([('text', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ul']))]))]))], null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='highlights',
            name='body',
            field=wagtail.fields.StreamField([('record_info', wagtail.blocks.StructBlock([('record', etna.records.blocks.RecordChooserBlock()), ('date', wagtail.blocks.CharBlock(max_length=30, required=False)), ('paragraph', wagtail.blocks.StructBlock([('text', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ul']))]))]))], null=True, use_json_field=True),
        ),
    ]
