# Generated by Django 4.0.8 on 2022-11-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0013_remove_highlights_short_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='closerlookgalleryimage',
            old_name='transcription',
            new_name='transcription_text',
        ),
        migrations.AddField(
            model_name='closerlookgalleryimage',
            name='transcription_header',
            field=models.CharField(blank=True, help_text='Header for the transcription', max_length=50, null=True),
        ),
    ]
