# Generated by Django 6.0.8 on 2026-08-20 13:08

from django.db import migrations, models


def set_null_page_sidebar_to_none(apps, schema_editor):
    GeneralPage = apps.get_model('generic_pages', 'GeneralPage')
    GeneralPage.objects.filter(page_sidebar__isnull=True).update(page_sidebar='none')


class Migration(migrations.Migration):

    dependencies = [
        ('generic_pages', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalpage',
            name='page_sidebar',
            field=models.CharField(blank=True, choices=[('none', 'No sidebar'), ('sections', 'H2 headings'), ('contents-two-levels', 'H2-H3 headings'), ('contents', 'H2-H4 headings'), ('pages', 'Pages')], default='sections', help_text="Select the sidebar style for this page. For more information, see the <a href='https://nationalarchives.github.io/design-system/components/sidebar/'>sidebar documentation</a>.", null=True),
        ),
        migrations.RunPython(set_null_page_sidebar_to_none, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='generalpage',
            name='page_sidebar',
            field=models.CharField(choices=[('none', 'No sidebar'), ('sections', 'H2 headings'), ('contents-two-levels', 'H2-H3 headings'), ('contents', 'H2-H4 headings'), ('pages', 'Pages')], default='sections', help_text="Select the sidebar style for this page. For more information, see the <a href='https://nationalarchives.github.io/design-system/components/sidebar/'>sidebar documentation</a>."),
        ),
    ]
