# Generated by Django 6.0.8 on 2026-09-14 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generic_pages', '0004_alter_generalpage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalpage',
            name='twitter_og_description',
        ),
        migrations.RemoveField(
            model_name='generalpage',
            name='twitter_og_image',
        ),
        migrations.RemoveField(
            model_name='generalpage',
            name='twitter_og_title',
        ),
        migrations.RemoveField(
            model_name='hubpage',
            name='twitter_og_description',
        ),
        migrations.RemoveField(
            model_name='hubpage',
            name='twitter_og_image',
        ),
        migrations.RemoveField(
            model_name='hubpage',
            name='twitter_og_title',
        ),
    ]
