# Generated by Django 5.0.2 on 2024-02-29 10:53

import app.core.blocks.paragraph
import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("generic_pages", "0008_make_page_uuid_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "paragraph",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "text",
                                    app.core.blocks.paragraph.APIRichTextBlock(
                                        features=["bold", "italic", "link", "ol", "ul"]
                                    ),
                                )
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
            ),
        ),
    ]
