# Generated by Django 5.0.6 on 2024-07-09 08:25

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("generic_pages", "0015_alter_generalpage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalpage",
            name="intro",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="1-2 sentences introducing the subject of the page, and explaining why a user should read on.",
                max_length=300,
                null=True,
                verbose_name="introductory text",
            ),
        ),
    ]
