# Generated by Django 5.0.7 on 2024-07-22 09:28

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generic_pages", "0024_alter_generalpage_body"),
        ("images", "0008_alter_customimagerendition_file"),
        ("wagtailcore", "0093_uploadedfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="hubpage",
            name="body",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="The main content of the page.",
                null=True,
                verbose_name="body",
            ),
        ),
        migrations.AddField(
            model_name="hubpage",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
            ),
        ),
        migrations.AddField(
            model_name="hubpage",
            name="hero_image_caption",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="An optional caption for hero images. This could be used for image sources or for other useful metadata.",
                verbose_name="hero image caption (optional)",
            ),
        ),
        migrations.AddField(
            model_name="hubpage",
            name="intro",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="1-2 sentences introducing the subject of the page, and explaining why a user should read on.",
                max_length=300,
                null=True,
                verbose_name="introductory text",
            ),
        ),
        migrations.CreateModel(
            name="LinkItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("url", models.URLField(blank=True, null=True, verbose_name="URL")),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
                (
                    "internal_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="generic_pages.hubpage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
