# Generated by Django 5.0.8 on 2024-10-22 10:10
# etna:allowRemoveField

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("generic_pages", "0037_alter_generalpage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generalpage",
            name="uuid",
        ),
        migrations.RemoveField(
            model_name="hubpage",
            name="uuid",
        ),
    ]
