# Generated by Django 6.0.3 on 2026-04-09 12:20
# etna:allowAlterField

import app.ciim.blocks
import django.core.validators
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("generic_pages", "0055_alter_generalpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("accordions", 10),
                    ("button", 15),
                    ("call_to_action", 17),
                    ("code", 22),
                    ("contact", 29),
                    ("description_list", 33),
                    ("details", 34),
                    ("document", 6),
                    ("do_dont_list", 41),
                    ("featured_external_link", 47),
                    ("featured_page", 50),
                    ("image", 53),
                    ("image_gallery", 55),
                    ("inset_text", 57),
                    ("media", 61),
                    ("paragraph", 57),
                    ("partner_logos", 65),
                    ("people_listing", 67),
                    ("quote", 74),
                    ("record_links", 76),
                    ("table", 78),
                    ("warning_text", 79),
                    ("youtube_video", 85),
                    ("content_section", 92),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    1: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "code", "ol", "ul"],
                            "required": True,
                        },
                    ),
                    2: ("wagtail.contrib.table_block.blocks.TableBlock", (), {}),
                    3: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": True},
                    ),
                    4: ("wagtail.blocks.StructBlock", [[("file", 3)]], {}),
                    5: ("wagtail.blocks.ListBlock", (4,), {"min_num": 1}),
                    6: ("wagtail.blocks.StructBlock", [[("documents", 5)]], {}),
                    7: (
                        "wagtail.blocks.StreamBlock",
                        [[("text", 1), ("table", 2), ("documents", 6)]],
                        {},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("body", 7)]],
                        {},
                    ),
                    9: ("wagtail.blocks.ListBlock", (8,), {}),
                    10: ("wagtail.blocks.StructBlock", [[("items", 9)]], {}),
                    11: ("wagtail.blocks.CharBlock", (), {}),
                    12: (
                        "app.core.blocks.page_chooser.APIPageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    13: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    14: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "Use the accented button style",
                            "label": "Accented",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 11),
                                ("link", 12),
                                ("external_link", 13),
                                ("accented", 14),
                            ]
                        ],
                        {},
                    ),
                    16: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "code", "ol", "ul"],
                            "max_length": 100,
                        },
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("body", 16), ("button", 15)]],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Display a filename with the extension e.g. example.html",
                            "label": "Code block title",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("html", "HTML"),
                                ("javascript", "JavaScript"),
                                ("python", "Python"),
                                ("xml", "XML"),
                                ("json", "JSON"),
                                ("bash", "Bash"),
                                ("git", "git"),
                                ("markdown", "Markdown"),
                                ("graphql", "GraphQL"),
                                ("powershell", "PowerShell"),
                                ("yaml", "YAML"),
                            ],
                            "label": "Code language",
                            "required": False,
                        },
                    ),
                    20: ("wagtail.blocks.TextBlock", (), {"max_length": 500}),
                    21: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Allow copy to clipboard",
                            "required": False,
                        },
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("filename", 18),
                                ("language", 19),
                                ("code", 20),
                                ("allow_copying", 21),
                            ]
                        ],
                        {},
                    ),
                    23: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"features": ["link"], "required": False},
                    ),
                    24: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "code"],
                            "required": False,
                        },
                    ),
                    25: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    26: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"required": False},
                    ),
                    27: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    28: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "code"],
                            "required": False,
                        },
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 11),
                                ("body", 23),
                                ("address", 24),
                                ("telephone", 25),
                                ("chat_link", 13),
                                ("chat_note", 26),
                                ("email", 27),
                                ("website_link", 13),
                                ("social_media", 28),
                            ]
                        ],
                        {},
                    ),
                    30: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link", "code"]},
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [[("term", 0), ("detail", 30)]],
                        {},
                    ),
                    32: ("wagtail.blocks.ListBlock", (31,), {}),
                    33: ("wagtail.blocks.StructBlock", [[("items", 32)]], {}),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("body", 1)]],
                        {},
                    ),
                    35: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": 'Custom do heading (defaults to "Do")',
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 30)]],
                        {"icon": "check", "label": "Do item"},
                    ),
                    37: ("wagtail.blocks.ListBlock", (36,), {"label": "Dos"}),
                    38: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Custom don't heading (defaults to \"Don't\")",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    39: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 30)]],
                        {"icon": "cross", "label": "Don't item"},
                    ),
                    40: ("wagtail.blocks.ListBlock", (39,), {"label": "Don'ts"}),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("do_heading", 35),
                                ("do", 37),
                                ("dont_heading", 38),
                                ("dont", 40),
                            ]
                        ],
                        {},
                    ),
                    42: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Supertitle", "max_length": 20, "required": False},
                    ),
                    43: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Title", "max_length": 100},
                    ),
                    44: ("wagtail.blocks.CharBlock", (), {"label": "Description"}),
                    45: ("wagtail.blocks.URLBlock", (), {"label": "URL"}),
                    46: (
                        "app.core.blocks.image.APIImageChooserBlock",
                        (),
                        {"label": "Image", "required": False},
                    ),
                    47: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("supertitle", 42),
                                ("title", 43),
                                ("description", 44),
                                ("url", 45),
                                ("image", 46),
                            ]
                        ],
                        {},
                    ),
                    48: (
                        "app.core.blocks.page_chooser.APIPageChooserBlock",
                        (),
                        {
                            "label": "Page",
                            "page_type": ["wagtailcore.Page"],
                            "required": True,
                        },
                    ),
                    49: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional override for the teaser text",
                            "label": "Teaser text override",
                            "required": False,
                        },
                    ),
                    50: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 48), ("teaser_text", 49)]],
                        {},
                    ),
                    51: (
                        "app.core.blocks.image.APIImageChooserBlock",
                        (),
                        {"rendition_size": "max-900x900", "required": True},
                    ),
                    52: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "If provided, displays directly below the image. Can be used to specify sources, transcripts or other useful metadata.",
                            "label": "Caption (optional)",
                            "required": False,
                        },
                    ),
                    53: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 51), ("caption", 52)]],
                        {},
                    ),
                    54: ("wagtail.blocks.ListBlock", (53,), {}),
                    55: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 25), ("description", 28), ("images", 54)]],
                        {},
                    ),
                    56: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link", "code", "ol", "ul"]},
                    ),
                    57: ("wagtail.blocks.StructBlock", [[("text", 56)]], {}),
                    58: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "A descriptive title for the media block",
                            "required": True,
                        },
                    ),
                    59: (
                        "app.core.blocks.image.APIImageChooserBlock",
                        (),
                        {
                            "help_text": "A thumbnail image for the media block",
                            "rendition_size": "fill-960x540",
                            "required": False,
                        },
                    ),
                    60: ("app.media.blocks.MediaChooserBlock", (), {}),
                    61: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 58), ("thumbnail", 59), ("media", 60)]],
                        {},
                    ),
                    62: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional override for the partner logos section lead text. Will display a default if not provided.",
                            "max_length": 40,
                            "required": False,
                        },
                    ),
                    63: ("app.core.blocks.image.PartnerLogoChooserBlock", (), {}),
                    64: (
                        "wagtail.blocks.ListBlock",
                        (63,),
                        {"max_num": 4, "required": True},
                    ),
                    65: (
                        "wagtail.blocks.StructBlock",
                        [[("lead_text", 62), ("logos", 64)]],
                        {},
                    ),
                    66: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("people.PersonRole",),
                        {
                            "help_text": "Select a role to filter people by their roles.",
                            "label": "Role selection",
                        },
                    ),
                    67: ("wagtail.blocks.StructBlock", [[("role", 66)]], {}),
                    68: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The name of the person being quoted. e.g. King Edward VIII",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    69: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The title of the work or document from which the quote is taken. e.g. Instrument of Abdication, 10 December 1936. Catalogue reference: PC 11/1",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    70: (
                        "app.core.blocks.page_chooser.APIPageChooserBlock",
                        (),
                        {
                            "help_text": "Reference another page published on the site",
                            "label": "Internal page",
                            "required": False,
                        },
                    ),
                    71: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Add a URL here to refer to an external source",
                            "label": "External link",
                            "required": False,
                        },
                    ),
                    72: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("citation_internal_link", 70),
                                ("citation_external_link", 71),
                            ]
                        ],
                        {},
                    ),
                    73: (
                        "wagtail.blocks.StructBlock",
                        [[("attribution", 68), ("citation", 69), ("source_link", 72)]],
                        {},
                    ),
                    74: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 1), ("source", 73)]],
                        {},
                    ),
                    75: (
                        "wagtail.blocks.ListBlock",
                        (app.ciim.blocks.RecordLinkBlock,),
                        {"label": "Items"},
                    ),
                    76: ("wagtail.blocks.StructBlock", [[("items", 75)]], {}),
                    77: (
                        "wagtail.contrib.table_block.blocks.TableBlock",
                        (),
                        {
                            "table_options": {
                                "contextMenu": [
                                    "row_above",
                                    "row_below",
                                    "---------",
                                    "col_left",
                                    "col_right",
                                    "---------",
                                    "remove_row",
                                    "remove_col",
                                    "---------",
                                    "undo",
                                    "redo",
                                    "---------",
                                    "alignment",
                                ]
                            }
                        },
                    ),
                    78: ("wagtail.blocks.StructBlock", [[("table", 77)]], {}),
                    79: ("wagtail.blocks.StructBlock", [[("body", 56)]], {}),
                    80: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Title", "max_length": 100, "required": True},
                    ),
                    81: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "YouTube Video ID",
                            "max_length": 11,
                            "required": True,
                            "validators": [
                                django.core.validators.RegexValidator(
                                    message="Invalid YouTube Video ID",
                                    regex="^[a-zA-Z0-9_-]{11}$",
                                )
                            ],
                        },
                    ),
                    82: (
                        "app.core.blocks.image.APIImageChooserBlock",
                        (),
                        {
                            "label": "Preview Image",
                            "rendition_size": "fill-640x360",
                            "required": True,
                        },
                    ),
                    83: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Transcript", "required": False},
                    ),
                    84: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "Tick if the video has captions on YouTube",
                            "label": "Captions available",
                            "required": False,
                        },
                    ),
                    85: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 80),
                                ("video_id", 81),
                                ("preview_image", 82),
                                ("transcript", 83),
                                ("captions_available", 84),
                            ]
                        ],
                        {},
                    ),
                    86: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Heading", "max_length": 100},
                    ),
                    87: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Sub-heading", "max_length": 100},
                    ),
                    88: ("wagtail.blocks.StructBlock", [[("heading", 87)]], {}),
                    89: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Sub-sub-heading", "max_length": 100},
                    ),
                    90: ("wagtail.blocks.StructBlock", [[("heading", 89)]], {}),
                    91: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("accordions", 10),
                                ("button", 15),
                                ("call_to_action", 17),
                                ("code", 22),
                                ("contact", 29),
                                ("description_list", 33),
                                ("details", 34),
                                ("document", 6),
                                ("do_dont_list", 41),
                                ("featured_external_link", 47),
                                ("featured_page", 50),
                                ("image", 53),
                                ("image_gallery", 55),
                                ("inset_text", 57),
                                ("media", 61),
                                ("paragraph", 57),
                                ("partner_logos", 65),
                                ("people_listing", 67),
                                ("quote", 74),
                                ("record_links", 76),
                                ("sub_heading", 88),
                                ("sub_sub_heading", 90),
                                ("table", 78),
                                ("warning_text", 79),
                                ("youtube_video", 85),
                            ]
                        ],
                        {"required": False},
                    ),
                    92: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 86), ("content", 91)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
