# Generated by Django 6.0.3 on 2026-04-09 08:51
# etna:allowAlterField

import app.ciim.blocks
import django.core.validators
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("generic_pages", "0055_alter_generalpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("accordions", 10),
                    ("button", 15),
                    ("call_to_action", 18),
                    ("code", 23),
                    ("contact", 30),
                    ("description_list", 34),
                    ("details", 35),
                    ("document", 36),
                    ("do_dont_list", 43),
                    ("featured_external_link", 49),
                    ("featured_page", 52),
                    ("image", 55),
                    ("image_gallery", 58),
                    ("inset_text", 60),
                    ("media", 64),
                    ("paragraph", 65),
                    ("partner_logos", 69),
                    ("people_listing", 71),
                    ("quote", 73),
                    ("record_links", 75),
                    ("table", 77),
                    ("warning_text", 78),
                    ("youtube_video", 84),
                    ("content_section", 91),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    1: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "code", "ol", "ul"],
                            "required": True,
                        },
                    ),
                    2: ("wagtail.contrib.table_block.blocks.TableBlock", (), {}),
                    3: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": True},
                    ),
                    4: ("wagtail.blocks.StructBlock", [[("file", 3)]], {}),
                    5: ("wagtail.blocks.ListBlock", (4,), {"min_num": 1}),
                    6: ("wagtail.blocks.StructBlock", [[("documents", 5)]], {}),
                    7: (
                        "wagtail.blocks.StreamBlock",
                        [[("text", 1), ("table", 2), ("documents", 6)]],
                        {},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("body", 7)]],
                        {},
                    ),
                    9: ("wagtail.blocks.ListBlock", (8,), {}),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("items", 9)]],
                        {"group": "Structured and collapsible content"},
                    ),
                    11: ("wagtail.blocks.CharBlock", (), {}),
                    12: (
                        "app.core.blocks.page_chooser.APIPageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    13: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    14: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "Use the accented button style",
                            "label": "Accented",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 11),
                                ("link", 12),
                                ("external_link", 13),
                                ("accented", 14),
                            ]
                        ],
                        {"group": "Onward journeys"},
                    ),
                    16: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "code", "ol", "ul"],
                            "max_length": 100,
                        },
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 11),
                                ("link", 12),
                                ("external_link", 13),
                                ("accented", 14),
                            ]
                        ],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("body", 16), ("button", 17)]],
                        {"group": "Onward journeys"},
                    ),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Display a filename with the extension e.g. example.html",
                            "label": "Code block title",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("html", "HTML"),
                                ("javascript", "JavaScript"),
                                ("python", "Python"),
                                ("xml", "XML"),
                                ("json", "JSON"),
                                ("bash", "Bash"),
                                ("git", "git"),
                                ("markdown", "Markdown"),
                                ("graphql", "GraphQL"),
                                ("powershell", "PowerShell"),
                                ("yaml", "YAML"),
                            ],
                            "label": "Code language",
                            "required": False,
                        },
                    ),
                    21: ("wagtail.blocks.TextBlock", (), {"max_length": 500}),
                    22: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Allow copy to clipboard",
                            "required": False,
                        },
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("filename", 19),
                                ("language", 20),
                                ("code", 21),
                                ("allow_copying", 22),
                            ]
                        ],
                        {"group": "Structured and collapsible content"},
                    ),
                    24: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"features": ["link"], "required": False},
                    ),
                    25: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "code"],
                            "required": False,
                        },
                    ),
                    26: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    27: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"required": False},
                    ),
                    28: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    29: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "code"],
                            "required": False,
                        },
                    ),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 11),
                                ("body", 24),
                                ("address", 25),
                                ("telephone", 26),
                                ("chat_link", 13),
                                ("chat_note", 27),
                                ("email", 28),
                                ("website_link", 13),
                                ("social_media", 29),
                            ]
                        ],
                        {"group": "Onward journeys"},
                    ),
                    31: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link", "code"]},
                    ),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [[("term", 0), ("detail", 31)]],
                        {},
                    ),
                    33: ("wagtail.blocks.ListBlock", (32,), {}),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [[("items", 33)]],
                        {"group": "Structured and collapsible content"},
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("body", 1)]],
                        {"group": "Structured and collapsible content"},
                    ),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [[("documents", 5)]],
                        {"group": "Video, audio and downloads"},
                    ),
                    37: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": 'Custom do heading (defaults to "Do")',
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    38: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 31)]],
                        {"icon": "check", "label": "Do item"},
                    ),
                    39: ("wagtail.blocks.ListBlock", (38,), {"label": "Dos"}),
                    40: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Custom don't heading (defaults to \"Don't\")",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 31)]],
                        {"icon": "cross", "label": "Don't item"},
                    ),
                    42: ("wagtail.blocks.ListBlock", (41,), {"label": "Don'ts"}),
                    43: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("do_heading", 37),
                                ("do", 39),
                                ("dont_heading", 40),
                                ("dont", 42),
                            ]
                        ],
                        {"group": "Emphasis"},
                    ),
                    44: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Supertitle", "max_length": 20, "required": False},
                    ),
                    45: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Title", "max_length": 100},
                    ),
                    46: ("wagtail.blocks.CharBlock", (), {"label": "Description"}),
                    47: ("wagtail.blocks.URLBlock", (), {"label": "URL"}),
                    48: (
                        "app.core.blocks.image.APIImageChooserBlock",
                        (),
                        {"label": "Image", "required": False},
                    ),
                    49: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("supertitle", 44),
                                ("title", 45),
                                ("description", 46),
                                ("url", 47),
                                ("image", 48),
                            ]
                        ],
                        {"group": "Onward journeys"},
                    ),
                    50: (
                        "app.core.blocks.page_chooser.APIPageChooserBlock",
                        (),
                        {
                            "label": "Page",
                            "page_type": ["wagtailcore.Page"],
                            "required": True,
                        },
                    ),
                    51: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional override for the teaser text",
                            "label": "Teaser text override",
                            "required": False,
                        },
                    ),
                    52: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 50), ("teaser_text", 51)]],
                        {"group": "Onward journeys"},
                    ),
                    53: (
                        "app.core.blocks.image.APIImageChooserBlock",
                        (),
                        {"rendition_size": "max-900x900", "required": True},
                    ),
                    54: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "If provided, displays directly below the image. Can be used to specify sources, transcripts or other useful metadata.",
                            "label": "Caption (optional)",
                            "required": False,
                        },
                    ),
                    55: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 53), ("caption", 54)]],
                        {"group": "Images"},
                    ),
                    56: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 53), ("caption", 54)]],
                        {},
                    ),
                    57: ("wagtail.blocks.ListBlock", (56,), {}),
                    58: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 26), ("description", 29), ("images", 57)]],
                        {"group": "Images"},
                    ),
                    59: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link", "code", "ol", "ul"]},
                    ),
                    60: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 59)]],
                        {"group": "Emphasis"},
                    ),
                    61: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "A descriptive title for the media block",
                            "required": True,
                        },
                    ),
                    62: (
                        "app.core.blocks.image.APIImageChooserBlock",
                        (),
                        {
                            "help_text": "A thumbnail image for the media block",
                            "rendition_size": "fill-960x540",
                            "required": False,
                        },
                    ),
                    63: ("app.media.blocks.MediaChooserBlock", (), {}),
                    64: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 61), ("thumbnail", 62), ("media", 63)]],
                        {"group": "Video, audio and downloads"},
                    ),
                    65: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 59)]],
                        {"group": "Basic text"},
                    ),
                    66: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional override for the partner logos section lead text. Will display a default if not provided.",
                            "max_length": 40,
                            "required": False,
                        },
                    ),
                    67: ("app.core.blocks.image.PartnerLogoChooserBlock", (), {}),
                    68: (
                        "wagtail.blocks.ListBlock",
                        (67,),
                        {"max_num": 4, "required": True},
                    ),
                    69: (
                        "wagtail.blocks.StructBlock",
                        [[("lead_text", 66), ("logos", 68)]],
                        {"group": "Images"},
                    ),
                    70: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("people.PersonRole",),
                        {
                            "help_text": "Select a role to filter people by their roles.",
                            "label": "Role selection",
                        },
                    ),
                    71: (
                        "wagtail.blocks.StructBlock",
                        [[("role", 70)]],
                        {"group": "Onward journeys"},
                    ),
                    72: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 100, "required": False},
                    ),
                    73: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 1), ("attribution", 72)]],
                        {"group": "Basic text"},
                    ),
                    74: (
                        "wagtail.blocks.ListBlock",
                        (app.ciim.blocks.RecordLinkBlock,),
                        {"label": "Items"},
                    ),
                    75: (
                        "wagtail.blocks.StructBlock",
                        [[("items", 74)]],
                        {"group": "Onward journeys"},
                    ),
                    76: (
                        "wagtail.contrib.table_block.blocks.TableBlock",
                        (),
                        {
                            "table_options": {
                                "contextMenu": [
                                    "row_above",
                                    "row_below",
                                    "---------",
                                    "col_left",
                                    "col_right",
                                    "---------",
                                    "remove_row",
                                    "remove_col",
                                    "---------",
                                    "undo",
                                    "redo",
                                    "---------",
                                    "alignment",
                                ]
                            }
                        },
                    ),
                    77: (
                        "wagtail.blocks.StructBlock",
                        [[("table", 76)]],
                        {"group": "Structured and collapsible content"},
                    ),
                    78: (
                        "wagtail.blocks.StructBlock",
                        [[("body", 59)]],
                        {"group": "Emphasis"},
                    ),
                    79: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Title", "max_length": 100, "required": True},
                    ),
                    80: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "YouTube Video ID",
                            "max_length": 11,
                            "required": True,
                            "validators": [
                                django.core.validators.RegexValidator(
                                    message="Invalid YouTube Video ID",
                                    regex="^[a-zA-Z0-9_-]{11}$",
                                )
                            ],
                        },
                    ),
                    81: (
                        "app.core.blocks.image.APIImageChooserBlock",
                        (),
                        {
                            "label": "Preview Image",
                            "rendition_size": "fill-640x360",
                            "required": True,
                        },
                    ),
                    82: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Transcript", "required": False},
                    ),
                    83: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "Tick if the video has captions on YouTube",
                            "label": "Captions available",
                            "required": False,
                        },
                    ),
                    84: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 79),
                                ("video_id", 80),
                                ("preview_image", 81),
                                ("transcript", 82),
                                ("captions_available", 83),
                            ]
                        ],
                        {"group": "Video, audio and downloads"},
                    ),
                    85: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Heading", "max_length": 100},
                    ),
                    86: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Sub-heading", "max_length": 100},
                    ),
                    87: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 86)]],
                        {"group": "Basic text"},
                    ),
                    88: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Sub-sub-heading", "max_length": 100},
                    ),
                    89: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 88)]],
                        {"group": "Basic text"},
                    ),
                    90: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("accordions", 10),
                                ("button", 15),
                                ("call_to_action", 18),
                                ("code", 23),
                                ("contact", 30),
                                ("description_list", 34),
                                ("details", 35),
                                ("document", 36),
                                ("do_dont_list", 43),
                                ("featured_external_link", 49),
                                ("featured_page", 52),
                                ("image", 55),
                                ("image_gallery", 58),
                                ("inset_text", 60),
                                ("media", 64),
                                ("paragraph", 65),
                                ("partner_logos", 69),
                                ("people_listing", 71),
                                ("quote", 73),
                                ("record_links", 75),
                                ("sub_heading", 87),
                                ("sub_sub_heading", 89),
                                ("table", 77),
                                ("warning_text", 78),
                                ("youtube_video", 84),
                            ]
                        ],
                        {"required": False},
                    ),
                    91: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 85), ("content", 90)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
