# Generated by Django 6.0.5 on 2026-06-02 12:49
# etna:allowAlterField

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic_pages', '0056_alter_generalpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkitem',
            name='supertitle',
            field=models.CharField(blank=True, help_text="Optional text, ONLY use to simplify autogenerated chips, eg 'nationalarchives.wd3.myworkdayjobs.com' to 'myworkdayjobs.com'", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='linkitem',
            name='url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='URL'),
        ),
    ]
