# Generated by Django 3.2.13 on 2022-06-03 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0001_create_beta_testers_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="IDPProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_name", models.CharField(db_index=True, max_length=100)),
                ("provider_user_id", models.CharField(db_index=True, max_length=36)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="idp_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="idpprofile",
            constraint=models.UniqueConstraint(
                fields=("provider_name", "provider_user_id"), name="idp_unique"
            ),
        ),
    ]
