# Generated by Django 3.2.13 on 2022-06-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idpprofile",
            name="provider_user_id",
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
