# Generated by Django 4.0.8 on 2023-02-03 13:02

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0003_customimage_add_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customimage",
            name="translation_language",
        ),
        migrations.AlterField(
            model_name="customimage",
            name="description",
            field=wagtail.fields.RichTextField(
                blank=True, max_length=300, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="customimage",
            name="transcription_language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Old English", "Old English"),
                    ("Middle English", "Middle English"),
                    ("Early Modern English", "Early Modern English"),
                    ("Modern English", "Modern English"),
                    ("Latin", "Latin"),
                ],
                max_length=20,
                verbose_name="transcription language",
            ),
        ),
        migrations.AlterField(
            model_name="customimage",
            name="translation",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="An optional English / Modern English translation of the transcription. This is only required if the original language is something other than Modern English.",
                max_length=1500,
                verbose_name="translation",
            ),
        ),
    ]
