# Generated by Django 5.2.4 on 2025-07-16 09:05
# etna:allowAlterField

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0012_customimage_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customimage',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='alt text'),
        ),
    ]
