# Generated by Django 6.0.6 on 2026-06-24 10:34
# etna:allowAlterField
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0013_alter_customimage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customimage',
            name='transcription',
            field=wagtail.fields.RichTextField(blank=True, help_text='If the image contains text consider adding a transcript.', max_length=4500, verbose_name='transcript'),
        ),
        migrations.AlterField(
            model_name='customimage',
            name='translation',
            field=wagtail.fields.RichTextField(blank=True, help_text='An optional English / Modern English translation of the transcription.', max_length=4500, verbose_name='translation'),
        ),
    ]
