# Generated by Django 3.1.8 on 2021-08-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0008_add_hierarchy"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordpage",
            name="media_reference_id",
            field=models.UUIDField(null=True),
        ),
    ]
