# Generated by Django 3.1.8 on 2021-08-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_add_media_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordpage',
            name='availablility_access_closure_label',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recordpage',
            name='availablility_access_display_label',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recordpage',
            name='availablility_delivery_condition',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recordpage',
            name='availablility_delivery_surrogates',
            field=models.JSONField(null=True),
        ),
    ]
