# Generated by Django 3.1.8 on 2021-08-09 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_add_availability_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recordpage',
            old_name='date_range',
            new_name='origination_date',
        ),
        migrations.RemoveField(
            model_name='recordpage',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='recordpage',
            name='date_start',
        ),
    ]
