# Generated by Django 3.1.8 on 2021-08-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0012_add_topics"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordpage",
            name="next_record",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="recordpage",
            name="previous_record",
            field=models.JSONField(null=True),
        ),
    ]
