# Generated by Django 3.1.8 on 2021-08-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0013_add_next_previous_record"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordpage",
            name="related_articles",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="recordpage",
            name="related_records",
            field=models.JSONField(null=True),
        ),
    ]
