# Generated by Django 6.0.2 on 2026-03-27 14:17
# etna:allowAlterField

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foirequestpage",
            name="annexe",
            field=wagtail.fields.StreamField(
                [
                    ("content_section", 19),
                    ("paragraph", 4),
                    ("description_list", 9),
                    ("table", 11),
                    ("details", 13),
                    ("document", 17),
                    ("inset_text", 4),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Heading", "max_length": 100},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Sub-heading", "max_length": 100},
                    ),
                    2: ("wagtail.blocks.StructBlock", [[("heading", 1)]], {}),
                    3: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link", "code", "ol", "ul"]},
                    ),
                    4: ("wagtail.blocks.StructBlock", [[("text", 3)]], {}),
                    5: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    6: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link", "code"]},
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("term", 5), ("detail", 6)]],
                        {},
                    ),
                    8: ("wagtail.blocks.ListBlock", (7,), {}),
                    9: ("wagtail.blocks.StructBlock", [[("items", 8)]], {}),
                    10: (
                        "wagtail.contrib.table_block.blocks.TableBlock",
                        (),
                        {
                            "table_options": {
                                "contextMenu": [
                                    "row_above",
                                    "row_below",
                                    "---------",
                                    "col_left",
                                    "col_right",
                                    "---------",
                                    "remove_row",
                                    "remove_col",
                                    "---------",
                                    "undo",
                                    "redo",
                                    "---------",
                                    "alignment",
                                ]
                            }
                        },
                    ),
                    11: ("wagtail.blocks.StructBlock", [[("table", 10)]], {}),
                    12: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "code", "ol", "ul"],
                            "required": True,
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 5), ("body", 12)]],
                        {},
                    ),
                    14: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": True},
                    ),
                    15: ("wagtail.blocks.StructBlock", [[("file", 14)]], {}),
                    16: ("wagtail.blocks.ListBlock", (15,), {}),
                    17: ("wagtail.blocks.StructBlock", [[("documents", 16)]], {}),
                    18: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("sub_heading", 2),
                                ("paragraph", 4),
                                ("description_list", 9),
                                ("table", 11),
                                ("details", 13),
                                ("document", 17),
                                ("inset_text", 4),
                            ]
                        ],
                        {"required": False},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("content", 18)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="foirequestpage",
            name="request",
            field=wagtail.fields.StreamField(
                [
                    ("content_section", 19),
                    ("paragraph", 4),
                    ("description_list", 9),
                    ("table", 11),
                    ("details", 13),
                    ("document", 17),
                    ("inset_text", 4),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Heading", "max_length": 100},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Sub-heading", "max_length": 100},
                    ),
                    2: ("wagtail.blocks.StructBlock", [[("heading", 1)]], {}),
                    3: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link", "code", "ol", "ul"]},
                    ),
                    4: ("wagtail.blocks.StructBlock", [[("text", 3)]], {}),
                    5: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    6: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link", "code"]},
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("term", 5), ("detail", 6)]],
                        {},
                    ),
                    8: ("wagtail.blocks.ListBlock", (7,), {}),
                    9: ("wagtail.blocks.StructBlock", [[("items", 8)]], {}),
                    10: (
                        "wagtail.contrib.table_block.blocks.TableBlock",
                        (),
                        {
                            "table_options": {
                                "contextMenu": [
                                    "row_above",
                                    "row_below",
                                    "---------",
                                    "col_left",
                                    "col_right",
                                    "---------",
                                    "remove_row",
                                    "remove_col",
                                    "---------",
                                    "undo",
                                    "redo",
                                    "---------",
                                    "alignment",
                                ]
                            }
                        },
                    ),
                    11: ("wagtail.blocks.StructBlock", [[("table", 10)]], {}),
                    12: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "code", "ol", "ul"],
                            "required": True,
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 5), ("body", 12)]],
                        {},
                    ),
                    14: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": True},
                    ),
                    15: ("wagtail.blocks.StructBlock", [[("file", 14)]], {}),
                    16: ("wagtail.blocks.ListBlock", (15,), {}),
                    17: ("wagtail.blocks.StructBlock", [[("documents", 16)]], {}),
                    18: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("sub_heading", 2),
                                ("paragraph", 4),
                                ("description_list", 9),
                                ("table", 11),
                                ("details", 13),
                                ("document", 17),
                                ("inset_text", 4),
                            ]
                        ],
                        {"required": False},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("content", 18)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="foirequestpage",
            name="response",
            field=wagtail.fields.StreamField(
                [
                    ("content_section", 19),
                    ("paragraph", 4),
                    ("description_list", 9),
                    ("table", 11),
                    ("details", 13),
                    ("document", 17),
                    ("inset_text", 4),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Heading", "max_length": 100},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Sub-heading", "max_length": 100},
                    ),
                    2: ("wagtail.blocks.StructBlock", [[("heading", 1)]], {}),
                    3: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link", "code", "ol", "ul"]},
                    ),
                    4: ("wagtail.blocks.StructBlock", [[("text", 3)]], {}),
                    5: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    6: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link", "code"]},
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("term", 5), ("detail", 6)]],
                        {},
                    ),
                    8: ("wagtail.blocks.ListBlock", (7,), {}),
                    9: ("wagtail.blocks.StructBlock", [[("items", 8)]], {}),
                    10: (
                        "wagtail.contrib.table_block.blocks.TableBlock",
                        (),
                        {
                            "table_options": {
                                "contextMenu": [
                                    "row_above",
                                    "row_below",
                                    "---------",
                                    "col_left",
                                    "col_right",
                                    "---------",
                                    "remove_row",
                                    "remove_col",
                                    "---------",
                                    "undo",
                                    "redo",
                                    "---------",
                                    "alignment",
                                ]
                            }
                        },
                    ),
                    11: ("wagtail.blocks.StructBlock", [[("table", 10)]], {}),
                    12: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "code", "ol", "ul"],
                            "required": True,
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 5), ("body", 12)]],
                        {},
                    ),
                    14: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": True},
                    ),
                    15: ("wagtail.blocks.StructBlock", [[("file", 14)]], {}),
                    16: ("wagtail.blocks.ListBlock", (15,), {}),
                    17: ("wagtail.blocks.StructBlock", [[("documents", 16)]], {}),
                    18: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("sub_heading", 2),
                                ("paragraph", 4),
                                ("description_list", 9),
                                ("table", 11),
                                ("details", 13),
                                ("document", 17),
                                ("inset_text", 4),
                            ]
                        ],
                        {"required": False},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("content", 18)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
