# Generated by Django 6.0.8 on 2026-09-14 11:31
# etna:allowRemoveField

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foi', '0003_alter_foirequestpage_annexe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foiindexpage',
            name='twitter_og_description',
        ),
        migrations.RemoveField(
            model_name='foiindexpage',
            name='twitter_og_image',
        ),
        migrations.RemoveField(
            model_name='foiindexpage',
            name='twitter_og_title',
        ),
        migrations.RemoveField(
            model_name='foirequestpage',
            name='twitter_og_description',
        ),
        migrations.RemoveField(
            model_name='foirequestpage',
            name='twitter_og_image',
        ),
        migrations.RemoveField(
            model_name='foirequestpage',
            name='twitter_og_title',
        ),
    ]
