# Generated by Django 6.0.7 on 2026-07-30 13:11

import django.db.models.deletion
import modelsearch.index
import taggit.managers
import wagtail.fields
import wagtail.models.media
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_name', models.CharField(max_length=255, verbose_name='Space name')),
                ('at_tna', models.BooleanField(default=False, help_text='Check if this venue is at The National Archives.', verbose_name='at The National Archives')),
                ('online', models.BooleanField(default=False, help_text='Check if this is an online venue.', verbose_name='online venue')),
                ('address_line_1', models.CharField(blank=True, help_text='First line of address for the location, if applicable.', max_length=255, null=True, verbose_name='first line of address')),
                ('address_line_2', models.CharField(blank=True, help_text='Second line of address for the location, if applicable.', max_length=255, null=True, verbose_name='second line of address')),
                ('postcode', models.CharField(blank=True, help_text='Postcode for the location, if applicable.', max_length=20, null=True, verbose_name='postcode')),
                ('online_detail', models.CharField(blank=True, help_text='Additional detail for online venues, if applicable.', max_length=255, null=True, verbose_name='online detail')),
                ('details_title', models.CharField(blank=True, help_text="Leave blank to default to 'Plan your visit'.", max_length=100)),
                ('details', wagtail.fields.StreamField([('details', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link', 'code', 'ol', 'ul'], 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('body', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {})})),
                ('venue_link', models.URLField(blank=True, help_text="A link to the venue's website or visit us page.", null=True, verbose_name='Venue link')),
                ('venue_link_text', models.CharField(blank=True, help_text='Text to display for the venue link, if applicable.', max_length=50, null=True, verbose_name='Venue link text')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='PartnerLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CustomDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents', verbose_name='file')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('file_size', models.PositiveBigIntegerField(editable=False, null=True)),
                ('file_hash', models.CharField(blank=True, editable=False, max_length=40)),
                ('title', models.CharField(help_text='The name of the document as it will appear on the webpage. Please format this in sentence case with spaces between the words. e.g. Preservation policy part one.', max_length=255, verbose_name='title')),
                ('extent', models.CharField(blank=True, help_text="The volume of the file so that users understand how much there is to consume. E.g. '3 pages' or '120 images'.", null=True)),
                ('description', models.TextField(blank=True, help_text='A short summary of what the document contains to help users understand what they are downloading.', null=True)),
                ('collection', models.ForeignKey(default=wagtail.models.media.get_root_collection_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.collection', verbose_name='collection')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text=None, through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tags')),
                ('uploaded_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='uploaded by user')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'abstract': False,
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
    ]
