# Generated by Django 5.1.7 on 2025-03-25 14:38
# etna:allowRemoveField
# etna:allowDeleteModel

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_customdocument_file_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='site',
        ),
        migrations.DeleteModel(
            name='MainMenuItem',
        ),
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
