# Generated by Django 5.2.4 on 2025-08-21 11:35

import app.core.models.partner_logos
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_location_venue_link_location_venue_link_text'),
        ('images', '0013_alter_customimage_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('svg_file', models.FileField(blank=True, help_text='Upload the SVG file for the partner logo.', null=True, upload_to='partner_logos/', validators=[app.core.models.partner_logos.validate_svg_file], verbose_name='SVG File')),
                ('svg_file_dark', models.FileField(blank=True, help_text='Upload the dark mode SVG file for the partner logo.', null=True, upload_to='partner_logos/', validators=[app.core.models.partner_logos.validate_svg_file], verbose_name='SVG File (Dark Mode)')),
                ('alt_text', models.CharField(max_length=255)),
                ('raster_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
                ('raster_file_dark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
            ],
        ),
    ]
