# Generated by Django 5.2.4 on 2025-08-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_location_venue_link_location_venue_link_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('svg_code', models.TextField()),
                ('alt_text', models.CharField(max_length=255)),
            ],
        ),
    ]
