# Generated by Django 6.0.2 on 2026-03-27 14:17
# etna:allowAlterField

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_partnerlogo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="details",
            field=wagtail.fields.StreamField(
                [("details", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    1: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "code", "ol", "ul"],
                            "required": True,
                        },
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("body", 1)]],
                        {},
                    ),
                    3: ("wagtail.blocks.ListBlock", (2,), {}),
                },
            ),
        ),
    ]
