# Each route describes how an incoming URL is going to be processed by Platform.sh.

"https://{default}/":
  type: upstream
  upstream: "app:http"
  cache:
    enabled: true
    default_ttl: 300
    cookies:
      - sessionid
      - csrftoken
      - messages
      - csrftoken
      - cookies_policy
      - dontShowCookieNotice
    headers:
      - Accept
      - Vary

# Redirect www routes to preseve links to old plaform.sh domain
"https://www.{default}/":
  type: redirect
  to: "https://{default}/"
