# Generated by Django 5.0.8 on 2024-08-15 14:54

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0008_personpage_first_name_personpage_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="personpage",
            name="research_summary",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
