# Generated by Django 5.0.9 on 2024-09-03 15:10

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0012_shopitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personpage",
            name="research_summary",
            field=wagtail.fields.StreamField(
                [("inset_text", 1), ("paragraph", 1), ("content_section", 4)],
                blank=True,
                block_lookup={
                    0: (
                        "etna.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "link",
                                "footnotes",
                                "ol",
                                "ul",
                            ]
                        },
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("text", 0)]], {}),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Heading", "max_length": 100},
                    ),
                    3: (
                        "wagtail.blocks.StreamBlock",
                        [[("inset_text", 1), ("paragraph", 1)]],
                        {"required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 2), ("content", 3)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
