# Generated by Django 5.0.8 on 2024-10-22 10:10
# etna:allowRemoveField

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0012_shopitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="peopleindexpage",
            name="uuid",
        ),
        migrations.RemoveField(
            model_name="personpage",
            name="uuid",
        ),
    ]
