# Generated by Django 4.2.7 on 2024-01-10 15:58

from django.db import migrations
import etna.core.blocks.paragraph
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("generic_pages", "0008_make_page_uuid_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "paragraph",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "text",
                                    etna.core.blocks.paragraph.APIRichTextBlock(
                                        features=[
                                            "bold",
                                            "italic",
                                            "link",
                                            "ol",
                                            "ul",
                                        ]
                                    ),
                                )
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
