# Generated by Django 5.0.7 on 2024-07-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generic_pages", "0027_alter_generalpage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalpage",
            name="page_sidebar",
            field=models.CharField(
                blank=True,
                choices=[
                    ("contents", "Contents"),
                    ("sections", "Sections"),
                    ("pages", "Pages"),
                ],
                help_text="Select the sidebar style for this page. For more information, see the <a href='https://nationalarchives.github.io/design-system/components/sidebar/'>sidebar documentation</a>.",
                null=True,
            ),
        ),
    ]
