# Generated by Django 5.0.7 on 2024-08-02 09:13
# etna:allowAlterField

import etna.ciim.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("generic_pages", "0029_alter_generalpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("accordions", 10),
                    ("button", 15),
                    ("call_to_action", 17),
                    ("contact", 23),
                    ("description_list", 27),
                    ("document", 6),
                    ("do_dont_list", 32),
                    ("featured_record_article", 34),
                    ("image", 38),
                    ("image_gallery", 40),
                    ("inset_text", 42),
                    ("media", 46),
                    ("paragraph", 42),
                    ("promoted_item", 58),
                    ("promoted_list", 65),
                    ("quote", 68),
                    ("record_links", 70),
                    ("table", 72),
                    ("warning_text", 73),
                    ("youtube_video", 77),
                    ("content_section", 84),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    1: (
                        "etna.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "ol", "ul"],
                            "required": True,
                        },
                    ),
                    2: ("wagtail.contrib.table_block.blocks.TableBlock", (), {}),
                    3: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": True},
                    ),
                    4: ("wagtail.blocks.StructBlock", [[("file", 3)]], {}),
                    5: ("wagtail.blocks.ListBlock", (4,), {}),
                    6: ("wagtail.blocks.StructBlock", [[("documents", 5)]], {}),
                    7: (
                        "wagtail.blocks.StreamBlock",
                        [[("text", 1), ("table", 2), ("documents", 6)]],
                        {},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("body", 7)]],
                        {},
                    ),
                    9: ("wagtail.blocks.ListBlock", (8,), {}),
                    10: ("wagtail.blocks.StructBlock", [[("items", 9)]], {}),
                    11: ("wagtail.blocks.CharBlock", (), {}),
                    12: (
                        "etna.core.blocks.page_chooser.APIPageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    13: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    14: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "Use the accented button style",
                            "label": "Accented",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 11),
                                ("link", 12),
                                ("external_link", 13),
                                ("accented", 14),
                            ]
                        ],
                        {},
                    ),
                    16: (
                        "etna.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "ol", "ul"],
                            "max_length": 100,
                        },
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("body", 16), ("button", 15)]],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"features": ["bold", "italic", "link"], "required": False},
                    ),
                    19: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    20: (
                        "etna.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"required": False},
                    ),
                    21: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    22: (
                        "etna.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link"], "required": False},
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 11),
                                ("address", 18),
                                ("telephone", 19),
                                ("chat_link", 13),
                                ("chat_note", 20),
                                ("email", 21),
                                ("website_link", 13),
                                ("social_media", 22),
                            ]
                        ],
                        {},
                    ),
                    24: (
                        "etna.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link"]},
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [[("term", 0), ("detail", 24)]],
                        {},
                    ),
                    26: ("wagtail.blocks.ListBlock", (25,), {}),
                    27: ("wagtail.blocks.StructBlock", [[("items", 26)]], {}),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 24)]],
                        {"icon": "check", "label": "Do item"},
                    ),
                    29: ("wagtail.blocks.ListBlock", (28,), {"label": "Dos"}),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 24)]],
                        {"icon": "cross", "label": "Don't item"},
                    ),
                    31: ("wagtail.blocks.ListBlock", (30,), {"label": "Don'ts"}),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [[("do", 29), ("dont", 31)]],
                        {},
                    ),
                    33: (
                        "etna.core.blocks.page_chooser.APIPageChooserBlock",
                        (),
                        {
                            "label": "Page",
                            "page_type": ["articles.RecordArticlePage"],
                            "required_api_fields": ["teaser_image"],
                        },
                    ),
                    34: ("wagtail.blocks.StructBlock", [[("page", 33)]], {}),
                    35: (
                        "etna.core.blocks.image.APIImageChooserBlock",
                        (),
                        {"rendition_size": "max-900x900", "required": True},
                    ),
                    36: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Alternative (alt) text describes images when they fail to load, and is read aloud by assistive technologies. Use a maximum of 100 characters to describe your image. <a href="https://html.spec.whatwg.org/multipage/images.html#alt" target="_blank">Check the guidance for tips on writing alt text</a>.',
                            "label": "Alternative text",
                            "max_length": 100,
                        },
                    ),
                    37: (
                        "etna.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "If provided, displays directly below the image. Can be used to specify sources, transcripts or other useful metadata.",
                            "label": "Caption (optional)",
                            "required": False,
                        },
                    ),
                    38: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 35), ("alt_text", 36), ("caption", 37)]],
                        {},
                    ),
                    39: ("wagtail.blocks.ListBlock", (38,), {}),
                    40: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 19), ("description", 22), ("images", 39)]],
                        {},
                    ),
                    41: (
                        "etna.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link", "ol", "ul"]},
                    ),
                    42: ("wagtail.blocks.StructBlock", [[("text", 41)]], {}),
                    43: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "A descriptive title for the media block",
                            "required": True,
                        },
                    ),
                    44: (
                        "etna.core.blocks.image.APIImageChooserBlock",
                        (),
                        {"help_text": "A background image for the media block"},
                    ),
                    45: ("etna.media.blocks.MediaChooserBlock", (), {}),
                    46: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 43), ("background_image", 44), ("media", 45)]],
                        {},
                    ),
                    47: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Title of the promoted page",
                            "label": "Title",
                            "max_length": 100,
                        },
                    ),
                    48: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("blog", "Blog post"),
                                ("podcast", "Podcast"),
                                ("video", "Video"),
                                ("video-external", "External video"),
                                ("external-link", "External link"),
                            ],
                            "label": "Category",
                        },
                    ),
                    49: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "This is a free text field. Please enter date as per agreed format: 14 April 2021",
                            "required": False,
                        },
                    ),
                    50: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Podcast or video duration.",
                            "label": "Duration",
                            "max_length": 50,
                            "required": False,
                        },
                    ),
                    51: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "URL for the external page",
                            "label": "External URL",
                        },
                    ),
                    52: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "label": "Should this URL open in a new tab? <p style='font-size: 11px;'>Tick the box if 'yes'</p>",
                            "required": False,
                        },
                    ),
                    53: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The text displayed on the button for your URL. If your URL links to an external site, please add the name of the site users will land on, and what they will find on this page. For example 'Watch our short film  <strong>about Shakespeare on YouTube</strong>'.",
                            "label": "Call to action label",
                            "max_length": 50,
                        },
                    ),
                    54: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": 'Decorative images are used for visual effect and do not add information to the content of a page. <a href="https://www.w3.org/WAI/tutorials/images/decorative/" target="_blank">"Check the guidance to see if your image is decorative</a>.',
                            "label": "Is this image decorative? <p class='field-title__subheading'>Tick the box if 'yes'</p>",
                            "required": False,
                        },
                    ),
                    55: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Alternative (alt) text describes images when they fail to load, and is read aloud by assistive technologies. Use a maximum of 100 characters to describe your image. Decorative images do not require alt text. <a href="https://html.spec.whatwg.org/multipage/images.html#alt" target="_blank">Check the guidance for tips on writing alt text</a>.',
                            "label": "Image alternative text",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    56: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 35), ("decorative", 54), ("alt_text", 55)]],
                        {
                            "label": "Teaser image",
                            "template": "articles/blocks/images/blog-embed__image-container.html",
                        },
                    ),
                    57: (
                        "etna.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "A description of the promoted page",
                        },
                    ),
                    58: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 47),
                                ("category", 48),
                                ("publication_date", 49),
                                ("author", 19),
                                ("duration", 50),
                                ("url", 51),
                                ("target_blank", 52),
                                ("cta_label", 53),
                                ("image", 56),
                                ("description", 57),
                            ]
                        ],
                        {},
                    ),
                    59: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("categories.Category",),
                        {},
                    ),
                    60: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The title of the target page",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    61: (
                        "etna.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "A description of the target page",
                            "required": False,
                        },
                    ),
                    62: ("wagtail.blocks.URLBlock", (), {"required": True}),
                    63: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 60), ("description", 61), ("url", 62)]],
                        {},
                    ),
                    64: ("wagtail.blocks.ListBlock", (63,), {}),
                    65: (
                        "wagtail.blocks.StructBlock",
                        [[("category", 59), ("summary", 22), ("promoted_items", 64)]],
                        {},
                    ),
                    66: (
                        "etna.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link"], "required": True},
                    ),
                    67: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 100, "required": False},
                    ),
                    68: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 66), ("attribution", 67)]],
                        {},
                    ),
                    69: (
                        "wagtail.blocks.ListBlock",
                        (etna.ciim.blocks.RecordLinkBlock,),
                        {"label": "Items"},
                    ),
                    70: ("wagtail.blocks.StructBlock", [[("items", 69)]], {}),
                    71: (
                        "wagtail.contrib.table_block.blocks.TableBlock",
                        (),
                        {
                            "table_options": {
                                "contextMenu": [
                                    "row_above",
                                    "row_below",
                                    "---------",
                                    "col_left",
                                    "col_right",
                                    "---------",
                                    "remove_row",
                                    "remove_col",
                                    "---------",
                                    "undo",
                                    "redo",
                                    "---------",
                                    "alignment",
                                ]
                            }
                        },
                    ),
                    72: ("wagtail.blocks.StructBlock", [[("table", 71)]], {}),
                    73: ("wagtail.blocks.StructBlock", [[("body", 41)]], {}),
                    74: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Title", "max_length": 100, "required": True},
                    ),
                    75: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "YouTube Video ID",
                            "max_length": 11,
                            "required": True,
                        },
                    ),
                    76: (
                        "etna.core.blocks.image.APIImageChooserBlock",
                        (),
                        {
                            "label": "Preview Image",
                            "rendition_size": "max-640x360",
                            "required": False,
                        },
                    ),
                    77: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 74), ("video_id", 75), ("preview_image", 76)]],
                        {},
                    ),
                    78: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Heading", "max_length": 100},
                    ),
                    79: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Sub-heading", "max_length": 100},
                    ),
                    80: ("wagtail.blocks.StructBlock", [[("heading", 79)]], {}),
                    81: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Sub-sub-heading", "max_length": 100},
                    ),
                    82: ("wagtail.blocks.StructBlock", [[("heading", 81)]], {}),
                    83: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("accordions", 10),
                                ("button", 15),
                                ("call_to_action", 17),
                                ("contact", 23),
                                ("description_list", 27),
                                ("document", 6),
                                ("do_dont_list", 32),
                                ("featured_record_article", 34),
                                ("image", 38),
                                ("image_gallery", 40),
                                ("inset_text", 42),
                                ("media", 46),
                                ("paragraph", 42),
                                ("promoted_item", 58),
                                ("promoted_list", 65),
                                ("quote", 68),
                                ("record_links", 70),
                                ("sub_heading", 80),
                                ("sub_sub_heading", 82),
                                ("table", 72),
                                ("warning_text", 73),
                                ("youtube_video", 77),
                            ]
                        ],
                        {"required": False},
                    ),
                    84: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 78), ("content", 83)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
