# Generated by Django 6.0.7 on 2026-07-30 13:11

import app.core.models.mixins
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MourningNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', wagtail.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('twitter_og_title', models.CharField(blank=True, help_text='If left blank, the OpenGraph title will be used.', max_length=255, null=True, verbose_name='Twitter OpenGraph title')),
                ('twitter_og_description', models.TextField(blank=True, help_text='If left blank, the OpenGraph description will be used.', null=True, verbose_name='Twitter OpenGraph description')),
                ('short_title', models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=45, null=True, verbose_name='short title')),
                ('teaser_text', models.TextField(help_text='A short, enticing description of this page. This will appear in promos and under thumbnails around the site.', max_length=160, verbose_name='teaser text')),
                ('intro', wagtail.fields.RichTextField(help_text='1-2 sentences introducing the subject of the page, and explaining why a user should read on.', max_length=300, verbose_name='introductory text')),
                ('primary_promo', wagtail.fields.StreamField([('featured_page', 2), ('featured_external_link', 8)], blank=True, block_lookup={0: ('app.core.blocks.page_chooser.APIPageChooserBlock', (), {'label': 'Page', 'page_type': ['wagtailcore.Page'], 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional override for the teaser text', 'label': 'Teaser text override', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('page', 0), ('teaser_text', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Supertitle', 'max_length': 20, 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 100}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Description'}), 6: ('wagtail.blocks.URLBlock', (), {'label': 'URL'}), 7: ('app.core.blocks.image.APIImageChooserBlock', (), {'label': 'Image', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('supertitle', 3), ('title', 4), ('description', 5), ('url', 6), ('image', 7)]], {})}, verbose_name='Primary promo link')),
                ('secondary_promos', wagtail.fields.StreamField([('featured_page', 2), ('featured_external_link', 8)], blank=True, block_lookup={0: ('app.core.blocks.page_chooser.APIPageChooserBlock', (), {'label': 'Page', 'page_type': ['wagtailcore.Page'], 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional override for the teaser text', 'label': 'Teaser text override', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('page', 0), ('teaser_text', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Supertitle', 'max_length': 20, 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 100}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Description'}), 6: ('wagtail.blocks.URLBlock', (), {'label': 'URL'}), 7: ('app.core.blocks.image.APIImageChooserBlock', (), {'label': 'Image', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('supertitle', 3), ('title', 4), ('description', 5), ('url', 6), ('image', 7)]], {})}, verbose_name='Secondary promo links')),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='alerts.alert')),
            ],
            options={
                'abstract': False,
            },
            bases=(app.core.models.mixins.CustomHeadlessPreviewMixin, 'wagtailcore.page', models.Model),
        ),
    ]
