# Generated by Django 4.0.8 and condensed to single file.

from django.db import migrations
import app.core.blocks.page_list
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0014_alter_homepage_body"),
    ]

    operations = [
        # _alter_homepage_featured_pages
        migrations.AlterField(
            model_name="homepage",
            name="featured_pages",
            field=wagtail.fields.StreamField(
                [
                    (
                        "featuredpages",
                        wagtail.blocks.StructBlock(
                            [
                                ("heading", wagtail.blocks.CharBlock(max_length=100)),
                                (
                                    "description",
                                    wagtail.blocks.TextBlock(max_length=200),
                                ),
                                (
                                    "items",
                                    app.core.blocks.page_list.PageListBlock(
                                        "articles.ArticlePage", max_num=9, min_num=3
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        # _rename_featured_insight_homepage_featured_article
        migrations.RenameField(
            model_name="homepage",
            old_name="featured_insight",
            new_name="featured_article",
        ),
    ]
