# Generated by Django 4.0.8 on 2023-02-16 16:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0018_alter_sub_heading_fields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="homepage",
            old_name="sub_heading",
            new_name="intro",
        ),
    ]
