# Generated by Django 4.1.8 on 2023-04-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0022_alter_homepage_search_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="uuid",
            field=models.UUIDField(null=True),
        ),
    ]
