# Generated by Django 5.0.8 on 2024-10-22 10:10
# etna:allowRemoveField

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0029_homepage_twitter_og_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="uuid",
        ),
    ]
