# Generated by Django 5.2.4 on 2025-07-15 16:54
# etna:allowAlterField

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_homepage_short_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', 1)], blank=True, block_lookup={0: ('app.core.blocks.paragraph.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul']}), 1: ('wagtail.blocks.StructBlock', [[('text', 0)]], {})}, null=True),
        ),
    ]
