# Generated by Django 5.2.6 on 2025-10-09 11:30
# etna:allowRemoveField

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_homepage_body'),
        ('images', '0013_alter_customimage_description'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image_caption',
            field=wagtail.fields.RichTextField(blank=True, help_text='An optional caption for hero images. This could be used for image sources or for other useful metadata.', verbose_name='hero image caption (optional)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='primary_promo_chip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='primary_promo_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='primary_promo_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='primary_promo_internal_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='primary_promo_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='primary_promo_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='secondary_promos',
            field=wagtail.fields.StreamField([('secondary_promos', 8)], blank=True, block_lookup={0: ('app.core.blocks.page_chooser.APIPageChooserBlock', (), {'label': 'Page', 'page_type': ['wagtailcore.Page'], 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional override for the teaser text', 'label': 'Teaser text override', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('page', 0), ('teaser_text', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 100}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Description'}), 5: ('wagtail.blocks.URLBlock', (), {'label': 'URL'}), 6: ('app.core.blocks.image.APIImageChooserBlock', (), {'label': 'Image', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 3), ('description', 4), ('url', 5), ('image', 6)]], {}), 8: ('wagtail.blocks.StreamBlock', [[('featured_page', 2), ('featured_external_link', 7)]], {})}, verbose_name='Secondary promo links'),
        ),
    ]
