# Generated by Django 5.2.6 on 2025-10-10 13:42

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_homepage_body'),
        ('images', '0013_alter_customimage_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image_caption',
            field=wagtail.fields.RichTextField(blank=True, help_text='An optional caption for hero images. This could be used for image sources or for other useful metadata.', verbose_name='hero image caption (optional)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='primary_promo',
            field=wagtail.fields.StreamField([('featured_page', 2), ('featured_external_link', 8)], blank=True, block_lookup={0: ('app.core.blocks.page_chooser.APIPageChooserBlock', (), {'label': 'Page', 'page_type': ['wagtailcore.Page'], 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional override for the teaser text', 'label': 'Teaser text override', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('page', 0), ('teaser_text', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Supertitle', 'max_length': 20, 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 100}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Description'}), 6: ('wagtail.blocks.URLBlock', (), {'label': 'URL'}), 7: ('app.core.blocks.image.APIImageChooserBlock', (), {'label': 'Image', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('supertitle', 3), ('title', 4), ('description', 5), ('url', 6), ('image', 7)]], {})}, verbose_name='Primary promo link'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='secondary_promos',
            field=wagtail.fields.StreamField([('featured_page', 2), ('featured_external_link', 8)], blank=True, block_lookup={0: ('app.core.blocks.page_chooser.APIPageChooserBlock', (), {'label': 'Page', 'page_type': ['wagtailcore.Page'], 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional override for the teaser text', 'label': 'Teaser text override', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('page', 0), ('teaser_text', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Supertitle', 'max_length': 20, 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 100}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Description'}), 6: ('wagtail.blocks.URLBlock', (), {'label': 'URL'}), 7: ('app.core.blocks.image.APIImageChooserBlock', (), {'label': 'Image', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('supertitle', 3), ('title', 4), ('description', 5), ('url', 6), ('image', 7)]], {})}, verbose_name='Secondary promo links'),
        ),
    ]
