# Generated by Django 5.2.6 on 2025-10-20 16:41
# etna:allowAlterField

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_remove_homepage_body_homepage_hero_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='short_title',
            field=models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=46, null=True, verbose_name='short title'),
        ),
    ]
