# Generated by Django 4.0.8 on 2023-02-01 21:43

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0002_migrate_old_image_data_to_new_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="customimage",
            name="is_sensitive",
            field=models.BooleanField(
                default=False, verbose_name="This image is sensitive"
            ),
        ),
        migrations.AddField(
            model_name="customimage",
            name="translation",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="An optional translation of the above transcription.",
                max_length=1500,
                verbose_name="translation",
            ),
        ),
        migrations.AddField(
            model_name="customimage",
            name="translation_language",
            field=models.CharField(
                blank=True,
                help_text="e.g. Modern English.",
                max_length=50,
                verbose_name="translation language",
            ),
        ),
    ]
