# Generated by Django 4.2.1 on 2023-05-19 15:43

import wagtail.images.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0007_customimage_custom_sensitive_image_warning_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customimagerendition",
            name="file",
            field=wagtail.images.models.WagtailImageField(
                height_field="height",
                storage=wagtail.images.models.get_rendition_storage,
                upload_to=wagtail.images.models.get_rendition_upload_to,
                width_field="width",
            ),
        ),
    ]
