# Generated by Django 5.0.2 on 2024-02-28 13:16

import etna.core.blocks.paragraph
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0008_alter_customimagerendition_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customimage",
            name="description",
            field=etna.core.blocks.paragraph.APIRichTextField(
                blank=True,
                help_text="This text will appear in highlights galleries. A 100-300 word description of the story of the record and why it is significant.",
                max_length=900,
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="customimage",
            name="transcription",
            field=etna.core.blocks.paragraph.APIRichTextField(
                blank=True,
                help_text="If the image contains text consider adding a transcript.",
                max_length=1500,
                verbose_name="transcript",
            ),
        ),
        migrations.AlterField(
            model_name="customimage",
            name="translation",
            field=etna.core.blocks.paragraph.APIRichTextField(
                blank=True,
                help_text="An optional English / Modern English translation of the transcription.",
                max_length=1500,
                verbose_name="translation",
            ),
        ),
    ]
