# Generated by Django 5.2 on 2025-05-21 11:08

from django.db import migrations, models
from etna.collections.models import Highlight
from etna.articles.models import PageGalleryImage
from wagtail.models import Page
from etna.images.models import CustomImage
from etna.articles.models import ArticlePage, FocusedArticlePage
from etna.blog.models import BlogPostPage

def migrate_image_data_to_highlight(apps, schema_editor):
    Highlight = apps.get_model("collections", "Highlight")

    for obj in Highlight.objects.all():
        if img := obj.image:
            obj.record = img.record
            obj.record_dates = img.record_dates
            obj.description = img.description
            obj.title = img.title
            obj.save()

def migrate_alt_text_to_custom_image(apps, schema_editor):
    for obj in PageGalleryImage.objects.all():
        if obj.image and obj.alt_text:
            image = CustomImage.objects.get(id=obj.image.id)
            image.description = obj.alt_text
            image.save()
    
    for obj in Highlight.objects.all():
        if obj.image and obj.alt_text:
            image = CustomImage.objects.get(id=obj.image.id)
            image.description = obj.alt_text
            image.save()
    
    for page in Page.objects.type(ArticlePage, FocusedArticlePage, BlogPostPage):
        if body := page.specific.body:
            for block in body._raw_data:
                if block["type"] == "content_section":
                    for sub_block in block["value"]["content"]:
                        if sub_block["type"] == "image":
                            if sub_block["value"]["image"] and sub_block["value"]["alt_text"]:
                                image = CustomImage.objects.get(id=sub_block["value"]["image"])
                                image.description = sub_block["value"]["alt_text"]
                                image.save()
                        if sub_block["type"] == "image_gallery":
                            for image in sub_block["value"]["images"]:
                                if image["value"]["image"] and image["value"]["alt_text"]:
                                    image_instance = CustomImage.objects.get(id=image["value"]["image"])
                                    image_instance.description = image["value"]["alt_text"]
                                    image_instance.save()
                        if sub_block["type"] == "promoted_item":
                            if image := sub_block["value"]["image"]:
                                if image["image"] and image["alt_text"] and image["decorative"] is False:
                                    image_instance = CustomImage.objects.get(id=image["image"])
                                    image_instance.description = image["alt_text"]
                                    image_instance.save()
                if block["type"] == "image":
                    if block["value"]["image"] and block["value"]["alt_text"]:
                        image = CustomImage.objects.get(id=block["value"]["image"])
                        image.description = block["value"]["alt_text"]
                        image.save()
                if block["type"] == "image_gallery":
                    for image in block["value"]["images"]:
                        if image["value"]["image"] and image["value"]["alt_text"]:
                            image_instance = CustomImage.objects.get(id=image["value"]["image"])
                            image_instance.description = image["value"]["alt_text"]
                            image_instance.save()
                if block["type"] == "promoted_item":
                    if image := sub_block["value"]["image"]:
                        if image["image"] and image["alt_text"] and image["decorative"] is False:
                            image_instance = CustomImage.objects.get(id=image["image"])
                            image_instance.description = image["alt_text"]
                            image_instance.save()
                

class Migration(migrations.Migration):

    dependencies = [
        ('images', '0010_alter_customimage_copyright'),
        ('collections', '0063_highlight_description_highlight_record_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_image_data_to_highlight, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='customimage',
            name='custom_sensitive_image_warning',
        ),
        migrations.RemoveField(
            model_name='customimage',
            name='is_sensitive',
        ),
        migrations.RemoveField(
            model_name='customimage',
            name='record',
        ),
        migrations.RemoveField(
            model_name='customimage',
            name='record_dates',
        ),
        migrations.AlterField(
            model_name='customimage',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='description'),
        ),
        migrations.RunPython(migrate_alt_text_to_custom_image, migrations.RunPython.noop),
    ]
