# Generated by Django 5.2 on 2025-06-10 13:32
# etna:allowAlterField

import uuid
from django.db import migrations, models

def gen_uuids(apps, schema_editor):
    CustomImage = apps.get_model('images', 'CustomImage')
    for obj in CustomImage.objects.filter(uuid__isnull=True):
        obj.uuid = uuid.uuid4()
        obj.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0010_alter_customimage_copyright'),
    ]

    operations = [
        migrations.AddField(
            model_name='customimage',
            name='uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True, verbose_name='UUID'),
        ),
        migrations.RunPython(gen_uuids),
        migrations.AlterField(
            model_name='customimage',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
    ]
