# Generated by Django 4.2.4 on 2023-08-04 09:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authors", "0003_authorindexpage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="authorpage",
            name="name",
        ),
    ]
