# Generated by Django 4.2.4 on 2023-08-04 10:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authors", "0005_authortag"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="authortag",
            options={},
        ),
        migrations.RenameField(
            model_name="authortag",
            old_name="topic",
            new_name="author",
        ),
        migrations.RemoveField(
            model_name="authortag",
            name="sort_order",
        ),
    ]
