# format <record_field_name> : <human readable label name>
FIELD_LABELS = {
    "summary_title": "Summary title",
    "reference_number": "Reference",
    "legal_status": "Legal status",
    "created_by": "Creator",
    "description": "Description",
    "date_created": "Date",
    "access_condition": "Access conditions",
    "held_by": "Held by",
    "parent": "This record is in",
    "hierarchy": "Where am I in the catalogue?",
    "topics": "Topics covered in this record",
    "next_record": "Next",
    "previous_record": "Previous",
    "related_records": "Related records",
    "related_articles": "Related content",
    "related_materials": "Related material",
    "closure": "Closure Status",
    "arrangement": "Arrangement",
    "record_opening": "Record opening date",
    "title": "Title",
    "creator": "Creator",
    "dimensions": "Dimensions",
    "former_department_reference": "Former reference in its original department",
    "former_pro_reference": "Former reference in The National Archives",
    "language": "Language",
    "map_designation": "Map designation",
    "map_scale": "Map scale",
    "note": "Note",
    "physical_condition": "Physical condition",
    "physical_description": "Physical description",
    "accruals": "Accruals",
    "accumulation_dates": "Accumulation dates",
    "appraisal_information": "Selection and destruction information",
    "immediate_source_of_acquisition": "Immediate source of acquisition",
    "administrative_background": "Administrative/ biographical background",
    "separated_materials": "Separated material",
    "unpublished_finding_aids": "Unpublished finding aids",
    "copies_information": "Copies information",
    "custodial_history": "Custodial history",
    "location_of_originals": "Originals held at",
    "restrictions_on_use": "Restrictions on use",
    "publication_note": "Publication note",
}
