# format <record_field_name> : <human readable label name>
FIELD_LABELS = {
    "summary_title": "Summary title",
    "reference_number": "Reference",
    "legal_status": "Legal status",
    "created_by": "Creator",
    "description": "Description",
    "date_created": "Date",
    "access_condition": "Access conditions",
    "held_by": "Held by",
    "parent": "This record is in",
    "hierarchy": "Where am I in the catalogue?",
    "topics": "Topics covered in this record",
    "next_record": "Next",
    "previous_record": "Previous",
    "related_records": "Related records",
    "related_articles": "Related content",
    "related_materials": "Related material",
    "closure": "Closure Status",
    "record_opening": "Record opening date",
    "title": "Title",
    "former_department_reference": "Former reference in its original department",
}
