# Generated by Django 6.0.8 on 2026-09-14 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peopleindexpage',
            name='twitter_og_description',
        ),
        migrations.RemoveField(
            model_name='peopleindexpage',
            name='twitter_og_image',
        ),
        migrations.RemoveField(
            model_name='peopleindexpage',
            name='twitter_og_title',
        ),
        migrations.RemoveField(
            model_name='personpage',
            name='twitter_og_description',
        ),
        migrations.RemoveField(
            model_name='personpage',
            name='twitter_og_image',
        ),
        migrations.RemoveField(
            model_name='personpage',
            name='twitter_og_title',
        ),
    ]
