# Generated by Django 5.0.7 on 2024-08-01 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0003_authorindexpage_alert_authorpage_alert"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="authorpage",
            options={
                "verbose_name": "Person page",
                "verbose_name_plural": "People pages",
            },
        ),
    ]
