# Generated by Django 5.0.8 on 2024-08-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0007_peopleindexpage_twitter_og_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personpage",
            name="first_name",
            field=models.CharField(default="first", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="personpage",
            name="last_name",
            field=models.CharField(default="name", max_length=255),
            preserve_default=False,
        ),
    ]
