# Generated by Django 5.0.8 on 2024-08-19 09:53
# etna:allowAlterField
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0009_personpage_research_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personpage",
            name="research_summary",
            field=wagtail.fields.StreamField(
                [("inset_text", 1), ("paragraph", 1), ("content_section", 4)],
                blank=True,
                block_lookup={
                    0: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link", "ol", "ul"]},
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("text", 0)]], {}),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Heading", "max_length": 100},
                    ),
                    3: (
                        "wagtail.blocks.StreamBlock",
                        [[("inset_text", 1), ("paragraph", 1)]],
                        {"required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 2), ("content", 3)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
