# Generated by Django 5.1.5 on 2025-01-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0014_externalauthortag'),
    ]

    operations = [
        migrations.AddField(
            model_name='peopleindexpage',
            name='short_title',
            field=models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=30, null=True, verbose_name='short title'),
        ),
        migrations.AddField(
            model_name='personpage',
            name='short_title',
            field=models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=30, null=True, verbose_name='short title'),
        ),
    ]
