# Generated by Django 5.2.4 on 2025-08-04 10:50

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0017_personpage_archived_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('display_on_card', models.BooleanField(default=False, help_text="Display this role on a person's card.")),
            ],
            options={
                'verbose_name': 'Person role',
                'verbose_name_plural': 'Person roles',
            },
        ),
        migrations.CreateModel(
            name='PersonRoleSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='people.personpage')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_roles', to='people.personrole')),
            ],
            options={
                'verbose_name': 'Person role',
                'verbose_name_plural': 'Person roles',
            },
        ),
    ]
