# Generated by Django 5.2.5 on 2025-09-23 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0018_personrole_personroleselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='personroleselection',
            name='weighting',
            field=models.PositiveIntegerField(default=1, help_text='The weighting of the person within this role from 1-5. Higher numbers place the person higher in lists.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
