# Generated by Django 5.0.8 on 2024-10-22 10:10
# etna:allowRemoveField

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cookies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cookiedetailspage",
            name="uuid",
        ),
        migrations.RemoveField(
            model_name="cookiespage",
            name="uuid",
        ),
    ]
