# Generated by Django 5.2.6 on 2025-10-20 16:41
# etna:allowAlterField

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0003_cookiedetailspage_short_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookiedetailspage',
            name='short_title',
            field=models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=45, null=True, verbose_name='short title'),
        ),
        migrations.AlterField(
            model_name='cookiespage',
            name='short_title',
            field=models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=45, null=True, verbose_name='short title'),
        ),
    ]
