# Generated by Django 6.0.2 on 2026-03-27 14:17
# etna:allowAlterField

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cookies", "0004_alter_cookiedetailspage_short_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cookiedetailspage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("inset_text", 1),
                    ("paragraph", 1),
                    ("description_list", 6),
                    ("table", 8),
                    ("content_section", 13),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link", "code", "ol", "ul"]},
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("text", 0)]], {}),
                    2: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    3: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link", "code"]},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("term", 2), ("detail", 3)]],
                        {},
                    ),
                    5: ("wagtail.blocks.ListBlock", (4,), {}),
                    6: ("wagtail.blocks.StructBlock", [[("items", 5)]], {}),
                    7: (
                        "wagtail.contrib.table_block.blocks.TableBlock",
                        (),
                        {
                            "table_options": {
                                "contextMenu": [
                                    "row_above",
                                    "row_below",
                                    "---------",
                                    "col_left",
                                    "col_right",
                                    "---------",
                                    "remove_row",
                                    "remove_col",
                                    "---------",
                                    "undo",
                                    "redo",
                                    "---------",
                                    "alignment",
                                ]
                            }
                        },
                    ),
                    8: ("wagtail.blocks.StructBlock", [[("table", 7)]], {}),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Heading", "max_length": 100},
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Sub-heading", "max_length": 100},
                    ),
                    11: ("wagtail.blocks.StructBlock", [[("heading", 10)]], {}),
                    12: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("inset_text", 1),
                                ("paragraph", 1),
                                ("description_list", 6),
                                ("sub_heading", 11),
                                ("table", 8),
                            ]
                        ],
                        {"required": False},
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 9), ("content", 12)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
