name: Run Python tests

inputs:
  codecov-token:
    description: "Codecov token"
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Start Docker containers
      run: docker compose up --detach --wait --wait-timeout 300 || docker compose logs app
      shell: bash
    - name: Check formatting
      run: docker compose exec app checkformat
      shell: bash
    - name: Run check
      run: docker compose exec app poetry run python manage.py check
      shell: bash
    - name: Run tests
      run: docker compose exec app poetry run python manage.py test
      shell: bash
    - name: Check for missing migrations
      run: docker compose exec app poetry run python manage.py makemigrations --check --noinput
      shell: bash
