name: Run Python tests

inputs:
  codecov-token:
    description: "Codecov token"
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - run: |
        echo "PLATFORMSH_CLI_TOKEN=abc123" >> $GITHUB_ENV
      shell: bash
    - uses: actions/setup-python@v5
      with:
        python-version: 3.13
    - run: pip install flake8 isort black
      shell: bash
    - name: Check compliance with isort
      run: isort -c .
      shell: bash
    - name: Check compliance with Black
      run: black -t py38 -t py39 -t py310 -t py311 -t py312 --line-length 88 --verbose app config
      shell: bash
    - name: Check compliance with flake8
      run: flake8 .
      shell: bash
    - name: Start Docker containers
      run: docker compose up -d
      shell: bash
    - name: Run check in the app Docker container
      run: docker compose exec app poetry run python /app/manage.py check
      shell: bash
    - name: Run tests in the dev Docker container
      run: docker compose exec dev poetry run python /app/manage.py test
      shell: bash
    - name: Check for missing migrations
      run: docker compose exec app poetry run python /app/manage.py makemigrations --check --noinput
      shell: bash
