name: Run Python tests

inputs:
  codecov-token:
    description: "Codecov token"
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
    - run: pip install flake8 isort black
    - name: Check compliance with isort
      run: isort -c .
      shell: bash
    - name: Check compliance with Black
      run: black -t py38 -t py39 -t py310 -t py311 -t py312 --line-length 88 --verbose etna config
      shell: bash
    - name: Check compliance with flake8
      run: flake8 .
      shell: bash
    - uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        virtualenvs-path: .venv
    - name: Install Poetry dependencies
      run: poetry install --no-interaction --no-root --with dev
      shell: bash
    - name: Run Django checks
      run: poetry run python manage.py check
      shell: bash
    - name: Run test suite
      run: poetry run coverage run manage.py test etna
      shell: bash
    - name: Check for missing migrations
      run: poetry run python manage.py makemigrations --check --noinput
      shell: bash
    - name: Prepare coverage report
      run: poetry run coverage xml
      shell: bash
    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ inputs.codecov-token }}
        fail_ci_if_error: true
        move_coverage_to_trash: true
