# Generated by Django 5.0.2 on 2024-02-28 13:16

import etna.core.blocks.paragraph
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etnamedia",
            name="description",
            field=etna.core.blocks.paragraph.APIRichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="etnamedia",
            name="transcript",
            field=etna.core.blocks.paragraph.APIRichTextField(blank=True, null=True),
        ),
    ]
