# Generated by Django 5.2.1 on 2025-05-12 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_etnamedia_chapters_file_etnamedia_subtitles_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etnamedia',
            options={'verbose_name': 'media', 'verbose_name_plural': 'media items'},
        ),
    ]
