# Generated by Django 3.1.8 on 2021-07-07 11:40

from django.db import migrations
import etna.richtexts.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0003_add_collection_results_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorypage',
            name='content',
            field=wagtail.core.fields.StreamField([('quote', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=100, required=True)), ('quote', etna.richtexts.blocks.BasicRichTextBlock(required=True)), ('attribution', wagtail.core.blocks.CharBlock(max_length=100, required=False))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='explorerpage',
            name='content',
            field=wagtail.core.fields.StreamField([('quote', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=100, required=True)), ('quote', etna.richtexts.blocks.BasicRichTextBlock(required=True)), ('attribution', wagtail.core.blocks.CharBlock(max_length=100, required=False))]))], blank=True, null=True),
        ),
    ]
