# Generated by Django 3.1.8 on 2021-07-13 14:24

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0015_add_teaser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explorerindexpage',
            name='body',
            field=wagtail.core.fields.StreamField([('time_period_explorer_index', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(default='Explore by time period', max_length=100)), ('sub_heading', wagtail.core.blocks.CharBlock(default='Discover 1,000 years of British history through time periods including:', max_length=200)), ('page', wagtail.core.blocks.PageChooserBlock(page_type=['collections.TimePeriodExplorerIndexPage']))])), ('topic_explorer_explorer_index', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(default='Explore by topic', max_length=100)), ('sub_heading', wagtail.core.blocks.CharBlock(default='Browse highlights of the collection through topics including:', max_length=200)), ('page', wagtail.core.blocks.PageChooserBlock(page_type=['collections.TopicExplorerIndexPage']))]))], blank=True),
        ),
    ]
