# Generated by Django 3.1.8 on 2021-08-13 09:47

from django.db import migrations
import etna.collections.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("collections", "0017_add_time_period_topic_index_page_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeperiodexplorerpage",
            name="body",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "collection_highlights",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.core.blocks.CharBlock(
                                        default="Collection Highlights", max_length=100
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "featured_page",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.core.blocks.CharBlock(max_length=100),
                                ),
                                (
                                    "description",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="A description of the featured page",
                                        max_length=200,
                                        required=False,
                                    ),
                                ),
                                ("page", wagtail.core.blocks.PageChooserBlock()),
                            ]
                        ),
                    ),
                    (
                        "promoted_pages",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.core.blocks.CharBlock(max_length=100),
                                ),
                                (
                                    "sub_heading",
                                    wagtail.core.blocks.CharBlock(max_length=200),
                                ),
                                (
                                    "promoted_items",
                                    wagtail.core.blocks.ListBlock(
                                        etna.collections.blocks.PromotedItemBlock,
                                        max=3,
                                        min=3,
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
            ),
        ),
        migrations.AlterField(
            model_name="topicexplorerpage",
            name="body",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "collection_highlights",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.core.blocks.CharBlock(
                                        default="Collection Highlights", max_length=100
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "featured_page",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.core.blocks.CharBlock(max_length=100),
                                ),
                                (
                                    "description",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="A description of the featured page",
                                        max_length=200,
                                        required=False,
                                    ),
                                ),
                                ("page", wagtail.core.blocks.PageChooserBlock()),
                            ]
                        ),
                    ),
                    (
                        "promoted_pages",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.core.blocks.CharBlock(max_length=100),
                                ),
                                (
                                    "sub_heading",
                                    wagtail.core.blocks.CharBlock(max_length=200),
                                ),
                                (
                                    "promoted_items",
                                    wagtail.core.blocks.ListBlock(
                                        etna.collections.blocks.PromotedItemBlock,
                                        max=3,
                                        min=3,
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
            ),
        ),
    ]
