# Generated by Django 3.2.13 on 2022-06-20 20:00

from django.db import migrations, models
import django.db.models.deletion
import etna.collections.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("insights", "0042_alter_insightspage_body"),
        ("collections", "0020_rename_result_page_record_relationship"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeperiodexplorerpage",
            name="featured_insight",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="insights.insightspage",
            ),
        ),
        migrations.AddField(
            model_name="topicexplorerpage",
            name="featured_insight",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="insights.insightspage",
            ),
        ),
        migrations.AlterField(
            model_name="timeperiodexplorerpage",
            name="body",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "collection_highlights",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.core.blocks.CharBlock(
                                        default="Collection Highlights", max_length=100
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "promoted_pages",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.core.blocks.CharBlock(max_length=100),
                                ),
                                (
                                    "sub_heading",
                                    wagtail.core.blocks.CharBlock(max_length=200),
                                ),
                                (
                                    "promoted_items",
                                    wagtail.core.blocks.ListBlock(
                                        etna.collections.blocks.PromotedItemBlock,
                                        max=3,
                                        min=3,
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
            ),
        ),
        migrations.AlterField(
            model_name="topicexplorerpage",
            name="body",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "collection_highlights",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.core.blocks.CharBlock(
                                        default="Collection Highlights", max_length=100
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "promoted_pages",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.core.blocks.CharBlock(max_length=100),
                                ),
                                (
                                    "sub_heading",
                                    wagtail.core.blocks.CharBlock(max_length=200),
                                ),
                                (
                                    "promoted_items",
                                    wagtail.core.blocks.ListBlock(
                                        etna.collections.blocks.PromotedItemBlock,
                                        max=3,
                                        min=3,
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
            ),
        ),
    ]
