# Generated by Django 3.2.12 on 2022-03-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collections", "0020_rename_result_page_record_relationship"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="slug"),
                ),
            ],
            options={
                "verbose_name": "Category tag",
            },
        ),
        migrations.CreateModel(
            name="ThemeTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="slug"),
                ),
            ],
            options={
                "verbose_name": "theme tag",
            },
        ),
    ]
