# Generated by Django 4.0.8 on 2022-11-01 19:42

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0077_alter_revision_user'),
        ('collections', '0024_timeperiodtag_topictag_taggedtopics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggedtimeperiods',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_time_periods', to='wagtailcore.page'),
        ),
        migrations.AlterField(
            model_name='taggedtopics',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_topics', to='wagtailcore.page'),
        ),
    ]
