# Generated by Django 4.0.8 on 2022-11-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collections", "0025_alter_explorerindexpage_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeperiodexplorerindexpage",
            name="sub_heading",
            field=models.CharField(
                default="Default intro needs changing", max_length=200
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="timeperiodexplorerpage",
            name="sub_heading",
            field=models.CharField(
                default="Default intro needs changing", max_length=200
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="topicexplorerindexpage",
            name="sub_heading",
            field=models.CharField(
                default="Default intro needs changing", max_length=200
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="topicexplorerpage",
            name="sub_heading",
            field=models.CharField(
                default="Default intro needs changing", max_length=200
            ),
            preserve_default=False,
        ),
    ]
