# Generated by Django 4.0.8 and condensed to single file.

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("collections", "0025_timeperiodexplorerindexpage_sub_heading_and_more"),
    ]

    operations = [
        # _rename_featured_insight_timeperiodexplorerpage_featured_article_and_more.py
        migrations.RenameField(
            model_name="timeperiodexplorerpage",
            old_name="featured_insight",
            new_name="featured_article",
        ),
        migrations.RenameField(
            model_name="topicexplorerpage",
            old_name="featured_insight",
            new_name="featured_article",
        ),
    ]
