# Generated by Django 4.0.8 on 2022-11-17 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0024_remove_timeperiodexplorerindexpage_sub_heading_and_more'),
        ('collections', '0025_alter_taggedtimeperiods_content_object_and_more'),
    ]

    operations = [
    ]
