# Generated by Django 4.1.7 on 2023-03-16 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0062_fix_incorrectly_formatted_article_revision_content"),
        ("collections", "0033_set_teaser_text_from_intro"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeperiodexplorerpage",
            name="featured_record_article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="articles.recordarticlepage",
            ),
        ),
        migrations.AddField(
            model_name="topicexplorerpage",
            name="featured_record_article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="articles.recordarticlepage",
            ),
        ),
    ]
