# Generated by Django 4.1.7 on 2023-03-20 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0066_alter_articleindexpage_search_image_and_more"),
        ("collections", "0036_alter_explorerindexpage_search_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeperiodexplorerpage",
            name="featured_record_article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="articles.recordarticlepage",
            ),
        ),
        migrations.AddField(
            model_name="topicexplorerpage",
            name="featured_record_article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="articles.recordarticlepage",
            ),
        ),
    ]
