# Generated by Django 4.1.7 on 2023-03-22 15:15

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("collections", "0037_timeperiodexplorerpage_featured_record_article_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="highlightgallerypage",
            name="custom_warning_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="If specified, will be used for the content warning. Otherwise the default text will be used.",
                verbose_name="custom content warning text (optional)",
            ),
        ),
        migrations.AddField(
            model_name="highlightgallerypage",
            name="display_content_warning",
            field=models.BooleanField(
                default=False, verbose_name="display a content warning on this page"
            ),
        ),
    ]
