# Generated by Django 4.1.7 on 2023-03-23 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("collections", "0037_timeperiodexplorerpage_featured_record_article_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="highlight",
            name="long_description",
        ),
    ]
