# Generated by Django 4.1.8 on 2023-04-11 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0007_customimage_custom_sensitive_image_warning_and_more"),
        ("collections", "0042_highlight_alt_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeperiodexplorerpage",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
            ),
        ),
        migrations.AddField(
            model_name="topicexplorerpage",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
            ),
        ),
    ]
