# Generated by Django 4.1.8 on 2023-05-05 14:55

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("collections", "0050_make_page_uuid_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="explorerindexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "large_card_links",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        max_length=100, required=False
                                    ),
                                ),
                                (
                                    "page_1",
                                    wagtail.blocks.PageChooserBlock(
                                        label="Link one target"
                                    ),
                                ),
                                (
                                    "page_2",
                                    wagtail.blocks.PageChooserBlock(
                                        label="Link two target"
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="timeperiodexplorerindexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "large_card_links",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        max_length=100, required=False
                                    ),
                                ),
                                (
                                    "page_1",
                                    wagtail.blocks.PageChooserBlock(
                                        label="Link one target"
                                    ),
                                ),
                                (
                                    "page_2",
                                    wagtail.blocks.PageChooserBlock(
                                        label="Link two target"
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="topicexplorerindexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "large_card_links",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        max_length=100, required=False
                                    ),
                                ),
                                (
                                    "page_1",
                                    wagtail.blocks.PageChooserBlock(
                                        label="Link one target"
                                    ),
                                ),
                                (
                                    "page_2",
                                    wagtail.blocks.PageChooserBlock(
                                        label="Link two target"
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
    ]
