# Generated by Django 4.1.8 on 2023-05-05 15:21

from django.db import migrations, models
import django.db.models.deletion
import etna.core.blocks.page_list
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("collections", "0051_alter_explorerindexpage_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="explorerindexpage",
            name="featured_article",
            field=models.ForeignKey(
                blank=True,
                help_text="Select a page to display in the featured area. This can be an Article, or Record Article.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
        migrations.AddField(
            model_name="explorerindexpage",
            name="featured_pages",
            field=wagtail.fields.StreamField(
                [
                    (
                        "featuredpages",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "items",
                                    etna.core.blocks.page_list.PageListBlock(
                                        "articles.ArticlePage",
                                        "articles.RecordArticlePage",
                                        max_num=6,
                                        min_num=3,
                                    ),
                                )
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
