# Generated by Django 4.2.2 on 2023-06-28 12:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("collections", "0051_explorerindexpage_articles_introduction_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="timeperiodexplorerpage",
            options={
                "verbose_name": "time period page",
                "verbose_name_plural": "time period pages",
            },
        ),
        migrations.AlterModelOptions(
            name="topicexplorerpage",
            options={
                "verbose_name": "topic page",
                "verbose_name_plural": "topic pages",
            },
        ),
    ]
