# Generated by Django 4.1.9 on 2023-05-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collections", "0052_explorerindexpage_featured_article_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="explorerindexpage",
            name="articles_introduction",
            field=models.CharField(
                blank=True,
                help_text="The introduction to display for the articles section.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="explorerindexpage",
            name="articles_title",
            field=models.CharField(
                blank=True,
                default="Stories from the collection",
                help_text="The title to display for the articles section.",
                max_length=100,
            ),
        ),
    ]
