# Generated by Django 4.1.9 on 2023-05-18 13:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("images", "0007_customimage_custom_sensitive_image_warning_and_more"),
        ("highlights", "0005_create_highlights_from_images"),
        ("collections", "0052_add_model_verbose_names"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Highlight",
            new_name="PageHighlight",
        ),
    ]
