# Generated by Django 4.1.9 on 2023-05-18 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("highlights", "0005_create_highlights_from_images"),
        ("collections", "0053_rename_highlight_pagehighlight"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagehighlight",
            name="highlight",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="highlights.highlight",
                verbose_name="highlight",
            ),
        ),
    ]
