# Generated by Django 5.0.3 on 2024-03-27 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("collections", "0053_alter_explorerindexpage_featured_article_and_more"),
        ("wagtailcore", "0091_remove_revision_submitted_for_moderation"),
    ]

    def record_article_into_article(apps, schema_editor):
        HighlightGalleryPage = apps.get_model("collections", "HighlightGalleryPage")

        for obj in HighlightGalleryPage.objects.all():
            if not obj.featured_article and obj.featured_record_article:
                obj.featured_article = obj.featured_record_article
                obj.save(update_fields=["featured_article"])

    operations = [
        migrations.RunPython(record_article_into_article),
    ]
