# Generated by Django 5.0.2 on 2024-02-28 13:16

import etna.core.blocks.paragraph
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("collections", "0053_alter_explorerindexpage_featured_article_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="explorerindexpage",
            name="intro",
            field=etna.core.blocks.paragraph.APIRichTextField(
                help_text="1-2 sentences introducing the subject of the page, and explaining why a user should read on.",
                max_length=300,
                verbose_name="introductory text",
            ),
        ),
        migrations.AlterField(
            model_name="highlightgallerypage",
            name="custom_warning_text",
            field=etna.core.blocks.paragraph.APIRichTextField(
                blank=True,
                help_text="If specified, will be used for the content warning. Otherwise the default text will be used.",
                verbose_name="custom content warning text (optional)",
            ),
        ),
        migrations.AlterField(
            model_name="highlightgallerypage",
            name="intro",
            field=etna.core.blocks.paragraph.APIRichTextField(
                help_text="1-2 sentences introducing the subject of the page, and explaining why a user should read on.",
                max_length=300,
                verbose_name="introductory text",
            ),
        ),
        migrations.AlterField(
            model_name="timeperiodexplorerindexpage",
            name="hero_image_caption",
            field=etna.core.blocks.paragraph.APIRichTextField(
                blank=True,
                help_text="An optional caption for hero images. This could be used for image sources or for other useful metadata.",
                verbose_name="hero image caption (optional)",
            ),
        ),
        migrations.AlterField(
            model_name="timeperiodexplorerindexpage",
            name="intro",
            field=etna.core.blocks.paragraph.APIRichTextField(
                help_text="1-2 sentences introducing the subject of the page, and explaining why a user should read on.",
                max_length=300,
                verbose_name="introductory text",
            ),
        ),
        migrations.AlterField(
            model_name="timeperiodexplorerpage",
            name="hero_image_caption",
            field=etna.core.blocks.paragraph.APIRichTextField(
                blank=True,
                help_text="An optional caption for hero images. This could be used for image sources or for other useful metadata.",
                verbose_name="hero image caption (optional)",
            ),
        ),
        migrations.AlterField(
            model_name="timeperiodexplorerpage",
            name="intro",
            field=etna.core.blocks.paragraph.APIRichTextField(
                help_text="1-2 sentences introducing the subject of the page, and explaining why a user should read on.",
                max_length=300,
                verbose_name="introductory text",
            ),
        ),
        migrations.AlterField(
            model_name="topicexplorerindexpage",
            name="hero_image_caption",
            field=etna.core.blocks.paragraph.APIRichTextField(
                blank=True,
                help_text="An optional caption for hero images. This could be used for image sources or for other useful metadata.",
                verbose_name="hero image caption (optional)",
            ),
        ),
        migrations.AlterField(
            model_name="topicexplorerindexpage",
            name="intro",
            field=etna.core.blocks.paragraph.APIRichTextField(
                help_text="1-2 sentences introducing the subject of the page, and explaining why a user should read on.",
                max_length=300,
                verbose_name="introductory text",
            ),
        ),
        migrations.AlterField(
            model_name="topicexplorerpage",
            name="hero_image_caption",
            field=etna.core.blocks.paragraph.APIRichTextField(
                blank=True,
                help_text="An optional caption for hero images. This could be used for image sources or for other useful metadata.",
                verbose_name="hero image caption (optional)",
            ),
        ),
        migrations.AlterField(
            model_name="topicexplorerpage",
            name="intro",
            field=etna.core.blocks.paragraph.APIRichTextField(
                help_text="1-2 sentences introducing the subject of the page, and explaining why a user should read on.",
                max_length=300,
                verbose_name="introductory text",
            ),
        ),
    ]
