# Generated by Django 4.2.2 on 2023-07-05 12:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("collections", "0056_remove_pagehighlight_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pagehighlight",
            name="alt_text",
        ),
    ]
