# Generated by Django 4.2.7 on 2023-11-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("whatson", "0004_eventsession_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventpage",
            name="venue_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("online", "Online"),
                    ("in_person", "In person"),
                    ("hybrid", "In person and online"),
                ],
                default="in_person",
                max_length=15,
                verbose_name="venue type",
            ),
        ),
    ]
