# Generated by Django 4.2.7 on 2023-11-22 15:55

from django.db import migrations
import app.core.blocks.page_list
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("whatson", "0006_merge_20231122_1535"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsonpage",
            name="large_card_links",
            field=wagtail.fields.StreamField(
                [
                    (
                        "large_card_links",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        max_length=100, required=False
                                    ),
                                ),
                                (
                                    "page_1",
                                    wagtail.blocks.PageChooserBlock(
                                        label="Link one target"
                                    ),
                                ),
                                (
                                    "page_2",
                                    wagtail.blocks.PageChooserBlock(
                                        label="Link two target"
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
        migrations.AddField(
            model_name="whatsonpage",
            name="promoted_links",
            field=wagtail.fields.StreamField(
                [
                    (
                        "promoted_links",
                        wagtail.blocks.StructBlock(
                            [
                                ("heading", wagtail.blocks.CharBlock(required=False)),
                                (
                                    "promoted_links",
                                    app.core.blocks.page_list.PageListBlock(
                                        max_num=3, min_num=1
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
    ]
