# Generated by Django 5.0.8 on 2024-10-22 10:10
# etna:allowRemoveField

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("whatson", "0012_eventpage_twitter_og_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventpage",
            name="uuid",
        ),
        migrations.RemoveField(
            model_name="exhibitionpage",
            name="uuid",
        ),
        migrations.RemoveField(
            model_name="whatsonpage",
            name="uuid",
        ),
    ]
