# Generated by Django 5.1.4 on 2025-01-07 11:44
# etna:allowAlterField

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("whatson", "0015_alter_exhibitionpage_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exhibitionpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("paragraph", 1), ("quote", 4)],
                blank=True,
                block_lookup={
                    0: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link", "ol", "ul"]},
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("text", 0)]], {}),
                    2: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "ol", "ul"],
                            "required": True,
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 100, "required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 2), ("attribution", 3)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
