# Generated by Django 5.1.7 on 2025-04-02 09:10

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatson', '0019_exhibitionpage_related_pages_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitionpage',
            name='event_description',
            field=wagtail.fields.RichTextField(blank=True, help_text='The description to display for the events section.'),
        ),
    ]
