# Generated by Django 5.1.7 on 2025-04-17 14:08
# etna:allowAlterField

import django.core.validators
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatson', '0020_exhibitionpage_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitionpage',
            name='video',
            field=wagtail.fields.StreamField([('youtube', 5), ('media', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 100, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'YouTube Video ID', 'max_length': 11, 'required': True, 'validators': [django.core.validators.RegexValidator(message='Invalid YouTube Video ID', regex='^[a-zA-Z0-9_-]{11}$')]}), 2: ('app.core.blocks.image.APIImageChooserBlock', (), {'label': 'Preview Image', 'rendition_size': 'fill-640x360', 'required': True}), 3: ('wagtail.blocks.RichTextBlock', (), {'label': 'Transcript', 'required': False}), 4: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Tick if the video has captions on YouTube', 'label': 'Captions available', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('video_id', 1), ('preview_image', 2), ('transcript', 3), ('captions_available', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'A descriptive title for the media block', 'required': True}), 7: ('app.core.blocks.image.APIImageChooserBlock', (), {'help_text': 'A thumbnail image for the media block', 'rendition_size': 'fill-960x540', 'required': False}), 8: ('app.media.blocks.MediaChooserBlock', (), {}), 9: ('wagtail.blocks.StructBlock', [[('title', 6), ('thumbnail', 7), ('media', 8)]], {})}),
        ),
    ]
