# Generated by Django 5.2.4 on 2025-07-16 13:33
# etna:allowAlterField

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatson', '0025_seriestag_sort_order_alter_eventpage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displaypage',
            name='shop',
            field=wagtail.fields.StreamField([('shop', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 100}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Description', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'default': 'Shop now', 'label': 'CTA text', 'max_length': 50}), 3: ('wagtail.blocks.URLBlock', (), {'help_text': 'The URL to the shop collection', 'label': 'URL'}), 4: ('app.core.blocks.image.APIImageChooserBlock', (), {'label': 'Background image', 'rendition_size': 'fill-1200x480'}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('cta_text', 2), ('url', 3), ('background_image', 4)]], {})}),
        ),
        migrations.AlterField(
            model_name='exhibitionpage',
            name='shop',
            field=wagtail.fields.StreamField([('shop', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 100}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Description', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'default': 'Shop now', 'label': 'CTA text', 'max_length': 50}), 3: ('wagtail.blocks.URLBlock', (), {'help_text': 'The URL to the shop collection', 'label': 'URL'}), 4: ('app.core.blocks.image.APIImageChooserBlock', (), {'label': 'Background image', 'rendition_size': 'fill-1200x480'}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('cta_text', 2), ('url', 3), ('background_image', 4)]], {})}),
        ),
    ]
