# Generated by Django 5.2.4 on 2025-08-21 17:20

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatson', '0027_alter_displaypage_display_highlights_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displaypage',
            name='shop',
            field=wagtail.fields.StreamField([('shop', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 100}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Description', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'default': 'Shop now', 'label': 'CTA text', 'max_length': 50}), 3: ('wagtail.blocks.URLBlock', (), {'help_text': 'The URL to the shop collection', 'label': 'URL'}), 4: ('app.core.blocks.image.APIImageChooserBlock', (), {'label': 'Background image', 'rendition_size': 'fill-1800x720'}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('cta_text', 2), ('url', 3), ('background_image', 4)]], {})}),
        ),
        migrations.AlterField(
            model_name='exhibitionpage',
            name='shop',
            field=wagtail.fields.StreamField([('shop', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 100}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Description', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'default': 'Shop now', 'label': 'CTA text', 'max_length': 50}), 3: ('wagtail.blocks.URLBlock', (), {'help_text': 'The URL to the shop collection', 'label': 'URL'}), 4: ('app.core.blocks.image.APIImageChooserBlock', (), {'label': 'Background image', 'rendition_size': 'fill-1800x720'}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('cta_text', 2), ('url', 3), ('background_image', 4)]], {})}),
        ),
    ]
