# Generated by Django 5.2.4 on 2025-08-21 11:35

import app.core.fields.choosers
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_partnerlogo'),
        ('whatson', '0027_alter_displaypage_display_highlights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitionpage',
            name='partnership',
            field=app.core.fields.choosers.PartnerLogoField(blank=True, help_text='The partnership logo for the exhibition.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', verbose_name='partnership'),
        ),
    ]
