# Generated by Django 5.2.5 on 2025-09-17 15:37

import app.core.fields.choosers
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_partnerlogo'),
        ('whatson', '0028_alter_displaypage_shop_alter_exhibitionpage_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitionpage',
            name='partnership',
            field=app.core.fields.choosers.PartnerLogoField(blank=True, help_text='The partnership logo for the exhibition.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', verbose_name='partnership'),
        ),
        migrations.AddField(
            model_name='exhibitionpage',
            name='partnership_lead_text',
            field=models.CharField(blank=True, help_text='Optional override for the partner logos section lead text. Will display a default if not provided.', max_length=40, verbose_name='partnership lead text'),
        ),
    ]
