# Generated by Django 5.2.5 on 2025-09-02 09:03

import app.core.fields.choosers
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_partnerlogo'),
        ('whatson', '0028_alter_displaypage_shop_alter_exhibitionpage_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitionpage',
            name='partnership',
            field=app.core.fields.choosers.PartnerLogoField(blank=True, help_text='The partnership logo for the exhibition.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', verbose_name='partnership'),
        ),
    ]
