# Generated by Django 5.2.6 on 2025-10-21 13:06
# etna:allowAlterField

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatson', '0031_alter_displaypage_body_alter_exhibitionpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displaypage',
            name='short_title',
            field=models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=45, null=True, verbose_name='short title'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='short_title',
            field=models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=45, null=True, verbose_name='short title'),
        ),
        migrations.AlterField(
            model_name='eventslistingpage',
            name='short_title',
            field=models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=45, null=True, verbose_name='short title'),
        ),
        migrations.AlterField(
            model_name='exhibitionpage',
            name='short_title',
            field=models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=45, null=True, verbose_name='short title'),
        ),
        migrations.AlterField(
            model_name='exhibitionslistingpage',
            name='short_title',
            field=models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=45, null=True, verbose_name='short title'),
        ),
        migrations.AlterField(
            model_name='whatsoncategorypage',
            name='short_title',
            field=models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=45, null=True, verbose_name='short title'),
        ),
        migrations.AlterField(
            model_name='whatsondatelistingpage',
            name='short_title',
            field=models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=45, null=True, verbose_name='short title'),
        ),
        migrations.AlterField(
            model_name='whatsonlocationlistingpage',
            name='short_title',
            field=models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=45, null=True, verbose_name='short title'),
        ),
        migrations.AlterField(
            model_name='whatsonpage',
            name='short_title',
            field=models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=45, null=True, verbose_name='short title'),
        ),
        migrations.AlterField(
            model_name='whatsonseriespage',
            name='short_title',
            field=models.CharField(blank=True, help_text='A shorter title for use in breadcrumbs and other navigational elements, where applicable.', max_length=45, null=True, verbose_name='short title'),
        ),
    ]
