# Generated by Django 5.2.8 on 2025-11-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatson', '0032_alter_displaypage_short_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsonpageselection',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
