# Generated by Django 6.0.2 on 2026-02-24 09:40
# etna:allowAlterField

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("whatson", "0034_alter_whatsonpageselection_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventpage",
            name="description",
            field=wagtail.fields.StreamField(
                [
                    ("contact", 8),
                    ("inset_text", 10),
                    ("paragraph", 10),
                    ("partner_logos", 14),
                    ("content_section", 19),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"features": ["link"], "required": False},
                    ),
                    2: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"features": ["bold", "italic", "link"], "required": False},
                    ),
                    3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    4: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    5: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"required": False},
                    ),
                    6: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    7: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link"], "required": False},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("body", 1),
                                ("address", 2),
                                ("telephone", 3),
                                ("chat_link", 4),
                                ("chat_note", 5),
                                ("email", 6),
                                ("website_link", 4),
                                ("social_media", 7),
                            ]
                        ],
                        {},
                    ),
                    9: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link", "ol", "ul"]},
                    ),
                    10: ("wagtail.blocks.StructBlock", [[("text", 9)]], {}),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional override for the partner logos section lead text. Will display a default if not provided.",
                            "max_length": 40,
                            "required": False,
                        },
                    ),
                    12: ("app.core.blocks.image.PartnerLogoChooserBlock", (), {}),
                    13: (
                        "wagtail.blocks.ListBlock",
                        (12,),
                        {"max_num": 4, "required": True},
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("lead_text", 11), ("logos", 13)]],
                        {},
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Heading", "max_length": 100},
                    ),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Sub-heading", "max_length": 100},
                    ),
                    17: ("wagtail.blocks.StructBlock", [[("heading", 16)]], {}),
                    18: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("contact", 8),
                                ("inset_text", 10),
                                ("paragraph", 10),
                                ("partner_logos", 14),
                                ("sub_heading", 17),
                            ]
                        ],
                        {"required": False},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 15), ("content", 18)]],
                        {},
                    ),
                },
                help_text="The description of the event.",
                null=True,
                verbose_name="description",
            ),
        ),
    ]
