# Generated by Django 6.0.2 on 2026-03-24 15:33
# etna:allowAlterField

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("whatson", "0035_alter_eventpage_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="displaypage",
            name="body",
            field=wagtail.fields.StreamField(
                [("paragraph", 1), ("quote", 7), ("inset_text", 1), ("sub_heading", 9)],
                blank=True,
                block_lookup={
                    0: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link", "ol", "ul"]},
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("text", 0)]], {}),
                    2: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "ol", "ul"],
                            "required": True,
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "e.g. Author",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "e.g. Some Book",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    5: (
                        "app.core.blocks.page_chooser.APIPageChooserBlock",
                        (),
                        {
                            "help_text": "Reference another page published on the site",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Add a URL here to refer to an external source",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("quote", 2),
                                ("attribution", 3),
                                ("citation", 4),
                                ("citation_internal_link", 5),
                                ("citation_external_link", 6),
                            ]
                        ],
                        {},
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Sub-heading", "max_length": 100},
                    ),
                    9: ("wagtail.blocks.StructBlock", [[("heading", 8)]], {}),
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="exhibitionpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("paragraph", 1), ("quote", 7), ("inset_text", 1), ("sub_heading", 9)],
                blank=True,
                block_lookup={
                    0: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link", "ol", "ul"]},
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("text", 0)]], {}),
                    2: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "ol", "ul"],
                            "required": True,
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "e.g. Author",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "e.g. Some Book",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    5: (
                        "app.core.blocks.page_chooser.APIPageChooserBlock",
                        (),
                        {
                            "help_text": "Reference another page published on the site",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Add a URL here to refer to an external source",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("quote", 2),
                                ("attribution", 3),
                                ("citation", 4),
                                ("citation_internal_link", 5),
                                ("citation_external_link", 6),
                            ]
                        ],
                        {},
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Sub-heading", "max_length": 100},
                    ),
                    9: ("wagtail.blocks.StructBlock", [[("heading", 8)]], {}),
                },
                null=True,
            ),
        ),
    ]
