# Generated by Django 6.0.3 on 2026-04-01 12:21
# etna:allowAlterField

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("whatson", "0035_alter_eventpage_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="displaypage",
            name="body",
            field=wagtail.fields.StreamField(
                [("paragraph", 1), ("quote", 4), ("inset_text", 1), ("sub_heading", 6)],
                blank=True,
                block_lookup={
                    0: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link", "code", "ol", "ul"]},
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("text", 0)]], {}),
                    2: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "code", "ol", "ul"],
                            "required": True,
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 100, "required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 2), ("attribution", 3)]],
                        {},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Sub-heading", "max_length": 100},
                    ),
                    6: ("wagtail.blocks.StructBlock", [[("heading", 5)]], {}),
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="displaypage",
            name="display_highlights",
            field=wagtail.fields.StreamField(
                [("display_highlights", 6)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    1: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "code"],
                            "required": False,
                        },
                    ),
                    2: (
                        "app.core.blocks.image.APIImageChooserBlock",
                        (),
                        {"rendition_size": "max-900x900", "required": True},
                    ),
                    3: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "If provided, displays directly below the image. Can be used to specify sources, transcripts or other useful metadata.",
                            "label": "Caption (optional)",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("caption", 3)]],
                        {},
                    ),
                    5: ("wagtail.blocks.ListBlock", (4,), {}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("images", 5)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="description",
            field=wagtail.fields.StreamField(
                [
                    ("contact", 8),
                    ("inset_text", 10),
                    ("paragraph", 10),
                    ("partner_logos", 14),
                    ("content_section", 19),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"features": ["link"], "required": False},
                    ),
                    2: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "code"],
                            "required": False,
                        },
                    ),
                    3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    4: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    5: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"required": False},
                    ),
                    6: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    7: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "code"],
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("body", 1),
                                ("address", 2),
                                ("telephone", 3),
                                ("chat_link", 4),
                                ("chat_note", 5),
                                ("email", 6),
                                ("website_link", 4),
                                ("social_media", 7),
                            ]
                        ],
                        {},
                    ),
                    9: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link", "code", "ol", "ul"]},
                    ),
                    10: ("wagtail.blocks.StructBlock", [[("text", 9)]], {}),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional override for the partner logos section lead text. Will display a default if not provided.",
                            "max_length": 40,
                            "required": False,
                        },
                    ),
                    12: ("app.core.blocks.image.PartnerLogoChooserBlock", (), {}),
                    13: (
                        "wagtail.blocks.ListBlock",
                        (12,),
                        {"max_num": 4, "required": True},
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("lead_text", 11), ("logos", 13)]],
                        {},
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Heading", "max_length": 100},
                    ),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Sub-heading", "max_length": 100},
                    ),
                    17: ("wagtail.blocks.StructBlock", [[("heading", 16)]], {}),
                    18: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("contact", 8),
                                ("inset_text", 10),
                                ("paragraph", 10),
                                ("partner_logos", 14),
                                ("sub_heading", 17),
                            ]
                        ],
                        {"required": False},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 15), ("content", 18)]],
                        {},
                    ),
                },
                help_text="The description of the event.",
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="event_highlights",
            field=wagtail.fields.StreamField(
                [("event_highlights", 6)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    1: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "code"],
                            "required": False,
                        },
                    ),
                    2: (
                        "app.core.blocks.image.APIImageChooserBlock",
                        (),
                        {"rendition_size": "max-900x900", "required": True},
                    ),
                    3: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "If provided, displays directly below the image. Can be used to specify sources, transcripts or other useful metadata.",
                            "label": "Caption (optional)",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("caption", 3)]],
                        {},
                    ),
                    5: ("wagtail.blocks.ListBlock", (4,), {}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("images", 5)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="exhibitionpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("paragraph", 1), ("quote", 4), ("inset_text", 1), ("sub_heading", 6)],
                blank=True,
                block_lookup={
                    0: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link", "code", "ol", "ul"]},
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("text", 0)]], {}),
                    2: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "code", "ol", "ul"],
                            "required": True,
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 100, "required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 2), ("attribution", 3)]],
                        {},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Sub-heading", "max_length": 100},
                    ),
                    6: ("wagtail.blocks.StructBlock", [[("heading", 5)]], {}),
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="exhibitionpage",
            name="exhibition_highlights",
            field=wagtail.fields.StreamField(
                [("exhibition_highlights", 6)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    1: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "code"],
                            "required": False,
                        },
                    ),
                    2: (
                        "app.core.blocks.image.APIImageChooserBlock",
                        (),
                        {"rendition_size": "max-900x900", "required": True},
                    ),
                    3: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "If provided, displays directly below the image. Can be used to specify sources, transcripts or other useful metadata.",
                            "label": "Caption (optional)",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("caption", 3)]],
                        {},
                    ),
                    5: ("wagtail.blocks.ListBlock", (4,), {}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("images", 5)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="exhibitionpage",
            name="review",
            field=wagtail.fields.StreamField(
                [("review", 3)],
                blank=True,
                block_lookup={
                    0: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "code"],
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 100, "required": True},
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                (0, "No stars"),
                                (3, "3 stars"),
                                (4, "4 stars"),
                                (5, "5 stars"),
                            ],
                            "icon": "pick",
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 0), ("attribution", 1), ("stars", 2)]],
                        {},
                    ),
                },
            ),
        ),
    ]
