# Generated by Django 6.0.3 on 2026-04-17 09:13
# etna:allowAlterField

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("whatson", "0036_alter_displaypage_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="displaypage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("paragraph", 1),
                    ("quote", 9),
                    ("inset_text", 1),
                    ("sub_heading", 11),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link", "code", "ol", "ul"]},
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("text", 0)]], {}),
                    2: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "code", "ol", "ul"],
                            "required": True,
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The name of the person being quoted. e.g. King Edward VIII",
                            "max_length": 100,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The title of the work or document from which the quote is taken. e.g. The Telegraph, 23 June 1986",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    5: (
                        "app.core.blocks.page_chooser.APIPageChooserBlock",
                        (),
                        {
                            "help_text": "Reference another page published on the site",
                            "label": "Internal page",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Add a URL here to refer to an external source",
                            "label": "External link",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("citation_internal_link", 5),
                                ("citation_external_link", 6),
                            ]
                        ],
                        {},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("citation", 4), ("source_link", 7)]],
                        {},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 2), ("attribution", 3), ("source", 8)]],
                        {},
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Sub-heading", "max_length": 100},
                    ),
                    11: ("wagtail.blocks.StructBlock", [[("heading", 10)]], {}),
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="exhibitionpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("paragraph", 1),
                    ("quote", 9),
                    ("inset_text", 1),
                    ("sub_heading", 11),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link", "code", "ol", "ul"]},
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("text", 0)]], {}),
                    2: (
                        "app.core.blocks.paragraph.APIRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "code", "ol", "ul"],
                            "required": True,
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The name of the person being quoted. e.g. King Edward VIII",
                            "max_length": 100,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The title of the work or document from which the quote is taken. e.g. The Telegraph, 23 June 1986",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    5: (
                        "app.core.blocks.page_chooser.APIPageChooserBlock",
                        (),
                        {
                            "help_text": "Reference another page published on the site",
                            "label": "Internal page",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Add a URL here to refer to an external source",
                            "label": "External link",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("citation_internal_link", 5),
                                ("citation_external_link", 6),
                            ]
                        ],
                        {},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("citation", 4), ("source_link", 7)]],
                        {},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 2), ("attribution", 3), ("source", 8)]],
                        {},
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Sub-heading", "max_length": 100},
                    ),
                    11: ("wagtail.blocks.StructBlock", [[("heading", 10)]], {}),
                },
                null=True,
            ),
        ),
    ]
