# Generated by Django 6.0.6 on 2026-07-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatson', '0038_eventsupplementarypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsupplementarypage',
            name='page_sidebar',
            field=models.CharField(blank=True, choices=[('contents', 'Contents'), ('sections', 'Sections'), ('section_tabs', 'Section tabs'), ('pages', 'Pages'), ('pages_tabs', 'Pages tabs')], help_text="Select the sidebar style for this page. For more information, see the <a href='https://nationalarchives.github.io/design-system/components/sidebar/'>sidebar documentation</a>.", null=True),
        ),
    ]
