# Generated by Django 3.1.8 on 2021-07-01 13:24

from django.db import migrations, models
import etna.text_formats.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', etna.text_formats.fields.BasicRichTextField()),
                ('active', models.BooleanField(default=False)),
                ('cascade', models.BooleanField(default=False, verbose_name='Show on this and all child pages')),
                ('alert_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=6)),
            ],
        ),
    ]
