# Generated by Django 3.1.8 on 2021-07-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='cascade',
            field=models.BooleanField(default=False, verbose_name='Show on current and all child pages'),
        ),
    ]
