name: Deploy to Platform.sh main

on:
  workflow_dispatch:

concurrency:
  group: cd-psh-${{ github.ref }}

jobs:
  check-migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Run tests
        uses: ./.github/actions/check-migrations

  test-python:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16.0
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 1s --health-timeout 3s --health-retries 10
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Run tests
        uses: ./.github/actions/python-tests

  deploy:
    environment:
      name: beta
      url: https://beta.nationalarchives.gov.uk
    runs-on: ubuntu-latest
    needs:
      - test-python
      - check-migrations
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: axelerant/platformsh-deploy-action@v1
        with:
          project-id: ${{ secrets.PLATFORM_PROJECT_ID }}
          cli-token: ${{ secrets.PLATFORM_CLI_TOKEN }}
          ssh-private-key: ${{ secrets.PLATFORM_SSH_KEY }}
          force-push: true
          environment-name: main

  notify-slack:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: "A deployment to main is complete"
