name: Deploy to Platform.sh develop

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  check-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: snok/install-poetry@v1
      - name: Check Poetry dependencies
        run: poetry show -o

  check-migrations:
    name: Check Migrations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        uses: ./.github/actions/check-migrations

  test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        uses: ./.github/actions/python-tests

  deploy:
    environment:
      name: beta-develop
      url: https://develop-sr3snxi-rasrzs7pi6sd4.uk-1.platformsh.site/
    runs-on: ubuntu-latest
    needs:
      - test-python
      - check-migrations
      - check-dependencies
    steps:
      - uses: actions/checkout@v4
      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - uses: axelerant/platformsh-deploy-action@v1
        with:
          project-id: ${{ secrets.PLATFORM_PROJECT_ID }}
          cli-token: ${{ secrets.PLATFORM_CLI_TOKEN }}
          ssh-private-key: ${{ secrets.PLATFORM_SSH_KEY }}
          force-push: true
          environment-name: ${{ steps.extract_branch.outputs.BRANCH }}

  notify-slack:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v4
      - uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: "A deployment to develop is complete"
